### ISSUE TITLE
macOS: Asset Processor fails to process multiple assets and Editor displays black viewport on specific macOS machines

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#6449] opened 2021-12-16 14:38 UTC
**Describe the bug**
Launching a development branch build on a 2020 Macbook Air (M1 chipset, Monterey 12.0.1 , Xcode version 13.1) and 2019 Macbook Pro (I9-9980HK CPU, Big Sur 11.6.1, Xcode version 13.1) results in Asset Processor failing to process 100+ assets, including shaders and fonts. The viewport displays a black(blue in case of 2019 Macbook Pro) background when the Editor is launched.

It was also observed that prior to the Editor launch, an error prompt with the following message appears:

```
O3DE could not initialize correctly for the following reason(s):
Could not load font: Fonts/default.font
Could not load font: Fonts/default-ui.font
```
and the Project Manager screen does not have the o3de graphic.

The issue was observed for AutomatedTesting, AtomTest and new projects.

Please note that it failed to reproduce on 2017 Macbook Pro (I7-7820HQ CPU) machines.

For further information please refer to the attached video files and log files from Asset Processor and Editor.

**Steps to reproduce**

1. Obtain the development branch build via Github.
2. Create a new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
3. Obtain python packages with the _get_python.sh_ script located in the _o3de/python_ directory.
4. Create the osx_build folder under the o3de path.
5. Set the following temporary environment variables in the Terminal:
```
export PATH=$PATH:/Users/<home_folder_name>/o3de/3rdParty/CMake/CMake.app/Contents/bin
export LY_3RDPARTY_PATH=/Users/<home_folder_name>/o3de/3rdParty
export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
```
6. Configure and generate the Xcode solution with the following command:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=1`

7. Build Mac binaries with the following command:
`cmake -E time cmake --build . --target ALL_BUILD --config profile`

8. Navigate to the _o3de/osx_build/bin/profile_ directory and launch the Editor.app

9. In the Project Manager window, select the AutomatedTesting project and click the Open Editor button.

**Expected behavior**
Asset Processor successfully processes all the assets and the Editor is launched without errors.

**Actual behavior**
Asset Processor fails to process multiple critical assets, launching the Editor results in a font error and with a black background displayed in the viewport.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/146391331-00189ea6-a880-443b-8778-e63deb6e7b1a.mov

https://user-images.githubusercontent.com/86953456/146395782-5de2eb56-d18f-44d2-be6c-aa634b9ee8a0.mov

**Found in Branch**
Development (df8326a)

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: macOS
- Version: Monterey 12.0.1
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**

[Macbook Air logs M1 2020.zip](https://github.com/o3de/o3de/files/7728146/Macbook.Air.logs.M1.2020.zip)

[MacbookPro 2019 logs_.zip](https://github.com/o3de/o3de/files/7728343/MacbookPro.2019.logs_.zip)

**Comment by amzn-sj** [comment] 2021-12-16 17:38
A lot of the errors from the logs are complaining about failing to load source assets. This indicates that the assets are missing or corrupt for some reason. It's possible that this could be related to git lfs. Eg error:
```ImageProcessing: Trace::Error
~~1639663208099~~3~~0x70000eb73000~~AssetBuilder~~E: >	/Users/macpro14/o3de/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/QtImageLoader.cpp(31): 'ImageProcessingAtom::IImageObject *ImageProcessingAtom::QtImageLoader::LoadImageFromFile(const AZStd::string &)'
~~1639663208099~~3~~0x70000eb73000~~AssetBuilder~~E: >	Failed to load [/Users/macpro14/o3de/Assets/Editor/Materials/voxel_editor.png] via QImage```

**Comment by LB-MateuszSzweda** [comment] 2021-12-17 15:27
Today with https://github.com/o3de/o3de/issues/6407 fixed it was verified that the above issue also affects Stabilization/2111RTE (d7dc257) branch build on my machines.

**Comment by amzn-sj** [comment] 2021-12-17 17:07
I'm unable to reproduce this with AutomatedTesting or AtomSampleViewer on M1 Mac Mini or MacBookPro with Intel i7 in latest development

**Comment by LB-MateuszSzweda** [comment] 2021-12-21 16:58
Today on Development (366a711) I was able to workaround this on both machines by reinstalling the Homebrew and Git LFS.

The exact configuration steps I did perform to achieve a working Editor were:

1. Verifying that Git is properly installed by running _git --version_ command in the terminal.
2. Installing the Homebrew with _/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"_ command in the terminal
and setting paths provided in the terminal after installation.
3. Installing Git lfs with _brew install git-lfs_ command.
4. Running _git config credential.helper_ command to verify if credential manager is properly set.
5. Cloning o3de from my forked repository instead of public https://github.com/o3de/o3de .
6. Building and running the Editor with steps provided in the bug description.


The previous configuration steps which resulted in machines having Asset Processor issues were:

1. Installing the Homebrew by running _ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"_ command in the terminal.
2. Installing GIT with _brew install git_ command in the terminal.
3. Installling GIT LFS with _brew install git-lfs_ command in the terminal.
4. Running _git credential-osxkeychain_ command in the terminal.
5. Installing Cmake command tools by dragging CMake app bundle to Applications directory and running the
_sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install_ command in the terminal.
6. Cloning o3de from the public repository by _git clone https://github.com/o3de/o3de.git_ command.
7. Building and running the Editor with steps provided in the bug description.

**Comment by alexmontAmazon** [comment] 2022-01-05 18:56
This was an individual setup issue, that the OP has fixed themselves. Closing...

**Closed by alexmontAmazon** 2022-01-05 18:56 UTC
Labels: kind/bug, platform/macos, sig/platform, priority/critical, triage/declined
