### ISSUE TITLE
Un-parenting or assigning a new parent for multiple selected entities causes an error and doesn’t work

### ISSUE THREAD

**Issue by pwalterscarb** [o3de/o3de#17740] opened 2024-04-15 19:38 UTC
Assigning a new parent for multiple entities causes an error and doesn’t work. Limitation is that you can only do one entity at a time. 

1. In the editor
2. Make 2 or more new entities and parent them under each other
3. Select all entities at once
4. in the inspector, in the transform component, hit the X in 'Parent entity' (or select another entity to parent to)
5. witness the errors and lack of re-parenting

I would expect multiple entities to be re-parented all un-parented.

Here's a video showing the steps and error.
https://github.com/o3de/o3de/assets/50999342/c03fb231-d962-4394-871a-9b75b6a2daaa

**Found in Branch**
https://github.com/carbonated-dev/o3de
Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository
custom engine version 2310.2

**Desktop/Device:**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, 3501 Mhz, 6 Core(s), 12 Logical Processor(s)]
GPU [NVIDIA GeForce RTX 3090]
Memory [32GB]

**Comment by AMZN-daimini** [comment] 2024-04-17 12:33
I can't reproduce this locally.

![Reparent](https://github.com/o3de/o3de/assets/82231674/4ffbd86d-a6be-4e32-ae0d-e2101abc84e9)

Could you give me a list of components that are assigned to that entity? Is there any custom component that is not in the base repo? Also, is TrackView controlling those entities?

I will keep trying to get a repro for a little bit based on the video before moving to a different issue.

**Comment by AMZN-daimini** [comment] 2024-04-17 13:57
Update, I can repro this in the 23.10.3 point release branch.
I will try to look up the fix for this and cherry-pick it...

**Comment by AMZN-daimini** [comment] 2024-04-17 16:06
Found [the PR that fixed that issue](https://github.com/o3de/o3de/pull/17031) and cherry-picked it to the 23.10.3 branch: https://github.com/o3de/o3de/pull/17763

Will verify if this fixes other issues as well.

**Comment by AMZN-daimini** [comment] 2024-04-18 14:26
Fix was cherry-picked to the 23.10.3 point release branch.

**Closed by AMZN-daimini** 2024-04-18 14:26 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major
