### ISSUE TITLE
Script Canvas node shrinks on mouseover

### ISSUE THREAD

**Issue by evanchia-ly-sdets** [o3de/o3de#6459] opened 2021-12-16 20:00 UTC
When mousing over certain nodes in script canvas, the node will temporarily shrink causing a flickering sensation. The bug does not occur on all node types, but seems to be larger nodes.

1. Open the Editor
2. Open Script Canvas and create a new script
3. Place larger nodes into the script
4. Mouse over the nodes

**Expected behavior**
The nodes do not shrink

**Actual behavior**
The nodes temporarily shrink

https://user-images.githubusercontent.com/80914607/146440908-8cf8568c-8e65-4181-99d1-8416deebddbb.mp4

**Found in Branch**
Used installer for O3DE 21.11

**Comment by monroegm** [comment] 2022-01-06 19:47
@lsemp3d Possible duplicate

**Comment by lsemp3d** [comment] 2022-01-06 19:49
duplicate of #2457

**Closed by lsemp3d** 2022-01-06 19:49 UTC
Labels: feature/scripting, kind/bug, needs-triage, sig/content
