### ISSUE TITLE
The Editor crashes upon launching

### ISSUE THREAD

**Issue by jborut** [o3de/o3de#6139] opened 2021-12-03 18:37 UTC
**Describe the bug**
The project (with default gems) created with Project Manager (GUI) can't be opened. Editor crashes with an error message saying that Shaders/SimpleTextured.azshader, Fonts/default.font, and Fonts/default-ui.font can't be found.

![image](https://user-images.githubusercontent.com/31534934/144654509-f46d1c49-e7d7-44eb-b7a2-f57ce795d37f.png)

**Steps to reproduce**
1. Install O3DE with windows installer
2. Open O3DE Project Manager
3. Click Create new Project
4. Click Create (with default gems selection)
5. Once the project is created, build it
6. When the project is built, click Open Editor

**Expected behavior**
When I click Open Editor on a project in Project Manager, Editor should open.

**Actual behavior**
When I click Open Editor on a project in Project Manager, the above described error message pops up and editor doesn't open.

**Found in Branch**
Release 21.11.1

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Ryzen 5900x
 - GPU NVidia 1050Ti
 - Memory 32GB

**Additional context**
This problem is probably related to this https://github.com/o3de/o3de/issues/3955

**Comment by stephanrb3** [comment] 2021-12-07 00:07
I'm running into the same problem.

**Comment by WayneKoorts** [comment] 2021-12-07 23:04
Same problem, I just downloaded this for the first time and set up a new project with all defaults (except project location), built the project from the launcher but can't launch the editor because of this error.

**Comment by lumberyard-employee-dm** [comment] 2021-12-08 00:58
I have a fix for this issue up for PR now https://github.com/o3de/o3de/pull/6234

**Comment by wangbq96** [comment] 2022-01-10 12:17
I cloned and built the latest source code but still encountered this problem. 
```
Logged at Monday, January 10, 2022 20:12:51
FileVersion: 0.0.0.0
ProductVersion: 0.0.0.0
LogFile: @log@/Editor.log
ProjectDir: C:\Users\boquan\O3DE\Projects\NewProject
Executable: Editor.exe (debug: no
Exception Code: 0xC0000005
Exception Addr: 0x0033:0x00007FFC2ABC8811
Exception Module: 
Exception Description: EXCEPTION_ACCESS_VIOLATION, Attempt to read from address 0x00000448

The memory could not be "read"

Call Stack Trace:
25) 00007FFCC034B7F7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFCC29551B0 (ntdll) : memset
23) 00007FFCC293C766 (ntdll) : _C_specific_handler
22) 00007FFCC29520CF (ntdll) : _chkstk
21) 00007FFCC2901454 (ntdll) : RtlRaiseException
20) 00007FFCC2950BFE (ntdll) : KiUserExceptionDispatcher
19) C:\o3de\Gems\Atom\RHI\Code\Source\RHI.Reflect\ShaderResourceGroupLayout.cpp (442) : AZ::RHI::ShaderResourceGroupLayout::FindShaderInputBufferIndex
18) C:\o3de\Gems\Atom\Feature\Common\Code\Source\Utils\GpuBufferHandler.cpp (28) : AZ::Render::GpuBufferHandler::GpuBufferHandler
17) C:\o3de\Gems\Atom\Feature\Common\Code\Source\CoreLights\SimplePointLightFeatureProcessor.cpp (51) : AZ::Render::SimplePointLightFeatureProcessor::Activate
16) C:\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\Scene.cpp (156) : AZ::RPI::Scene::Activate
15) C:\o3de\Gems\Atom\Bootstrap\Code\Source\BootstrapSystemComponent.cpp (281) : AZ::Render::Bootstrap::BootstrapSystemComponent::GetOrCreateAtomSceneFromAzScene
14) C:\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (165) : `AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1>::operator()
13) C:\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Request,0,0>::Dispatcher<AZ::EBus<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Request> 
12) C:\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (174) : AtomToolsFramework::RenderViewportWidget::SetScene
11) C:\o3de\Code\Editor\EditorViewportWidget.cpp (2329) : EditorViewportWidget::UpdateScene
10) C:\o3de\Code\Editor\EditorViewportWidget.cpp (945) : EditorViewportWidget::SetViewportId
 9) C:\o3de\Code\Editor\ViewPane.cpp (307) : CLayoutViewPane::AttachViewport
 8) C:\o3de\Code\Editor\ViewPane.cpp (223) : CLayoutViewPane::SetViewClass
 7) C:\o3de\Code\Editor\LayoutWnd.cpp (207) : CLayoutWnd::MaximizeViewport
 6) C:\o3de\Code\Editor\LayoutWnd.cpp (307) : CLayoutWnd::CreateLayout
 5) C:\o3de\Code\Editor\MainWindow.cpp (440) : MainWindow::InitCentralWidget
 4) C:\o3de\Code\Editor\MainWindow.cpp (455) : MainWindow::Initialize
 3) C:\o3de\Code\Editor\CryEdit.cpp (1705) : CCryEditApp::InitInstance
 2) C:\o3de\Code\Editor\CryEdit.cpp (4176) : CryEditMain
 1) C:\o3de\Code\Editor\main.cpp (32) : main
```

**Comment by LB-BartoszDudzinski** [comment] 2022-02-14 13:19
The issue occurs in development branch also when the engine is built as a source and a pre-built SDK. However it is a one time error and project can be opened when launched a second time.

**Comment by lumberyard-employee-dm** [comment] 2022-02-14 17:15
> The issue occurs in development branch also when the engine is built as a source and a pre-built SDK. However it is a one time error and project can be opened when launched a second time.

Do you have a callstack available of when it crashes the first time it launches?

**Comment by LB-BartoszDudzinski** [comment] 2022-02-15 14:51
I am afraid I do not have it and I was unable to reproduce this issue with the latest development. I will try reproduce it tomorrow.

**Comment by LB-BartoszDudzinski** [comment] 2022-02-21 13:50
I was unable to repro this. Maybe it was a random build issue as the issue no longer occurs.

**Comment by VickyAtAZ** [comment] 2023-01-12 18:09
https://github.com/o3de/o3de/pull/14027

**Closed** 2023-01-18 04:46 UTC
Labels: kind/bug, sig/content, triage/accepted, feature/build, priority/critical
