### ISSUE TITLE
Linux: Default physics material library material's Debug Color values mismatch the values on Windows

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7717] opened 2022-02-17 12:14 UTC
**Describe the bug**
On Linux, all of the default physics material library materials Debug Color property values are either [0,0,0] or [255,0,0], while on Windows each default physics material has a unique color (e.g. [234,178,113] for the Character material, and [151,126,97] for the Concrete material).

**Steps to reproduce**
1. Go to Tools > PhysX Configuration (PREVIEW).
2. In the PhysX Configuration (PREVIEW) window go to Physics Materials > Physics Material Library and click "Edit asset" button on the right.

**Expected behavior**
Default physics materials Debug Color values are consistent between systems.

**Actual behavior**
Default physics materials Debug Color values are inconsistent between systems.

**Screenshots**
Linux default physics materials:
![DefaultPhysicsMaterialsDebugColorValuesLinux](https://user-images.githubusercontent.com/86952082/154478762-e5f13f5b-ad06-48ef-b7f1-742ef63969d2.png)
Windows default physics materials:
![DebugColorValuesWindows](https://user-images.githubusercontent.com/86952082/154478785-145d4346-05cd-4f75-b873-4b3e862bb657.png)

**Found in Branch**
Development (3f2aa74)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by lumberyard-employee-dm** [comment] 2022-04-06 16:18
This appears to be related or a duplicate of #7316

**Comment by moraaar** [comment] 2022-07-13 16:19
Closing this as it's a duplicate of https://github.com/o3de/o3de/issues/9927

**Closed by moraaar** 2022-07-13 16:19 UTC
Labels: platform/linux, feature/physics, kind/bug, needs-triage, sig/platform, sig/ui-ux, priority/minor
