### ISSUE TITLE
When the Be this camera option is enabled the Go to selected object action moves the Camera Entity in a random direction

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#4141] opened 2021-09-15 10:53 UTC
**Describe the bug**
Performing the _Go to selected object_ action while being in the _Be this camera_ mode moves the Entity in a random direction instead of moving the Camera to the selected object. 

Additionally, the following error appears in the Console:
`[Error] (Transform) - Can't create look-at matrix when 'to' and 'from' positions are equal.`

Please refer to the attached video for more details.

**To Reproduce**
1. Open any Level.
2. Create an Entity.
3. Add the Camera Component to the Entity.
4. Press the _Be this camera_ button on the Camera Component.
5. Press the _Z_ key on the keyboard (or the _Go to selected object_ button on the toolbar).

**Expected behavior**
The Camera moves to the selected Entity.

**Video**

https://user-images.githubusercontent.com/86953108/133419922-81e5a98f-1525-454a-9f47-be0098698a7c.mp4

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by hultonha** [comment] 2021-09-30 14:54
Just reproduced this - the problem is going to the 'yourself' (the entity selected being the one with the camera on it). We most likely need a 'self' check before doing this as you're by definition, _already there_. I'll see if I can combine this with some other related camera polish work.

**Comment by hultonha** [comment] 2021-11-17 22:50
Fixed by #5703

**Closed by hultonha** 2021-11-17 22:50 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/viewport

**Comment by LB-TomaszSerwanski** [comment] 2021-11-18 09:12
Issue verified as fixed in Stabilization_2110 (d222aee).
