### ISSUE TITLE
[Animation] The Actor is not selected in the animation editor. If you select motion event under Time View and motion under Motions, and press Delete, the Actor is deleted instead of the selected object.

### ISSUE THREAD

**Issue by nielianpeng** [o3de/o3de#5641] opened 2021-11-16 07:59 UTC
**Describe the bug**
[Animation] The Actor is not selected in the animation editor. If you select motion event under Time View and motion under Motions, and press Delete, the Actor is deleted instead of the selected object.

**Steps to reproduce**
1. Open the animation editor and select the corresponding Actor and Motion Sets.
2. Click Motions, select a motion, press Delete, and press Ctrl+Z.
3. Add an event motion in Time View, select the event motion, press Delete, and then press Ctrl+Z.

**Expected behavior**
1. Press Delete to delete the selected item.

**Actual behavior**
1. Press Delete to delete an unselected actor.

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel Xeon Gold 6234]
 - GPU [NVidia RTX 5000]
 - Memory [32GB]
 - Working Branch: Main branch e7f7875

**Additional context**

**Comment by FuzzyCarterAWS** [comment] 2022-01-11 00:35
I'm definitely seeing this behavior. Adding a video to show behavior.

However, to note, this only happens if the actor is selected in the viewport.


https://user-images.githubusercontent.com/29718640/148860867-dc00b625-e3ec-4768-a9db-a92620e8eaf1.mp4

**Comment by rainbj** [comment] 2022-01-12 18:42
@yuyihsu

**Comment by rainbj** [comment] 2022-01-12 18:45
Idea - from community:  the capturing the of input from the screen could be the cause of this issue.

**Comment by svitlani** [comment] 2022-02-01 18:44
@yuyihsu seems like some feedback from you is needed, so Scripting team can proceed with the fixing this issue.

**Comment by lsemp3d** [comment] 2022-02-08 22:09
> I'm definitely seeing this behavior. Adding a video to show behavior.
> 
> However, to note, this only happens if the actor is selected in the viewport.

If this only happens when the actor is selected in the viewport, we need to re-verify this issue using the new viewport, @FuzzyCarterAWS  can you check?

**Comment by FuzzyCarterAWS** [comment] 2022-02-08 22:32
@lsemp3d With the Atom Viewport, you are unable to delete any motions or other items with the delete key. However, the actor is not deleted. You can still delete things with the _Right-Click > Remove_ context menu however.

This appears to be a larger issue where the delete key is not being received correctly throughout the EMFX Animation Editor.

**Comment by lsemp3d** [comment] 2022-02-08 22:36
Thanks @FuzzyCarterAWS , @amzn-rhhong assigning this to you to check when you have a chance, if it's a global editor hotkey issue we may start a discussion with others about it

**Comment by hultonha** [comment] 2022-04-12 09:44
Discussed this with @amzn-jillich and with the Atom viewport you can only have one character so this issue is no longer relevant

**Comment by hultonha** [comment] 2022-04-12 09:51
Note: I reviewed this with @amzn-jillich and we have confirmed the initial reported issue no longer occurs. This is more of a feature request for the delete key to work with the EMFX editor

**Comment by hultonha** [comment] 2022-04-12 09:51
Note: A new issue will be created to cover the change in functionality for the delete key

**Closed by hultonha** 2022-04-12 09:51 UTC
Labels: feature/animation, kind/bug, sig/content, sig/ui-ux, triage/accepted, priority/critical, WF3, RTE, needs-ux-action
