### ISSUE TITLE
 fbx setting setting parameters do not take effect

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#2420] opened 2021-07-26 08:49 UTC
**Describe the bug**

The actors interface setting the Coordinate system change parameter does not take effect

**To Reproduce**
1. Open fbx setting and switch to actors interface
2. Click the "Add Modifie" button and select "Coordinate system change"
3. "Facing direction" select "Rotate 180 degrees around the up axis" under "Coordinate system change"
4.  click "update",  then Drag the model into the scene
5. "Facing direction" select ""Do nothing" under "Coordinate system change"
6. click "update",  then Drag the model into the scene
7. Move the two models together, don’t rotate

**Expected behavior**
The two models should be facing differently, 180° apart

**Screenshots**

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU: [Intel Xeon Gold 6234]
GPU: [NVidia RTX 5000]
Memory: [32GB]
Working Branch: Main branch: e7f787572e805c413115265e5873fb2425e2f41b

**Additional context**

**Comment by monroegm** [comment] 2021-11-09 19:56
Duplicate of #2426

**Closed by monroegm** 2021-11-09 19:56 UTC
Labels: feature/animation, kind/bug, sig/content, status/duplicate
