### ISSUE TITLE
Product dependencies Bug Report

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#9611] opened 2022-05-18 06:58 UTC
#8089

This bug still exists and is not resolved in version 2205

the result of compiling together：
![image](https://user-images.githubusercontent.com/97455291/168977601-370d1f09-5dc3-49af-9f21-b0890a49c149.png)

The final result of separate compilation：
![image](https://user-images.githubusercontent.com/97455291/168977661-531367fb-dfa6-42d2-8554-bce6f6a67bde.png)

**Comment by AMZN-stankowi** [comment] 2023-03-30 18:22
I'm closing this as a duplicate of https://github.com/o3de/o3de/issues/15338 , now that I've gotten far into working on 15338, I understand what's happening. I'm using 15338 as the source ticket because it's being tracked elsewhere for Multiplayer Sample improvements.

**Closed by AMZN-stankowi** 2023-03-30 18:22 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, triage/accepted, priority/major
