### ISSUE TITLE
AR Bug Report - AssetJobsFloodTest.FloodTest Failed

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10692] opened 2022-07-15 12:39 UTC
**Describe the bug**

`AssetJobsFloodTest.FloodTest` failed while running AR on an unrelated change

**Failed Jenkins Job Information:**

Platform/Job: Linux [profile_nounity_pipe] - test_profile_nounity

https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-10091/2/

```
[2022-07-14T20:03:16.536Z] [----------] 22 tests from AssetJobsFloodTest
[2022-07-14T20:03:16.536Z] [ RUN      ] AssetJobsFloodTest.FloodTest
[2022-07-14T20:03:16.536Z] /data/workspace/o3de/Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp:469: Failure
[2022-07-14T20:03:16.536Z] Expected equality of these values:
[2022-07-14T20:03:16.536Z]   m_testAssetManager->GetAssetContainers().size()
[2022-07-14T20:03:16.536Z]     Which is: 1
[2022-07-14T20:03:16.536Z]   0
[2022-07-14T20:03:16.536Z] [  FAILED  ] AssetJobsFloodTest.FloodTest (147 ms)
...
[2022-07-14T20:03:16.788Z] [----------] Global test environment tear-down
[2022-07-14T20:03:16.788Z] [==========] 10165 tests from 694 test cases ran. (128604 ms total)
[2022-07-14T20:03:16.788Z] [  PASSED  ] 10164 tests.
[2022-07-14T20:03:16.788Z] [  FAILED  ] 1 test, listed below:
[2022-07-14T20:03:16.788Z] [  FAILED  ] AssetJobsFloodTest.FloodTest
```

**Attachments**

[log.txt](https://github.com/o3de/o3de/files/9120767/log.txt)

**Comment by AMZN-stankowi** [comment] 2022-07-21 13:30
This happened on development branch build: https://jenkins.build.o3de.org/job/O3DE/job/development/2769/

**Comment by amzn-mike** [comment] 2022-07-25 20:46
This may be fixed by https://github.com/o3de/o3de/pull/10864

**Comment by amzn-mike** [comment] 2022-07-29 17:06
I'm going to mark this as closed for now since its difficult to reproduce locally and may have been fixed by the above mentioned PR.  If this occurs again, please re-open this issue.

**Closed by amzn-mike** 2022-07-29 17:06 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, triage/accepted, priority/critical, kind/automation
