### ISSUE TITLE
[iOS] Level does not load after launching the app

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#3415] opened 2021-08-24 13:59 UTC
**Describe the bug**
It has been observed that a level will not launch when app with a built project is launched. Only a black screen which shows up after the o3de splashscreen can be seen.

For further information please refer to the log from Xcode.

[xcode output.txt](https://github.com/o3de/o3de/files/7039664/xcode.output.txt)

**Prerequisites**

* autoexec.cfg containing "loadlevel <level_name>" present in AutomatedTesting folder.
* iOS assets were processed by Asset Processor.
* AutomatedTesting project built for iOS.

**To Reproduce**
1. Deploy the App to iOS device with Xcode.
2. Launch the App manually on iOS device or with Xcode.

**Expected behavior**
Level from the autoexec.cfg file is loading after launching the app.

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: MacOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Comment by amzn-sj** [comment] 2021-08-24 16:41
I'm seeing the following in the logs:
`System: Trace::Assert
 /Users/lumberpro6/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp(377): (4655413440) 'void AZ::Metal::Device::InitFeatures()'
System: Atom needs Argument buffer support to run
System: ------------------------------------------------
System: ==================================================================`

Can you provide details about the iOS device you're using(device model, iOS version, etc.,)? It's possible that your device may not support running Atom.

**Comment by moudgils** [comment] 2021-08-24 16:59
I recommend using Iphone8 or above for testing purposes.

**Comment by amzn-sj** [comment] 2021-08-30 17:10
I still see this error from Atom in the new log that's attached:

`System: 
==================================================================
System: Trace::Assert
 /Users/lumberpro6/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp(377): (4711266432) 'void AZ::Metal::Device::InitFeatures()'
System: Atom needs Argument buffer support to run
System: ------------------------------------------------
System: ==================================================================`

It doesn't look like Atom was successfully initialized.

**Comment by moudgils** [comment] 2021-08-30 17:34
Actually I will rework that message a bit. The api has changed since I wrote that code. I dont think the issue is Argument Buffer support. m_metalDevice.argumentBuffersSupport returns 0 for tier1 support which should work with Atom so we can ignore that assert for now (I will fix it later). The log sort of ends abruptly. Is there any more to it? Like a callstack or something? It is weird to see so many messages like (Failed to open log file). Maybe it dies because it is unable to load assets for some reason?

**Comment by amzn-sj** [comment] 2021-08-30 17:42
I'll try to repro on my device. I had another question about this: `Today following the exact same steps I was again unable to even get the black screen with "Atom using Metal RHI" and a FPS counter **_when Iphone 8 was used_**.` Are you using a different device now? If so, can you provide details about this one?

**Comment by LB-MateuszSzweda** [comment] 2021-08-31 11:33
The log ended abruptly because of me stopping the running scheme after 3-5 minutes. Without stopping it will just repeat the same. " AutomatedTesting.GameLauncher[620:176928] Failed to open log file [@log@/Game.log], mode [44] " line over and over for a given time.

Each day I have tried to use a different iOS device to determine if all the devices encounter the issue.
So far it was tested on:
Ipad Pro 3gen with 14.4.2 version of the system
Ipad Air2 with 12.2 version of the system
Iphone 7 with 13.3 version of the system
and Iphone 8 with 14.4.2 version of the system which was tested against yesterday and the day before.

For now I'll stick to Iphone 8 as it is the recommended machine.

**Comment by LB-MateuszSzweda** [comment] 2021-09-14 14:04
Big update: Somehow I was able to successfully launch the created and deployed level on iOS device today. I am attaching an XCode output from that.

I do not know if its is due to some new commit to Development branch in the last 3 days or some minor things I did differently this time which are:
1. Using "LoadLevel xxxxxx" instead of "loadlevel xxxxx" line in autoexec.cfg
2. Creating and putting in autoexec.cfg prior to building iOS.
3. Launching AutomatedTesting launcher with created level on macOS prior to building iOS
4. Using a new Iphone 11 Pro device instead of Iphone8/Ipad Pro
the specs of Iphone 11 were:
 * Device: iPhone 11 Pro
 * OS: iOS
 * Version: 14.7.1
 * CPU: A13 Bionic
 * GPU: A13 Bionic
 * Memory: 6GB
 
[iOS XCode output from working level 14-09.txt](https://github.com/o3de/o3de/files/7162555/iOS.XCode.output.from.working.level.14-09.txt)

**Comment by LB-MateuszSzweda** [comment] 2021-09-15 15:27
Today I have verified that indeed autoexec.cfg file has to be included in AutomatedTesting prior to building. 
After that it can be modified with level names which will open the desired level when app is deployed to iOS. 
The created levels successfully launched on Iphone 8, Iphone 11 Pro and Ipad Pro.

Therefore the issue can be closed.

**Comment by tkothadev** [comment] 2022-09-16 10:20
This issue has been marked open for the past year, and per the author's last comment, it can now be closed as he's found a sufficient answer for the original issue.

As such I will be closing this.

**Closed by tkothadev** 2022-09-16 10:20 UTC
Labels: kind/bug, sig/platform, priority/critical
