### ISSUE TITLE
Bug Report: Component Asset Picker finds no assets to choose

### ISSUE THREAD

**Issue by mythrz** [o3de/o3de#17105] opened 2023-11-21 17:57 UTC
**Describe the bug**
In the O3DE editor. If you add components like "Actor", "Anim Graph", "Mesh" or "Material" and press the folder icon to pick an asset, nothing is found. The list is empty.
However, if you open the Emotion FX Animator Editor, for example, you can File->Open Actor. The asset .fbx is open correctly.
The problem appears to reside in the O3DE editor only and most components that have an Asset Picker.

**Steps to reproduce**
1. O3DE editor. Create an entity. Add a component like "Actor"
2. Try to pick an asset
3. Nothing can be selected as an asset.
4. Try to drag and drop an asset
5. Nothing happens

**Expected behavior**
A list of assets should be presented allowing the user to pick one.
Or
When I drag the correct asset to the picker, it becomes selected.

**Actual behavior**
There are no assets to choose from.
No asset is ever selected.

**Screenshots/Video**
If you try to pick the asset by clicking the folder icon, nothing is presented.
![pickAsset_nothing](https://github.com/o3de/o3de/assets/44119535/984869d2-61e8-4d9d-9d51-4350a8724001)

If you try to drag and drop an asset, nothing happens. The asset is still not selected.
![Drag_nothing](https://github.com/o3de/o3de/assets/44119535/a4da9671-d980-4f91-92d5-96e969b832c4)

BUT, notice that if you open the Emotion FX Animator Editor you can select an Actor there.
![FileOpen_Works](https://github.com/o3de/o3de/assets/44119535/2a460963-7700-47e7-a69b-980729a7be6c)

**Found in Branch**
Developer Branch.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
The issue started around the same time the engine was crashing due to failed jobs.
Commit Link: https://github.com/o3de/o3de/commit/c8f9a66709bcc2901d8ec321ab8522a3bda59187

**Desktop/Device (please complete the following information):**
- Device: [e.g. PC]
- OS: [e.g. Windows]
- Version [e.g. 11]
- CPU [e.g. AMD Ryzen 2700X ]
- GPU [ NVidia 1060]
- Memory [e.g. 32GB]

**Additional context**
O3DE with GitHub, Developer Branch. But all other branches are probably with the same issue (tested only Dev).
Used Visual Studio CMake instead of manual install of CMake.
Created a new project, and built it, with CLI instead of O3DE Project Manager.
Recorded the installation here:
https://www.youtube.com/watch?v=u-jpFuwVV1Y&ab_channel=rzDmyth
No Jobs fail to process, but there are still some errors due to materials and shaders. Unsure if this is a cascade error. A consequence of the materials/shader error that the current O3DE version has.

Unsure if it is related to the latest changes to Asset Picker and Browser, since the browser is displaying the assets correctly.
Maybe some portion of the code that is used in all components or the existing errors prevents the Asset Picker from working correctly in the O3DE editor. All components suffer from the same problem, but other editors (like Emotion FX Animator Editor) are working fine.

**Comment by lumberyard-employee-dm** [comment] 2023-11-22 17:09
@alexmontAmazon I believe this is a duplicate of #16922 whose fixes were just merged into the development branch yesterday https://github.com/o3de/o3de/pull/17107

**Closed as completed** 2023-11-23 13:02 UTC
Labels: kind/bug, needs-triage, sig/content
