### ISSUE TITLE
Components from the Multiplayer category are missing tooltips in the Entity Inspector

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#8662] opened 2022-04-01 09:32 UTC
**Describe the bug**
When adding a component in the Entity Inspector, the following components in the Multiplayer category are missing tooltips:

- LocalPredictionPlayerInputComponent
- NetworkCharacterComponent
- NetworkHierarchyChildComponent
- NetworkHierarchyRootComponent
- NetworkHitVolumesComponent
- NetworkRigidBodyComponent
    - Why is there a net rigid body but no net-collider? (customer ask)
- NetworkTransformComponent
    - Why does it not have any properties? (customer ask)

Network Binding is the only component in the Multiplayer category that has a tooltip.

**Steps to reproduce**
1. Create an Entity.
2. Open the Entity Inspector.
3. Click the Add Component button.
4. Scroll down to the Multiplayer category and mouse over its components.

**Expected behavior**
Every component has a tooltip.

**Actual behavior**
Components mentioned in the description are missing tooltips.

**Video**

https://user-images.githubusercontent.com/99388484/161234941-08707d31-bfa2-4306-83ff-420accb332b8.mp4

**Found in Branch**
Development (8077789)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by lmbr-pip** [comment] 2022-04-29 00:09
Not sure if this is sig-ui-ux issue, would argue sig-ui-ux may want to review tooltips but components are owned by sig-network.

Would also argue this could be a "good-first-issue" item as the technical bar is low (ish), may require autogen code changes.

**Comment by lmbr-pip** [comment] 2022-09-01 17:34
Closing out as this is a duplicate of https://github.com/o3de/o3de/issues/9660

**Closed by lmbr-pip** 2022-09-01 17:34 UTC
Labels: feature/networking, kind/bug, needs-triage, sig/network, sig/ui-ux, status/duplicate, priority/minor, WF6

**Comment by LB-TomaszSerwanski** [comment] 2022-09-06 08:21
Further progress on the issue will be covered in #9660, as per the comment above. Removing the status/duplicate label as the mentioned issue has been logged after the original one.
