### ISSUE TITLE
Project Manager: Change of project's engine is not visible under the project tile in the projects list

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#15360] opened 2023-03-24 14:20 UTC
**Describe the bug**
Changing engine version in the Project Manager for a project does not update the project tile in the projects list. 
Note that the issue cannot be verified on Linux due to the reported [#15357](https://github.com/o3de/o3de/issues/15357).

Please note that upon launching the 2nd instance of the engine (2.0.0) installed, all projects created using the first one (1.2.0) change to 2.0.0 in project tile. The projects fail to launch until rebuilt (there is no information about the rebuild being required).

Please refer to the attached screenshot and video for more information.

**Steps to reproduce**
1. Download and install the O3DE Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/O3DE_latest.deb).
2. Launch the O3DE from the _/opt/O3DE/1.2.0/bin/Windows/profile/Default_ directory.
3. Create the project, build it and launch the Editor verifying it works.
4. Close the Editor and the Project Manager.
5. Download and install the O3DE Development Installer (https://o3debinaries.org/development/Latest/Windows/O3DE_latest.deb).
6. Launch the O3DE from the _/opt/O3DE/2.0.0/bin/Windows/profile/Default_ directory.
7. Observe the project tile.
8. Press the hamburger icon next to the project created in Step 3. and select Edit Project Settings.
9. Change Engine entry and press save.
10. Observe the project tile.

**Expected behavior**
Project tile displays the version of the O3DE it has been built in. Changing the Engine entry for the project updates the engine version in the project tile and it becomes yellow if it is different than Project Manager version.

**Actual behavior**
Project tile displays the version of the O3DE that has been last built. Changing the Engine entry for the project does not update the engine version in the project tile and it never changes to yellow.

**Screenshots/Video**
![EngineVersionPM](https://user-images.githubusercontent.com/86953659/227544881-2b4b0022-6bb4-4479-bc4d-8d3ecb670a92.PNG)

https://user-images.githubusercontent.com/86953659/227544929-90745dbb-f129-4b2f-bf30-05f50b0b751c.mp4

**Found in Branch**
Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb)
Development Installer build (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Comment by AMZN-alexpete** [comment] 2023-03-29 20:09
I think this is a bug and am working on a fix.

**Comment by AMZN-alexpete** [comment] 2023-04-18 00:51
fixed by https://github.com/o3de/o3de/pull/15474

**Closed by AMZN-alexpete** 2023-04-18 00:51 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/minor, feature/project-manager

**Comment by AMZN-alexpete** [comment] 2023-04-20 21:48
Hi @LB-KacperKapusta  It appears https://github.com/o3de/o3de/issues/15536 has been resolved, and the installer is working again, the issue just hasn't been marked as closed yet.

**Comment by LB-KacperKapusta** [comment] 2023-04-21 09:22
Hi @AMZN-alexpete, I have confirmed that the O3DE now properly displays the version it has been built with. Changing the Engine entry for the project inside the Project Manager updates the engine version in the project tile. Although, it does never become yellow [as it is described here](https://github.com/o3de/sig-content/blob/6bee6571e63776729c952db3db1b4754f0b4d28c/testing-guidance/workflow-tests/o3de-project-manager/engine-versioning/engine-versioning.md#:~:text=Color%20is%20white%20if%20it%20matches%20the%20current%20engine%20and%20yellow%20if%20it%20is%20for%20a%20different%20version%20than%20what%20Project%20Manager%20was%20launched%20from.).

Please note that the Stabilization-2305 project (created using the Stabilization/2305 Installer) could be built using both available Engine versions. The Development project (created using the Development Installer) however, failed to build while using the 23.05.0 version with the following error:
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/11294301/CMakeProjectBuildError.log)


Let us know if any of this should be logged as a separate issue. We are uncertain about the current behavior as the changes seem to only be merged to the Stabilization/2305 Installer and not the Development Installer, which could possibly be causing some issues.

**Comment by AMZN-alexpete** [comment] 2023-04-21 18:14
Hello @LB-KacperKapusta, the potential issues you mentioned are expected, here's an explanation:
-  The engine version is no longer displayed in yellow by design because the color distinction was not good at indicating what yellow text means to customers, so we made it white for now till we have a better UX for displaying incompatibility.
- Development has new features including `AZ_COMPONENT_DECL` which Stabilization/2305 does not have and that is why you cannot build a project created with Development using the Stabilization/2305 engine.

**Comment by LB-KacperKapusta** [comment] 2023-04-24 07:29
Issue verified as fixed in the latest Installer based on the comment above. 
Please note that the mentioned [Engine Versioning Workflow](https://github.com/o3de/sig-content/blob/6bee6571e63776729c952db3db1b4754f0b4d28c/testing-guidance/workflow-tests/o3de-project-manager/engine-versioning/engine-versioning.md#:~:text=Color%20is%20white%20if%20it%20matches%20the%20current%20engine%20and%20yellow%20if%20it%20is%20for%20a%20different%20version%20than%20what%20Project%20Manager%20was%20launched%20from.) requires an update due to the new expected results.
