### ISSUE TITLE
Editor Server Connection Drops After Short Idle Time.

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9491] opened 2022-05-11 22:39 UTC
**Describe the bug**
Attempting to connect client to a remote server, but it kept disconnecting. We believe this was also happening on other launchers (may need repro)

**Steps to reproduce**
1. Go to Multiplayer Sample
2. Set editorsv_hidden=false
3. CTRL+G to start playing
4. See the player spawn into the level
5. Tab back to another app
6. Wait 10 seconds

**Expected behavior**
Server and client network simulation stay connected

**Actual behavior**
Server disconnects

![image](https://user-images.githubusercontent.com/32776221/167968146-9249be69-892c-4c2d-b1be-3d1b015a191b.png)

**Found in Branch**
Nightly build 5/10/2022

**Comment by AMZN-puvvadar** [comment] 2022-05-12 17:16
This will likely be addressed by https://github.com/o3de/o3de/pull/9470

**Comment by AMZN-puvvadar** [comment] 2022-05-16 16:46
https://github.com/o3de/o3de/pull/9470 has been merged. This can now be retested.

**Comment by AMZN-puvvadar** [comment] 2022-05-24 17:26
> This might be addressed by #9470 when the client is the Editor. Otherwise the question is why is the server terminating the connection? Further, why is there such a heavy amount of desyncing?

The heavy amount of desyncs was likely addressed by https://github.com/o3de/o3de-multiplayersample/pull/149

**Comment by allisaurus** [comment] 2022-05-27 18:55
Retested with latest (`146b2c84`, at the time), and was not able to re-pro this from the Editor. Tabbed away for a full minute, a couple times, and was able to see client + server were still connected upon coming back.

![image](https://user-images.githubusercontent.com/34254888/170771052-0916d466-2e62-4b97-ba4e-c89a578eee75.png)

...however, I wasn't able to verify the fix when invoking the server & client launchers directly, as shortly after establishing a connection (able to move the player briefly and see it replicated on the server), the server crashes. 
It's behavior that feels a lot like https://github.com/o3de/o3de-multiplayersample/issues/123. So maybe not relevant to this issue, but will test again and then see about revisiting that one.

**Comment by lmbr-pip** [comment] 2022-06-24 06:06
I could not reproduce, will get Rob to reconfirm and close.

**Comment by robhaco** [comment] 2022-06-24 22:29
@lmbr-pip I was unable to reproduce this in latest development.  Setting to closed.

**Closed by robhaco** 2022-06-24 22:29 UTC
Labels: kind/bug, sig/network, triage/accepted, priority/critical, WF6, RTE
