### ISSUE TITLE
Bug Report - Parent / Child window promotion

### ISSUE THREAD

**Issue by CMelissinos** [o3de/o3de#6820] opened 2022-01-11 16:17 UTC
**Describe the bug**
When breaking an O3DE component, like Script Canvas, out into a separate window, it always remains on top of any other window. Selecting the main editor window (Parent) will not promote it to the top. In addition, you can not assign and of those windows to a virtual desktop for the developer to toggle between. This makes working on a single screen more cumbersome than it should be, having to minimize or constant resize windows during the workflow. 

**Steps to reproduce**
1. Open O3DE
2. Open the Script Canvas
3. Try clicking on the editor screen to promote it to the front
4. Try moving the Script Canvas to a 2nd virtual desktop in Windows 10

**Expected behavior**
Clicking on a window should promote it to the top of the stack. 

**Actual behavior**
Clicking on the editor window will not promote it to the top of the stack. Child windows remain on top, forcing the user to have to constantly resize or minimize the child windows depending on what activity they are doin. In addition, a user can not assign an windows to a virtual desktop. All windows, Parent and Child, must remain on the same desktop.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Version: 19041.1415
 - CPU: Intel Core i5-6600K @ 3.50GHz
 - GPU: NVidia 1080 FE
 - Memory: 16GB

**Comment by cgalvan** [comment] 2022-01-11 17:42
This is a duplicate of https://github.com/o3de/o3de/issues/2930

**Closed by cgalvan** 2022-01-11 17:42 UTC
Labels: kind/bug, needs-sig, needs-triage
