### ISSUE TITLE
Issue when driving two Actors to share animation through the Attachment Component

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#9066] opened 2022-04-21 09:41 UTC
**Describe the bug**
Some Issue When driving two Actors to share animation through the Attachment component.

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/32164562/164426774-03a220cb-e7c9-4ba5-935d-b7ac4283e352.png)

as shown in the figure, the skinmesh of the head part is head, the root bone is Boy_Bip, the skinmesh of the hair part is hair, and the root bone is Point_Hair_000, how does O3DE make the bones of hair tied fixed to the head's bones, and then share the same animation. only Boy_Bip has animation, I need Point_Hair_000 do same animation with Boy_Bip.

1. I have my entity with an actor component on it (up in myimage)
2. create a child entity to that
3. create an actor component and anim graph component, assign the same anim graph to here than the main entity (for the hair, right side in my image)
4. add an attachment component to your new entity and attach it to the main character entity
4. Scroll down to '...'
5. See error

![image](https://user-images.githubusercontent.com/32164562/164426596-8d2deb90-4694-40a0-a4a7-30a34a55ebaf.png)

**Expected behavior**
Two Actors share animation normally

**Actual behavior**
Two Actors share animation unnormally

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32164562/164427690-4e3087cc-5bf8-4c6a-9073-9566f552c275.png)

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by hultonha** [comment] 2022-04-21 17:26
Discussed with @amzn-rhhong and this actually does look like a separate issue from https://github.com/o3de/o3de/issues/8182 as this is dealing with the Attachment Component and not a Skinned Attachment

**Comment by hultonha** [comment] 2022-04-25 14:01
Thank you very much for following-up on this @amzn-jillich, I'd be interested to hear what @sysuNie's thoughts are. Is there anything we can do to warn/inform the user that this is what's causing the problem and how to resolve it if someone else runs into this?

**Comment by sysuNie** [comment] 2022-05-05 14:06
I'm currently using the full skeleton for the implementation. But I think our engine needs to add the function of bone attach
![image](https://user-images.githubusercontent.com/32164562/166940999-6757f99d-592b-484b-8a0c-2b65a247496d.png)

I can't use static attachments, because my character still wears a hat. At this time, I need to drive the blendshape of the hair to prevent wearing through the mold
We need to implement the function of bone attachment that can be achieved on Maya in the engine.
This is a more common scenario

**Comment by hultonha** [comment] 2022-05-05 15:48
Thanks for the update @sysuNie, did you try any of the suggestions put forward by @amzn-jillich? Did those not work or were not possible?

**Comment by hultonha** [comment] 2022-05-23 16:28
Pinging @sysuNie, we think this could be an asset issue (coming from the DCC tool) - did the comment from @amzn-jillich help at all with this? Can you please try those suggestions? Thanks!

**Comment by hultonha** [comment] 2022-06-13 16:17
Hey @sysuNie, we are going to close this issue after seven days if there have been no further updates/comments.

**Comment by amzn-jillich** [comment] 2022-06-23 09:03
Closing as we cannot reproduce this anymore after the fix and did not hear back from @sysuNie.

**Closed by amzn-jillich** 2022-06-23 09:03 UTC
Labels: feature/animation, kind/bug, sig/graphics-audio, priority/critical, WF3, RTE, sig/simulation
