### ISSUE TITLE
Pressing the HOME key even in a text box opens ImGui and disables the editor

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#2432] opened 2021-07-26 16:02 UTC
When writing text in a text box if you press the HOME key, it will toggle ImGui in the viewport, when this happens the editor becomes mostly disabled. 

**To Reproduce**
1. Create an entity
2. Select it, press F2 to rename it
3. Click in the textbox, press the HOME key to move the cursor to the start of the text
4. ImGui opens in the viewport, the editor gets blocked

**Expected behavior**
Pressing HOME while in a text box behaves correctly and does not open ImGui

**Comment by lumberyard-employee-dm** [comment] 2021-07-26 20:53
Duplicate of https://github.com/o3de/o3de/issues/2270

**Closed by lumberyard-employee-dm** 2021-07-26 20:53 UTC
Labels: kind/bug, needs-triage, sig/content
