### ISSUE TITLE
[Animation] There is a problem with the skin weight of the model, which is very obvious when doing jumping movements, and there are edges and corners on the hips and knees.

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#5690] opened 2021-11-17 07:28 UTC
**Describe the bug**
There is a problem with the skin weight of the model, which is very obvious when doing jumping movements, and there are edges and corners on the hips and knees.

**Steps to reproduce**
1. Go to 'Create a entity'
2. Click on 'Add Actor and simple component'
3. Select attached asset 'Actor and Motion'
4. Scroll down to 'Camera'
5. See error

**Expected behavior**
Normal movement of the buttocks and knees.

**Actual behavior**
Unnormal movement of the buttocks and knees.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

**Found in Branch**
development.

**Desktop/Device (please complete the following information):**
- Device: [PC]
- OS: [Windows]
- Version [10]
- CPU [Gold 6234]
- GPU [NVidia RTX 5000]
- Memory [e.g. 128GB]

**Additional context**

**Comment by amzn-jillich** [comment] 2021-11-18 12:28
Uploading assets for @sysuNie as "I can’t upload assets due to some network reasons. So I sent you on discord there.".

[Ch29_nonPBR.zip](https://github.com/o3de/o3de/files/7562735/Ch29_nonPBR.zip)

**Comment by amzn-tommy** [comment] 2021-11-19 23:10
I took a look at the provided asset. There are two issues going on. The flattening at the knees is being caused by the o3de mesh optimization. Possibly the same bug as https://github.com/o3de/o3de/issues/4644

If I disable mesh optimization, the flat knees are resolved, but the upper thigh is still popping through the hips. I believe this is caused by o3de limiting the number of skin influences to 4. In the source asset, there are 5 influences for these vertices, and I'm guessing those extra influences are being used to prevent the mesh from extruding through itself.

I'm digging into the mesh optimization bug now.

**Comment by monroegm** [comment] 2021-12-08 16:50
@amzn-tommy It seems like you are already looking into this as a mesh optimization issue. Should SIG-Graphics-Audio triage this?

**Comment by amzn-tommy** [comment] 2021-12-13 21:35
The skin weight issue is fixed by https://github.com/o3de/o3de/pull/6336. The knees should be smooth now. 

As I mentioned above, there are some places on the asset that use more than 4 influences per vertex. In particular, this ends up as an artifact in the upper thigh at a deep squat.

O3DE only supports a maximum of 4 influences per vertex at the moment, though that is something we would like to fix.

**Comment by svitlani** [comment] 2022-02-01 18:30
@sysuNie can you please confirm you are not seeing issues anymore, so we can close this issue appropriately?
Thank you!

**Comment by sysuNie** [comment] 2022-02-10 02:13
> @sysuNie can you please confirm you are not seeing issues anymore, so we can close this issue appropriately? Thank you!

The latest version has fixed this Issue.

**Comment by yuyihsu** [comment] 2022-05-18 05:56
Closing this issue as both the dev and the user confirmed the issue has been fixed.

**Closed by yuyihsu** 2022-05-18 05:56 UTC
Labels: kind/bug, sig/content, sig/graphics-audio, status/active, priority/critical, WF3, RTE
