### ISSUE TITLE
Material Editor failed to launch

### ISSUE THREAD

**Issue by CodeLikeCXK** [o3de/o3de#15069] opened 2023-03-11 16:00 UTC
**Describe the bug**
Failed to launch material editor. In asset processor-connection tab, the material editor was seen but then disappear

**Assets required**
Just a new blank project.

**Steps to reproduce**
1. Create a new project
2. Click on 'material editor'
3. Failed to launch. See error

**Expected behavior**
In asset processor-connection tab, the material editor was seen but then disappear. Material editor failed to launch.

**Actual behavior**
 Material editor launch.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![QQ截图20230312000006](https://user-images.githubusercontent.com/44729188/224494617-9517e60b-7edc-4293-b0d2-972a65f9495e.png)
![QQ截图20230312000012](https://user-images.githubusercontent.com/44729188/224494625-3a494108-5450-45c9-8540-652c36153e12.png)

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d4b4033f77d9dd6ab93cd2b47682f863fa862d6a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Ryzen 6800u
 - GPU Radeon 680
 - Memory 16GB

**Additional context**

**Comment by galibzon** [comment] 2023-03-14 17:06
Closing as duplicate of https://github.com/o3de/o3de/issues/7113

**Closed by galibzon** 2023-03-14 17:06 UTC
Labels: kind/bug, needs-triage, sig/graphics-audio
