### ISSUE TITLE
UI Editor window opens off-center, even when maximized, in various Portrait modes using 4k resolution with 200% scaling

### ISSUE THREAD

**Issue by dm-amzn** [o3de/o3de#11773] opened 2022-09-06 05:29 UTC
**Describe the bug**
UI Editor window opens off-center, even when maximized, in various Portrait modes using 4k resolution with 200% scaling.

**Steps to reproduce**

1. In Windows, open Display Settings
2. Identify and select your display in the preview
3. For Scaling, set to 200%
4. In Scale and Layout, set the Display resolution to 3840 x 2160
5. Set the Display orientation to either Portrait or Portrait (flipped)
6. Select Keep Settings
7. Launch the Editor
8. Create a new level, or load an existing level
9. Open the UI Editor (Tools > UI Editor)
10. Observe issue
11. Maxmize the UI Editor window
12. Observe issue

**Expected behavior**
The UI Editor window opens, centered to screen, with access to all tools and features, especially when maximized.

**Actual behavior**
UI Editor window opens off-center, even when maximized, in various Portrait modes using 4k resolution with 200% scaling.

**Screenshots/Video**

![image (7)](https://user-images.githubusercontent.com/97991771/188553930-2e42eee2-73c8-42eb-a0f3-4fdc6e2704d4.png)

**Found in Branch**
stabilization/2210

**Comment by AMZN-daimini** [comment] 2022-09-07 18:47
Since it only happens on the UI Editor, we assumed it may be caused by custom code. If upon further investigation it seems to be related to viewpane code, feel free to redirect to `feature/editor`.

**Comment by monroegm** [comment] 2022-09-21 22:29
Marking as resolved based on linked PR being merged

**Closed by monroegm** 2022-09-21 22:29 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/lyshine
