### ISSUE TITLE
[Linux] Editor crashes after changing the viewport resolution to a high one when using a high-resolution display

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#10115] opened 2022-06-14 12:53 UTC
**Describe the bug**
When using a high-resolution display, changing the viewport resolution to a high one such as 2k, 4k, 6k, etc. causes the editor to crash. This issue occurs only on Linux.

Reproduced with the following displays:
- LG 27UL500-W
- Samsung UE43MU6190UXZG

**Steps to reproduce**
1. Set your monitor display to a high resolution, for example 4k.
2. Set your monitor display Scale to a value higher then 100%, for example 200%.
3. Open any level.
4. Navigate to the Viewport resolution dropdown menu.
5. Change resolution to a high one, for example 4k.

**Expected behavior**
Viewport resolution is changed and the editor remains stable.

**Actual behavior**
The editor crashes after changing the viewport resolution to a high one.

**Video**

https://user-images.githubusercontent.com/96232062/173560249-3cd8e92e-cda1-4c8f-82c6-1b14e5d53107.mp4

**Found in Branch**
Development(https://github.com/o3de/o3de/commit/501ee917dc9559309ae971017d7c81764355e405)

**Desktop/Device:**

- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[O3DE.log](https://github.com/o3de/o3de/files/8899518/O3DE.log)

**Comment by rainbj** [comment] 2022-06-17 16:27
We agree with the ticket problem that is being reported . So please work on that part. However! We also noticed that the play button in the video also is not showing the dropdown as if it wasn't the latest build. I assume either play button is broken OR this is an older build. Please confirm which problem this is.
![capture-016-17-2022](https://user-images.githubusercontent.com/82551958/174338749-a57d2f5e-4aec-45e6-a9a5-153aaf7cfc56.png)
.

**Comment by LB-HubertUberman** [comment] 2022-06-20 10:58
Hello @rainbj, the issue with the Play Game button that you mentioned was investigated further and a new ticket was created for it, https://github.com/o3de/o3de/issues/10212.

**Comment by rainbj** [comment] 2022-10-03 17:54
@LB-HubertUberman - Just curious if this issue was ever resolved. I still see this ticket open. Thanks

**Comment by LB-HubertUberman** [comment] 2022-10-04 11:34
@rainbj  Verified that the issue still occurs on Development(https://github.com/o3de/o3de/commit/78f7061b0a95e881a2f1d37aad00a5e98e958a39) and Stabilization(https://github.com/o3de/o3de/commit/d327e2f9db22d8491ed9e3e925b97db2ec5076fd) branches.

**Comment by spham-amzn** [comment] 2023-01-05 00:36
As of commit https://github.com/o3de/o3de/commit/e3d3c8031bf64d07f966badfb07925dbd6b21f13 this cannot be reproduced.

-  Device: PC
-  OS: Linux
-  Version: Ubuntu 20.04.3 LTS
-  CPU: AMD Threadripper
-  GPU: NVIDIA GeForce RTX 3070
-  Memory: 64GB

See attached video

**Comment by spham-amzn** [comment] 2023-01-05 00:40
@LB-HubertUberman Closing as cannot reproduce, please re-open and attach any additional context if it is still occuring

**Comment by LB-HubertUberman** [comment] 2023-01-05 09:13
@spham-amzn Reopening the issue as it still occurs on the Development branch (https://github.com/o3de/o3de/commit/af94a59086da9fc7e5af403a56ce12e6aba2f800). Repro steps and description remains the same.
[O3DE.log](https://github.com/o3de/o3de/files/10350838/O3DE.log)

**Comment by spham-amzn** [comment] 2023-01-05 17:18
@LB-HubertUberman The attached log provides no useful information. Can this be repro'd on a different machine?

**Comment by spham-amzn** [comment] 2023-01-05 23:14
@LB-HubertUberman Still unable to reproduce on a different Linux box (commt 7c2c3da079f5a5a46f66d5e377b956bd274fdf25)

- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.1 LTS
- CPU: AMD Threadripper
- GPU: NVIDIA GeForce RTX 3080
- Memory: 64GB

**Comment by spham-amzn** [comment] 2023-01-06 23:07
@LB-HubertUberman Unable to reproduce on a 3rd machine, this time on an Intel pc

* Device : PC
* OS: Linux
* Version: Ubuntu 22.04.1 LTS
* CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
* GPU: NVIDIA Corporation TU104M [GeForce RTX 2080 Mobile]
* Memory: 16GB

**Comment by LB-HubertUberman** [comment] 2023-01-09 14:29
@spham-amzn Hi, I managed to reproduce the issue on another machine. 

- Device : PC
- OS: Linux
- Version: Ubuntu 20.04.3 LTS
- CPU: AMD Ryzen 5 3600
- GPU: MSI RTX 2060 SUPER VENTUS GP OC 8GB
- Memory: 16GB

Turns out that there is one additional step require for the reproduction and the crash will occur if in the Linux display settings, the Scale parameter is set to a higher value than a 100%, for example 200%.  Updated the repro steps with new info.

**Comment by spham-amzn** [comment] 2023-01-09 17:20
> @spham-amzn Hi, I managed to reproduce the issue on another machine.
> 
>     * Device : PC
> 
>     * OS: Linux
> 
>     * Version: Ubuntu 20.04.3 LTS
> 
>     * CPU: AMD Ryzen 5 3600
> 
>     * GPU: MSI RTX 2060 SUPER VENTUS GP OC 8GB
> 
>     * Memory: 16GB
> 
> 
> Turns out that there is one additional step require for the reproduction and the crash will occur if in the Linux display settings, the Scale parameter is set to a higher value than a 100%, for example 200%. Updated the repro steps with new info.

@LB-HubertUberman Setting to 200% scale parameter did not cause a crash for me either. Instead, it made the window larger than the size of the display, but since I have a multiple monitor setup, I was able to resize the window back

**Comment by LB-KacperMetelski** [comment] 2023-01-10 12:29
@spham-amzn Hi, we had noticed the issue has been more prominent on the 470 Proprietary driver. We'd like to ask, which drivers were you using on machines used to reproduce this issue?
Moreover, we had noticed that the same issue occurs with the 1920x1080 with scale larger than 100% on specs listed below.

Device: PC
OS: Linux
Version: Ubuntu 20.04.5 LTS
CPU: i7-17000F
GPU: RTX-3070 MSI
GPU Driver: Nvidia 470.161.03 Proprietary
Memory: 32GB

**Comment by LB-KacperMetelski** [comment] 2023-01-11 14:44
@spham-amzn Today we observed that this issue has not occured on any of our devices, although one device (the one with specs listed above) keeps crashing when the resolution of the Viewport is changed to 4k while the display is set to FHD and 125% and 150% scale and the Editor is undocked. How would you like to proceed with this issue?

**Comment by spham-amzn** [comment] 2023-01-11 16:58
@LB-KacperMetelski In situations where there is a low reproducibility, we lower the priority of the bug

**Comment by byrcolin** [comment] 2024-06-04 16:39
Low occurrence = minor

**Closed** 2024-10-01 16:39 UTC
Labels: platform/linux, kind/bug, sig/platform, sig/ui-ux, triage/accepted, priority/minor, status/ux-approved
