### ISSUE TITLE
New Camera System input dropping 

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#8114] opened 2022-03-07 22:56 UTC
[Migrated from JIRA LYN-4322]
See attach vid as reference
Repro case requires new camera system to be on when the editor starts. User.cfg attached needs to be in the project to enable. 

- As seen in the video pressing ALT causes the camera look target orb to activate. 
- Pressing and releasing ALT repeatedly its clear sometimes the orb doesn't get activated. 
- Note that the viewport UI switching to local space is also activate by the ALT key but its correctly receiving the inputs for press / release as expected. 
- Expected behavior is that there is a 100% 1 to 1 action with the key presses. 

This has also been reproduced with RMB (turn camera) and ALT RMB Dolly although harder to debug since there isn't secondary visual indication for all inputs.  

So far it has not been reproduced with the legacy editor camera system but its very challenging to debug inputs and actions since nothing has clear visual indication.  

https://user-images.githubusercontent.com/82228511/157275315-7fb9426d-6c22-4673-b209-a7439853ca3f.mp4

**Comment by hultonha** [comment] 2022-03-08 15:58
@benblack75 I do not believe this is still an issue but would you please be able to verify if you have a moment (the bug won't be exactly the same as we no longer have the sphere but the way Alt behaves (starting orbit/tumble or not) should give an indication).

**Comment by hultonha** [comment] 2023-03-14 14:39
Closing as could not reproduce. I believe the issue is now resolved.

**Closed by hultonha** 2023-03-14 14:39 UTC
Labels: feature/editor, kind/bug, sig/content, status/active, priority/major
