### ISSUE TITLE
Main editor viewport clusters can appear on top of animation editor

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#12711] opened 2022-10-20 11:17 UTC
If you close the editor with the animation editor open, so that the animation editor is already open on the next start, the viewport clusters from the main editor appear on top of the animation editor

![image](https://user-images.githubusercontent.com/82226198/196934507-17b49e28-2386-489a-bce8-087f0ba37d20.png)

**Comment by hultonha** [comment] 2022-11-08 16:01
This is related to https://github.com/o3de/o3de/issues/2603

**Comment by hultonha** [comment] 2023-03-31 11:27
Closing as duplicate of https://github.com/o3de/o3de/issues/2603

**Closed by hultonha** 2023-03-31 11:27 UTC
Labels: kind/bug, sig/content, status/duplicate, triage/accepted, priority/minor, feature/viewport
