### ISSUE TITLE
Material may flicker after using a texture

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#7185] opened 2022-01-27 03:14 UTC
**Describe the bug**
I created a material with texture and assign it to an entity, flickering may occur.

**Steps to reproduce**
1. Create an Entity
2. Create a material and assign a texture to the base color
3. Add the Material Component to the entity
4. Assign the material to the entity
5.See error

**Expected behavior**
The material is used normally.

**Actual behavior**
The material may flicker.

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![issue](https://user-images.githubusercontent.com/55627654/151281140-bde7c06a-02f0-4296-ac5f-4fba2c46ad7d.JPG)
![issue2](https://user-images.githubusercontent.com/55627654/151281222-15997e8e-ea58-439b-b5a8-3f8ec7a8fc49.JPG)
![issue3](https://user-images.githubusercontent.com/55627654/151281283-3573b9b1-0a1b-4fb6-9dab-c6812863432c.JPG)
I cannot upload video, here are some screenshots of the scene, during which I did not modify the material
**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-10700 
 - GPU NVIDIA GTX1650
 
**Additional context**

**Comment by AMZN-alexpete** [comment] 2022-01-27 05:42
I'm seeing this too, it seemed most noticeable when the material had transparency.  In this case I'm attempting to use one of the trees from StarterGame AM_Plains_Cotton_Tree

https://user-images.githubusercontent.com/26804013/151298609-1c2ef5ab-c9d6-48b4-9146-0973c6101995.mp4

**Comment by superkitcath** [comment] 2022-02-02 18:19
@liukaikai-g ; could you confirm your drivers version? Thanks!

**Comment by liukaikai-g** [comment] 2022-02-09 02:29
The version is 2111.1

**Comment by superkitcath** [comment] 2022-02-09 18:23
Hi @liukaikai-g! I was referring to the NVidia drivers :-) It should be either the minimum requirements, 471.11 or later. Could you confirm? Thanks!!

**Comment by liukaikai-g** [comment] 2022-02-14 01:16
The Nvidia driver version is 472.84

**Comment by superkitcath** [comment] 2022-02-16 18:19
Thanks @liukaikai-g ; we will try to reproduce at that driver version. Did you try to reproduce it with the latest drivers? 
Also, would it be possible to provide the test scene?

**Comment by santorac** [comment] 2022-02-23 19:51
Here is another flickering issue, not sure if they are related https://github.com/o3de/o3de/issues/4322

**Comment by santorac** [comment] 2022-03-05 01:10
Is this issue still happening? How readily can you reproduce it? Is there a test level you can attach the shows the issue?

**Comment by AMZN-alexpete** [comment] 2022-03-05 03:33
I cannot repro the flickering issue anymore with that tree asset in latest dev branch.

**Comment by liukaikai-g** [comment] 2022-03-07 02:37
I also can't reproduce this problem in my scenes, it doesn't seem to come up very often

**Comment by superkitcath** [comment] 2022-03-07 22:10
Cannot reproduce, closing.

**Closed by superkitcath** 2022-03-07 22:10 UTC
Labels: kind/bug, sig/graphics-audio, triage/needs-information, status/not-reproducible, feature/graphics/materials

**Comment by santorac** [comment] 2022-03-07 23:51
We have seen flickering issues like this off and on for a long time now, and they are always hard to reproduce. So closing this ticket doesn't necessarily mean the issue is fixed; it might pop up again later.

**Comment by santorac** [comment] 2022-11-01 17:53
> It should be either the minimum requirements, 471.11 or later. Could you confirm? Thanks!!

> The Nvidia driver version is 472.84

The topic of flickering textures came up again today, so I'm adding a bit of info here in case it's useful. Keep in mind, it isn't confirmed whether this is the same as the NVidia issue, but they do look similar. The NVidia flickering bug seemed to be most prevalent in World of Warcraft forums. According to [this post](https://us.forums.blizzard.com/en/wow/t/main-thread-nvidia-460xx-driver-flickering/766732/964) the bug appears to be fixed as of Nvidia driver 471.11. Although, as noted in the above comments, the OP had driver version 472.84 which is later, so who knows.

Here are some examples of the issue in WoW for comparison:
https://www.youtube.com/watch?v=8QjGQvxdoJc
https://www.youtube.com/watch?v=SLManmQ2mBs
https://www.reddit.com/r/classicwow/comments/nmu5nz/flickering_texture_bug_for_nvidia_cards_from/

**Comment by santorac** [comment] 2022-11-01 18:08
Also, somewhere I read that DX12 background shader optimization might contribute to this kind of flashing, so if it shows up again, consider using the APIs described here for troubleshooting. https://devblogs.microsoft.com/directx/background-shader-optimizations/
