### ISSUE TITLE
[Assert] Browsing Terrain Gem assets in Asset Browser results in 2 asserts being printed in the console

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#6969] opened 2022-01-18 13:58 UTC
**Describe the bug**
Browsing the assets included in the **Terrain Gem** with the **Asset Browser** results in 2 asserts being printed in the console.
Please note that before asserts are printed in the console, the **Editor** freezes for around 1-2 seconds.

**Assert 1:**

**File:**
`C:/builds/o3de/Gems/Atom/RHI/Code/Source/RHI.Reflect/ShaderInputNameIndex.cpp`

**Condition:**
```
(15768) 'void __cdecl AZ::RHI::ShaderInputNameIndex::AssertValid(void) const'
(System) - ShaderInputNameIndex [m_objectId] does not have a valid index. Please initialize with the Shader Resource Group.
```

**Line:**
`216`

**Assert 2:**

**File:**
`C:\builds\o3de\Gems\Atom\RHI\DX12\Code\Source\RHI/CommandList.h`

**Condition:**
```
(11568) 'bool __cdecl AZ::DX12::CommandList::CommitShaderResources<AZ::RHI::PipelineStateType::Draw,struct AZ::RHI::DrawItem>(const struct AZ::RHI::DrawItem &)'
(System) - ShaderResourceGroup in slot '7' is null at DrawItem submit time. This is not valid and means the shader is expecting an Srg that isF not currently bound in the pipeline. Current bindings: Slot #0 = 'LightCullingTilePrepare_DrawSrg', Slot #1 = 'TerrainPBR_ForwardPass_ObjectSrg', Slot #2 = 'TerrainPBR_ForwardPass_TerrainMaterialSrg', Slot #4 = 'ForwardPassSrg_PassSrg', Slot #5 = 'SceneAndViewSrgs_ViewSrg', Slot #6 = 'SceneAndViewSrgs_SceneSrg'
```

**Line:**
`423`

**Prerequisites:**
The **Terrain Gem** is enabled in the project.

**Steps to reproduce**
1. Create a new level.
2. Type "Terrain" in the **Asset Browser** search bar.
3. Scroll down to find the assets included in the **Terrain Gem**.

**Expected behavior**
The Editor remains stable when browsing assets in the **Asset Browser**, no asserts are printed in the console.

**Actual behavior**
The asserts are printed in the console when browsing **Terrain Gem** assets in the **Asset Browser**.

**Video**

https://user-images.githubusercontent.com/86951967/149944327-224e1c7f-b2ff-4bf3-b73a-e8538258158d.mp4

**Found in Branch**
Development (4cd3568)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/7889291/Editor.log)

**Comment by invertednormal** [comment] 2022-07-05 18:32
I recently was unable to repro this issue. @LB-JakubSkorupka please let me know if this is still happening for you- Thanks!

**Comment by invertednormal** [comment] 2022-07-06 16:30
Closing as cannot reproduce. It's been almost 6 months since this was reported and the code has changed a great deal.

**Closed by invertednormal** 2022-07-06 16:30 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/terrain
