### ISSUE TITLE
Creating a physxmesh on an .fbx asset causes the editor to process it indefinitely

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#3643] opened 2021-08-27 13:24 UTC
**Describe the bug**
It has been noticed that creating a physxmesh on an .fbx asset causes it to be processed for an indefinite amount of time.  It should be noted that the Editor remains responsive while the asset is being processed, but cannot be closed during it. Killing the Editor.exe via the Task Manager process shuts down the Editor and the physxmesh is properly created upon relaunching the Editor.

**To Reproduce**
1. Go to Asset Browser and find an .fbx file without a generated physxmesh (e.g. BeveledCube.fbx).
2. Right-click the chosen .fbx and select Edit Settings...
3. Go to the PhysX tab in the Fbx Settings (PREVIEW) window.
4. In the Select meshes, select the mesh of the .fbx.
5. Click Update.

**Expected behavior**
The Editor remains usable and the physxmesh asset is properly generated.

**Video**

https://user-images.githubusercontent.com/86952082/131132916-e78cf6bb-3862-487b-91b4-d3aef1336346.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by ppinfel** [comment] 2021-08-28 19:26
Some extra info this was not an issue for me on the main branch using source build with my own custom mesh

**Comment by moraaar** [comment] 2021-10-08 12:03
I cannot reproduce this issue with the latest from development branch @6be8c9d6

I'm going to close this issue because the bug doesn't occur, BUT it's true that the current implementation of "FBX Editor Setting" waits until Asset Processor has finished (which it can be seen in the video at the bottom "Pending Jobs: 1", meaning AP didn't finish to process the fbx yet).

@LB-ArturSiewniak if you think "FBX Editor Settings" should have an option to cancel the process once it has started, please open a new github feature for the owner of "FBX Editor Settings", which I think it is sig/content.

Thanks

**Closed as completed by moraaar** 2021-10-08 12:03 UTC
Labels: feature/physics, kind/bug, triage/accepted, priority/critical, WF2, RTE, sig/simulation
