### ISSUE TITLE
[Material Editor] Precision of float in the property reflection widget is not correct.

### ISSUE THREAD

**Issue by jiangwenming2021** [o3de/o3de#8295] opened 2022-03-12 06:46 UTC
Describe the bug
The precision of float in the property reflection widget is not correct.

when enter 0.7 to the float widget, it shows 0.6999999. 
After focus leaving ,it shows 0.699.

Actual behavior
![image](https://user-images.githubusercontent.com/80514815/158007322-4ac112da-2e92-4c94-b813-10987368c63a.png)

Assets required
NA

**Comment by gadams3** [comment] 2022-03-24 03:30
@superkitcath @monroegm This is a known issue for @o3de/sig-content where the floating point property spinner/slider control is not respecting the precision or step attribute.

**Comment by santorac** [comment] 2022-03-24 17:49
Seems to be a duplicate of https://github.com/o3de/o3de/issues/2648

**Comment by hultonha** [comment] 2022-03-29 11:46
I know @jjjoness did some work on something very similar fairly recently, does this sound familiar John?

**Comment by jjjoness** [comment] 2022-03-29 12:30
It rings a bell! I believe it was caused by passing the value through 2 or 3 stages with each one losing a bit of precision.

**Closed** 2022-07-14 15:02 UTC
Labels: kind/bug, sig/graphics-audio, priority/major, feature/graphics/tools
