### ISSUE TITLE
Multiple Errors are displayed due to missing PythonAssetBuilder after launching Asset Processor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#2256] opened 2021-07-19 08:46 UTC
[Migrated from Jira-LYN-7239]
**Describe the bug**
Running Asset Processor causes multiple Errors regarding missing PythonAssetBuilder module to pop up.
In addition to the Errors, the following jobs fail in the Asset Processor:
`C:/Builds/Git/o3de/AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C1564073/test_slice.slice`
`C:/Builds/Git/o3de/AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C1569087/C1569087_corrupted.slice`
`C:/Builds/Git/o3de/AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C24168802/Jack.fbx`
The issue occurs both in AutomatedTesting Project as well as newly created Projects.
Please refer to the attached files for more details. 

**To Reproduce**
1. Open the Project Manager.
2. Launch the AutomatedTesting Project.

**Expected behavior**
All the assets are processed successfully. No Errors are displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/86953108/126130501-bd2b84f7-bcf0-4849-a8aa-5c975331b665.png)

https://user-images.githubusercontent.com/86953108/126130516-7dfa96ed-8f0b-43d9-9a40-0f6a7bbc9315.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[Jack.fbx-1507222451-12071.log](https://github.com/o3de/o3de/files/6839286/Jack.fbx-1507222451-12071.log)
[C1569087_corrupted.slice-2739536344-2360.log](https://github.com/o3de/o3de/files/6839288/C1569087_corrupted.slice-2739536344-2360.log)
[test_slice.slice-2693354849-10435.log](https://github.com/o3de/o3de/files/6839289/test_slice.slice-2693354849-10435.log)

**Comment by amzn-pratikpa** [comment] 2021-10-01 22:59
Cannot reproduce - please re-open if you see it occurring again.

**Comment by LB-TomaszSerwanski** [comment] 2021-10-04 09:13
Hi @amzn-pratikpa. We have found out, that the issue only occurs in Projects with the Atom DCCScriptingInterface and Python Asset Builder Gems enabled, therefore it no longer happens when launching the AutomatedTesting but still occurs in new Projects with these two Gems enabled (on Development (7dc5c8b)). Re-opening as requested.

**Comment by amzn-phist** [comment] 2021-10-13 21:52
I get different errors with AutomatedTesting than reported here.  Looks to be related to looking for `~/.o3de/Registry/bootstrap.setreg` and not finding it.  Maybe that's part of the setup instructions for using DccScriptingInterface Gem.  I will try again with a brand new project.

**Comment by svitlani** [comment] 2022-01-31 19:53
Hello, @amzn-phist, can you please provide a status update on this ticket? Did you have a chance to verify this while building brand new project? Thank you!

**Comment by svitlani** [comment] 2022-02-01 18:57
@AMZN-stankowi , do you have any update on this issue? Thank you!

**Comment by AMZN-stankowi** [comment] 2022-02-01 19:04
We have a potential improvement that is waiting on UX review. We will post an update when we have more info.

**Comment by lmbr-pip** [comment] 2022-09-07 17:00
This does not appear to be happening any longer, resolving as fixed. Please reopen if this continue to occur. Believe fixed as part of https://github.com/o3de/o3de/pull/6484

**Closed by lmbr-pip** 2022-09-07 17:00 UTC
Labels: feature/graphics, kind/bug, sig/core, triage/accepted, priority/blocker, feature/systems, WF1, RTE
