### ISSUE TITLE
AssetProcessor does not support multiple source assets that have the same name but different extensions.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#15311] opened 2023-03-23 10:46 UTC
**Describe the bug**

To improve the user experience of URDF import, we need to allow creation of product assets from source assets that have the same filename and different extensions. It is common practice to have packages that describe robots in URDF format that have their visual mesh in DAE and collision mesh in STL:

```
base_link.dae
base_link.stl
```

Such practice fails with AssetProcesor . It will generate a Product asset for the first file and fail for the second one. It creates confusion for URDF users and requires manual renaming and makes the experience worse.

**Assets required**

[fail_urdf.zip](https://github.com/o3de/o3de/files/11049747/fail_urdf.zip)

**Steps to reproduce**

1. Decompress [fail_urdf.zip](https://github.com/o3de/o3de/files/11049747/fail_urdf.zip) to location that Asset Processor observes
2. Start Editor
3. Wait for asset process finish reprocessing
4. Open Jobs tab in Asset Processor and locate failed job : `Assets/fail_urdf/base_link.stl` or `Assets/fail_urdf/base_link.dae`
5. See error for failed source asset :
```
~~1679567531561~~3~~0x7f448a1ee640~~Error~~Failed processing /home/michal/github/o3de-physics-test-scene/Assets/fail_urdf/base_link.stl
~~1679567531572~~3~~0x7f448a1ee640~~Error~~A different source file
~~1679567531575~~3~~0x7f448a1ee640~~Error~~Assets/fail_urdf/base_link.dae
~~1679567531578~~3~~0x7f448a1ee640~~Error~~is already outputting the product
~~1679567531580~~3~~0x7f448a1ee640~~Error~~/home/michal/github/o3de-physics-test-scene/Cache/linux/assets/fail_urdf/base_link_defaultmaterial_3809502407269006983.azmaterial
~~1679567531582~~3~~0x7f448a1ee640~~Error~~Please check other files in the same folder as source file and make sure no two sources output the product file.
~~1679567531584~~3~~0x7f448a1ee640~~Error~~For example, you can't have a DDS file and a TIF file in the same folder, as they would cause overwriting.
~~1679567531586~~3~~0x7f448a1ee640~~Error~~Builder indicated that the job has failed.
```

**Expected behavior**

It would be great to produce a warning and have Asset Processor add some suffixes to the Product asset.

**Actual behavior**

Fails and produces confusion during URDF import (e.g. https://github.com/o3de/o3de-extras/issues/121)

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/3209244/227178739-6ebee1f1-e802-40a0-8abb-5ce96b483808.png)

**Found in Branch**

Development 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**

```
952a535aa3616e399cdc22b2b1f05494f60d9cf3
```

**Desktop/Device (please complete the following information):**

 - Device: PC
 - OS: Ubuntu
 - Version Ubuntu 22.04

**Comment by AMZN-stankowi** [comment] 2023-03-23 15:42
That behavior is currently as-designed, so we'll either need to adjust the design of AP as a whole to handle cases like this, adjust the design of the scene builder in particular , or the URDF tool will need to adjust its design to work around it.

The current behavior is generally desired in many workflows, it means that content creators don't have to think about product names, and for images especially it's useful: PNGs, TIFs, JPGs, etc, all result in the same products. This says to me I wouldn't want to adjust AP itself.

I feel like the system is working correctly right now, because your desired outcome (collision data from the STL, visual mesh from the DAE) actually doesn't match what you're giving it - this error is saying that you're getting a visible mesh from the STL and the DAE, which you don't seem to want. Luckily, that's exactly what the assetinfo file and scene settings are built to manage.

In my mind, the best path forward would be to have the URDF tool generate a sidecar assetinfo file that contains the processing info for the STL, and a second for the DAE. This would let you prevent the output asset collision because you could scope the STL to just output a visible mesh, and the DAE to just output the physics mesh.

Here's an example of this, I took a simple cube.fbx, disabled the visible mesh information, added a PhsyX Mesh, so I'm getting just the physics output, no visible mesh product asset. The assetinfo file that contains scene settings is purposefully in JSON to allow for automated tools like yours to output it easier.

![image](https://user-images.githubusercontent.com/4838196/227256933-224e95fa-a6e9-4b3e-9361-6bd2f3495a9a.png)

**Comment by michalpelka** [comment] 2023-03-23 19:06
Thanks @AMZN-stankowi , assetinfo looks like very promising direction.
I've tried, however, and written pair of asset info for my failed case, I still get errors.
![image](https://user-images.githubusercontent.com/3209244/227321033-c4eec67a-f363-49c2-bc97-0af44fe23acd.png)

[fail_urdf.zip](https://github.com/o3de/o3de/files/11054971/fail_urdf.zip)
And failed jobs:
[base_link.dae-1228267746-24116.log](https://github.com/o3de/o3de/files/11055001/base_link.dae-1228267746-24116.log)
[base_link.dae-1228267746-24117.log](https://github.com/o3de/o3de/files/11055002/base_link.dae-1228267746-24117.log)
[base_link.dae-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log](https://github.com/o3de/o3de/files/11055003/base_link.dae-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log)
[base_link.stl-3070110025-24119.log](https://github.com/o3de/o3de/files/11055004/base_link.stl-3070110025-24119.log)
[base_link.stl-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log](https://github.com/o3de/o3de/files/11055005/base_link.stl-BD8BF658-9485-4FE3-830E-8EC3A23C35F3_createJobs.log)
It seems, that it still creates some conflicting product asset.

**Comment by lawsonamzn** [comment] 2023-03-27 22:42
I can confirm this is because the material seems to be the same output in each case.  Everything else is correct, but it seems to not take the name of the meshgroup into account and in fact creates a default material with the name of the source file even if there is no mesh group at all (clearly a bug in o3de)

**Comment by mbalfour-amzn** [comment] 2023-08-30 17:26
This should be fixed with https://github.com/o3de/o3de/pull/16517 .

**Closed by mbalfour-amzn** 2023-08-30 17:26 UTC
Labels: feature/asset-pipeline, kind/feature, sig/content, triage/accepted, priority/major, ROS2, feature/robotics
