### ISSUE TITLE
Input handler is handling mouse_delta inputs inconsistently

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#14879] opened 2023-03-01 13:27 UTC
**Describe the bug**
All different mouse_delta Inputs (*mouse_delta_x*, *mouse_delta_y* and *mouse_delta_z*) are sending inputs differently when used through the *Input Handler* Script Canvas node's pins.

* *mouse_delta_x* - Updates constantly, all mouse movements are picked up the same way. When used via *Held* pin instead of *Pressed* it updates sporadically.
* *mouse_delta_y* - Updates sporadically on quick mouse movements and/or does not seem to be picking up input when horizontal movement is applied along the vertical one. It appears that slow mouse movement allows for more frequent updates. Alternating movement between up/down seems to be updating more frequently as well. When used via *Held* pin instead of *Pressed* it updates constantly.
* *mouse_delta_z* - Updates sporadically when quickly scrolling the mouse wheel. Slow scrolling or quick alternation between scrolling up/down appears to update the output more frequently as well. When used via *Held* pin instead of *Pressed* it updates constantly on quick mouse scrolls, but very infrequently when scrolling slowly.

**Assets required**
Script Canvas and Input Bindings shown on the image below are required to reproduce this issue:
![mouse_delta_xSCandIB](https://user-images.githubusercontent.com/86952082/222140781-9fc7e736-b0ac-489d-831d-c0df473321f3.png)

**Steps to reproduce**
1. Create an entity, add *Script Canvas* and *Input* components to it.
2. Assign assets mentioned in the **Assets required** section to their respective components.
3. Enter the Game Mode (for example *Ctrl + G*).
4. Move the mouse left and right and note the Console output.
5. Open the .inputbindings file mentioned in the **Assets required** section, change the *Input Name* from *mouse_delta_x* to *mouse_delta_y* and save the changes.
6. Enter the Game Mode (for example *Ctrl + G*).
7. Move the mouse up and down and note the Console output.
8. Open the .inputbindings file mentioned in the **Assets required** section, change the *Input Name* from *mouse_delta_y* to *mouse_delta_z* and save the changes.
9. Enter the Game Mode (for example *Ctrl + G*).
10. Scroll the mouse wheel up and down and note the Console output.

**Expected behavior**
All mouse_delta Inputs behave similarly when used in the same *Input Handler*/*Pressed*/*Held* script.

**Actual behavior**
All mouse_delta Inputs behave differently when used in the same *Input Handler*/*Pressed*/*Held* script.

**Video**

https://user-images.githubusercontent.com/86952082/222145372-18c36283-0bfe-4c98-b351-09a2acbeba52.mp4

**Found in Branch**
Development (a775010)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
a775010c5c3ea6b067df2ef0a398fbe02bb54434

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by nick-l-o3de** [comment] 2024-04-02 17:17
I can reproduce this on linux on this machine, so its definitely not just 1 machine.

Looking at the input monitor, which shows the low level input streams, I see a difference between the axes
![image](https://github.com/o3de/o3de/assets/70027408/e5f33312-6375-41a9-912b-663deb210ec6)

The above screenshot is moving the mouse vertically and continuously.  notably, the state is "Updated" most of the time, meaning that the mouse was active last frame, and is still active this frame.  It would be using the `Held` pin of the script canvas, since this is what happens when you move an input continuouslyh.

However, when I move the mouse horizontally, this happens:
![image](https://github.com/o3de/o3de/assets/70027408/92c759c5-34c9-4306-9e30-05d081756ca4)

The mouse is reporting "BEGAN" for every frame (like, 99% of the time), which would imply its starting, stopping, and starting again as opposed to smoothly moving.  This would cause it to trigger the "pressed" input repeatedly (as well as the released).

Mouse Z is sort of a mix, which can be expected.  My mouse is a notched wheel, not a smooth continuous wheel.  If I move it FAST, I see `Began --> Updated, Updated, Updated, Updated -> Released -> Idle`
But if I move it slowly, I see `Began -> Updated -> Released -> Began -> Updated -> released` as it clicks.

So yeah, I can confirm this is coming from the low level mouse driver, its behaving as if the X channel is continuously being released for some reason.  It means the Y channel is actually the correct one, that is, if you connect the graph to the "HELD" and "RELEASED" ports, you'll see it be normal, as in, "Pressed -> Held (until you stop moving) -> released"

**Comment by nick-l-o3de** [comment] 2024-04-02 17:50
Looking at the underlying XCB input system, the raw events coming from the linux XCB system seem consistent for the 2 axes, that is, if I log the raw data coming from the input system of the operating system, I get a pattern like this for horizontal (X) movement:

```
XCB Input - axis 0 triggered with value -5 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
XCB Input - axis 0 triggered with value -5 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
XCB Input - axis 0 triggered with value -5 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
XCB Input - axis 0 triggered with value -5 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
XCB Input - axis 0 triggered with value -4 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
XCB Input - axis 0 triggered with value -4 with mask[0] of 3
XCB Input - axis 1 triggered with value 0 with mask[0] of 3
...
```

Note that input events always appear in pairs, that is, no matter how you move the mouse,
XCB always triggers one event which contains BOTH Axes (that is, the mask for 'which axes are present in this update packet') is 0x01 and 0x02, making 0x03, which means both x and y axes are present in the packet.  This happens even if the mouse is moving purely horizontally as you can see above, each tick it gets (-5, 0) for a leftwards movement.

Then for vertical it looks similar:
```
XCB Input - axis 0 triggered with value 0 with mask[0] of 3
XCB Input - axis 1 triggered with value 3 with mask[0] of 3
XCB Input - axis 0 triggered with value 0 with mask[0] of 3
XCB Input - axis 1 triggered with value 2 with mask[0] of 3
XCB Input - axis 0 triggered with value 0 with mask[0] of 3
XCB Input - axis 1 triggered with value 3 with mask[0] of 3
XCB Input - axis 0 triggered with value 0 with mask[0] of 3
XCB Input - axis 1 triggered with value 2 with mask[0] of 3
XCB Input - axis 0 triggered with value 0 with mask[0] of 3
XCB Input - axis 1 triggered with value 2 with mask[0] of 3
XCB Input - axis 0 triggered with value 1 with mask[0] of 3
XCB Input - axis 1 triggered with value 2 with mask[0] of 3
```
As you can see above, its similar, just with the X axis (axis 0) reporting 0 for most of the pairs of events.

So this confirms at least that the difference in behavior is not in the low level XCB system, which leads me to think that yeah, something in the middle layer is affecting this, and it will be active on all platforms.

**Comment by nick-l-o3de** [comment] 2024-04-02 17:55
Now investigating this suspicious code in InputDeviceMouse.cpp
```cpp
// Mouse movement events are distinct in that we may not receive an 'ended' event with delta
        // value of zero when the mouse stops moving, so queueing one here ensures the channels will
        // always correctly transition into the 'ended' state the next time this function is called,
        // unless another movement delta is queued above in which case it will simply be added to 0.
        for (const InputChannelId& movementChannelId : Movement::All)
        {
            QueueRawMovementEvent(movementChannelId, 0.0f);
        }

```

**Comment by nick-l-o3de** [comment] 2024-04-02 18:29
From what I can tell, the code in InputDeviceMouse.cpp is artificually queueing a delta of 0, every tick, for every mouse movement channel. 
I assume this is because on most operating systems, events only occur when the device actually moves, and when you stop moving it, it produces no more events, resulting in a sequence of events like
(-5,0), (-5,0), (-5,0), (-5,0)  (moving the mouse to the left) but never a (0,0) when you stop moving because stopping moving is stopping generating events.

There's nothing wrong with the above code intention but I'm not sure why it isn't symmetrically doing this for every channel.

**Closed** 2024-04-04 21:31 UTC
Labels: feature/scripting, kind/bug, sig/content, triage/accepted, priority/major
