### ISSUE TITLE
Asset Browser: Editor can crash if Asset Browser is not visible upon startup

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#10583] opened 2022-07-08 17:53 UTC
**Describe the bug**
Editor can crash if Asset Browser is not visible upon startup.

```
Call Stack Trace:
25) 00007FF9762EFF27 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FF9789951B0 (ntdll) : memset
23) 00007FF97897C766 (ntdll) : _C_specific_handler
22) 00007FF97899209F (ntdll) : _chkstk
21) 00007FF978941454 (ntdll) : RtlRaiseException
20) 00007FF978990BCE (ntdll) : KiUserExceptionDispatcher
19) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\AssetBrowserFilterModel.cpp (112) : AzToolsFramework::AssetBrowser::AssetBrowserFilterModel::LeftmostColumn
18) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\AssetBrowserModel.cpp (353) : AzToolsFramework::AssetBrowser::AssetBrowserModel::BeginAddEntry
17) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzToolsFramework::AssetBrowser::AssetBrowserModelRequests,AzToolsFramework::AssetBrowser::AssetBrowserModelRequests,0,0>::Dispatcher<AZ::EBus<Az
16) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\Entries\AssetBrowserEntry.cpp (78) : AzToolsFramework::AssetBrowser::AssetBrowserEntry::AddChild
15) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\Entries\RootAssetBrowserEntry.cpp (371) : AzToolsFramework::AssetBrowser::RootAssetBrowserEntry::CreateFolder
14) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\Entries\RootAssetBrowserEntry.cpp (396) : AzToolsFramework::AssetBrowser::RootAssetBrowserEntry::CreateFolders
13) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\Entries\RootAssetBrowserEntry.cpp (140) : AzToolsFramework::AssetBrowser::RootAssetBrowserEntry::AddFile
12) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\AssetEntryChange.h (63) : AzToolsFramework::AssetBrowser::AddFileChange::Apply
11) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\AssetEntryChangeset.cpp (79) : AzToolsFramework::AssetBrowser::AssetEntryChangeset::Synchronize
10) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\AssetBrowser\AssetBrowserComponent.cpp (165) : AzToolsFramework::AssetBrowser::AssetBrowserComponent::OnTick
 9) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AZ::TickEvents,AZ::TickEvents,0,2>::Dispatcher<AZ::EBus<AZ::TickEvents,AZ::TickEvents> >::Broadcast<void (__cdecl AZ::TickEvents::*)(float,AZ::S
 8) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1346) : AZ::ComponentApplication::Tick
 7) D:\GitHub\o3de\Code\Editor\GameEngine.cpp (815) : CGameEngine::Update
 6) D:\GitHub\o3de\Code\Editor\CryEdit.cpp (2292) : CCryEditApp::IdleProcessing
 5) D:\GitHub\o3de\Code\Editor\CryEdit.cpp (2189) : CCryEditApp::OnIdle
 4) D:\GitHub\o3de\Code\Editor\Core\QtEditorApplication.cpp (312) : Editor::EditorQtApplication::maybeProcessIdle
 3) 00007FF901259A24 (Qt5Core) : QMetaCallEvent::placeMetaCall
 2) 00007FF9012583C1 (Qt5Core) : QObject::event
 1) 00007FF8FF8149A1 (Qt5Widgets) : QApplicationPrivate::notify_helper
```

**Steps to reproduce**
1. Launch the Editor.
2. Close the Asset Browser, and then click View > Layouts > Save Layout and save the custom layout.
3. Close and relaunch the Editor.

**Expected behavior**
Editor launches with the previous layout with the Asset Browser closed.

**Actual behavior**
Editor launches with the previous layout, but quickly crashes with the callstack above.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/178044756-564531d2-b2f9-4e62-9ff7-d996702a7e60.mp4

**Found in Branch**
editor/jjjoness/AssetBrowserUpdate@ 4100a18a57edb86e018e8420a31fa24ed0e738e5 

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by amzn-tmryan** [comment] 2022-07-08 21:12
Can't link the PR here apparently, but this is fixed now in the lumberyard fork. The root causes hasn't yet made it to o3de proper, so waiting for the eventual merge won't hurt anything.

**Closed by amzn-tmryan** 2022-07-08 21:12 UTC
Labels: feature/editor, kind/bug, sig/content
