### ISSUE TITLE
Linux: Material Editor and Material Canvas tools are not opening on projects with all gems enabled

### ISSUE THREAD

**Issue by LB-MateuszPlatakis** [o3de/o3de#15022] opened 2023-03-09 13:08 UTC
**Describe the bug**
The _Material Editor_ and _Material Canvas_ tools cannot be opened on the _All-Gems_ project, in the _O3DE Editor_ Linux installer version. After clicking on _Material Editor_ or _Material Canvas_ tool from the _Tools_ dropdown menu, the console prints information: `(Material Component) - Launching Material Editor/Canvas (Preview)` and the tool does not launch. 

Sometimes after attempting to open the tool a Linux system crash error popup shows up with the information `MaterialEditor/Canvas has stopped unexpectedly` and with the title: `MaterialEditor/Canvas crashed with SIGSEGV`.

All assets were processed when this issue occurred, the Asset Processor was Idle. Note that the issue does not occur on the _Default_ and the _Minimal_ projects. Also due to other issues with installing _O3DE Editor_ on the Linux system, we were not able to confirm that issue on Linux Pre-Build SDK.

This issue might be related to https://github.com/o3de/o3de/issues/7113

**Steps to reproduce**
1. Install the _Linux O3DE Editor_ installer version (https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb).
2. Build a project with all gems enabled.
3. Open the Editor.
4. From the _Tools_ dropdown menu choose _Material Editor_ or _Material Canvas (Preview)._
5. Observe the Issue.

**Expected behavior**
_Material Editor_ and _Material Canvas_ tools open without a problem.

**Actual behavior**
_Material Editor_ and _Material Canvas_ tools do not launch.

**Log/Screenshots/Video**
[Editor1.log](https://github.com/o3de/o3de/files/10931397/Editor1.log)

![image](https://user-images.githubusercontent.com/119418207/224022743-c0b2978b-080e-4da6-b811-c40c7297eb7a.png)
![Screenshot from 2023-03-09 12-13-26](https://user-images.githubusercontent.com/119418207/224022780-b35f487e-c766-4a1d-a348-d590c524b843.png)

**Found in Branch**
(https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.5 LTS
- CPU: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8
- GPU: NVIDIA GeForce RTX 2070
- Memory: 16GB

**Comment by galibzon** [comment] 2023-03-14 17:07
Closing as duplicate of https://github.com/o3de/o3de/issues/7113

**Closed by galibzon** 2023-03-14 17:07 UTC
Labels: platform/linux, kind/bug, needs-triage, sig/graphics-audio, priority/major

**Comment by LB-MateuszPlatakis** [comment] 2023-03-15 07:48
Confirming the issue has been closed as a duplicate.
