### ISSUE TITLE
Linux: Physics Material Library Debug Color color pickers are blank until they are selected, or their default color is changed

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7718] opened 2022-02-17 12:27 UTC
**Describe the bug**
Default physics materials' Debug Color property color picker is blank unless it is selected, or updated with a different value.

**Steps to reproduce**
1. Go to Tools > PhysX Configuration (PREVIEW).
2. In the PhysX Configuration (PREVIEW) window go to Physics Materials > Physics Material Library and click "Edit asset" button on the right.
3. Click on the Debug Color color picker next to any of the default physics materials and change it.
4. Click on the Debug Color color picker next to another of the default physics materials, and without changing it close the "Select Color" window.

**Expected behavior**
Default physics material's Debug Color property's color picker shows selected color all the time.

**Actual behavior**
Default physics material's Debug Color property's color picker shows the selected color only when the "Select Color" window is opened, or it is modified.

**Video**

https://user-images.githubusercontent.com/86952082/154480174-a676bdb2-9bd7-4011-bc15-5d2bd2394454.mp4

**Found in Branch**
Development (3f2aa74)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by spham-amzn** [comment] 2022-05-31 19:47
Need UI/UX input on this. Clicking 'X' on the window should mean a cancel operation, not a confirmation. The behavior looks like what the expected result should be

**Comment by moraaar** [comment] 2022-07-13 16:21
Closing this as it's a duplicate of https://github.com/o3de/o3de/issues/9927

**Closed by moraaar** 2022-07-13 16:21 UTC
Labels: platform/linux, feature/physics, kind/bug, sig/platform, triage/accepted, priority/minor, sig/simulation
