### ISSUE TITLE
DPE Inspector: White Box component has multiple [0] properties which can only be removed

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#16416] opened 2023-07-20 13:15 UTC
**Describe the bug**
*White Box* component has multiple [0] properties if viewed with `ed_enableDPE` enabled. These properties do not do anything and can be removed by pressing bin buttons to their right.

It should be noted that this does not occur if `ed_enableDPE` is disabled.

**Steps to reproduce**
1. Execute `ed_enableDPE` 1 command in Console.
2. Create an entity and add a *White Box* component to it.
3. View the *White Box* component in the *Inspector*.

**Expected behavior**
*White Box* component has the same properties as with DPE disabled.

**Actual behavior**
*White Box* component has multiple [0] properties, which can only be deleted.

**Video**

https://github.com/o3de/o3de/assets/86952082/b7929756-1fb8-4e47-b11e-7ec6ae080945

**Found in Branch**
Development (b305c20)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
b305c2074f0c43276ddc7835e8018d57206e26fa

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600X 6-Core Processor
 - GPU AMD Radeon RX 5700 XT
 - Memory 16GB

**Comment by cgalvan** [comment] 2023-07-20 20:33
Closing this as duplicate of #16082

**Closed by cgalvan** 2023-07-20 20:33 UTC
Labels: kind/bug, needs-triage, sig/content, priority/minor

**Comment by LB-ArturZieba** [comment] 2023-07-21 13:15
Confirming the issue has been closed.
