### ISSUE TITLE
It's very easy to break connections in Script Canvas when trying to make a new one

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3772] opened 2021-08-31 19:45 UTC
### Problem description

When clicking on a data or event output in Script Canvas, if there is an existing connection, it seems to be very easy to disconnect the existing connection as opposed to starting a new one. This happens very often and is quite frustrating. It might be better to just ditch this entirely and use the delete key as a means to remove a connection (or have the cross on the middle of the connection itself to remove it).

Reported by @hultonha through LY game gem

**Comment by lsemp3d** [comment] 2021-11-24 20:37
Duplicate of #2714

**Closed by lsemp3d** 2021-11-24 20:37 UTC
Labels: feature/scripting, sig/content, sig/ui-ux, priority/major, WF2, RTE, needs-ux-action
