### ISSUE TITLE
Be This Camera - Undo switches to the Editor Camera

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#2735] opened 2021-08-02 20:32 UTC
**Describe the bug**
When in "Be This Camera" mode, pressing Ctrl+Z reverts the last change to the camera, but it also switches the controlled camera back to the Editor Camera. This makes it confusing/harder to revert multiple operations (since the feedback of where the camera gets moved after that is lost).

**To Reproduce**
1. Open a Level
2. Select the Camera entity
3. Press Be This Camera
4. Move the camera around a couple times
5. Undo (Ctrl+Z)

**Expected behavior**
The camera moves back to the last position it had before it was moved. Control of the current camera is retained.

**Actual behavior**
The camera moves back, but then switches to Editor Camera.

**Comment by AMZN-Igarri** [comment] 2021-11-29 14:22
This should have been fixed with #5650 I can't reproduce it anymore.
Can you verify this @AMZN-daimini ?

**Comment by hultonha** [comment] 2021-11-30 15:15
Hmm it does seem to mostly work, but I do see the error

**Comment by AMZN-Igarri** [comment] 2021-11-30 16:21
@hultonha yes! That issue is actually #5951

**Closed** 2022-01-13 13:22 UTC
Labels: kind/bug, sig/content, sig/ui-ux, triage/accepted, priority/major, feature/viewport
