### ISSUE TITLE
AR Bug Report - Test AutomatedTesting::MultiplayerTests_Main failed

### ISSUE THREAD

**Issue by pollend** [o3de/o3de#9324] opened 2022-04-30 02:43 UTC
**Describe the bug**

`AutomatedTesting::MultiplayerTests_Main.main::TEST_RUN` failed while running AR 

**Failed Jenkins Job Information:**

platform linux -- Python 3.7.12, pytest-5.3.2, py-1.11.0, pluggy-0.13.1 -- /data/workspace/o3de/python/runtime/python-3.7.12-rev2-linux/python/bin/python

```
[2022-04-29T10:46:42.179Z] E   Failed: Test test_Multiplayer_AutoComponent_NetworkInput:
[2022-04-29T10:46:42.179Z] E   Test FAILED
[2022-04-29T10:46:42.179Z] E   ------------
[2022-04-29T10:46:42.179Z] E   |  Output  |
[2022-04-29T10:46:42.179Z] E   ------------
[2022-04-29T10:46:42.179Z] E   Starting test Multiplayer_AutoComponent_NetworkInput...
[2022-04-29T10:46:42.179Z] E   Test Multiplayer_AutoComponent_NetworkInput finished.
[2022-04-29T10:46:42.179Z] E   Report:
[2022-04-29T10:46:42.179Z] E   [SUCCESS] Success: Unexpected line not found: LaunchEditorServer failed! The ServerLauncher binary is missing!
[2022-04-29T10:46:42.179Z] E   [SUCCESS] Success: Found expected line: Editor has connected to the editor-server.
[2022-04-29T10:46:42.179Z] E   [SUCCESS] Success: Found expected line: Editor is sending the editor-server the level data packet.
[2022-04-29T10:46:42.179Z] E   [FAILED ] Failure: Failed to find expected line: Logger: Editor Server completed receiving the editor's level assets, responding to Editor...
[2022-04-29T10:46:42.179Z] E   EXCEPTION raised:
[2022-04-29T10:46:42.179Z] E     Traceback (most recent call last):
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
[2022-04-29T10:46:42.179Z] E         test_function()
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py", line 57, in Multiplayer_AutoComponent_NetworkInput
[2022-04-29T10:46:42.179Z] E         helper.multiplayer_enter_game_mode(Tests.enter_game_mode)
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 178, in multiplayer_enter_game_mode
[2022-04-29T10:46:42.179Z] E         TestHelper.succeed_if_log_line_found("EditorServer", "Logger: Editor Server completed receiving the editor's level assets, responding to Editor...", section_tracer.prints, 5.0)
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 138, in succeed_if_log_line_found
[2022-04-29T10:46:42.179Z] E         Report.critical_result(("Found expected line: " + line, "Failed to find expected line: " + line), TestHelper.find_line(window, line, print_infos))
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 410, in critical_result
[2022-04-29T10:46:42.179Z] E         TestHelper.fail_fast(fast_fail_message)
[2022-04-29T10:46:42.179Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 213, in fail_fast
[2022-04-29T10:46:42.179Z] E         raise FailFast()
[2022-04-29T10:46:42.179Z] E     editor_python_test_tools.utils.FailFast
[2022-04-29T10:46:42.179Z] E   Test result:  FAILURE
```

**Attachments**

[log.txt](https://github.com/o3de/o3de/files/8595521/log.txt)

**Comment by AMZN-Gene** [comment] 2022-05-02 16:07
Duplicate of https://github.com/o3de/o3de/issues/8902

**Comment by hultonha** [comment] 2022-05-03 11:01
Hey @AMZN-Gene, I've added the `status/duplicate` label, if this is being tracked elsewhere please feel free to close this (and thanks for reporting @pollend, it is helpful to know this is happening often).

**Closed** 2022-07-14 17:55 UTC
Labels: feature/networking, kind/bug, sig/network, status/duplicate, priority/critical, kind/automation
