### ISSUE TITLE
[MAJOR] PhysX/Prefab: Invalid asset reference error when physics colliders exist and prefabs enabled

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2501] opened 2021-07-27 18:27 UTC
**Describe the bug**
When an entity exists in the level prefab with a physics collider the following error is displayed when entering game mode
[Error] (Prefab) - Invalid asset found referenced in scene while entering game mode
[Error] (Prefab) - Invalid asset found referenced in scene while entering game mode

**To Reproduce**
1. Create an entity in the editor with a PhysX collider
2. Enter game mode

**Expected behavior**
No error occurs

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6

**Additional context**
n/a

**Comment by moraaar** [comment] 2021-07-28 17:27
Duplicate of https://github.com/o3de/o3de/issues/2532
Closing.

**Closed by moraaar** 2021-07-28 17:27 UTC
Labels: kind/bug, needs-sig, needs-triage
