### ISSUE TITLE
Periodic Failure - development - Android [release]/release

### ISSUE THREAD

**Issue by shirangj** [o3de/o3de#11939] opened 2022-09-13 18:49 UTC
### Identified problems:
* **Android [release] - release**
  * **Log URL**: https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE_periodic-incremental-daily/pipelines/development/runs/99/nodes/1040//log
  * **Ninja Build Compilation Failure**
    [2022-09-13T05:31:39.548Z] ninja: build stopped: subcommand failed.

**Comment by byrcolin** [comment] 2022-09-26 21:03
Dupe of https://github.com/o3de/o3de/issues/11942

**Closed by byrcolin** 2022-09-26 21:03 UTC
Labels: needs-triage, platform/android, sig/build, sig/platform, periodic_failure/development
