### ISSUE TITLE
It is possible to delete a component while its Pick Asset window is open which may lead to a crash

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#10877] opened 2022-07-26 09:52 UTC
**Describe the bug**
When in the Pick Asset window (e.g. Pick EMotion FX Actor) it is possible to delete a component and after that if the User will try to pick an asset for the non-existing component, after pressing the "OK" button Editor will crash.
Additionally, after deleting a component while in the Pick Asset window, its close button icon disappears. Also, while in the Pick Asset window, pressing Ctrl+D results in the duplication of an entity. Please refer to the attached video and log files.

**Steps to reproduce**
1. Create an entity.
2. Open pinned Inspector for the created entity.
3. Add any component that contains the Pick Asset window (e.g. Actor).
4. Select the component.
5. On the component click the file icon to open the Pick Emotion FX Actor window.
6. Search for any .actor or .fbx file and select it.
7. Press Del which will result in deletion of the Actor component.
8. Observe that the close button icon disappears.
9. Press the "OK" button.

**Expected behavior**
It is impossible to delete a component while its Pick Asset window is open.

**Actual behavior**
It is possible to delete a component while in the Pick Asset window, which may results in a crash.

**Video**

https://user-images.githubusercontent.com/100559077/180978025-95c1d75d-d3ff-4fde-8623-e5b055b11199.mp4

**Additional files**
[Editor.log](https://github.com/o3de/o3de/files/9188719/Editor.log)
[error.log](https://github.com/o3de/o3de/files/9188720/error.log)
[errordmp01.zip](https://github.com/o3de/o3de/files/9188745/errordmp01.zip)
[errordmp02.zip](https://github.com/o3de/o3de/files/9188746/errordmp02.zip)
[errordmp03.zip](https://github.com/o3de/o3de/files/9188747/errordmp03.zip)

**Found in Branch**
Development (663ed56)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by AMZN-daimini** [comment] 2022-07-26 15:13
I thought the Pick Asset was a blocking dialog? It may just not be parented correctly. Assigning to Editor as it's related to the PropertyAssetCtrl.

**Comment by AMZN-daimini** [comment] 2022-07-27 20:42
Got a repro. the Asset Picker is indeed a blocking dialog, but apparently it is still possible to delete the selection through it. Checking this out.

**Comment by AMZN-daimini** [comment] 2022-07-27 22:05
Looks like this issue is related to the ShortcutDispatcher sending the event from the Asset Picker to the Inspector, which shouldn't happen.

**Comment by AMZN-daimini** [comment] 2023-03-21 14:54
I tried reproducing this, and pressing `Delete` on step 7 results in the selected asset being deleted, not the component. As such, I think this is no longer a bug with the new Action Manager system.

Closing for now, feel free to re-open if I missed something :)

**Closed by AMZN-daimini** 2023-03-21 14:54 UTC
Labels: feature/editor, kind/bug, sig/content, status/approved, priority/critical

**Comment by LB-TomaszSerwanski** [comment] 2023-03-22 10:42
Issue verified as fixed on both Stabilization/2305 (169ab99) as well as Development (73e54c6) branches.
