### ISSUE TITLE
Prefabs are not affected by the changes made to Non-uniform Scale component

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#14226] opened 2023-01-26 14:38 UTC
**Describe the bug**
Changing Non-uniform Scale component's values of a prefab entity does not affect the prefab. Note that modifying the Uniform Scale works as expected.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a new level.
2. RMB on the Shader Ball entity and select "Create Prefab...".
3. Save the prefab.
4. Select the created prefab entity.
5. In the Transform component press the "Add non-uniform scale" button.
6. Modify values of the Non-uniform Scale component.

**Expected behavior**
The prefab is affected when changing Non-uniform Scale component's values.

**Actual behavior**
The prefab is not affected when changing Non-uniform Scale component's values.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/214862063-faba2e9b-5e4a-4b74-99c8-d79bfa6618dc.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
[57a500f](https://github.com/o3de/o3de/commit/57a500f3eaf2b0d8450003dd04016f5147e940a7)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.5 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by AMZN-daimini** [comment] 2023-01-26 15:14
Note, **this is not just an issue with prefabs**. I have just tried creating an entity and a child entity under it. Added a mesh component with a cube mesh to the child entity, then added a non-uniform scale component to the parent. Changes to uniform scale are applied to children, but changes to non-uniform scale are not.

This can still be directed to sig-content, but I'd raise its priority to major.

**Comment by monroegm** [comment] 2023-02-02 19:48
@hultonha Any idea why non-uniform scale doesn't seem to be working?

**Comment by greerdv** [comment] 2023-02-03 12:59
It is by design that non-uniform scale does not propagate to descendants.

**Comment by hultonha** [comment] 2023-02-03 14:01
Awesome thanks @greerdv

__I'll close this as 'By design' for now__

One thought I has is is it worth adding a tool-tip perhaps to make this more obvious? Not urgent but might be nice

**Closed by hultonha** 2023-02-03 14:01 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/math

**Comment by greerdv** [comment] 2023-02-03 14:08
There already is a tooltip.
