### ISSUE TITLE
Periodic Failure - development - Linux [benchmark_test_profile]/benchmark_test_profile

### ISSUE THREAD

**Issue by shirangj** [o3de/o3de#11954] opened 2022-09-13 18:49 UTC
### Identified problems:
* **Linux [benchmark_test_profile] - benchmark_test_profile**
  * **Log URL**: https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE_periodic-incremental-daily/pipelines/development/runs/99/nodes/856//log
  * **CTest failure(s)/error(s)**
    The following tests FAILED:
[2022-09-13T07:18:21.525Z] 	  4 - AZ::AzCore.Benchmarks.benchmark::TEST_RUN (Timeout)
[2022-09-13T07:18:21.525Z] 	  9 - AZ::AzToolsFramework.Benchmarks.benchmark::TEST_RUN (Timeout)
[2022-09-13T07:18:21.525Z] Errors while running CTest

**Comment by moraaar** [comment] 2022-10-28 17:28
Related to https://github.com/o3de/o3de/issues/12484

**Comment by Kadino** [comment] 2022-11-08 19:20
Closing as duplicate of https://github.com/o3de/o3de/issues/12484

**Closed by Kadino** 2022-11-08 19:20 UTC
Labels: needs-triage, sig/testing, periodic_failure/development, kind/periodicbuildfailure
