### ISSUE TITLE
Error pops up - material can not be compiled - when saving material

### ISSUE THREAD

**Issue by goldblaze** [o3de/o3de#6611] opened 2022-01-03 03:33 UTC
**Describe the bug**
all .material files seem to refuse to compile, gives a failed to compile error when ever a .material file is saved, also spits out some of the following warnings and errors:
1/2/2022 7:54 PM | Warn | No job was found to match the job dependency criteria declared by file C:/Users/goldblaze/O3DE/Projects/pong/Assets/Materials/ground.material. (File: Assets/Materials, JobKey: Atom Material Builder, Platform: pc) from Warning
1/2/2022 7:54 PM | Warn | This may be due to a mismatched job key. from Warning
1/2/2022 7:54 PM | Warn | Job ordering will not be guaranteed and could result in errors or unexpected output. from Warning
1/2/2022 7:54 PM | ERROR | JSON: Trace::Error from AssetBuilder
1/2/2022 7:54 PM | ERROR | >	D:/workspace/o3de/Gems/Atom/RPI/Code/Source/RPI.Edit/Common/JsonReportingHelper.cpp(59): 'union AZ::JsonSerializationResult::ResultCode __cdecl AZ::RPI::JsonReportingHelper::Reporting(class AZStd::basic_string_view<char,struct AZStd::char_traits<char> >,union AZ::JsonSerializationResult::ResultCode,class AZStd::basic_string_view<char,struct AZStd::char_traits<char> >)' from AssetBuilder
1/2/2022 7:54 PM | ERROR | >	'': Required field 'materialType' is missing or invalid - The operation has halted during a read field operation because a catastrophic issue was encountered from AssetBuilder

**Steps to reproduce**
1. start a new project
2. click on the Ground asset
3. go to materials and click on dropdown next to groundplane, click on Edit Material Instance
4. click the three lines menu and click save material.
5. save in project folder, error pops up that the material can not be compiled

**Expected behavior**
the file gets saved and compiled

**Actual behavior**
the file is saved but it gives out a unable to compile error

**Assets required**
starting project assets

**Screenshots/Video**
https://cdn.discordapp.com/attachments/211670388478967808/927389231154880572/unknown.png
https://puu.sh/IAak3/9258614ecd.png

**Found in Branch**
 21.11

**Desktop/Device (please complete the following information):**
 - Device: pc
 - OS: windows
 - Version 10
 - CPU Ryzen 5 2600
 - GPU Nvidia GeForce GTX 1060 6GB
 - Memory 16GB

**Comment by goldblaze** [comment] 2022-01-03 03:54
https://puu.sh/IAb0m/978f9dab8d.png This error pops up when I try to create a new material through the material editor

**Comment by santorac** [comment] 2022-01-06 00:29
Can you please provide the ground.material file?

**Comment by santorac** [comment] 2022-01-06 00:33
Also, what commit hash are you synced to? I cannot repro this as of...
commit f52d49834acc3dbaa1652bc93fb50e7bf834afc6 (HEAD -> development)
Date:   Thu Dec 16 13:42:38 2021

**Comment by santorac** [comment] 2022-01-06 00:39
Could this be a duplicate of https://github.com/o3de/o3de/issues/6289 ? If that's the case, the issue has already been fixed.

**Comment by gadams3** [comment] 2022-03-24 03:18
I cannot reproduce this on the current development branch. I believe I fixed it awhile ago.

**Closed by gadams3** 2022-03-24 03:18 UTC
Labels: kind/bug, sig/graphics-audio, priority/critical
