### ISSUE TITLE
.wbm assets are effectively unusable

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3957] opened 2021-09-07 10:25 UTC
**Describe the bug**
It has been noticed that saved .wbm files do not appear in the Mesh Asset select window, and even though they can be found using the Asset Browser, they cannot be drag and dropped into the Viewport to create a White Box entity. This renders .wbm files effectively unusable in the Editor.

**To Reproduce**
1. Create an entity and add a White Box component to it.
2. Click the Edit button in the White Box component to enter White Box Edit Mode.
3. Modify the White Box mesh in some way (e.g. grab any vertex and move it).
4. Click Done to exit the Edit Mode.
5. Click Save As... button on the White Box component and save the .wbm file.
6. Try to assign the .wbm file saved in step 5 via the White Box's Default Shape > Mesh Asset > Mesh Asset property.
7. Find the .wbm file saved in step 5 in the Asset Browser and try to drag and drop it into the Viewport.

**Expected behavior**
Saved .wbm assets are useable in some capacity.

**Video**

https://user-images.githubusercontent.com/86952082/132326193-9e69ae7b-ca36-4857-b8ef-f3bb05fb89f9.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment] 2021-09-07 11:12
I've triaged this and will take a look sometime later this week or early next (I'm in the middle of a higher priority task so will move to this when that is complete).

**Comment by jonawals** [comment] 2021-11-10 13:50
As of commit `0e3df14ea2f1b2e36c3d64cf6ff72b52eb2d2f5a` I cannot reproduce the issue locally (everything works as expected).

https://user-images.githubusercontent.com/77458631/141124888-4028c8a5-a066-44a5-90c8-f9b9225e4337.mp4

**Comment by hultonha** [comment] 2021-11-10 13:58
I have also attempted to reproduce this problem on latest and am not able to - @LB-ArturSiewniak could you please confirm this and close if you are also unable to reproduce? Thanks!

**Comment by hultonha** [comment] 2021-11-17 13:43
Hi @LB-ArturSiewniak, we believe this is to do with changes to the Asset Picker itself. Some recent changes were reverted and the White Box Mesh assets now do display. Could you please test again after this PR https://github.com/o3de/o3de/pull/5614 (commit https://github.com/o3de/o3de/commit/a5adf33427e3b2163c2f21c75148598b3364d8d4). Thanks!

**Comment by hultonha** [comment] 2021-11-18 13:48
@LB-ArturSiewniak would you please be able to check this again please, I'm 99% sure it's all working now, thanks!

**Comment by jckand-amzn** [comment] 2021-11-18 18:22
No longer reproduced as of stabilization/2110@1b63ca3bc0924a1. Mesh Asset is correctly assigned once saved, and can also be applied to other instances of the White Box component or dragged into the Viewport from the Asset Browser. However, when dragging the saved .wbm into the Viewport from the Asset Browser, the White Box component created is not set to the saved mesh, and instead defaults to the basic Cube shape.

**Comment by jckand-amzn** [comment] 2021-11-18 18:28
Logged a new ticket for the Asset Browser > Viewport issue: #5754

Closing this issue out.

**Closed by jckand-amzn** 2021-11-18 18:28 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, status/needs-testing, feature/viewport

**Comment by LB-ArturSiewniak** [comment] 2021-11-19 10:47
Issue verified as fixed on Development (e804fd2) and Stabilization_2110 (d30fdb7) builds.
