### ISSUE TITLE
User has to select the instance for the animgraph node to run the animation in the Animation Editor viewport

### ISSUE THREAD

**Issue by FuzzyCarterAWS** [o3de/o3de#9627] opened 2022-05-18 17:40 UTC
**Describe the bug**
If a user attempts to play an animation on an imported actor in the Animation Editor, the button will not work until the user has gone and selected the actor instance

**Repro Steps**
2. Open Character Editor
3. Open Actor
4. Create a Motion Set with desired Motions
5. Create an Anim Graph
6. Press the Play Button on the Time View tab

**Expected behavior**
User doesn't have to select the instance and actor animates when animation play button is pressed

**Actual behavior**
Pressing the Play button returns an error that it "Cannont play motion. no Actor instance selected."

**Comment by hultonha** [comment] 2022-05-23 16:22
Note: This is related to the ActorManager class and should go away once it is removed. Being looked into by @amzn-jillich in the near future.

**Comment by hultonha** [comment] 2022-05-30 16:13
@FuzzyCarterAWS Would you please be able to add more specific repro steps for this issue as it's not exactly clear how to get into this state. Thank you!

**Comment by hultonha** [comment] 2022-06-01 16:52
@yuyihsu This ticket came-up in sig-simulation triage and we would like to downgrade this to `priority/major` as while this issue is a nice to have it's not totally breaking any workflows.

**Comment by FuzzyCarterAWS** [comment] 2022-06-01 22:30
@hultonha 

I've updated the description. I'm unable to repro locally. However, I can send you a video reference of where the issue happened for analysis by you or by the dev that will work on this.

**Comment by hultonha** [comment] 2022-06-06 13:29
> @hultonha
> 
> I've updated the description. I'm unable to repro locally. However, I can send you a video reference of where the issue happened for analysis by you or by the dev that will work on this.

Thanks very much @FuzzyCarterAWS

**Comment by LB-KacperBieniek** [comment] 2022-06-14 10:55
When trying to reproduce this issue by following the exact steps from the description I was unable to encounter it. The reason behind it is that by simply opening the actor it is automatically selected. Deselecting the actor in Actor Manager tab, selecting a Motion, and then pressing the Play Button on the Time View tab results in the issue as described in Actual behavior. I believe this is the correct design. Please refer to the attached video.

https://user-images.githubusercontent.com/87059746/173555929-33ee6d1b-37ce-448f-bad8-5d8fec9de8cb.mp4

**Comment by hultonha** [comment] 2022-06-15 12:17
This is great thank you very much @LB-KacperBieniek, really appreciate you looking into this. I'm going to close this issue for now as it can no longer be reproduced.

**Closed by hultonha** 2022-06-15 12:17 UTC
Labels: feature/animation, kind/bug, sig/ui-ux, triage/accepted, priority/critical, WF3, RTE, sig/simulation
