### ISSUE TITLE
Editor freezes after exiting game mode

### ISSUE THREAD

**Issue by benblack75** [o3de/o3de#3856] opened 2021-09-01 21:12 UTC
The viewport locks up when exiting Game Mode, and the only way I've found to fix it is to quit out of the Editor and restart it.

**To Reproduce**
1.) Enter Game Mode
2.) Press escape key to exit game mode

From that point on you can no longer tumble through the scene or interact with objects in the viewport.

**Expected behavior**
Once exiting Game Mode, I would expect to regain control of moving the camera throughout the scene and manipulating objects

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - Intel I9
 - NVidia RTX 2080
 - 64 GB

**Additional context**

**Comment by srikappa-amzn** [comment] 2021-11-02 19:55
On the https://github.com/o3de/o3de/tree/stabilization/2110 branch, I've tested game mode on new levels with both prefabs enabled and disabled. In both cases, after existing the game mode, I was able to move the camera and manipulate viewport objects.

I'm closing this since I can't reproduce this. 

@benblack75 ,  please try to checkout the above stabilization branch since it has many other fixes to other systems too. If you still encounter this, please reopen this and provide more detailed repro steps and if possible, screenshots and videos

**Closed by srikappa-amzn** 2021-11-02 19:55 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
