### ISSUE TITLE
Deleting a duplicated prefab causes "Some of the patches are not successfully applied" Error

### ISSUE THREAD

**Issue by Amzn-Catdo** [o3de/o3de#3021] opened 2021-08-10 20:50 UTC
**Found in Build:**
dev
**Reproducibility:**
3/3
**Prerequisites:**
prefab system enabled
**Steps to Reproduce:**
1. Instantiate the same prefab twice
2. Delete one prefab

or

1. Instantiate a prefab
2. Right-click duplicate prefab
3. Delete one of the prefab
Expected Result:
Prefab deleted without any errors thrown
Actual Result:
An error is thrown when the duplicated prefab is deleted
[Error] (Prefab) - Some of the patches are not successfully applied.

![image](https://user-images.githubusercontent.com/82239748/128932053-9e4faac7-4060-4645-bdd4-0bac5a31510b.png)

Note:
I was still able to reproduce this on dev
This issue was brought over from Jira

**Comment by monroegm** [comment] 2022-03-01 02:20
Duplicate of #2921

**Closed by monroegm** 2022-03-01 02:20 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/minor, feature/prefabs
