### ISSUE TITLE
[Linux] Building project fails with configuration error

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#11743] opened 2022-09-02 13:12 UTC
**Describe the bug**
Building the project via Project Manager fails during the configuration process, which additionally results in a crash of Project Manager on one of our machines. CMakeProjectBuildError.log indicate that the configuring is incomplete due to the errors.

This issue does not occur on latest Github Stabilization build with Pre-built SDK engine.

Please refer to the attached log files for more information.

**Installer**
Reproduced the issue on 5 machines with Linux OS:
 - On 4 machines the OpenSSL error is occurring right after executing the command but the project configuration fails after using openmesh-8.1 package.

 - On 1 machine the **Project Manager** crashes and the following error is observed after starting the building process.

```
OpenSSL errorCMake Error at /opt/O3DE/0.0.0.0/cmake/Platform/Linux/OpenSSL_linux.cmake:18 (add_library):
  add_library cannot create ALIAS target "3rdParty::OpenSSL" because another target with the same name already exists.
```

Please note that this issue might be related to the following commit - https://github.com/o3de/o3de/commit/d3760da0ab375a21d67a3be5ecefbedad2440d27

**Steps to reproduce**

1. Download the latest Stabilization installer.
2. Perform the installation.
3. Launch the Project Manager.
4. Create a new project.
5. Build created project.

**Expected behavior**
Project is built without errors.

**Actual behavior**
Building the project fails during the configuration process.

**Found in Branch**
Latest Stabilization/2210 installer

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
Logs from the machine with latest Stabilization/2210 installer build that experienced configuration incomplete error:
[CMakeError.log](https://github.com/o3de/o3de/files/9476803/CMakeError.log)
[CMakeOutput.log](https://github.com/o3de/o3de/files/9476804/CMakeOutput.log)
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/9476805/CMakeProjectBuildError.log)

Logs from the machine with latest Stabilization/2210 installer build where **Project Manager** crashed during the project configuration process:
[CMakeOutput.log](https://github.com/o3de/o3de/files/9477808/CMakeOutput.log)
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/9477809/CMakeProjectBuildError.log)

**Comment by LB-BartoszDudzinski** [comment] 2022-09-06 11:51
Today we noticed that the issue occurs on Development branch and GitHub builds also when a clean engine setup is performed instead of a local repository update.

**Comment by spham-amzn** [comment] 2022-09-06 15:50
Fix has been merged in to stabilization/2210

**Closed** 2022-09-06 15:50 UTC
Labels: platform/linux, kind/bug, sig/build, triage/accepted, priority/blocker

**Comment by LB-JakubSkorupka** [comment] 2022-09-07 11:24
We verified that the issue no longer occurs on Stabilization/2210 (58fb16c) Pre-built SDK engine. Note that the fix is not yet implemented to the latest Stabilization installer.

**Comment by LB-BartoszDudzinski** [comment] 2022-09-08 08:06
We verified that the issue is fixed in Stabilization installer and will verify further once the fix is merged to the Development branch.
