### ISSUE TITLE
Feature Request:  Right click in Landscape Canvas only show the valid node

### ISSUE THREAD

**Issue by Alexlau1994** [o3de/o3de#4648] opened 2021-10-13 02:23 UTC
**Describe the solution you'd like**
When using Landscape Canvas, we drag a line from the outport of some node, then right click for show the node we want to add. It will be more convenient if it only show the valid node.

**Comment by yuyihsu** [comment] 2021-10-19 18:57
This issue not only exists in Landscape Canvas, but in all scripting tools that use the "Graph Canvas". We should improve the behavior to only show the valid nodes based on context when users try to link to another node.

Suggest to handle this request as part of the graph canvas consistency improvement.

**Comment by cgalvan** [comment] 2022-09-29 19:18
Closed as duplicate of https://github.com/o3de/o3de/issues/8933

**Closed by cgalvan** 2022-09-29 19:18 UTC
Labels: feature/scripting, kind/feature, sig/content, sig/ui-ux, triage/accepted, priority/major, feature/vegetation, needs-ux-design
