### ISSUE TITLE
Bug Report: Camera editor selection and other cameras move to the wrong position

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#13525] opened 2022-12-03 11:18 UTC
**Describe the bug**
switching to other cameras the wrong position

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/205438132-14bc2c61-f242-4302-8aa1-ef893794ccb3.mp4

https://user-images.githubusercontent.com/17591539/205438135-d2cb7ea7-a0d3-4b70-a5f7-53c806a10b01.mp4

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
4ac8adffbe54068a43b7e90d3248b7cf309ee843

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Version 36

**Comment by hultonha** [comment] 2022-12-05 13:14
Hi @Darkinggq, I'm afraid from the videos I don't quite fully understand the problem. It looks to me to be working correctly.

When you click 'Cam' (which is an `EditorCameraComponent` in the level) the camera aligns with that view. The normal Editor Camera isn't associated with any camera component and when clicked will return to where you last left it.

What are you expecting should happen? Could you please fill in the full bug description with the 'Expected' and 'Actual' sections please? Thanks!

**Comment by hultonha** [comment] 2022-12-05 13:15
Hmm actually watching again is this a game mode thing? Where the camera position/orientation is lost when going to/from game mode? 🤔 Can you let us know what build you're on too as this does not look to be the development build. Thanks!

**Comment by Darkinggq** [comment] 2022-12-05 16:09
@hultonha Hi, the camera becomes strange, for example, specify a place and start the play game in the wrong place point


https://user-images.githubusercontent.com/17591539/205684552-64377a22-8d28-4cd8-a8fb-25a3bae6800f.mp4


https://user-images.githubusercontent.com/17591539/205684555-c97c34d2-03e4-4e3a-824d-dc8b743c6a46.mp4

**Comment by Darkinggq** [comment] 2022-12-05 19:18
@hultonha I check 2210.0 camera works better than development

https://user-images.githubusercontent.com/17591539/205723721-5fa9fe06-d763-4db0-9b7d-6408bdec7ef9.mp4

**Comment by hultonha** [comment] 2022-12-06 09:15
Thanks for the updated video @Darkinggq, I definitely see a problem in the first of the new videos you shared. It definitely seems to be something to do with going into game mode right? If you don't go into game mode and just switch cameras it works as expected? Is that correct? Also if you could list very precise reproductions steps (step by step set of operations you do) that would be incredibly helpful to help me locally reproduce the problem. Thanks!

**Comment by hultonha** [comment] 2022-12-06 09:51
I also wanted to check did this only start happening very recently? There's a chance this PR might be causing some of these problems if you only saw this happening in the last week or so - https://github.com/o3de/o3de/pull/13433. You might be able to try reverting it and seeing if the issue goes away for you. I can look into the root cause soon if it doe seem to be something to do with that.

**Comment by Darkinggq** [comment] 2022-12-13 14:42
@hultonha Sorry was busy, view camera mode and non-mode both all the same behavior strange location

i don't check the previous commits https://github.com/o3de/o3de/pull/13433 and i don't want o3de recompilation of sources sorry, while i'm on a nightly build

**Comment by hultonha** [comment] 2022-12-16 10:09
@Darkinggq Apologies things are pretty busy this end but this is still very much on my radar! 😅 It'll be the next code change I get to (I just have lots of other admin things to deal with at the moment 😬). I'll let you know if I make any progress, watch this space.

**Comment by hultonha** [comment] 2022-12-16 16:47
I actually have an experimental branch with a potential fix - I need to do some more testing and write some tests to validate this but I think this is already an improvement. You can find it here if you're interested - https://github.com/aws-lumberyard-dev/o3de/tree/hultonha_GHI-13525_editor-camera-component (or try the attached patch file locally)

[0001-initial-experiment-to-improve-EditorCameraComponent-.patch](https://github.com/o3de/o3de/files/10247495/0001-initial-experiment-to-improve-EditorCameraComponent-.patch)

**Comment by hultonha** [comment] 2023-01-06 18:42
Just a quick update on this... I am actually still looking at it 😅 (off and on) but I've unfortunately discovered a lot of problems along the way and I'm trying to fix things properly. There's a horribly gnarly problem when you change level while in 'Be this camera' mode that I'm trying to fix along with some other fixes/improvements. I'll update the PR (#13772) when I have more updates, I'm traveling next week though so unfortunately will not be able to look at it then. Trust me it will eventually get fixed! 😅

**Comment by hultonha** [comment] 2023-01-18 09:38
Still making slow progress! 😅 I have a new branch with more fixes/changes (https://github.com/aws-lumberyard-dev/o3de/tree/hultonha_GHI-13525_editor-camera-component-updated). It's not in PR yet as all the code is a mess, but you can try it out if you like to see what you make of it (it's pretty up to date with development now). There's one more problem I know of I'll be fixing later this week and then I really want to try and write several Python automated tests to verify the behavior. I'll try and post a PR before then but won't merge until that's complete. Thanks for your patience!

**Comment by hultonha** [comment] 2023-01-30 13:51
This is getting close now - https://github.com/o3de/o3de/pull/14269. Still a couple more tests to write and some other features to test (e.g. Track View) but hopefully this will be merged (or at least reviewed this week) 👍

**Comment by hultonha** [comment] 2023-02-06 11:52
PR is finally ready! 😄 Sorry it took so long @Darkinggq, it fixes _a lot_ of issues though 😅 And there's tests to prove it! 🥳

**Closed** 2023-02-08 09:44 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/viewport
