### ISSUE TITLE
Linux: Project built via Project Manager on a Source engine build configuration cannot be launched from Project Manager

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#7748] opened 2022-02-18 13:10 UTC
**Describe the bug**
On Linux if a project is built via Project Manager on a Source engine (following the official documentation - https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/), it cannot be launched via the Project Manager "as is" most of the time. This could be related to https://github.com/o3de/o3de/issues/5862 , as in order to build Standard Template project or a project that contains all Gems, the build process in the Project Manager fails multiple times due to the "ninja: build stopped: subcommand failed" described in the issue.

Minimal Template project build goes through without an issue on one of the PCs (it started the Editor correctly). On another the Editor launched, but after processing about half of the assets in the Asset Processor it crashed, and could not be launched via the Project Manager again, turning off on the splash screen.

There was also one situation where Standard Template project was launched on one of the PCs after failing its build.

Overall reproduction rate of this issue while using the Source engine build configuration with a Standard template type project is **10/10**. Changing the build configuration and project template will affect the reproduction rate as described above.

It should be noted that reconfiguring the Source engine with a -DLY_PROJECTS=<path to the project built in Project Manager> (e.g. `cmake -B build/linux -S . -G "Ninja Multi-Config" -DLY_3RDPARTY_PATH=$HOME/o3de-packages -DLY_PROJECTS=/home/gpc-610/O3DE/Projects/NewProject`) and rebuilding it once again solves this issue.

It should also be noted that while using the Pre-built SDK configuration the issue does not occur and the project can be built and launched via Project Manager. On Windows this issue does not occur for either of the build configurations.

Please refer to the logs and hardinfo files attached in a section below for more information.

**Steps to reproduce**
1. Configure and build a Source engine as described on the https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/ documentation page.
2. Launch the Project Manager.
3. Create a Standard template project, with everything in configuration left at default values.
4. Build the project via the Project Manager.
5. Launch the project via the Project Manager.

**Expected behavior**
Project launches.

**Actual behavior**
Project won't launch without reconfiguring and rebuilding it.

**Logs and hardinfo files**
Source engine, Project Manager launched via Terminal, attempting to open successfully built Standard Template project via "Open Editor" button on its Tile:
[TerminalPMProjectLaunchLog.txt](https://github.com/o3de/o3de/files/8096670/TerminalPMProjectLaunchLog.txt)
Source engine, attempting to launch the Editor directly with --project-path=<path to the project built in Project Manager> argument:
[TerminalEditorPPArgLaunchLog.txt](https://github.com/o3de/o3de/files/8096669/TerminalEditorPPArgLaunchLog.txt)

Hardinfo files:
[hardinfo_report_gpc-427.txt](https://github.com/o3de/o3de/files/8096686/hardinfo_report_gpc-427.txt) - This is the PC which managed to successfully launch Minimum Template project after building it without issue, and could launch the Standard Template from the Project Manager project despite it failing to build.
[hardinfo_report_gpc-602.txt](https://github.com/o3de/o3de/files/8096744/hardinfo_report_gpc-602.txt) - This PC verified Source/Pre-built SDK Project Manager project builds, confirming both the reproduction of this issue on the Source configuration and lack of the issue on the Pre-built SDK configuration.
[hardinfo_report_gpc-610.txt](https://github.com/o3de/o3de/files/8096687/hardinfo_report_gpc-610.txt) - This is the PC which had the described crash to desktop on Minimal Template project after building it successfully, about midway through processing the assets in the Asset Processor.

**Found in Branch**
Development (c0299f0)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by spham-amzn** [comment] 2022-03-25 20:26
Verified still occuring with https://github.com/o3de/o3de/commit/621d841d3e82277e544f55b1ef41abca8b8efaea . 
The problem appears to be related to https://github.com/o3de/o3de/blob/621d841d3e82277e544f55b1ef41abca8b8efaea/Code/Tools/ProjectManager/Source/ProjectsScreen.cpp#L431 and how `LaunchUnwatchedProcess` is handled on Linux. 
Running the editor for the new project from command line launches the editor without issue

**Comment by AMZN-Gene** [comment] 2022-04-04 19:49
repro'd crash on first open. 2nd attempt editor opened.

**Comment by amzn-pratikpa** [comment] 2022-04-19 20:03
@AMZN-nggieber see comment above from @AMZN-Gene as they can reproduce it

**Comment by forhalle** [comment] 2022-05-03 18:12
@amzn-pratikpa - we don't feel feature/project-manager label should be applied here. If you have a question, please contact @AMZN-nggieber .

**Comment by spham-amzn** [comment] 2022-05-23 18:08
Cannot reproduce issue, closing for now

https://user-images.githubusercontent.com/82231385/169880689-9a400fe1-561f-4286-8f1f-a51775f33b83.mp4

**Closed by spham-amzn** 2022-05-23 18:08 UTC
Labels: platform/linux, feature/editor, kind/bug, sig/build, sig/content, sig/platform, priority/critical
