### ISSUE TITLE
Atom golden image test failing in main suite

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7885] opened 2022-02-24 21:33 UTC
**Describe the bug**
Tests against a golden image are failing when run locally, from TestAutomation.AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages_DX12. This unexpected failure suggests an environmentally dependent bug in rendering. This may instead be due to an unconstrained test, however tests in the main suite should be reproducible across different environments and this would still be considered a bug.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration, with the AutomatedTesting project enabled
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -R AutomatedTesting::Atom_TestSuite_Main_GPU --output-on-failure`
4. See error (likely machine dependent)

**Expected behavior**
Test pass.

**Actual behavior**
One of two failure types are observed:
49/50 were:
```
_ TestAutomation.AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages_DX12[windows-crash_log_watchdog0-windows_editor-AutomatedTesting] _
c:\gitly\o3de\tools\lytesttools\ly_test_tools\o3de\editor_test.py:439: in single_run
    next(wrap, None)
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py:69: in wrap_run
    assert compare_screenshot_to_golden_image(self.screenshot_directory,
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\atom_utils\atom_component_helper.py:109: in compare_screenshot_to_golden_image
    raise ImageComparisonTestFailure(f"Screenshot test failed: {screenshot_comparison_result}")
E   Atom.atom_utils.atom_component_helper.ImageComparisonTestFailure: Screenshot test failed: When comparing the test_screenshot: 'C:\gitly\o3de\AutomatedTesting\user/PythonTests/Automated/Screenshots\AreaLight_1.ppm' to golden_image: 'C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\atom_utils\..\golden_images\AreaLight_1.ppm'.
E   The mean similarity (0.8249384115890882) was lower than the similarity threshold (0.96)
```
1/50 was:
```
_ TestAutomation.AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages_DX12[windows-crash_log_watchdog0-windows_editor-AutomatedTesting] _
c:\gitly\o3de\tools\lytesttools\ly_test_tools\o3de\editor_test.py:439: in single_run
    next(wrap, None)
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py:69: in wrap_run
    assert compare_screenshot_to_golden_image(self.screenshot_directory,
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\atom_utils\atom_component_helper.py:107: in compare_screenshot_to_golden_image
    test_screenshot, golden_image, similarity_threshold, True, screenshot_directory)
C:\gitly\o3de\AutomatedTesting\Gem\PythonTests\Atom\atom_utils\atom_component_helper.py:84: in compare_screenshot_similarity
    mean_similarity = compare_screenshots(test_screenshot, golden_image)
c:\gitly\o3de\tools\lytesttools\ly_test_tools\image\screenshot_compare_qssim.py:98: in qssim
    hue2[:, :, 1:4] = img2
E   ValueError: could not broadcast input array from shape (1080,1920,3) into shape (2160,3840,3)
```

**Found in Branch**
Development @ b4db237c94

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10 Enterprise 64-bit, 20H2 build 19042.1526, Experience Pack 120.2212.4170.0
 - CPU AMD 3970X
 - GPU NVidia RTX 3070 Ti
 - GPU Driver: 511.56
 - Memory 64GB

**Additional context**
Unable to find a locally cached screenshot compared during this test. This test does not appear to fail in the AutomatedReview pipeline, and may be machine-specific.

**Comment by rgba16f** [comment] 2022-02-24 21:40
Could we get a little more info on your gpu hw, what driver revision you are running, and what OS revision you are running.
Thanks.

**Comment by Kadino** [comment] 2022-02-24 21:55
Updated GPU info. What additional OS revision information do you need?

**Comment by rgba16f** [comment] 2022-02-24 21:58
Just the build or revision. This is what I see in the "About this PC" section
![image](https://user-images.githubusercontent.com/82187279/155614541-fbbaa345-0efb-4edd-bc2e-81e9589cce0d.png)

**Comment by Kadino** [comment] 2022-02-24 22:25
This also occurs in development @ 5411a590ec with Nvidia driver 511.79

Uploading logs from each

**Comment by Kadino** [comment] 2022-02-24 22:28
[b4db237c94_1.txt](https://github.com/o3de/o3de/files/8136943/b4db237c94_1.txt)
[b4db237c94_2.txt](https://github.com/o3de/o3de/files/8136945/b4db237c94_2.txt)
[5411a590ec_1.txt](https://github.com/o3de/o3de/files/8136944/5411a590ec_1.txt)

**Comment by smurly** [comment] 2022-02-24 22:40
ValueError: could not broadcast input array from shape (1080,1920,3) into shape (2160,3840,3)
this is caused by windows accessibility scaling. qssim can't compensate for a desktop that scales the screenshot viewport 200%.
GPU tests need to be run with display scaling 100% (essentially no scaling)

**Comment by Kadino** [comment] 2022-02-25 01:19
Makes sense that this would be an environmental setting issue. Tests with significant environmental variance should either compensate for the variance, or not live in the Main suite.

If the desktop environment cannot be compensated for, I recommend generating the compared images directly from the renderer's API, instead of passing through the editor and/or operating system.

**Comment by smurly** [comment] 2022-02-25 01:49
screenshot utilizes
azlmbr.atom.FrameCaptureRequestBus(azlmbr.bus.Broadcast, "CaptureScreenshot", f"{folder_path}/{filename}")
The source seems to be from the window swapchain out of RPI
the bus is handled in .\o3de\Gems\Atom\Feature\Common\Code\Source\FrameCaptureSystemComponent.cpp
jenkins nodes do not utilize screen scaling.

the other error is a valid failure caused by the removal of lighting preset display name that should be fixed with
https://github.com/o3de/o3de-atom-sampleviewer/pull/352

**Comment by Kadino** [comment] 2022-02-25 02:22
Suggest that either qssim or RPI should be configured to compensate for the scaling factor.

**Comment by rgba16f** [comment] 2022-02-25 02:24
In the editor and launcher Atom is already rendering at the scaled resolution.

**Comment by Kadino** [comment] 2022-02-25 18:43
One concern is that a public customer would pull down O3DE and run the main tests suite, see a broken test, and decide it's not stable enough to use. The test could instead detect whether scaling is in use, and either compensate or skip itself.

**Comment by jromnoa** [comment] 2022-03-21 23:26
There has been a crash / swap chain error that has been blocking any progress on this. Once unblocked, this work will be assigned and taken on.

**Comment by jromnoa** [comment] 2023-03-16 15:22
These tests will continue to be skipped, but the code will remain to serve as an example of how to setup GPU tests for AR since there are other tests in `TestSuite_Main_GPU.py` that currently pass that utilize the GPU.
We mainly utilize AtomSampleViewer to verify GPU results.

In any case, users won't see this error any more unless they remove the test skipping manually, which would then place responsibility on them to fix it since we intend for it to be skipped for the time being.

**Closed by jromnoa** 2023-03-16 15:22 UTC
Labels: feature/graphics, kind/bug, sig/graphics-audio, priority/critical
