### ISSUE TITLE
Linux: Editor is unresponsive after launching Game Mode (Maximized)

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#4723] opened 2021-10-15 13:15 UTC
**Describe the bug**
Entering Game Mode (Maximized) causes the Editor to become unresponsive and its interface to disappear.

This issue does not occur on Windows.

**Steps to reproduce**
1. Create a level.
2. Press the "Play Game (Maximized)" button in the top right corner.

**Expected behavior**
Editor enters Game Mode in a maximized window.

**Actual behavior**
Editor stops responding.

**Video**

https://user-images.githubusercontent.com/86952082/137481307-17fd5b30-929e-49f3-9b79-9317aa45dcf6.mp4

**Found in Branch**
Development (16e60a9)

**Desktop**
Device: PC
OS: Linux
Version: Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment] 2021-11-01 22:07
@monroegm Potential reroute to editor

**Comment by FuzzyCarterAWS** [comment] 2022-01-22 00:06
I'm unable to repro this issue on my Linux machine.

@LB-ArturZieba, which GPU driver do you have installed? Are you able to send the editor.log over so we can see any potential warnings/errors that led up to the crash?

**Comment by Magical10240** [comment] 2022-01-22 08:16
it's the same #6764

**Comment by LB-ArturZieba** [comment] 2022-01-26 12:57
@FuzzyCarterAWS I've reproduced this issue on the Development (e6113eb) build, and entering the Play Game (Maximized) has a different effect currently. Currently it launches the Game Mode in a small window near the middle of the screen, I've attached a video of it happening. Please note that while you can see cursor in the video while in the Game Mode both regular, and maximized, as well as at the end of the video after exiting the maximized Game Mode, I did not have a cursor on my screen and had to close the Editor via Alt+F4 because I could not close it manually.

https://user-images.githubusercontent.com/86952082/151166431-e3a70c8f-06ce-4edd-8f45-25d5a734a66e.mp4

As for the Editor.log and the driver used:
I have the NVIDIA driver metapackage from nvidia-driver-470 (proprietary, tested) installed.

The Editor.log from the video I've attached to this comment can be found here: [Editor.log](https://github.com/o3de/o3de/files/7941822/Editor.log)

**Comment by jckand-amzn** [comment] 2022-02-16 16:34
@monroegm this doesn't appear related to prefabs or Editor. Seems to be a rendering or some other platform issue. I think sig/content can be removed from this ticket. [jiaweig-amzn](https://github.com/jiaweig-amzn) has another duplicate ticket assigned for investigation, so this ticket can potentially even just be closed out at this point.

**Comment by monroegm** [comment] 2022-03-01 17:40
Duplicate of #6764

**Closed by monroegm** 2022-03-01 17:40 UTC
Labels: platform/linux, kind/bug, sig/content, sig/platform, triage/accepted, priority/critical, feature/prefabs

**Comment by LB-ArturZieba** [comment] 2022-03-02 08:05
Further progress on the issue will be covered in https://github.com/o3de/o3de/issues/6764, as per the comment above.
