### ISSUE TITLE
UI Animation Editor is unusable

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2709] opened 2021-08-02 17:11 UTC
**Describe the bug**
The UI Animation editor appears to be missing the timeline view and there is no way to change the play head time, view keyframes or edit them (that I could find)

**To Reproduce**
1. Create a UI canvas
2. Add a UI sequence
3. In the sequence window add a UI element
4. Attempt to animate the element over time by fading it in and out
5. Attempt to change the keyframes for fading in and out

**Expected behavior**
The user can view and manipulate keyframes in the timeline

**Screenshots**
Here I attempted to record a fade out animation by using the 'record' functionality and hitting play to advance the playhead.  This kinda worked but ultimately was an exercise in frustration.  This is a regression.

![UIAnimationSadness](https://user-images.githubusercontent.com/26804013/127898666-d01120c4-f38d-4381-ba01-b1e3686e2a89.JPG)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by jckand-amzn** [comment] 2021-11-05 17:40
Unable to reproduce on stabilization/2110@fdc56b4a57f2f07.

Repro Steps:
1. Open a new level.
2. Open the UI Editor.
3. Click View > Animation editor if necessary.
4. Click the Add Sequence button in the UI Animation Editor.
5. Name the sequence, and click OK.
6. Right-click the canvas area and add a new Image element.
7. Right-click the open sequence in the UI Editor and Add Selected UI Element.
8. Add a Fader element to the Image element.
9. Click the Record button in the animation editor.
10. With the playhead at 0s, set the Fader component's Fade property to 0.
11. Move the playhead in the sequence to 2s.
12. Set the Fader component's Fade property to 1.
13. Click the Preview button.
14. With the created sequence selected, click the Play button.

**Comment by chiyenteng** [comment] 2021-11-09 20:43
Fix has been merge into stable: https://github.com/o3de/o3de/pull/5453

**Comment by chiyenteng** [comment] 2021-11-09 20:44
Closing the issue.

**Closed by chiyenteng** 2021-11-09 20:44 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/lyshine
