### ISSUE TITLE
PyTest intermittently fails to write xml results

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#11667] opened 2022-08-30 22:08 UTC
**Describe the bug**
PyTest can fail while preparing to write its XML report, causing test runs to unexpectedly report failure. This creates a severe impact to the health of the CI pipeline.

This bug appears to emit from PyTest when it attempts to write its XML report: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/3041/pipeline

**Assets required**
N/A

**Steps to reproduce**
Unknown

**Expected behavior**
Passing tests always report success.

**Actual behavior**
Intermittent failure while writing a file to disk results in:
```
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pytest\__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\junitxml.py", line 650, in pytest_sessionfinish
    os.makedirs(dirname)
  File "D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\workspace\\o3de\\build\\windows\\Testing\\Pytest

```

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Monterey, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
* This appears to be occurring due to running multiple instances of pytest in parallel, or pytest-calling-pytest
   * Rewriting the offending tests should be appropriate
* Calling the safe version of `os.makedirs(exist_ok=True)` should resolve this issue, but the call originates from third party code.
   * A change could be proposed to https://github.com/pytest-dev/pytest/blob/main/src/_pytest/junitxml.py#L649 (else a workaround will have to be employed)
   * May occur due to a file existing with the same name as the intended folder? Do not have access to the environment where this failed.

**Comment by evanchia-ly-sdets** [comment] 2022-08-30 22:53
This is a race condition when two pytests attempt to create their xml's (and thus must first create the parent directory). There should already be a workaround in AR where the directory is pre-created, so this should be investigated.

**Comment by evanchia-ly-sdets** [comment] 2022-09-02 19:51
The in place workarounds are still in tact and there is no obvious signs as to why this issue occurred despite them. This issue is not easily reproducible in the pipeline so an RFC will be created for a new feature that can help debug this issue.

**Comment by Kadino** [comment] 2022-09-02 22:30
I wonder if something could be removing the supposedly pre-existing directory, such as artifact copying?

A small RFC seems fine, as long as it proposes a specific action.

**Comment by evanchia-ly-sdets** [comment] 2022-09-02 23:38
The current hypothesis is lag between the mounted volume and jenkins because the directory exists 2 minutes before the test step executes, but as mentioned it is difficult to prove.

**Comment by Kadino** [comment] 2022-09-08 17:55
This recently occurred in the stabilization branch, being the only failure seen there: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/stabilization%2F2210/12/pipeline

**Comment by Kadino** [comment] 2022-09-09 18:18
This appears to only occur in scripts\ctest\sanity_test.py::test_Insanity while skipping a test.

Disabling this test until this can be further investigated.

**Comment by Kadino** [comment] 2022-09-13 18:16
Need to investigate the options for resolution, particularly whether the tests are important to retain/rewrite.

**Comment by Kadino** [comment] 2022-09-13 18:40
May be related to https://github.com/o3de/o3de/issues/11528

**Comment by tonybalandiuk** [comment] 2022-09-18 15:22
@Kadino @AMZN-Dk Do we think this needs to be resolved in the upcoming release? If so, we should add it to the "Release/2210" milestone

**Comment by Kadino** [comment] 2022-09-18 19:39
No. Initial investigation indicated this is due to 1-2 specific files of poorly written tests. These are self-tests of an experimental addition to the test framework, and not tests of O3DE production code.

The misbehaving tests are currently disabled in development and stabilization.

**Comment by Kadino** [comment] 2022-09-19 18:47
Could be occurring due to the tests of the (unused) CTest CLI wrapper which would be using CTest+PyTest to then internally re-invoke a script which uses CTest+PyTest

**Closed** 2022-10-07 17:22 UTC
Labels: kind/bug, sig/testing, triage/needs-information, priority/critical
