### ISSUE TITLE
Dependencies are not set for AutomatedTesting gem 

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#8353] opened 2022-03-16 10:30 UTC
**Describe the bug**
The AutomatedTesting gem needs at least one dependent gem to be enabled alongside, which is the Multiplayer gem. Without it, the Editor crashes at launch with the following Module Manager error.

![error](https://user-images.githubusercontent.com/86952009/158567217-9765d554-eb23-45aa-b4db-1f3befc6352a.JPG)

**Steps to reproduce**
1. Create a new project.
2. Enable the AutomatedTesting gem and disable the Multiplayer gem.
3. Rebuild and launch the Editor.

**Expected behavior**
All gem dependencies are set. The Editor launches.

**Actual behavior**
The Editor crashes at launch.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/158567502-e2692a0f-413b-4117-9fd7-fc62662fd132.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/b90a8f3007dbb41508ff7e2f36f99dd845a9fce5)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Additional context**
[dump.zip](https://github.com/o3de/o3de/files/8261130/dump.zip)
[Editor.log](https://github.com/o3de/o3de/files/8261131/Editor.log)
[error.log](https://github.com/o3de/o3de/files/8261132/error.log)

**Comment by lmbr-pip** [comment] 2022-03-16 18:20
Its this line thats breaking things: https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp#L53

```
   void AutomatedTestingSystemComponent::GetRequiredServices(AZ::ComponentDescriptor::DependencyArrayType& required)
    {
        required.push_back(AZ_CRC_CE("MultiplayerService"));
    }
```

System component is stating that it needs MultiplayerService, AutomatedTesting is not a multiplayer project.

**Comment by lumberyard-employee-dm** [comment] 2022-03-16 21:32
The AutomatedTesting Gem needs to add a RUNTIME_DEPENDENCIES on the `Gem::Multiplayer` Gem Module in it's [CMakeLists.txt](https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/Code/CMakeLists.txt#L28-L37)

That being said the AutomatedTesting gem shouldn't be used on a project that isn't the AutomatedTesting project.

The steps illustrates that the AutomatedTesting gem is trying to be used on new project, where the AutomatedTesting gem shouldn't be exposed in the Project Manager.

**Comment by lumberyard-employee-dm** [comment] 2022-03-16 21:38
The ProjectManager does have a command to retrieve all gems available to a specific project via it's [PythonBindings](https://github.com/o3de/o3de/blob/development/Code/Tools/ProjectManager/Source/PythonBindings.cpp#L573-L574).

I believe it might be showing the Gems for the AutomatedTesting project, in the Configure Gems dialog when it shouldn't

**Comment by LB-BartoszDudzinski** [comment] 2022-03-17 07:02
@amzn-pratikpa Hi! Yes, I am creating a new project and adding the Automated Testing gem to it.

**Comment by AMZN-alexpete** [comment] 2022-04-19 18:19
I agree ProjectManager should not show gems in other Project's folders for now until we have a good use case or user request to support this use case.

**Comment by forhalle** [comment] 2022-04-19 18:27
Per conversation with @Ulrick28, I am downgrading this to major because the user must go out of their way to make this happen - it is not a common workflow problem.

**Comment by robhaco** [comment] 2022-08-01 00:40
The automated testing gem no longer displays in the gem list for other projects.  Closing this issue as no longer able to reproduce.

**Closed by robhaco** 2022-08-01 00:40 UTC
Labels: kind/bug, sig/content, sig/ui-ux, triage/accepted, priority/major, feature/project-manager, needs-ux-action

**Comment by LB-BartoszDudzinski** [comment] 2022-08-01 09:16
Verified as Fixed in development.
