### ISSUE TITLE
[Linux] Users cannot interact with the Launcher Console on Linux 

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#8872] opened 2022-04-12 13:45 UTC
**Describe the bug**
After the launcher starts, the console goes black and the user cannot put any commands into it.

Project: MultiplayerSamples

**Steps to reproduce**
1. Build the MultiplayerSample project for Server.
2. Run the MultiplayerSampleServer.Launcher.

**Expected behavior**
The Launcher starts and the console is ready to accept commands.

**Actual behavior**
The console is black and the user cannot enter commands into it.

**Screenshots/Video**

![multiplayer server linux](https://user-images.githubusercontent.com/86952591/162974399-3dd30039-109f-4bfa-88c0-f120472e7c4e.png)

**Found in Branch**
Stabilization_2205 (3e47df2)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Comment by AMZN-Gene** [comment] 2022-04-14 17:45
It's working in AutomatedTesting. Need someone to test in MPS... doesn't seem like MPS would render anything differently.

**Comment by lmbr-pip** [comment] 2022-04-14 17:46
Needs server log, need to load in with a map to get console to work.

@AMZN-Gene - This appears to work in AutomatedTesting ServerLauncher on Linux, even without a map.

Need to identify the difference and potential help from sig-graphics-audio

**Comment by AMZN-Gene** [comment] 2022-04-15 16:49
> Needs server log, need to load in with a map to get console to work.
> 
> @AMZN-Gene - This appears to work in AutomatedTesting ServerLauncher on Linux, even without a map.
> 
> Need to identify the difference and potential help from sig-graphics-audio

attached server.log to my last comment

**Comment by junbo75** [comment] 2022-04-18 17:18
I couldn't repro this issue using MultiplayerSample.ServerLauncher. @LB-JakubSkoczylas Could you check whether the Asset Processor has finished processing in the background? 
I'm testing with o3de Stabilization/2205@201271c3 and o3de-multiplayersample Stabilization/2205@8dee2e5.
![image](https://user-images.githubusercontent.com/68558268/163845742-e745cdbe-0b25-44be-93ad-da91f09c3aef.png)

**Comment by lmbr-pip** [comment] 2022-04-18 18:09
@LB-JakubSkoczylas. Please confirm this is still an issue for you, otherwise will close as not reproducible (also likely that another issue resolved this). If this repros for you, please provide logs.

**Comment by LB-MateuszSzweda** [comment] 2022-04-21 12:48
@lmbr-pip 
I was unable to reproduce the issue on Stabilization_2205 (651a5a3) the built multiplayersample game and server launchers had a working console. It seems the issue can be closed as not reproducible.

**Comment by lmbr-pip** [comment] 2022-04-21 15:26
Closing as DNR

**Closed by lmbr-pip** 2022-04-21 15:26 UTC
Labels: platform/linux, kind/bug, sig/network, triage/accepted, status/not-reproducible, priority/blocker
