### ISSUE TITLE
Project does not launch when built using minimal template with Virtual Gamepad gem enabled

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#6995] opened 2022-01-19 10:48 UTC
**Describe the bug**
A minimal template project fails to launch when the Virtual Gamepad gem is added. The issue occurs only with this particular gem enabled.

**Steps to reproduce**
1. Launch the Project Manager.
2. Create a project using the minimal template and add the Virtual Gamepad gem to it.
3. Build the project and launch it afterwards.

**Expected behavior**
The project launches without issues.

**Actual behavior**
The project does not launch. Two errors related to the gems are displayed.

**Screenshots/Video**

![error](https://user-images.githubusercontent.com/86952009/150111339-b14a8841-b416-43dc-9223-ea803ada0c3f.JPG)
![error2](https://user-images.githubusercontent.com/86952009/150111341-ed0f63a9-18aa-44f6-ae93-1a2307622ac0.JPG)

https://user-images.githubusercontent.com/86952009/150111342-84b22236-eb1f-423b-9ad1-3a8a5793d4ed.mp4

**Found in Branch**
Installer

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by amznestebanpapp** [comment] 2022-01-19 17:20
@byrcolin we think this is related to your recent changes

**Comment by lumberyard-employee-dm** [comment] 2022-01-21 20:49
It looks like the VirtualGamepad Gem is missing a Gem dependency on LyShine.
I'll fix it

**Comment by amznestebanpapp** [comment] 2022-01-21 23:08
Should be fixed by #7081

**Comment by lumberyard-employee-dm** [comment] 2022-01-21 23:10
Actually this issue was caused by another change https://github.com/o3de/o3de/commit/193f529b9c8469930252b20d9fd15bd2bbc9bf60 for which I put up a fix for in PR #7087

**Closed** 2022-01-24 23:24 UTC
Labels: kind/bug, sig/core, priority/critical, WF1, RTE

**Comment by LB-BartoszDudzinski** [comment] 2022-01-26 13:20
Verified as Fixed in Development.
