### ISSUE TITLE
Material editor does not support drag-and-drop

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2852] opened 2021-08-04 20:52 UTC
**Describe the bug**
Dragging a material file from Windows Explorer into MaterialEditor.exe does not result in the file being opened.

**To Reproduce**
1. Drag a file into MaterialEditor.exe

**Expected behavior**
File opens

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**

**Comment by gadams3** [comment] 2022-03-24 18:55
Closing as duplicate of #3404

**Closed by gadams3** 2022-03-24 18:55 UTC
Labels: needs-priority, sig/graphics-audio, sig/ui-ux, kind/enhancement
