### ISSUE TITLE
Bug Report: DPE Inspector, Script canvas variables array add numbers not visible [Point Release 23.10.1]

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#17208] opened 2023-12-07 07:42 UTC
**Steps to reproduce**
1. Open Script Canvas
2. Create Variable
3. Any array example string
4. Script Canvas saved
5. DPE Inspector add array from SC array string
6. The beginning and end are visible but the center is not visible
![image](https://github.com/o3de/o3de/assets/17591539/1b416507-0834-4f33-bd9c-d2b3ae3f4edf)

**Screenshots/Video**

https://github.com/o3de/o3de/assets/17591539/c23d07f7-6d6f-4496-ba17-6fdc93089bf4

**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
dc6e2f7a2396aa1b9722bdae1c5453d7727266f9 (HEAD -> point-release/23101, origin/point-release/23101)

**Desktop/Device (please complete the following information):**
 - Device: Linux
 - OS: Fedora
 - Version 38

**Comment by loherangrin** [comment] 2023-12-13 16:35
The error happens also in simpler components that are using an array of strings, such as `Tag`.
![tag-missing-fields-1](https://github.com/o3de/o3de/assets/51530087/9aec460f-cae7-4fdd-8455-08f23393c553)

Moreover, when the container is cleared by pressing the `Delete All` button, any other button disappear too until the card is forced to refresh (i.e. select another entity and return to the previous).

![tag-missing-fields-2](https://github.com/o3de/o3de/assets/51530087/cb05a531-8d13-4136-ba81-f4cc81ffa628)


**Found in Branch**
point-release/23101

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
f0c150d75722b3302753972b28d73a8036b70b31

**Comment by Darkinggq** [comment] 2023-12-13 17:05
Component "Simple State" 

![image](https://github.com/o3de/o3de/assets/17591539/39f21a09-9d24-4840-b8ef-511ccbf0378a)

if you delete all the array, zero numbers are missing

![image](https://github.com/o3de/o3de/assets/17591539/d008595f-7df3-4fbd-bae9-447f3c0f3bd8)

https://github.com/o3de/o3de/assets/17591539/c1daa13b-c5ba-4984-9d9f-78391846c683

**Comment by AMZN-alexpete** [comment] 2023-12-18 19:03
Thanks for reporting this issue @Darkinggq, I think it sounds like the issue is related to more than just Script Canvas so perhaps it'd be a good idea to update the title?

**Comment by alexmontAmazon** [comment] 2023-12-19 19:17
In review here:
https://github.com/o3de/o3de/pull/17289

**Comment by Darkinggq** [comment] 2023-12-19 20:19
there are other GHI #17288 #17287

**Comment by alexmontAmazon** [comment] 2023-12-20 18:53
fixed in development branch.

**Closed by alexmontAmazon** 2023-12-20 18:53 UTC
Labels: kind/bug, sig/content, triage/accepted
