### ISSUE TITLE
Crash after deleting .prefab from disk

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#10697] opened 2022-07-15 18:24 UTC
**Describe the bug**
I deleted a .prefab file from my project, forgetting that I still had one instantiated in an open level, and when I switched back to the Editor, it crashed.

**Assets required**
none

**Steps to reproduce**
1. Create a .prefab file
2. Save it to disk
3. Instantiate the prefab in a level in the editor
4. delete the .prefab file
5. return to the Editor

**Expected behavior**
Some sort of error saying the asset is missing

**Actual behavior**
crash with the following callstack:
>	EditorLib.dll!rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>>::FindMember(const char * name) Line 1324	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabDomUtils::FindPrefabDomValue(rapidjson_ly::GenericValue<rapidjson_ly::UTF8<char>,rapidjson_ly::MemoryPoolAllocator<rapidjson_ly::CrtAllocator>> & parentValue, const char * valueName) Line 213	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::RemoveLink(std::unique_ptr<AzToolsFramework::Prefab::Instance,std::default_delete<AzToolsFramework::Prefab::Instance>> & sourceInstance, unsigned __int64 targetTemplateId, AzToolsFramework::UndoSystem::URSequencePoint * undoBatch) Line 546	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::DeleteFromInstance(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds) Line 1265	C++
 	EditorLib.dll!AzToolsFramework::Prefab::PrefabPublicHandler::DeleteEntitiesAndAllDescendantsInInstance(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entityIds) Line 1055	C++
 	EditorLib.dll!AzToolsFramework::EditorEntityManager::DeleteEntitiesAndAllDescendants(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entities) Line 65	C++
 	EditorLib.dll!AzToolsFramework::ToolsApplication::DeleteEntitiesAndAllDescendants(const AZStd::vector<AZ::EntityId,AZStd::allocator> & entities) Line 886	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 177	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::invoke(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 54	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) &&) Line 437	C++
 	ComponentEntityEditorPlugin.dll!AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests>>::Broadcast<void (__cdecl AzToolsFramework::ToolsApplicationRequests::*)(AZStd::vector<AZ::EntityId,AZStd::allocator> const &),AZStd::vector<AZ::EntityId,AZStd::allocator>>(void(AzToolsFramework::ToolsApplicationRequests::*)(const AZStd::vector<AZ::EntityId,AZStd::allocator> &) && func, AZStd::vector<AZ::EntityId,AZStd::allocator> && <args_0>) Line 1541	C++
 	ComponentEntityEditorPlugin.dll!SandboxIntegrationManager::DeleteSelectedEntities(bool includeDescendants) Line 1232	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::Internal::INVOKE(void(AzToolsFramework::EditorRequests::*)(bool) &&) Line 177	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZStd::invoke(void(AzToolsFramework::EditorRequests::*)(bool) &&) Line 54	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZ::EBusEventProcessingPolicy::Call(void(AzToolsFramework::EditorRequests::*)(bool) &&) Line 437	C++
 	ComponentEntityEditorPlugin.dll!AZ::Internal::EBusContainer<AzToolsFramework::EditorRequests,AzToolsFramework::EditorRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::EditorRequests,AzToolsFramework::EditorRequests>>::Broadcast<void (__cdecl AzToolsFramework::EditorRequests::*)(bool),bool>(void(AzToolsFramework::EditorRequests::*)(bool) && func, bool && <args_0>) Line 1541	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityOutlinerWidget::DoDeleteSelectionAndDescendants() Line 734	C++
 	[External Code]	
 	EditorLib.dll!ShortcutDispatcher::FindCandidateActionAndFire(QObject * focusWidget, QShortcutEvent * shortcutEvent, QList<QAction *> & candidates, QSet<QObject *> & previouslyVisited) Line 310	C++
 	EditorLib.dll!ShortcutDispatcher::shortcutFilter(QObject * obj, QShortcutEvent * shortcutEvent) Line 443	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3937	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 31	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development, commit 4c8dabd8218fc732a90fbb025944f3150ee1c7e1

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB

**Additional context**

**Comment by AMZN-Olex** [comment] 2022-07-24 04:34
I am seeing this when I delete a prefab placed on the level.

**Comment by srikappa-amzn** [comment] 2022-07-27 21:14
Efforts are currently underway to support hot reloading of prefabs, which will detect file changes including deletions

**Comment by srikappa-amzn** [comment] 2022-07-27 21:54
@AMZN-Olex and @amzn-tommy , I'm not able to reproduce the crash after deleting the prefab from file and returning to the editor. I even did a few operations on the prefab after returning to the editor. Are you doing any specific actions in the editor after you return to the editor that is making it crash?

**Comment by LB-JakubSkorupka** [comment] 2022-07-28 11:35
We managed to find the issue where Editor crashes after adding the component to the entity inside the prefab and then deleting that prefab from the level in Entity Outliner. Please refer to the attached logs.
Would you like us to create a separate issue for this?
[Editor.log](https://github.com/o3de/o3de/files/9208946/Editor.log)
[error.log](https://github.com/o3de/o3de/files/9208947/error.log)
[error01.zip](https://github.com/o3de/o3de/files/9208948/error01.zip)
[error02.zip](https://github.com/o3de/o3de/files/9208952/error02.zip)

**Comment by srikappa-amzn** [comment] 2022-07-28 18:54
@LB-JakubSkorupka , I came across another issue with deleting of prefabs from editor. So the issue you reported might not have anything to do with deleting prefab from disk. Can you verify if this is what you are running into? https://github.com/o3de/o3de/issues/10942

If so, this issue can be closed and we can track 10942 for a fix

**Comment by LB-JakubSkorupka** [comment] 2022-07-29 09:11
@srikappa-amzn, the https://github.com/o3de/o3de/issues/10942 issue does not reproduce for me with the current steps, I confirmed that an entity inside the prefab must be edited in some way (rename entity, add component to the entity, modify values in Transform component) before exiting the Focus Mode and deleting the prefab from the level to cause Editor crash.

**Comment by srikappa-amzn** [comment] 2022-07-29 16:42
Thanks for confirming @LB-JakubSkorupka . Yes you are correct. The entity inside the prefab must be edited in some manner before exiting focus and deleting the prefab to see the crash. I'll update the repro steps on that issue and closing this one as a duplicate.

**Closed by srikappa-amzn** 2022-07-29 16:42 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
