### ISSUE TITLE
Bug Report: WWise not functioning,  can't news instance of an AudioObject from the implementation.

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#13609] opened 2022-12-08 18:06 UTC
**Describe the bug**
Wwise audio is no longer working after recent memory allocation changes

**Assets required**
Any project with Wwise enabled, for example https://github.com/aws-lumberyard-dev/o3de-multiplayersample/tree/GameJam_2022_07

**Steps to reproduce**
1. Open Editor
2. Enter game
3. Observer the errors in the console and lack of sounds

**Expected behavior**
Wwise plays sound effects

**Actual behavior**
Wwise does not play sound effects

**Screenshots/Video**
```
[Error] (System) - Failed to get a new instance of an AudioObject from the implementation. If this limit was reached from legitimate content creation and not a scripting error, try increasing the Capacity of Audio::AudioSystemAllocator.
[Error] (System) - Failed to get a new instance of an AudioObject from the implementation. If this limit was reached from legitimate content creation and not a scripting error, try increasing the Capacity of Audio::AudioSystemAllocator.
[Error] (System) - Failed to get a new instance of an AudioObject from the implementation. If this limit was reached from legitimate content creation and not a scripting error, try increasing the Capacity of Audio::AudioSystemAllocator.
[Error] (System) - Failed to get a new instance of an AudioObject from the implementation. If this limit was reached from legitimate content creation and not a scripting error, try increasing the Capacity of Audio::AudioSystemAllocator.
[Error] (System) - Failed to get a new instance of an AudioObject from the implementation. If this limit was reached from legitimate content creation and not a scripting error, try increasing the Capacity of Audio::AudioSystemAllocator.
```

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
88af728fa08d508fb52f2983c9b281477cb106f8

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Comment by lmbr-pip** [comment] 2022-12-08 18:36
Recommendation is to treat as a blocker or at least critical as theres no way to play sounds in O3DE currently.

**Comment by amzn-phist** [comment] 2023-01-04 21:10
@AMZN-Olex I'm running the multiplayersample project and able to hear sounds in Editor as I play the game.  Are there any logs that you could attach from a run where you experienced this?  It might help track down a memory issue earlier in bootup.

**Comment by amzn-phist** [comment] 2023-01-04 22:16
Closing, it appeared to be caused by a configuration issue.  Wwise SDK was no longer being picked up by CMake, which caused downstream runtime issues.

**Closed by amzn-phist** 2023-01-04 22:16 UTC
Labels: kind/bug, sig/graphics-audio, priority/critical
