### ISSUE TITLE
Editor crashes after saving prefab with name of prefab removed from the disk through "Save as..." window

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#10821] opened 2022-07-22 13:56 UTC
**Describe the bug**
Saving a prefab and using the name of another .prefab file that has been removed from the disk in displayed "Save as..." window will result in Editor crashing.

Please refer to the attached logs and error.dmp files.

**Steps to reproduce**
1. Create an entity and create a prefab out of it "Prefab1.prefab".
2. Create another entity.
3. RMB on entity created in second step -> Create Prefab.
4. In "Save as..." window, remove the "Prefab1.prefab" from the disk.
5. Save the prefab with name of previously deleted prefab file - "Prefab1.prefab".
6. When overwrite prompt appears click "Yes".

**Expected behavior**
The Editor remains stable at all times, an error appears in the console or a prompt informing about the issue.

**Actual behavior**
The Editor crashes after saving the prefab with name of prefab file that has been removed from the disk in the "Save as..." window.

**Video**

https://user-images.githubusercontent.com/86951967/180453947-7801cb68-2432-4cc0-aaae-c4ffc341f5e0.mp4

**Found in Branch**
Development (7c01c40)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[error.zip](https://github.com/o3de/o3de/files/9168236/error.zip)
[error.log](https://github.com/o3de/o3de/files/9168238/error.log)
[Editor.log](https://github.com/o3de/o3de/files/9168242/Editor.log)

**Comment by monroegm** [comment] 2022-07-27 15:45
I'm pretty sure this is a duplicate. I will link the other issue when I find it

**Comment by monroegm** [comment] 2022-07-27 23:53
Duplicate of #2376

**Closed by monroegm** 2022-07-27 23:53 UTC
Labels: kind/bug, needs-triage, sig/content, status/duplicate, priority/critical
