### ISSUE TITLE
Feature Request -  When artist adds a PhysX Collider it will not default as a primitive object but a Blank PhysX Mesh

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#10169] opened 2022-06-16 19:48 UTC
**Is your feature request related to a problem? Please describe.**
During RTE an artist wish to have a collider, when adding the PhysX Collider it will not default as a primitive object but a Blank PhysX Mesh. The artist did not know about adding the _phys extension on a mesh in the DCC tool.

![image](https://user-images.githubusercontent.com/87207603/174151468-9569185f-1596-49c4-9752-83ae5eef6f7e.png)

**Describe the solution you'd like**
Maybe start off with simple primitives as default. Or have a tool tip explaining the _phys extension when over PhysX Mesh.

**Comment by lgleim** [comment] 2022-06-23 16:17
potential duplicate of #9867

**Closed** 2022-06-23 16:18 UTC
Labels: needs-triage, priority/critical, WF5, RTE, sig/simulation
