### ISSUE TITLE
Editor crashes when Script Canvas windows is being closed.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#16574] opened 2023-08-18 15:25 UTC
**Describe the bug**
Editor crashes when Script Canvas windows is being closed.

**Assets required**
No assets provided.

**Steps to reproduce**
1. Open Editor, no need to open level
2. Click on 'Tools' and 'Script Canvas'
3. Try to close Script Canvas.
4. Crash

**Expected behavior**
No crash, Script canvas window should be closed.

**Actual behavior**
Crash, reported assertions, after that termination.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/3209244/928470c2-9377-4b7e-8eb5-c02f83fa51cc

Stack traces (from Ubuntu / lldb):
https://gist.github.com/michalpelka/8e70cd923832edcad7a125420a143444

**Found in Branch**
development
Tested on Ubuntu on hash : 
```
a62f43b63c7ee3e92cc0d125a087e08788c60884 (HEAD, origin/development, origin/HEAD, aws/development)
```
Tested on Windows 11
```
57242daf88bed0e22639c297d95f04cdd4ed6873
```

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows/Ubuntu
 - Version Windows 11 / Ubuntu 22.04
 - CPU Intel 13th Gen Core i9-13900K
 - GPU RTX4080
 - Memory 64 Gb

**Additional context**
It is not crashing when Script Canvas is closed by unticking   'Script Canvas'  from 'Tools' in o3de-editor (what is shown in video).

**Comment by lumberyard-employee-dm** [comment] 2023-08-23 16:18
This looks like a potential issue with the ScriptCanvas `LiveLoggingWindowSession` widget being double deleted in the HphaAllocator.cpp line [1996](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Memory/HphaAllocator.cpp#L1996)
```
HPPA_ASSERT(bl->used());
```

**Comment by lsemp3d** [comment] 2023-08-29 21:09
Duplicate of #16449

**Closed by lsemp3d** 2023-08-29 21:09 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical
