### ISSUE TITLE
DPE View: The height of component is not updated correctly in DPE Inspector

### ISSUE THREAD

**Issue by forkercat** [o3de/o3de#14863] opened 2023-02-28 23:05 UTC
**Describe the bug**

Prerequisite: `ed_enableDPE` is on

The height of component is not calculated correctly. Needs to scroll down to view all properties in a component. It happens when you have couple of components in inspector.

**Steps to reproduce**
1. Enable DPE flag
1. Create an empty level
1. Create an entity
1. Add couple of components to the entity

**Expected behavior**

Like we're seeing in RPE Entity Inspector, each component's height should be large enough to show all properties.

**Actual behavior**

<img width=300px src="https://user-images.githubusercontent.com/11157226/222002389-ef7de0a6-661c-4fa9-8a89-de3d42d5f65d.png">

**Screenshots/Video**

See screenshot above

**Found in Branch**

Development

**Desktop/Device**
* Device: PC
* OS: Windows 10
* CPU: AMD Ryzen 5950x
* GPU: NVIDIA RTX 3070
* Memory: 64 GB

**Additional context**

Looks like currently in DPE Inspector we're not calculating the component widget height based on the content.

**Comment by alexmontAmazon** [comment] 2023-05-10 20:20
will be fixed by https://github.com/o3de/o3de/pull/15928

**Comment by LB-ArturZieba** [comment] 2023-07-24 15:03
Issue reoccurred on Development (0eaa719) on multiple components.

**Comment by LB-ArturZieba** [comment] 2023-07-25 09:50
Reopening the issue as it occurs on Development (3210473).

**Comment by LB-ArturZieba** [comment] 2023-07-26 11:49
This occurs on both Windows and Linux, confirmed this on Development (c9db420) build.

Attaching a video showcasing this issue:

https://github.com/o3de/o3de/assets/86952082/f3f87d41-47eb-4c57-996a-8a3e1d13a134

**Comment by alexmontAmazon** [comment] 2023-08-09 20:26
@LB-ArturZieba :
https://github.com/o3de/o3de/pull/16531 changes this behavior such that any Component Editors that are too small will show vertical scrollbars, which isn't ideal, but allows for easy editing for the user. If this issue still occurs in Windows or Linux, we'd like to downgrade this to a minor, since the scrollbars are obvious and easily accessible. We can't repro this in Windows anymore, so if you have specific Windows steps please add them here.

**Comment by LB-ArturZieba** [comment] 2023-08-10 12:20
We have reverified this on Windows and Linux on the Development (9a2b52c) build - it does not occur on Windows, however it still occurs on Linux.

**Comment by alexmontAmazon** [comment] 2023-08-10 23:02
ok great, that's what we're seeing too, thanks!

**Comment by alexmontAmazon** [comment] 2023-09-29 19:09
fixed by https://github.com/o3de/o3de/pull/16813

**Closed by alexmontAmazon** 2023-09-29 19:09 UTC
Labels: platform/linux, feature/editor, kind/bug, sig/content, priority/major
