### ISSUE TITLE
Bug Report: Ubuntu 22.04 - AssetProcessor can't process assets because all AssetBuilders die

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#13803] opened 2022-12-21 18:58 UTC
**Describe the bug**
The AP fails to process assets because all AssetBuilders die immediately.

**Assets required**
N/A

**Steps to reproduce**
Get latest "development" branch and try to compile at least with AutomatedTesting project.

**Expected behavior**
The AP builds all assets

**Actual behavior**
The AP fails as all AssetBuilders fail to start.

The first apparent bug is this error:
```
AssetBuilder: Module: Attempting to load module:/mnt/data/GIT/o3de/build/bin/profile/libSceneData.so
AssetBuilder: Module: Success!
AssetBuilder: Module: Attempting to load module:/mnt/data/GIT/o3de/build/bin/profile/libSceneBuilder.so
AssetBuilder: Module: Success!
AssetBuilder: C: [Trace] = /mnt/data/GIT/o3de/Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h(46): 'static void *QtForPython::InitializeEmbeddedPyside2::LoadModule(const char *)'
AssetBuilder: C: [Type] = Trace::Error
AssetBuilder: E: QtForPython: Unable to load python library libpython3.10.so for Pyside2: libpython3.10.so: cannot open shared object file: No such file or directory
AssetBuilder: Module: Attempting to load module:/mnt/data/GIT/o3de/build/bin/profile/libSceneCore.so
AssetBuilder: Module: Success!
```
And later all AssetBuilders fail to start:
```
BuilderManager: Builder 28AE731F67574EEEAA26E79F88FD959F connected, connId: 1
BuilderManager: Builder started successfully
AssetProcessor: Scanning file system for changes...
FileWatcher: Using 1180 file watch handles.
AssetProcessor: File Change Monitoring started.
AssetProcessor: File system scan done.
AssetProcessor: Received 7327 files from the scanner.  Assessing...
AssetProcessor: Initial Scan complete, checking for missing files...
BuilderManager: Builder F6409D05E0314EE1B233EBE67AA92C8A connected, connId: 2
BuilderManager: Lost connection to builder F6409D05E0314EE1B233EBE67AA92C8A
BuilderManager: Builder 601524CCE7B04340AD106793CEC4A1EF connected, connId: 3
BuilderManager: Lost connection to builder 601524CCE7B04340AD106793CEC4A1EF
BuilderManager: Builder E47A63B37FB94A79B6F4C8BD28D178F5 connected, connId: 4
BuilderManager: Lost connection to builder E47A63B37FB94A79B6F4C8BD28D178F5
BuilderManager: Builder 5BE46A2247824B22AD29397648DCDA67 connected, connId: 5
BuilderManager: Lost connection to builder 5BE46A2247824B22AD29397648DCDA67
BuilderManager: Builder 37D543B2A8CC4BE2AA6B3931D784446B connected, connId: 6
BuilderManager: Lost connection to builder 37D543B2A8CC4BE2AA6B3931D784446B
BuilderManager: Builder B27395F4F7164B42971151E142C91EAB connected, connId: 7

```

**Screenshots/Video**
N/A

**Found in Branch**
`development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
commit dcb7868af653b2d550066533590396f6b29ee577 (HEAD -> development, upstream/development)
Author: Qing Tao <55564570+VickyAtAZ@users.noreply.github.com>
Date:   Wed Dec 21 06:53:44 2022 -0800

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
 - GPU NVIDIA RTX 2080 Super
 - Memory 16GB

**Additional context**

**Comment by junbo75** [comment] 2022-12-22 02:11
The first error is not related and can be fixed by updating the [hardcoded library name](https://github.com/o3de/o3de/blob/development/Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h#L15) defined in the QtForPython gem.

The Asset Builder crashed when processing FBX assets, which caused the lost connection error. I got a call stack of it in debugger as below. After all the FBX assets were skipped, AP processed all the other types of assets without any problem.
![Screenshot from 2022-12-21 18-02-57](https://user-images.githubusercontent.com/68558268/209039244-7e53c03e-ccb3-43fc-a390-078a06abb947.png)

**Comment by junbo75** [comment] 2022-12-29 09:25
This issue is related to the recent rapidjson allocator update (https://github.com/o3de/o3de/pull/13151). The scene processing builder crashed when parsing .assetinfo files since the rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>was destroyed unexpectedly. 

I did the following tests to debug the issue :
- Modify the [existing AzCore test] (https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/Tests/Serialization/Json/JsonSerializationUtilsTests.cpp#L215) to read a json string copied from the failed assetinfo file - The test passed without any problem
- Test the [JSON serialization API](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/Json/JsonUtils.h#L71) using other asset builders (TextureAtlas builder) - The JSON string could be parsed successfully via the exact same JSON serialization API
- Simplify the scene processing gem to remove any logic that requires scene APIs - The builder could read the JSON string after this modification

All the tests above indicate that we may need to change the memory management inside SceneAPI, which will require more investigation. To unblock AR and the Linux platform, I'll will revert the recent rapidjson change and cut another GHI for the SceneAPI updates.

**Comment by junbo75** [comment] 2022-12-29 18:52
Debug into it a little bit more. I tried to run each call manually inside the debug console and notice that when the size of string type JSON value is long, std::memcpy is hit. Then I got the following error:

`no member named 'memcpy' in namespace 'std'`

This kinds of expresses why I could get around this call (it crashed at a later point when copy the entire object) when using a quite small JSON string: std::memcpy is only hit conditionally depending on the string value size. We may miss to include the cstring header somewhere in the code.

**Comment by junbo75** [comment] 2022-12-30 05:02
More information found during debugging:
The crash happens inside rapidjson when copy a string:
```
    //! Initialize this value as copy string with initial data, without calling destructor.
    void SetStringRaw(StringRefType s, Allocator& allocator) {
        Ch* str = 0;
        if (ShortString::Usable(s.length)) {
            data_.f.flags = kShortStringFlag;
            data_.ss.SetLength(s.length);
            str = data_.ss.str;
        } else {
            data_.f.flags = kCopyStringFlag;
            data_.s.length = s.length;
            str = static_cast<Ch *>(allocator.Malloc((s.length + 1) * sizeof(Ch)));
            SetStringPointer(str);
        }
        std::memcpy(str, s, s.length * sizeof(Ch));
        str[s.length] = '\0';
    }
```
When the string length is less than 13, it's considered as ShortString and allocator.Malloc will not be called. In this case, the function can pass without any problem. However, if the string length is longer (e.g. "{5B03C8E6-8CEE-4DA0-A7FA-CD88689DD45B} MeshGroup"), the crash can be caused by either of the two cases:
1) the allocator will fail to allocate more memory
2) std::memcpy fails to copy the string

allocator.Malloc eventually calls AZ::OSAllocator.allocate where I set a breakpoint to check whether it returns nullptr (https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Memory/OSAllocator.cpp#L66). However, the breakpoint was never hit. The debugger doesn't allow me to debug into the SetStringRaw as well.

**Closed** 2023-01-04 00:07 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, priority/blocker

**Comment by junbo75** [comment] 2023-01-04 00:43
The latest rapidjson change is reverted to unblock Linux. @lawsonamzn found out that rapidjson::PoolAllocator::Malloc function is being found inside libassimp.a and being linked in, since assimp appears on the linker line before azcore. The proper fix for this issue is under investigation.
