### ISSUE TITLE
Prefabs spawned via Script Canvas are automatically destroyed after a while

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#8357] opened 2022-03-16 13:15 UTC
**Describe the bug**
Prefabs spawned using the _Spawn_ node in Script Canvas despawn after a while. Please note that the time before the spawned Prefab is destroyed seems to be random, but it never took longer than ~20 seconds on our machines.

Please note that Prefabs spawned in edit-time via the _Instantiate Prefab..._ feature do not despawn at all. 

The issue occurs both on Windows and Linux. 

Please refer to the attached files for more details.

**Steps to reproduce**
1. Open any level. 
2. Create a new entity with a Mesh component and any model assigned to it (so that it can be easily visible in the Viewport).
3. Make a Prefab out of the above entity.
4. Create a Script Canvas graph that spawns the Prefab (refer to the attached files).
5. Assign the Script Canvas graph to another entity.
6. Enter Game Mode and wait ~30 seconds.

**Expected behavior**
Prefabs spawned using Script Canvas do not despawn automatically.

**Actual behavior**
Prefabs spawned using Script Canvas despawn automatically after a while.

**Assets required**
[spawnTest.zip](https://github.com/o3de/o3de/files/8262307/spawnTest.zip) - .scriptcanvas file (had to be compressed to .zip due to Github limitations)

**Screenshots/Video**
![SC_Spawn_Graph](https://user-images.githubusercontent.com/86953108/158596499-00aac111-b548-48c9-9d18-db73d7c14531.png)

https://user-images.githubusercontent.com/86953108/158596525-dc27813e-3346-4fdf-968f-08444c93c527.mp4

**Found in Branch**
Development (b90a8f3)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version 20.04 LTS
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by AMZN-mnaumov** [comment] 2022-04-13 22:13
This happens because SpawnTicket gets cleaned up by Lua after some arbitrary time. When the ticket gets destroyed, SpawnableAPI will despawn anything associated with this ticket. 

The solution is you need to create EntitySpawnTicket variable and cache this ticket.
![image](https://user-images.githubusercontent.com/82239319/163278300-49e10f82-769f-4f82-a94d-2068c8ce6fa5.png)

This can be done in either CreateSpawnTicket or Spawn node:
![image](https://user-images.githubusercontent.com/82239319/163278464-c1d67bdd-5242-4f34-9032-84788d6934d5.png)

It's also a good practice to clear out any EntitySpawnTicket when exiting the game mode, because SpawnableAPI does not despawn things when exiting the game mode:
![image](https://user-images.githubusercontent.com/82239319/163278816-98f4cf9b-bfbe-4cc7-91c8-c3cf73e94820.png)
Clearing the ticket like this will trigger SpawnableAPI to despawn anything associated with it.

**Comment by srikappa-amzn** [comment] 2022-04-18 16:58
Why does Lua clean up the SpawnTicket after a while ? Looks like this is a bug either from Lua or spawnable-integration with Lua. I'm reopening this so that we can fix that behavior where Lua destroys the spawn ticket without any explicit calls from user

**Comment by AMZN-daimini** [comment] 2022-04-26 20:30
Should a SpawnTicket going out of scope cause the spawned prefab instance to be deleted, in general?
Sounds to me like you may want to keep the ticket in some occasions, but in general you should be able to just let it go out of scope without that necessarily despawning the instance.

**Comment by ParasiteSt** [comment] 2022-05-20 01:39
Just wondering if this is still being looked into, the workaround is not very ideal when working with arrays, and storing all the tickets is extra resources wasted that could be used elsewhere.

**Comment by AMZN-mnaumov** [comment] 2022-05-20 20:14
I've discussed it with the team, and we want to intentionally leave ticket lifetime management to the user rather than caching it internally. Since the Spawnable C++ API does not cache tickets itself, and we want to reflect this functionality with Script Canvas as much as possible.

In the situation where you are spawning multiple things, you can create an Array<Ticket> variable, and then cache it like this:
![image](https://user-images.githubusercontent.com/82239319/169603583-250f2d1c-da93-4b10-a55f-a4aea9f48a5e.png)

Also you no longer need to manually clear any tickets when the spawner script is destroyed (referring to my earlier comment above this is no longer needed:
![image](https://user-images.githubusercontent.com/82239319/169603823-e2c40f20-e66e-439a-b9bb-7882a60a372e.png)

In future we will add an error message notifying you if ticket wasn't cached.

**Closed by AMZN-mnaumov** 2022-05-20 20:14 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs

**Comment by rainbj** [comment] 2022-05-20 21:02
Hi @AMZN-mnaumov so from reading over the description. It sounds like the user needs to store the tickets somewhere, which feels like it's putting the burden on the user side to know and deal with this process. I'm unsure of a simple fix but maybe we could review this workflow with a team like Carbonated to get their recommendation? And or Maybe through RTE? @lsemp3d and @yuyihsu for their recommendations.

**Comment by ParasiteSt** [comment] 2022-05-21 20:37
With the use of arrays it is not bad to leave it up to the developer since it does give more freedom for how they want to manage the tickets, but having an error message like @AMZN-mnaumov said at the end is what I feel would be the correct way of going about this so developers know that its not a bug and is intentional.

**Comment by LB-TomaszSerwanski** [comment] 2022-05-23 09:00
Issue accepted as closed.
