### ISSUE TITLE
Project Manager View Logs Button Does Nothing

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#5278] opened 2021-11-03 22:28 UTC
**Describe the bug**
When a project is building in Project Manager, there is a "view logs" link but clicking on it does nothing.

**Steps to reproduce**
1. Open Project Manager
2. Create a new project
3. Under My Projects, find the new project and click the Build Project button
4. A message says "Building Project... (X%) Click to view logs" where "view logs" is a link.
5. Click "view logs"

**Expected behavior**
Something should happen. A window should open to show logs.

**Actual behavior**
Nothing happens. The click is ignored.

**Screenshots/Video**

https://user-images.githubusercontent.com/55155825/140204511-bfb21d10-4f09-4e62-bc4d-818a866548c4.mp4

**Found in Branch**
stabilization/2110

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU GTX 1660 Super
 - Memory 64.0 GB

**Comment by AMZN-alexpete** [comment] 2022-03-04 19:31
@santorac have you been able to repro this issue lately?  I have not been able to repro this issue and there have been numerous changes in this area of the code since this issue was filed. Also, pro-tip on Windows use CMTrace (Configuration Manager Trace Log Tool) as the default editor for `.log` files and it will tail the log for you.

**Comment by santorac** [comment] 2022-03-04 20:35
I haven't tried this recently, it's not a normal part of my workflow. If you can't repro it then I would just close it out.

**Comment by AMZN-alexpete** [comment] 2022-03-07 21:40
Closing as cannot reproduce for now, but this could be a potential area to improve by adding a pop-up in the Project Manager that shows the path to where the log file is so a user can manually navigate to it and open it.

**Closed by AMZN-alexpete** 2022-03-07 21:40 UTC
Labels: kind/bug, sig/content, sig/ui-ux, triage/accepted, status/not-reproducible, feature/project-manager, WF1

**Comment by LB-KacperKapusta** [comment] 2022-03-09 14:33
It has been reverified using Development (34c9f41) that the issue is still active for macOS. Should a separate ticket be created or this one reopened for the tracking purposes?

**Comment by AMZN-alexpete** [comment] 2022-03-09 20:08
@LB-KacperKapusta lets open a separate issue specifically for MacOS please

**Comment by LB-KacperKapusta** [comment] 2022-03-10 13:38
A separate issue for macOS has been logged under https://github.com/o3de/o3de/issues/8228 as requested.
