### ISSUE TITLE
Reparenting entities inside a Prefab cannot be undone without a workaround 

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#5082] opened 2021-10-28 11:51 UTC
**Describe the bug**
Reparenting an entity inside a Prefab cannot be undone with a single _Undo_ action. In order to retrieve the hierarchy from before reparenting, the User has to perform the _Undo_ action multiple times (to get to the state when the Prefab does not exist) and then redo the creation of that Prefab.

Please refer to the attached video for more details.

**Steps to reproduce**
1. Open any level.
2. Create an entity (name it _ParentEntity_).
3. Add a child entity to it (name it _ChildEntity_).
4. Create a Prefab out of the parent entity.
5. Double click the Prefab to enter its Focus Mode.
6. Drag the _ChildEntity_ onto the Prefab entity (so that it is no longer a child of the _ParentEntity_).
7. Press _CTRL + Z_ or select _Edit_ -> _Undo_.

**Expected behavior**
The reparenting action is undone correctly. _ChildEntity_ becomes a child of the _ParentEntity_ again.

**Actual behavior**
Nothing happens.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/139249085-593208f7-e327-47dd-a7e6-56b9c944633e.mp4

**Found in Branch**
Stabilization_2110 (caab78d)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: Nvidia RTX 2060 SUPER
 - Memory: 16GB

**Comment by srikappa-amzn** [comment] 2021-11-02 19:02
PR https://github.com/o3de/o3de/pull/5174 fixed this issue in branch https://github.com/o3de/o3de/tree/stabilization/2110

However, ctrl+z doesn't seem to be triggering the undo action. Edit->undo works fine. And what's interesting is that after edit->undo is clicked at least once, ctrl+z works fine. I've done some debugging and the issue seems to be related to some QActions not being set correctly.

**Comment by srikappa-amzn** [comment] 2021-11-03 13:36
Discussed this with @NicholasVanSickle yesterday and he couldn't repro this. I'm using a mac to remote into a windows machine to test this. I think this is just a weird issue with drag-and-drop not getting correctly associated with the ctrl+z undo keys. Closing this for now. If anyone else can reproduce this, please reopen and provide detailed repro steps.

**Closed as completed by srikappa-amzn** 2021-11-03 13:36 UTC
Labels: feature/editor, kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs, WF2, RTE

**Comment by jckand-amzn** [comment] 2021-11-03 15:24
I also cannot reproduce on stabilization/2110@4e2c28105c38df. CTRL-Z works without issue to reparent the child entity.

**Comment by LB-TomaszSerwanski** [comment] 2021-11-04 08:50
The issue verified as Fixed in Stabilization/2110 (d598a7c) but it is still active in Development(cdf5a05).

**Comment by srikappa-amzn** [comment] 2021-11-04 13:08
The integration from stabilization/2110 to development happens every 2 weeks. Looks like we just didn't missed the cut this time. This should be fixed in development too when the next merge happens in about 2 weeks.
