### ISSUE TITLE
Yellow cube in the center of the entity gizmo is present in each mode, but only functional in the Translate mode

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6580] opened 2021-12-28 11:34 UTC
**Describe the bug**
The entity gizmo has a yellow wiremesh of a cube in the center in each of its available modes - Translate, Rotate, and Scale (in the Scale mode it can be noticed intersecting with the white box in the center). However, it is only functional in the Translate mode, where it allows to snap the entity to the surface that the cursor "points" to. In Rotate and Scale modes it has no functionality.

**Steps to reproduce**
1. Create a new level.
2. Move any entity (e.g. Shader Ball) around using the Translate mode gizmo.
3. While still in the Translate mode hold the left-click on the yellow box wiremesh in the center of the gizmo, and move the mouse.
4. Switch the gizmo mode to Rotate, and attempt to interact with the yellow box wiremesh in the center of the gizmo.
5. Switch the gizmo mode to Scale, and attempt to interact with the yellow box wiremesh in the center of the gizmo.

**Expected behavior**
Interacting with the yellow box wiremesh in each of the modes yields some result, or it is not present in the modes it has no function in.

**Actual behavior**
The yellow box wiremesh has functionality only in the Translate mode of the gizmo.

**Video**

https://user-images.githubusercontent.com/86952082/147560332-ff74b62b-0812-46de-95a4-49614d75096b.mp4

**Found in Branch**
Development (ad38c78)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment] 2023-03-24 22:58
This is by design, closing

**Closed** 2023-03-24 22:59 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/minor, feature/viewport

**Comment by LB-ArturZieba** [comment] 2023-03-27 07:07
Confirming the issue has been closed as by design.
