### ISSUE TITLE
[CRITICAL] Cannot press 'home' key when editing script canvas text without IMGUI activating

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2499] opened 2021-07-27 18:19 UTC
**Describe the bug**
Cannot press the 'home' key when editing a script canvas text field without IMGUI activating, sometimes when pressing home again the entity inspector remains disabled

**To Reproduce**
1. Open a level in the editor 
2. Move the editor camera out of the ground so you can see the ground surface
2. Right click in the Entity Outliner window and select 'Create Entity'

**Expected behavior**
The position of the created entity is on the surface of the ground

**Screenshots**
In this GIF I'm pressing the 'Home' key when editing the text of a comment field, but the same issue occurs in any text field.
![kXZi3sQjNU](https://user-images.githubusercontent.com/26804013/127207028-8be64353-c3a6-4dbc-b719-bc0fb5b43094.gif)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da474357f3d0ae9d9c3e884a397ccdcaec7e9be6 (development)

**Additional context**
n/a

**Comment by lumberyard-employee-dm** [comment] 2021-07-27 18:23
This is a duplicate of #2270

**Closed by lumberyard-employee-dm** 2021-07-27 18:23 UTC
Labels: kind/bug, needs-sig, needs-triage
