### ISSUE TITLE
Default axis of Camera in Viewport can be flipped incorrectly

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#14894] opened 2023-03-02 12:02 UTC
**Describe the bug**
Camera in the Viewport can be flipped incorrectly in relation to its default axis after using the Find In Viewport function on the rotated entity while the Camera is positioned perfectly along the Z axis of the corresponding entity.

This issue occurs both on Windows and Linux.

**Steps to reproduce**
1. Create a default level.
2. Select the Shaderball entity and press Z key.
3. Select the Sun entity and press Z key.
4. Select Shaderball entity once again and press Z key.

**Expected behavior**
The Camera works correctly.

**Actual behavior**
The Camera's default axis is flipped.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/222423209-c063286a-a106-41d6-97c8-089b960724d8.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
ba791dc

**Desktop/Device**
- Device: PC
- OS: Windows 
- Version: 11 21H2
- CPU: I7-11700f
- GPU: Geforce RTX3070 MSI
- Memory: 32GB

**Comment by hultonha** [comment] 2023-03-23 22:35
It looks like this is a duplicate of https://github.com/o3de/o3de/issues/9151.

I will try and have a quick look at what's going on here if I can...

**Comment by hultonha** [comment] 2023-03-31 06:31
This should be fixed by the above PR

**Closed** 2023-03-31 06:32 UTC
Labels: kind/bug, sig/content, status/active, triage/accepted, priority/major, feature/viewport

**Comment by LB-KacperMetelski** [comment] 2023-04-03 10:05
Issue verified as fixed in commit a6ca494 on Stabilization/2305 branch.
