### ISSUE TITLE
Intensity slider in Material Editor does not cover the full range

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#6645] opened 2022-01-04 11:56 UTC
**Describe the bug**
Intensity slider of the Emissive option in Material Editor does not cover full range of possible values. Possbile values are [-10, 20], while slider covers [-6, 16].

**Steps to reproduce**
1. Open Material Editor.
2. Create new/open existing material.
3. Enable Emissive option.
4. Slide the Intensity slider.
5. Observer the extreme values of the slider.

**Expected behavior**
Slider covers all possible values of the option, making it easy to manipulate.

**Actual behavior**
Slider covers a limited range of the possible values.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/148055474-9c46accc-e8e9-413a-b361-8503d694cd70.mp4

![image](https://user-images.githubusercontent.com/86951905/148055515-07618b65-4268-4570-b0bb-9fc8f771a9ca.png)

**Found in Branch**
Development (7581967)

**Desktop/Device:**
 - Device: PC 
 - OS: Windows
 - Version 10
 - CPU Ryzen 3600
 - GPU NVidia RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment] 2022-04-27 03:15
this is a duplicate of https://github.com/o3de/o3de/issues/6652

**Closed by gadams3** 2022-04-27 03:15 UTC
Labels: kind/bug, needs-triage, sig/ui-ux, priority/minor, feature/graphics/tools
