### ISSUE TITLE
[macOS] Building fails due to an Atom_RHI_Vulkan.Private.dylib normal error

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4045] opened 2021-09-10 12:09 UTC
**Describe the bug**
It has been observed that building a macOS build with Cmake will fail upon building 
**libAtom_RHI_Vulkan.Private.dylib normal**

This results in the following error:

```
/Users/lumberpro6/o3de/osx_build/bin/profile/libAtom_RHI_Vulkan.Private.dylib
Undefined symbols for architecture x86_64:
  "AZ::RHI::RHISystemInterface::Get()", referenced from:
      AZ::Vulkan::BufferPoolDescriptor::BufferPoolDescriptor() in unity_0_cxx.o
      AZ::Vulkan::ImagePoolDescriptor::ImagePoolDescriptor() in unity_0_cxx.o
      AZ::AnyTypeInfoConcept<AZ::Vulkan::BufferPoolDescriptor, void>::CreateAny(AZ::SerializeContext*) in unity_0_cxx.o
      AZ::AnyTypeInfoConcept<AZ::Vulkan::ImagePoolDescriptor, void>::CreateAny(AZ::SerializeContext*) in unity_0_cxx.o
  "AZ::RHI::Object::SetNameInternal(AZStd::basic_string_view<char, AZStd::char_traits<char> > const&)", referenced from:
      vtable for AZ::Vulkan::ShaderDescriptor in unity_0_cxx.o
  "typeinfo for AZ::RHI::Object", referenced from:
      typeinfo for AZ::Vulkan::ShaderDescriptor in unity_0_cxx.o
  "vtable for AZ::RHI::Object", referenced from:
      AZ::Serialize::InstanceFactory<AZ::Vulkan::ShaderDescriptor, true, false>::Create(char const*) in unity_0_cxx.o
      AZ::AnyTypeInfoConcept<AZ::Vulkan::ShaderDescriptor, void>::NonCopyableAnyHandler(AZ::SerializeContext*)::'lambda'(AZStd::any::Action, AZStd::any*, AZStd::any const*)::operator()(AZStd::any::Action, AZStd::any*, AZStd::any const*) const in unity_0_cxx.o
      AZ::Vulkan::ShaderDescriptor::~ShaderDescriptor() in unity_0_cxx.o
      AZStd::any::any<AZ::Vulkan::ShaderDescriptor>(AZStd::any::type_info const&, AZStd::in_place_type_t<AZ::Vulkan::ShaderDescriptor>) in unity_0_cxx.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The issue was reproduced on two machines with macOS versions **11.2.3** and **11.3.1**
with and without the _AutomatedTesting_ project specified during configuration.

For further information please refer to the attached build logs.

[Failing Cmake build log.txt](https://github.com/o3de/o3de/files/7143547/Failing.Cmake.build.log.txt)
[Failing Cmake build log architectures=x86_64.txt](https://github.com/o3de/o3de/files/7143548/Failing.Cmake.build.log.architectures.x86_64.txt)

**To Reproduce**
1. Use GitHub to obtain the latest O3DE build for macOS.
2. Create a new or move your preexisting 3rdParty folder into the O3DE folder.
3. Obtain Cmake.app and move it to the created _3rdParty/CMake_ directory (create
the CMake folder if necessary).
4. In the O3DE directory right-click on python folder and select **New Terminal at Folder**.
5. Run the command:
`export PATH=$PATH:/Users//o3de/3rdParty/CMake/CMake.app/Contents/bin`
6. Run the command:
`./get_python.sh`
7. Create a folder named **_osx_build_** in the O3DE folder.
8. Open a new terminal in the created **_osx_build_** folder and set the following temporary environment variables:
    ```
    export PATH=$PATH:/Users//o3de/3rdParty/CMake/CMake.app/Contents/bin
    export LY_3RDPARTY_PATH=/Users//o3de/3rdParty
    export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
    ```
9. Configure and generate an Xcode solution:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=1`
10. Build with Cmake by using:
`cmake -E time cmake --build . --target ALL_BUILD --config profile ` command.

**Expected behavior**
Building process successfully finishes.

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: MacOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Comment by lumberyard-employee-dm** [comment] 2021-09-10 14:51
Assigning to @bosnichd as the failure is caused by the commit https://github.com/o3de/o3de/commit/9976ee2b8ef6fca6f95a80257e3c54fe38cccf48#

**Comment by bosnichd** [comment] 2021-09-10 16:05
PR for a fix posted: https://github.com/o3de/o3de/pull/4053

**Comment by bosnichd** [comment] 2021-09-10 19:13
https://github.com/o3de/o3de/pull/4053 merged into o3de:development

**Closed by bosnichd** 2021-09-10 19:13 UTC
Labels: kind/bug, needs-triage, sig/build, sig/platform, sig/graphics-audio, priority/blocker

**Comment by LB-MateuszSzweda** [comment] 2021-11-15 13:06
The issue was verified as fixed on both Development and Stabilization/2110 branch and no longer occurs for over 2 months.
