### ISSUE TITLE
editor_entity_utils.py and prefab_utils.py have a circular import issue

### ISSUE THREAD

**Issue by smurly** [o3de/o3de#10121] opened 2022-06-14 18:51 UTC
**Describe the bug**
in https://github.com/o3de/o3de/commit/f1479668cb59b7721c36168b526290e493f42917 a circular import was introduced into editor_entity_utils.py in that the `import editor_python_test_tools.prefab_utils as PrefabUtils` was placed at the bottom of the file because prefab_utils itself imports EditorEntity from editor_entity_utils. This is a circular import because the import as each is fighting to load before the other.
Imports do not belong at the bottom of a python file like this. Also the import is aliasing as PrefabUtils which is not a proper pythonic name for non-class. the import is also too broad in that it imports all of prefab_utils when only actually using wait_for_propagation()

**Assets required**
https://github.com/o3de/o3de/blob/1ec4916bfcb1092c8c234da6acd4a1cc396d03f3/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
https://github.com/o3de/o3de/blob/1ec4916bfcb1092c8c234da6acd4a1cc396d03f3/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/prefab_utils.py

**Steps to reproduce**
1. move the line 818 `import editor_python_test_tools.prefab_utils as PrefabUtils` to the top of the file where it should exist
2. execute tests

**Expected behavior**
Tests pass

**Actual behavior**
tests fail because prefab_utils fails to import EditorEntity since it doesn't exist yet due to circular references

**Additional context**
prefab functions for wait_for_propagation() and other status helpers should be defined in a 3rd module that both mentioned modules can import. this is the optimal solution since there would be no circular import.

alternatively if the prefab_utils moves the `from editor_python_test_tools.editor_entity_utils import EditorEntity` to within each of the 3 classes that use it rather than globally for the module, editor_entity_utils can selectively import just the wait_for_propoation without tripping the circular import (it would still be there as each module is importing from the other but might be better managed.
editor_entity_utils can then have the specific `from editor_python_test_tools.prefab_utils import wait_for_propagation`

**Comment by lmbr-pip** [comment] 2022-06-15 15:24
Assigned to sig/content as most likely owners of EditorPythonTests (not called in codeowners), please assign to sig/testing if this actually framework related.

**Comment by monroegm** [comment] 2022-06-15 15:51
@srikappa-amzn Looks like this was caused by your commit. Can you take a look?

**Comment by srikappa-amzn** [comment] 2022-06-16 17:01
Thanks for pointing out the coding standards around imports. I'll put a follow up PR to fix this.

**Closed** 2022-07-18 18:56 UTC
Labels: feature/editor, kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs
