### ISSUE TITLE
Bug Report: New Sky Atmosphere Black out under world Z 0

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#11279] opened 2022-08-14 07:20 UTC
**Describe the bug**
If you go below 0 on the world Z coordinate you get a visual bug where the new Sky Atmosphere disappears.

**Steps to reproduce**
1. Create an entity and add the Sky Atmosphere component to it
2. Go into the viewport and fly down until you surpass into the negative Z value.
3. See the visual error with the Sky Atmosphere component.

**Expected behavior**
When going into negative values for your world z position the sky should still be visible.

**Actual behavior**
The Sky becomes black and seems to no longer render correctly when going below 0 for the world z coordinate.

**Screenshots/Video**
Look at the debug Cam Position Z value after you pass to the negative values.
![image](https://user-images.githubusercontent.com/100494538/184526669-4db3be35-c1f5-4e3f-bc20-d903802b8d2b.png)
![image](https://user-images.githubusercontent.com/100494538/184526673-6ee0a4ce-2258-48a8-ad4d-f97ac84c4159.png)

**Found in Branch**
Development [cf79675]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11

**Comment by AMZN-alexpete** [comment] 2022-08-15 17:00
Thanks @ParasiteSt!  This is currently by design to avoid the cost of rendering the atmosphere when you are "inside" the planet, but I agree we should 
- make drawing atmosphere below the surface optional
- allow users to draw the atmosphere below the horizon (instead of transparent)
- let the user set the color of the surface below the horizon

**Comment by ParasiteSt** [comment] 2022-08-15 19:23
Thanks for the response @AMZN-alexpete Should this be closed as it was as intended and is not really a bug? I know I got the suggestion with local space and bringing it down to have a lot of the issues gone for me.

**Comment by AMZN-alexpete** [comment] 2023-03-14 15:25
Fixed by https://github.com/o3de/o3de/pull/13815

**Closed by AMZN-alexpete** 2023-03-14 15:25 UTC
Labels: kind/bug, sig/graphics-audio
