### ISSUE TITLE
Some .tga files process incorrectly

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#10085] opened 2022-06-13 15:23 UTC
**Describe the bug**
Some .tga image files seem to not process correctly in the image builder, these can be opened in photoshop but due to failing processing could not be loaded in material. Material was default generated by FBX, so the material failed as well.  

The user retried the image a s a.tiff, but this can into o3de inverted.

User had to switch the image to .png to work with it correctly.

**Assets required**
To Do: get the image files from Carbonated.

**Steps to reproduce**
1. Use the basecoolor.tga in a material node in maya
2. export the FBX, the scene builder will generate default materials, once of them will try to load the basecolor map.
3. The .tga image will fail to process
4. The default .azmaterial trying to load the texture will fail
5. If User re-saves the image as a .tiff it may come inverted (upside down)
6. If the User re-saves as .png the texture is fine

**Expected behavior**
Various .tga files are processed correctly.
Various .tiff files are processed correctly.

**Actual behavior**
Some tga files will not process.
Some .tiff files are processed incorrectly.

**Screenshots/Video**
To Do: add 

**Found in Branch**
Nightly installer May 23, 2022

**Desktop/Device (please complete the following information):**
 - unknown PC

**Comment by VickyAtAZ** [comment] 2022-08-09 01:03
The issue is fixed in PR: https://github.com/o3de/o3de/pull/11161

**Closed** 2022-08-12 16:38 UTC
Labels: feature/graphics, kind/bug, sig/graphics-audio, priority/major, WF5, RTE
