### ISSUE TITLE
Full screen game preview should support multiple viewports

### ISSUE THREAD

**Issue by yuriy0** [o3de/o3de#1363] opened 2021-06-16 17:00 UTC
This is a follow up to the feature introduced here: https://github.com/aws-lumberyard/o3de/pull/1306

The full screen preview should work for every viewport layout. Right now it only works for the single viewport layout (the most common layout) and otherwise will do a non-full screen preview.

**Comment by amzn-leenguy** [comment] 2022-05-27 16:46
From @o3de/sig-ui-ux : UX suggests that we should disable the multiple viewports feature and reassign it until we can support the full use case. During our test we observed it was unstable and is not working as intended.

**Closed by amzn-leenguy** 2022-05-27 16:46 UTC
Labels: kind/bug, sig/content, sig/ui-ux, triage/accepted, priority/critical, feature/viewport
