### ISSUE TITLE
Script Canvas: Editor crashes when opening graph

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#8014] opened 2022-03-02 09:17 UTC
**Describe the bug**
Script Canvas editor crashes when opening the following graph: [Here](https://github.com/o3de/o3de/blob/development/Gems/MotionMatching/Assets/ControllableCharacter/CharacterController.scriptcanvas)

**Steps to reproduce**
1. Open the Script Canvas Editor
2. File Menu -> Open
3. Select the following script canvas graph: [Here](https://github.com/o3de/o3de/blob/development/Gems/MotionMatching/Assets/ControllableCharacter/CharacterController.scriptcanvas)
4. Press Open

**Expected behavior**
Graph loads and shows up in the editor

**Actual behavior**
Crash

**Assets required**
https://github.com/o3de/o3de/blob/development/Gems/MotionMatching/Assets/ControllableCharacter/CharacterController.scriptcanvas

**Found in Branch**
development

**Additional context**
```
 	vcruntime140.dll!00007ffec7801416()	Unknown
>	[Inline Frame] ScriptCanvas.Editor.dll!AZ::IO::ByteContainerStream<AZStd::vector<char,AZStd::allocator>>::Write(unsigned __int64) Line 196	C++
 	ScriptCanvas.Editor.dll!AZ::IO::ByteContainerStream<AZStd::vector<char,AZStd::allocator>>::Write(unsigned __int64 bytes, const void * iBuffer) Line 163	C++
 	ScriptCanvas.Editor.dll!AZ::ObjectStreamInternal::ObjectStreamImpl::WriteElement(const void * ptr, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1712	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass::__l2::<lambda_1>::operator()(const void *) Line 1516	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::INVOKE(AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass::__l2::<lambda_1> &) Line 208	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::invoke(AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass::__l2::<lambda_1> &) Line 55	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<bool>::call(AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass::__l2::<lambda_1> &) Line 31	C++
 	ScriptCanvas.Editor.dll!AZStd::Internal::function_util::get_invoker<bool __cdecl(void *,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, void * && <args_0>, const AZ::SerializeContext::ClassData * && <args_1>, const AZ::SerializeContext::ClassElement * && <args_2>) Line 171	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *>::operator()(void * &&) Line 603	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)>::operator()(void * <args_0>, const AZ::SerializeContext::ClassData * <args_1>, const AZ::SerializeContext::ClassElement * <args_2>) Line 683	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1907	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1>::operator()(void *) Line 2948	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::INVOKE(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 208	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::invoke(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 55	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<bool>::call(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 31	C++
 	ScriptCanvas.Editor.dll!AZStd::Internal::function_util::get_invoker<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::SerializeContext::EnumerateInstanceCallContext::EnumerateInstanceCallContext'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, void * && <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * && <args_2>, const AZ::SerializeContext::ClassElement * && <args_3>) Line 172	C++
 	[Inline Frame] GraphCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *>::operator()(void * &&) Line 603	C++
 	GraphCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)>::operator()(void * <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * <args_2>, const AZ::SerializeContext::ClassElement * <args_3>) Line 684	C++
 	GraphCanvas.Editor.dll!AZ::Internal::AZStdPairContainer<AZ::Uuid,GraphCanvas::ComponentSaveData *>::EnumElements(void * instance, const AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)> & cb) Line 945	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1912	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1>::operator()(void *) Line 2948	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::INVOKE(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 208	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::invoke(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 55	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<bool>::call(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 31	C++
 	ScriptCanvas.Editor.dll!AZStd::Internal::function_util::get_invoker<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::SerializeContext::EnumerateInstanceCallContext::EnumerateInstanceCallContext'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, void * && <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * && <args_2>, const AZ::SerializeContext::ClassElement * && <args_3>) Line 172	C++
 	[Inline Frame] GraphCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *>::operator()(void * &&) Line 603	C++
 	[Inline Frame] GraphCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)>::operator()(void * <args_0>, const AZ::Uuid & <args_2>, const AZ::SerializeContext::ClassData * <args_3>, const AZ::SerializeContext::ClassElement *) Line 683	C++
 	GraphCanvas.Editor.dll!AZ::Internal::AZStdAssociativeContainer<AZStd::unordered_map<AZ::Uuid,GraphCanvas::ComponentSaveData *,AZStd::hash<AZ::Uuid>,AZStd::equal_to<AZ::Uuid>,AZStd::allocator>>::EnumElements(void * instance, const AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)> & cb) Line 696	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1912	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1923	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1>::operator()(void *) Line 2948	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::INVOKE(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 208	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::invoke(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 55	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<bool>::call(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 31	C++
 	ScriptCanvas.Editor.dll!AZStd::Internal::function_util::get_invoker<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::SerializeContext::EnumerateInstanceCallContext::EnumerateInstanceCallContext'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, void * && <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * && <args_2>, const AZ::SerializeContext::ClassElement * && <args_3>) Line 172	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *>::operator()(void * &&) Line 603	C++
 	ScriptCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)>::operator()(void * <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * <args_2>, const AZ::SerializeContext::ClassElement * <args_3>) Line 684	C++
 	ScriptCanvas.Editor.dll!AZ::Internal::AZStdPairContainer<AZ::EntityId,GraphCanvas::EntitySaveDataContainer *>::EnumElements(void * instance, const AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)> & cb) Line 949	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1912	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1>::operator()(void *) Line 2948	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::INVOKE(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 208	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::invoke(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 55	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<bool>::call(AZ::SerializeContext::EnumerateInstanceCallContext::{ctor}::__l2::<lambda_1> &) Line 31	C++
 	ScriptCanvas.Editor.dll!AZStd::Internal::function_util::get_invoker<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::SerializeContext::EnumerateInstanceCallContext::EnumerateInstanceCallContext'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, void * && <args_0>, const AZ::Uuid & <args_1>, const AZ::SerializeContext::ClassData * && <args_2>, const AZ::SerializeContext::ClassElement * && <args_3>) Line 172	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *>::operator()(void * &&) Line 603	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)>::operator()(void * <args_0>, const AZ::Uuid & <args_2>, const AZ::SerializeContext::ClassData * <args_3>, const AZ::SerializeContext::ClassElement *) Line 683	C++
 	ScriptCanvas.Editor.dll!AZ::Internal::AZStdAssociativeContainer<AZStd::unordered_map<AZ::EntityId,GraphCanvas::EntitySaveDataContainer *,AZStd::hash<AZ::EntityId>,AZStd::equal_to<AZ::EntityId>,AZStd::allocator>>::EnumElements(void * instance, const AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::SerializeContext::ClassData const *,AZ::SerializeContext::ClassElement const *)> & cb) Line 696	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1912	C++
 	ScriptCanvas.Editor.dll!AZ::SerializeContext::EnumerateInstance(AZ::SerializeContext::EnumerateInstanceCallContext * callContext, void * ptr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData, const AZ::SerializeContext::ClassElement * classElement) Line 1923	C++
 	ScriptCanvas.Editor.dll!AZ::ObjectStreamInternal::ObjectStreamImpl::WriteClass(const void * classPtr, const AZ::Uuid & classId, const AZ::SerializeContext::ClassData * classData) Line 1552	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::ObjectStream::WriteClass(const ScriptCanvasEditor::UndoData *) Line 249	C++
 	ScriptCanvas.Editor.dll!ScriptCanvasEditor::UndoCache::UpdateCache(AZ::EntityId scriptCanvasId) Line 114	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!ScriptCanvasEditor::MainWindow::UpdateUndoCache(ScriptCanvasEditor::SourceHandle __formal) Line 1551	C++
 	ScriptCanvas.Editor.dll!ScriptCanvasEditor::MainWindow::SetActiveAsset(const ScriptCanvasEditor::SourceHandle & fileAssetId) Line 2496	C++
 	ScriptCanvas.Editor.dll!ScriptCanvasEditor::MainWindow::OpenFile(const char * fullPath) Line 1377	C++
 	ScriptCanvas.Editor.dll!ScriptCanvasEditor::MainWindow::OpenNextFile() Line 4156	C++
 	ScriptCanvas.Editor.dll!ScriptCanvasEditor::MainWindow::OnFileOpen() Line 1932	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4058	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 55	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]	

```

**Comment by michleza** [comment] 2022-03-02 17:56
Duplicate of https://github.com/o3de/o3de/issues/7991

**Comment by onecent1101** [comment] 2022-03-03 18:21
Fix has been merged https://github.com/o3de/o3de/pull/8032

**Closed by onecent1101** 2022-03-03 18:21 UTC
Labels: feature/scripting, kind/bug, sig/content, status/duplicate, triage/accepted, priority/critical
