### ISSUE TITLE
Artifacts when using diffuse exr with certain models.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#1981] opened 2021-07-08 17:42 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Global Skylight IBL Compenent'
2. Click on 'Diffuse Texture and select ChampagneCatle_exr'
3. Slide the exposure slider to see more artifacts become visible.

**Expected behavior**
When you set this exr with others, this is just an example some meshes start to get artifacts in them when the exposure is above a 0.0.
**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel i5-8400]
 - GPU [Nvidia GTX 1080ti]
 - Memory [16GB]

**Additional context**
You may need certain models to get this to happen, I am not positive it has happened on my actor model, and drone_start model.

**Comment by superkitcath** [comment] 2021-09-22 16:49
@HogJonny-AMZN , does this one still need more information? Thanks!

**Comment by superkitcath** [comment] 2021-11-10 18:22
@HogJonny-AMZN / @WashedUpStudio , could you verify if this one is fixed? Thanks!

**Comment by HogJonny-AMZN** [comment] 2022-03-17 15:00
@WashedUpStudio please make sure you are using this correctly?: https://github.com/o3de/o3de/wiki/%5BHow-To%5D-Work-with-Skybox-and-Skylight-Configurations

As written, I don't think this is a bug per-say but a probably hard to understand and incorrect usage.

Also need screenshots at least, but a short video clip would be best (so we can see what you are doing)

You can use any .exr file (examples: https://polyhaven.com/hdris) , but these have to be processed correctly by the image builder to generate the runtime compatible cubemaps.

Very high contrast IBLs can be improved by taking them into an image editor and making adjustments, pretty much that type of adjustment is described here: https://babylonjs.medium.com/using-high-contrast-image-based-lighting-in-babylon-js-627ac721f20

And if you have a IBL with a very bright Sun light, and you want to use this along with the Directional light w/ Shadows ... you need to versions of the IBL image, 1) with the bright sun to be used for _Skybox_, 2) one where the Sun is painted out to be used as the Global SkyLight (IBL) ... then you add the Directional Light and tune it's intensity to replace the lighting energy you removed from the IBL used as the skylight.  Then you will have the correct visual skybox and the correct overall light energy (along with shadows.)

Also processing of cubemaps for lighting have their limitations ... IBLs with very bright areas, can result in some speckled visual anomalies in sharp reflections, and this is because to process the mip map chan for specular lighting and reflections, there is a cone of important sampling and the N# of samples results are then filtered (naively people think of this as blurring the mip chain but there is more going on.)

Any time I can result in pixelated/splotchy artifacts, you can improve the visual results by manually altering the IBL source image (as described above).  I can not reproduce what you described, so I am closing this issue. Feel free to add more information, attach the IBL you were using, etc. and re-open this ticket.

**Closed by HogJonny-AMZN** 2022-03-17 15:00 UTC
Labels: kind/bug, sig/graphics-audio, triage/needs-information, priority/major
