### ISSUE TITLE
Fbx Setting crashes

### ISSUE THREAD

**Issue by lihongjun25** [o3de/o3de#9475] opened 2022-05-11 08:54 UTC
**Describe the bug**
In the Fbx Setting window, a user clicks Add another mesh on the mesh page. In the new mesh group, selects some meshes from the Select meshes drop-down list box and clicks Update. As a result, the system crashes easily.

**Steps to reproduce**
1. Open Level and double-click the model in the asset browser. The Fbx Setting(PREVIEW) window is displayed.
2. Click Add another mesh and click the icon on the right of Select meshes in the new mesh group.
3. In the Select nodes dialog box that is displayed, click UnSelect all, select some meshes, and click Select.
4. Click Update.
5. Repeat steps 2, 3, and 4 for multiple times.

**Expected behavior**
Crash does not occur.

**Actual behavior**
Crash

Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
Working Branch: Main branch https://github.com/o3de/o3de/commit/e7f787572e805c413115265e5873fb2425e2f41b

**Comment by AMZN-stankowi** [comment] 2022-06-07 18:06
Is there a specific FBX file you're seeing this with? I'm trying to reproduce this right now, I'm not getting any crashes trying to follow these steps with multiple different FBX files.

**Comment by lmbr-pip** [comment] 2022-06-14 21:56
@lihongjun25 - Can we get a sample FBX asset that shows this behaviour and/or logs that show the crash?

**Comment by lmbr-pip** [comment] 2022-07-19 18:11
@lihongjun25 - If you can provide FBX content that crashes system, repro steps or logs that may help fixing this issue, please reopen. For now marking as cannot reproduce and closing.

**Closed by lmbr-pip** 2022-07-19 18:11 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, triage/accepted, priority/critical
