### ISSUE TITLE
Nightly Build: Several builds failed with ModuleNotFoundError: No module named 'jinja2'

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14000] opened 2023-01-11 16:57 UTC
**Describe the bug**
Several builds failed with ModuleNotFoundError: No module named 'jinja2'.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/221/pipeline

**Attachments**
[log(1).txt](https://github.com/o3de/o3de/files/10394417/log.1.txt)

**Additional context**
This appears to affect all jobs.

**Comment by amzn-changml** [comment] 2023-01-11 18:14
Being addressed by https://github.com/o3de/o3de/pull/14004

**Comment by robhaco** [comment] 2023-01-11 18:20
Looks like this might be related/the same issue: https://github.com/o3de/o3de/issues/13992

**Comment by jackalbe** [comment] 2023-01-11 19:08
https://github.com/o3de/o3de/pull/14004

**Comment by moraaar** [comment] 2023-01-12 09:44
Today's nightly build confirmed this issue is not happening anymore.

**Closed by moraaar** 2023-01-12 09:44 UTC
Labels: kind/bug, needs-triage, kind/automation, kind/nightlybuildfailure
