### ISSUE TITLE
Feature Request: Upgrade to AssImp to 5.2.5 from 5.1.6

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#12091] opened 2022-09-20 20:51 UTC
**Is your feature request related to a problem? Please describe.**
AssImp just released a large collection of bug fixes as part of their 5.2.5 release: https://github.com/assimp/assimp/releases/tag/v5.2.5

**Describe the solution you'd like**
* Asses the stability of 5.2.5
* Update to take advantage of all the goodness

**Describe alternatives you've considered**
* Stay on old 5.1.6 version: https://github.com/o3de/o3de/blob/development/cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake#L23

**Additional context**

**Comment by lgleim** [comment] 2022-10-06 16:22
@amzn-rhhong If you can find the time, your feedback on this topic would be much appreciated. Thanks!

**Comment by amzn-rhhong** [comment] 2022-10-10 17:20
I don't think upgrade to 5.2.5 will address any character importing issue caused by https://github.com/assimp/assimp/issues/4015. We will likely to do another update once that addressed in a later version.

**Comment by greerdv** [comment] 2022-10-13 16:19
Discussed in sig-simulation triage. We are waiting for the one particular issue mentioned above to be resolved, which has not happened yet. Until that happens, updating is not urgent from our perspective.

**Comment by lgleim** [comment] 2023-07-21 08:59
Already resolved in https://github.com/o3de/o3de/issues/13734

**Closed by lgleim** 2023-07-21 08:59 UTC
Labels: needs-triage, sig/content
