### ISSUE TITLE
Prefab patch is trying to delete an already deleted prefab instance

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#3623] opened 2021-08-26 20:57 UTC
**Describe the bug**
While calling delete prefab api in python script and run the script in editor, we can see the following error:
`[Warning] (Prefab Serialization) - The "remove" operation failed to remove member 'Instance_[478843592681]' from object at path '/Instances/Instance_[478843592681]'.
    Reason: The operation has halted during a merge operation for '/0' because a field or element has an invalid value.`
`[Error] (Prefab) - Some of the patches were not successfully applied.`
We don't think it should break any features though. Still, it would be better to fix the bug in the prefab patch creation process to get rid of the error message.

It looks like the error message shown when deleting an instantiated prefab instance, not created one.

**To Reproduce**
[sample_test.txt](https://github.com/o3de/o3de/files/7062664/sample_test.txt)
1. Change this file to .py file. Use this file as the test python script.
2. Add this script to /Editor/Scripts .
3. Open editor.
4. Go to Tools->Other->Python Script
5. Find the script and execute it.
6. You can see the error message in console.

**Expected behavior**
No error message shown during deletion of prefab.

**Screenshots**
![Screenshot 2021-08-26 135202](https://user-images.githubusercontent.com/82238204/131034826-8ee68e7d-1dcc-4c32-a54a-4fd4454b8154.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by monroegm** [comment] 2022-03-01 01:44
Duplicate of #2921

**Closed by monroegm** 2022-03-01 01:44 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs
