### ISSUE TITLE
Unable to Open Script Canvas

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#9220] opened 2022-04-27 16:17 UTC
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

**Steps to reproduce**
1. Clone and build MultiplayerSample development branch https://github.com/o3de/o3de-multiplayersample
2. Notice AP fails to build SpawnIfAuthority.scriptcanvas
3. Open Editor and open SpawnIfAuthority.scriptcanvas

**Expected behavior**
Script canvas opens 

**Actual behavior**
Script Canvas errors and doesn't open the graph

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32776221/165564561-9161c3cc-6074-425e-b63d-f151bf93de2d.png)

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: Windows and Linux

**Comment by srikappa-amzn** [comment] 2022-05-12 20:41
This PR will provide a workaround:  https://github.com/o3de/o3de/pull/9492

**Comment by srikappa-amzn** [comment] 2022-05-12 20:43
Closing this as a dupe of https://github.com/o3de/o3de/issues/8994 . Please reopen if the above PR doesn't fix the issue for you

**Closed by srikappa-amzn** 2022-05-12 20:43 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
