### ISSUE TITLE
Linux: Editor icon on Ubuntu Toolbar persists after closing

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#10754] opened 2022-07-20 08:45 UTC
**Describe the bug**

Since the initial release on Linux, launching and closing the Editor leaves the icon on Ubuntu task bar. Re-running the Editor multiple times pollutes the Ubuntu task bar (toolbar) and makes it harder to access apps (see the attached screenshot).

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Build your project with the Editor target
2. Launch the Editor from bash console (e.g. `build/linux/bin/profile/Editor`)
3. Load a level (this step is necessary for the bug to occur. Closing the Editor without loading a level behaves OK).
4. Close the Editor.

**Expected behavior**
The O3DE icon disappears from the Ubuntu toolbar as we close the Editor.

**Actual behavior**
The O3DE icon remains after the Editor is closed. Re-running multiple times causes many icons to pollute the toolbar.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/16702721/179936310-dcc7ed0d-eac9-4dea-aa76-4821082d5903.png)

**Found in Branch**
development - 403ff183dd8ab
The bug seems to be there since the initial release.
This bug occurs on multiple different devices (listing one as an example).

**Desktop/Device (please complete the following information):**
 - Device: Lenovo Legion laptop
 - OS: Ubuntu
 - Version: 20.04
 - CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
 - GPU: NVidia RTX 2070 Super 8GB
 - Memory: 16GB

**Comment by monroegm** [comment] 2022-07-20 15:54
SIG-Content would like @o3de/sig-platform to take a look at this one first

**Comment by AMZN-daimini** [comment] 2022-07-28 00:15
Followed the steps on latest development on an EC2 instance running Ubuntu 20.04.4 LTS and could not repro even after multiple attempts (without loading a level, loading an existing level and closing with unsaved changes, creating a new level and saving...). The Editor was started both from the Project Manager and directly from bash.

More information on the environment may be necessary. It could also be possible that the Editor crashes on shutdown for the user, causing undefined behavior. If possible, please attach the log that is left in the bash after closing the Editor. Also, does the bash become responsive again after the Editor is closed, or does it hang there?

**Comment by adamdbrw** [comment] 2022-07-28 18:09
@spham-amzn I remember you mentioned that there can be a difference when running with an EC2 instance. Could you chip in?

**Comment by spham-amzn** [comment] 2022-07-28 18:17
I have seen this issue occur on my physical linux box, usually when this don't get closed properly. The icon will not clear itself unless you reboot or re-log into ubuntu

**Comment by adamdbrw** [comment] 2022-08-04 15:33
Just to clarify, the Editor does not crash on shutdown, and this also shows up with an empty project.

**Comment by adamdbrw** [comment] 2022-09-08 14:56
@spham-amzn @AMZN-daimini any progress on this issue?

**Comment by AMZN-daimini** [comment] 2022-09-09 19:39
Not really, no. I was not able to reproduce in the EC2 instance. I would have to access a proper Linux machine with a repro to get more information to understand the issue.

**Comment by adamdbrw** [comment] 2022-09-12 12:08
The issue is still there as for #358c6b02bb2b071 (stabilization/2210) branch. It is likely the Editor window itself that does not close properly (see image):
![image](https://user-images.githubusercontent.com/16702721/189649341-61e4b8d1-f9d5-4f5d-9cae-81b93c3f8033.png)

**Comment by spham-amzn** [comment] 2022-09-12 21:37
Unfortunately, I am also unable to reproduce this issue. Here are the scenarios that I've checked so far:

1. ROSConDemo on Ubuntu 20.04
2. ROSConDemo on Ubuntu 22.04
3. o3de-demo-project on Ubuntu 20.04 (this is crashing after loading the level, but even after the crash the icon is cleaned up)

I last saw this issue many months ago but have not seen it in a while. The next it happens can you attach what the Editor.log is reporting?

**Comment by adamdbrw** [comment] 2022-09-15 15:54
On my machine and env (as in the description) it is happening every time:
[Editor.log](https://github.com/o3de/o3de/files/9576877/Editor.log)

**Comment by spham-amzn** [comment] 2024-04-17 15:17
This issue hasn't been reported a over a year and a half, closing as no longer reproducable

**Closed** 2024-04-17 15:16 UTC
Labels: feature/editor, kind/bug, sig/content, sig/platform, triage/accepted, priority/minor
