### ISSUE TITLE
Add "triage-complete" label

### ISSUE THREAD

**Issue by drakeredwind01** [o3de/o3de#15877] opened 2023-05-04 19:36 UTC
**Is your feature request related to a problem? Please describe.**
> hard to tell when a triage issue still needs work.

**Describe the solution you'd like**
> would be nice is you could quickly first see a label declaring an issue is a non-issue anymore

**Describe alternatives you've considered**
renaming issues might also help. 
alternative names:
> complete
> fix
> done
> etc.

**Additional context**
> NA

**Comment by lgleim** [comment] 2023-05-06 10:53
Could you elaborate on what difference between a closed issue and an issue with the label `triage-complete` would be? In case you are thinking about issues that track several subtasks, using [task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) may be a suitable approach to track if further work is needed before an issue can be closed.

**Comment by lmbr-pip** [comment] 2023-05-08 17:41
We have a general triage guide here: https://github.com/o3de/community/blob/main/sigs/docs/sig-issues-triage-guide.md

* The label `triage/accepted` is designed to indicate triage has been completed.

**Comment by drakeredwind01** [comment] 2023-05-10 22:34
triage/accepted
It sounds like it could mean this is a valid triage subject or that the
proper information has been provided to complete triage.
It might confuse people who are new to triage (such as myself).
I know that for myself, not sure for anyone else. I look at the tags rather
than the issue when doing triage and bring everything up in another tab.

**Comment by lgleim** [comment] 2023-05-11 16:06
Maybe you have a suggestion on improving the triage guide documentation? I currently do not see sufficient justification to introduce an additional label

**Comment by AMZN-Gene** [comment] 2023-05-18 17:38
Echo'ing @lmbr-pip [triage/accepted](https://github.com/o3de/o3de/labels/triage%2Faccepted) works to tell everyone the sig has accepted an issue. For example, if there's a multiplayer issue the networking sig would add the triage-accept and sig-networking label during their triage meeting.

**Comment by lgleim** [comment] 2023-05-25 16:06
@drakeredwind01 Do you have further comments on this topic? Otherwise, this issue is unlikely to be accepted based on the existing triage process.

**Comment by drakeredwind01** [comment] 2023-05-25 17:30
@lgleim 
I was only thinking that the [triage/accepted](https://github.com/o3de/o3de/labels/triage%2Faccepted) might confuse newer people (such as myself) into thinking that it was accepted for triage but not yet completed.
if this is not an concern then yes we may close this issue.
Or maybe triage/completed would be a better term?

**Comment by AMZN-Gene** [comment] 2023-05-25 17:46
+1 that triage/complete is better term than triage/accepted. triage/complete works even in the event that the issue is closed as "wont fix". We're saying, "yes, this has been triaged". Rather than "yes, this has been triaged, and we agree it needs to be worked on"

The fact that an issue is OPEN means it needs to either be triaged, or it's been triaged (ie triage/complete) and needs to be fixed.

**Comment by michalpelka** [comment] 2023-09-07 14:52
Discussed in sig-simulation, some next steps were proposed in the closed duplicate issue :
https://github.com/o3de/o3de/issues/16109#issuecomment-1710284785

**Comment by lumberyard-employee-dm** [comment] 2024-01-10 17:12
The triage/accepted is used after an issue has been triaged by the appropriate SIG-group. 
I am closing this issue, unless there is a more compelling reason to not use the triage/accepted and triage/declined labels.

**Closed by lumberyard-employee-dm** 2024-01-10 17:12 UTC
Labels: needs-sig, needs-triage
