### ISSUE TITLE
Windows installer fails to install O3DE

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#15536] opened 2023-04-04 07:16 UTC
**Describe the bug**
O3DE cannot be installed while using the Stabilization_2305 Installer. Setup fails with the `0x80091007 - The hash value is not correct.` message. This issue occurs only on Windows.

Please refer to the attached screenshot and log file for more information.

**Steps to reproduce**
1. Download the newest Stabilization Installer.
2. Run the installation process.

**Expected behavior**
O3DE is installed without issues.

**Actual behavior**
Installation fails.

**Screenshots/Video**
![installer_fail](https://user-images.githubusercontent.com/86952318/229709873-d533481d-d5fd-43a7-a67a-fa23e419a0e7.jpg)
[installation_fail_log.txt](https://github.com/o3de/o3de/files/11145455/installation_fail_log.txt)

**Found in Branch**
Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe)

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by AMZN-alexpete** [comment] 2023-04-04 21:44
I wasn't able to reproduce this issue.  
![image](https://user-images.githubusercontent.com/26804013/229929129-17d205bd-c8a0-4ba0-a01d-e5452f22b293.png)

Is it possible some of the files were corrupted during download or didn't download correctly?
How many attempts did you make to run the installer and download the file?

**Comment by LB-MichalRodzos** [comment] 2023-04-05 06:36
@AMZN-alexpete Yesterday I downloaded the installer 3 times and tried to install the engine 5 times. Also, this issue occurred on two machines. However; today I downloaded the installer once again and I was able to install the O3DE successfully.

**Comment by LB-KacperKapusta** [comment] 2023-04-18 08:02
Due to this issue we are unable to install the latest version of the Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe) even after multiple redownloads/reinstall attempts. Same issue occurred on 3 different machines.

[O3DE_[Developer_Preview]_20230418094343.log](https://github.com/o3de/o3de/files/11259359/O3DE_.Developer_Preview._20230418094343.log)

**Comment by amzn-changml** [comment] 2023-04-19 17:16
Latest run appears to have signed the binary files properly now. Please verify that the bootstrap installer pulls all installer files

**Comment by LB-KacperKapusta** [comment] 2023-04-20 08:11
The latest Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe) has been verified to finish installation without any issues. @amzn-changml, let us know if we should still hold on this issue or it can be now closed.

**Comment by LB-KacperKapusta** [comment] 2023-04-24 13:32
It has been reverified today using the latest Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe) that the issue has reoccurred and it is impossible to finish the installation.

**Comment by amzn-changml** [comment] 2023-04-24 17:37
I've re-generated the installer and installed it on my end successfully. Please verify that this issue is no longer occuring @LB-KacperKapusta

**Comment by LB-KacperKapusta** [comment] 2023-04-25 08:47
The issue has been reverified on today's Stabilization/2305 Installer (https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe) and it does still occur for the following machines:

- [GPC-427_DxDiag.txt](https://github.com/o3de/o3de/files/11320475/GPC-427_DxDiag.txt)
- [GPC-462_DxDiag.txt](https://github.com/o3de/o3de/files/11320481/GPC-462_DxDiag.txt)
- [GPC-589_DxDiag.txt](https://github.com/o3de/o3de/files/11320484/GPC-589_DxDiag.txt)
- [GPC-94301_DxDiag.txt](https://github.com/o3de/o3de/files/11320553/GPC-94301_DxDiag.txt)

[O3DE_[Developer_Preview]_20230425092032.log](https://github.com/o3de/o3de/files/11320570/O3DE_.Developer_Preview._20230425092032.log)


However, the installation completes without issues on this one machine:

- [GPC-610_DxDiag.txt](https://github.com/o3de/o3de/files/11320557/GPC-610_DxDiag.txt)

**Comment by amzn-changml** [comment] 2023-04-25 16:56
Do you have a approximate time that you've downloaded the installer? For those machines that failed, did we try downloading the installer again for a repeat test?

**Comment by amzn-changml** [comment] 2023-04-27 16:59
Yes, let's close the issue for now. I think we resolved the root cause.

**Comment by LB-ArturZieba** [comment] 2023-04-28 14:15
Issue verified as fixed on GPC-610 (https://github.com/o3de/o3de/issues/15536#issuecomment-1521412119 for reference), the installation started and successfully completed. The executable was downloaded from https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe at 3:54PM GMT+2 time.

**Comment by LB-MateuszSzweda** [comment] 2023-05-02 07:22
Unfortunately the issue has reocurred. 
On 05/02 the same `0x80091007 - The hash value is not correct.` message was observed together with installation failure.

The executable was downloaded from https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe at 8:30AM GMT+2 time.

Reopening the issue.

**Comment by amzn-changml** [comment] 2023-05-02 18:42
I've invalidated the CDN cache for the installer files. @LB-MateuszSzweda can you please download the installer again and retry?

**Comment by LB-MateuszSzweda** [comment] 2023-05-04 08:29
Issue verified as fixed on Stabilization/2305 Installer obtained from https://o3debinaries.org/stabilization-2305/Latest/Windows/o3de_installer.exe at 10AM GMT+2 time. I was able to install,build and launch a project.

@amzn-changml

**Closed** 2023-06-29 18:38 UTC
Labels: kind/bug, sig/build, triage/accepted, priority/blocker

**Comment by LB-MichalRodzos** [comment] 2023-06-30 07:12
Confirming that issue has been closed and does not occur on latest development installer (https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe).
