### ISSUE TITLE
Script canvas crashes with DPE

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#16809] opened 2023-09-26 18:18 UTC
**Describe the bug**
With DPE ScripCanvas with input parameters. Such configuration crashes the Editor with DPE:
![image](https://github.com/o3de/o3de/assets/3209244/f0b0bc22-e964-4c8b-a60b-0b5e170837c6)

**Assets required**
No asset required

**Steps to reproduce**
1. Create an empty level
2. Create an empty script canvas with one variable of type Entity Id. Set "From component" in Initial Value Source
![image](https://github.com/o3de/o3de/assets/3209244/7b8a3f0c-3e5b-4a97-ab16-0e4a10cba8ed)
3. Save the script canvas.
4. Add entity
6. Add "Script Canvas Component" to the entity
7. Set the `Source` to script mentioned above
8. Get crash
**Expected behavior**
The editor should not crash; the modified card with Script Canvas should look correct.

**Actual behavior**
Editor crashes.

**Screenshots/Video**
The @jhanca-robotecai recorded a video during his work:
[Screencast from 26.09.2023 18_45_08.webm](https://github.com/o3de/o3de/assets/3209244/f0676e33-8870-49b5-89e1-756e37b58832)

**Found in Branch**
stabilization/2305

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
deff45bfdebb96a75d89ed0bc611a4bcc0c4428e - For ubuntu
08cb981a46d7a39f8c4badc0c125c18a8b5579c4 - For Windows

**Stack Trace for visual studio and clang/lldb **
https://gist.github.com/michalpelka/81866625593288453d968ec4c71dc464

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows/Ubuntu]
 - Version [Windows 11, Ubuntu 22.04]
 - CPU [tested on multiple]
 - GPU [ested on multiple]
 - Memory [tested on multiple]

**Additional context**
`ed_enableDPE=false` allows to circle-navigate issue.

Btw, https://github.com/o3de/o3de/issues/16449  is still present.

**Comment by cgalvan** [comment] 2023-09-28 17:16
Closing this as duplicate of https://github.com/o3de/o3de/issues/16762

**Closed by cgalvan** 2023-09-28 17:16 UTC
Labels: kind/bug, sig/content
