### ISSUE TITLE
Entity Outliner: Editor crashes after collapsing "double nested" prefab with left arrow key

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#8636] opened 2022-03-31 11:21 UTC
**Describe the bug**
Collapsing a selected nested prefab placed inside another nested prefab in the **Entity Outliner** with the left arrow key when its focus mode is enabled, crashes the Editor.

Note that this issue occurs on Windows and Linux.

Refer to the attached logs from a Windows machine for more information.

**Steps to reproduce**
1. Create a new level.
2. Create a prefab in the **Entity Outliner**.
3. In the prefab created in previous step, create another prefab (creating a nested prefab).
4. In the prefab created in previous step, create another prefab (creating a **"double nested"** prefab).
5. While in Focus mode of the prefab created in the previous step, select the prefab in the **Entity Outliner**.
6. Press the left arrow key on the keyboard to collapse the selected prefab.

**Expected behavior**
In the **Entity Outliner**, the **"double nested"** prefab collapses after selecting it in its focus mode and pressing the left arrow key, the **Editor** remains stable.

**Actual behavior**
After collapsing the selected **"double nested"** prefab when its focus mode is enabled with the left arrow key in the **Entity Outliner**, the **Editor** crashes.

**Call Stack Trace:**
```
25) 00007FFCB743B857 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFCB98B51B0 (ntdll) : memset
23) 00007FFCB989C766 (ntdll) : _C_specific_handler
22) 00007FFCB98B20CF (ntdll) : _chkstk
21) 00007FFCB9861454 (ntdll) : RtlRaiseException
20) 00007FFCB98B0BFE (ntdll) : KiUserExceptionDispatcher
19) 00007FFC67B56583 (Qt5Core) : QSortFilterProxyModel::parent
18) 00007FFC67B55582 (Qt5Core) : QSortFilterProxyModel::mapToSource
17) 00007FFC67B5291E (Qt5Core) : QSortFilterProxyModel::buddy
16) 00007FFC662ED9F9 (Qt5Widgets) : QAbstractItemView::currentChanged
15) 00007FFC6634C54D (Qt5Widgets) : QTreeView::currentChanged
14) 00007FFC67B90E17 (Qt5Core) : QObject::qt_static_metacall
13) 00007FFC67B44C73 (Qt5Core) : QItemSelectionModel::setCurrentIndex
12) 00007FFC662F2F55 (Qt5Widgets) : QAbstractItemView::mousePressEvent
11) C:\o3de\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Outliner\EntityOutlinerTreeView.cpp (177) : AzToolsFramework::EntityOutlinerTreeView::mouseReleaseEvent
10) 00007FFC660F7B02 (Qt5Widgets) : QWidget::event
 9) 00007FFC6619A090 (Qt5Widgets) : QFrame::event
 8) 00007FFC662F9428 (Qt5Widgets) : QAbstractItemView::viewportEvent
 7) 00007FFC67B73BDA (Qt5Core) : QCoreApplicationPrivate::sendThroughObjectEventFilters
 6) 00007FFC660D499C (Qt5Widgets) : QApplicationPrivate::notify_helper
 5) 00007FFC660D28D0 (Qt5Widgets) : QApplication::notify
 4) 00007FFC67B71B4A (Qt5Core) : QCoreApplication::notifyInternal2
 3) 00007FFC660D5BC5 (Qt5Widgets) : QApplicationPrivate::sendMouseEvent
 2) 00007FFC6612088A (Qt5Widgets) : QSizePolicy::QSizePolicy
 1) 00007FFC6611E80E (Qt5Widgets) : QSizePolicy::QSizePolicy

```

**Video**

https://user-images.githubusercontent.com/86951967/161041742-f6a2118c-8f2c-486a-986c-462056d22b09.mp4

**Found in Branch**
Development (9b24dc9)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.4 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/8388771/Editor.log)
[dump.zip](https://github.com/o3de/o3de/files/8388773/dump.zip)
[error.log](https://github.com/o3de/o3de/files/8388775/error.log)

**Comment by srikappa-amzn** [comment] 2022-04-06 23:50
Was able to reproduce this not only with creation but also with instantiation. I played around the with left and right arrow keys a bunch with deeply nested prefabs and ran into different crashes from what looked like Qt errors coming from outliner tree updates. See the below stacktrace for one such crash:
```
 	Qt5Core.dll!00007ffd121b62cf()	Unknown
 	Qt5Core.dll!00007ffd121b52e2()	Unknown
 	Qt5Core.dll!00007ffd121b3ff9()	Unknown
 	Qt5Widgets.dll!00007ffd0991166b()	Unknown
 	Qt5Widgets.dll!00007ffd09971c8b()	Unknown
 	Qt5Widgets.dll!00007ffd097179eb()	Unknown
 	Qt5Widgets.dll!00007ffd097b98b0()	Unknown
 	Qt5Widgets.dll!00007ffd097bb038()	Unknown
 	Qt5Widgets.dll!00007ffd096f49a1()	Unknown
 	Qt5Widgets.dll!00007ffd096f2510()	Unknown
 	Qt5Core.dll!00007ffd121d17cb()	Unknown
 	Qt5Widgets.dll!00007ffd0973e5ee()	Unknown
 	Qt5Widgets.dll!00007ffd096f49a1()	Unknown
 	Qt5Widgets.dll!00007ffd096f3a23()	Unknown
 	Qt5Core.dll!00007ffd121d17cb()	Unknown
 	Qt5Gui.dll!00007ffd09093f50()	Unknown
 	Qt5Gui.dll!00007ffd0907ee99()	Unknown
 	Qt5Core.dll!00007ffd1221a84a()	Unknown
 	qwindows.dll!00007ffd1a2c3799()	Unknown
 	Qt5Core.dll!00007ffd121cdc5f()	Unknown
 	Qt5Core.dll!00007ffd121d0795()	Unknown
>	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3944	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 55	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++

```
Since it doesn't look like the errors are happening due to prefab logic, assigning this to the editor team for further investigation.

**Closed** 2022-06-30 13:03 UTC
Labels: feature/editor, kind/bug, sig/content, triage/accepted, priority/critical
