### ISSUE TITLE
Prefabs: Editor can crash when exiting focus mode on a prefab that is not properly dirtied

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#13100] opened 2022-11-09 23:19 UTC
**Describe the bug**
Editor can crash when exiting focus mode on a prefab that is not properly dirtied. This was noted while using the Gradient Paint Brush tools on an entity in a prefab. There is an issue causing the level/entity/prefab to not immediately dirty when certain changes are made on the Image Gradient component (https://github.com/o3de/o3de/issues/13099). If the user in this state exits focus mode on the prefab, the Editor can crash.

```
Call Stack Trace:
25) 00007FFD4CFB02E7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFD4F495530 (ntdll) : memset
23) 00007FFD4F47C876 (ntdll) : _C_specific_handler
22) 00007FFD4F49241F (ntdll) : _chkstk
21) 00007FFD4F4414A4 (ntdll) : RtlRaiseException
20) 00007FFD4F490F4E (ntdll) : KiUserExceptionDispatcher
19) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Link\Link.cpp (242) : AzToolsFramework::Prefab::Link::ConstructLinkDomFromPatches
18) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Link\Link.cpp (119) : AzToolsFramework::Prefab::Link::GetLinkDom
17) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\Undo\PrefabUndoUpdateLink.cpp (68) : AzToolsFramework::Prefab::PrefabUndoUpdateLink::Capture
16) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabPublicHandler.cpp (924) : AzToolsFramework::Prefab::PrefabPublicHandler::Internal_HandleContainerOverride
15) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabPublicHandler.cpp (899) : AzToolsFramework::Prefab::PrefabPublicHandler::GenerateUndoNodesForEntityChangeAndUpdateCache
14) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Application\ToolsApplication.cpp (1678) : AzToolsFramework::ToolsApplication::CreateUndosForDirtyEntities
13) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Application\ToolsApplication.cpp (1583) : AzToolsFramework::ToolsApplication::EndUndoBatch
12) D:\GitHub\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1541) : AZ::Internal::EBusContainer<AzToolsFramework::ToolsApplicationRequests,AzToolsFramework::ToolsApplicationRequests,0,0>::Dispatcher<AZ::EBus<AzToolsFramework::ToolsApplicati
11) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\Prefab\PrefabFocusHandler.cpp (193) : AzToolsFramework::Prefab::PrefabFocusHandler::FocusOnParentOfFocusedPrefab
10) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Prefab\PrefabUiHandler.cpp (522) : AzToolsFramework::PrefabUiHandler::OnOutlinerItemCollapse
 9) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Outliner\EntityOutlinerWidget.cpp (988) : AzToolsFramework::EntityOutlinerWidget::OnTreeItemCollapsed
 8) 00007FFCE18509AA (Qt5Core) : QObject::qt_static_metacall
 7) 00007FFCE063C1BA (Qt5Widgets) : QTreeView::collapsed
 6) 00007FFCE063BF4E (Qt5Widgets) : QTreeViewPrivate::collapse
 5) 00007FFCE063F588 (Qt5Widgets) : QTreeViewPrivate::expandOrCollapseItemAtPos
 4) 00007FFCE064385F (Qt5Widgets) : QTreeView::mousePressEvent
 3) D:\GitHub\o3de\Code\Framework\AzToolsFramework\AzToolsFramework\UI\Outliner\EntityOutlinerTreeView.cpp (177) : AzToolsFramework::EntityOutlinerTreeView::mouseReleaseEvent
 2) 00007FFCE03E7912 (Qt5Widgets) : QWidget::event
 1) 00007FFCE04898B0 (Qt5Widgets) : QFrame::event
```

**Steps to reproduce**
1. Launch the Editor and open a new or existing level.
2. Create an entity, and add an Image Gradient component and all required dependencies.
3. Assign any valid Image Gradient asset to the component.
4. Set the Save Mode property to Auto Save With Incrementing Names.
5. Create a prefab from the entity.
6. Save all changes to the prefab and level so nothing is dirty.
7. Enter Focus Mode on the prefab, and select the gradient entity.
8. Click the Edit button on the Image Gradient component, and then click Done (with no changes made, the file assigned to the component is still updated due to the Save Mode).
9. Note the dirty status of the prefab, and without deselecting the entity or making any other component changes, exit Focus Mode on the prefab.

**Expected behavior**
Prefab collapses without issue.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**
https://user-images.githubusercontent.com/82226555/200962873-d0de2072-3ac6-450b-9391-90d8c9c5ae40.mp4

**Found in Branch**
development@ 9080579e3e388388913a9f73a140d19442cb10cc

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by forkercat** [comment] 2022-12-01 17:04
I tried it in latest development 12/1.
- I could not reproduce crash. I didn't see the prefab warnings showing up in video. I think they could be related as well.
- The "not properly dirtied" issue still exist.

@jckand-amzn will try to reproduce to see if it still occurs.

**Comment by forkercat** [comment] 2022-12-01 20:10
Verified that it could not be reproduced. After some recent changes, the prefab is no longer dirtied unless you actually do anything between "edit" and "save".

We can close it. But before that, I will take a look into the crash on previous commit to see which part of prefab code might lead to this. Maybe it is worth adding some check to prevent the crash.

**Comment by forkercat** [comment] 2022-12-02 01:00
Update: Interestingly, I still could not repro the crash even on one commit before the above changes. I didn't see the prefab-related warnings showing up neither. Looks like some other prefab changes might fix it.

**Closed by forkercat** 2022-12-02 01:00 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
