### ISSUE TITLE
Editor crashes when clicking on more information in components for slices

### ISSUE THREAD

**Issue by aaguilea** [o3de/o3de#2595] opened 2021-07-29 08:50 UTC
**Describe the bug**
The bug happens when I click on the more information part of the component of a slice (see video)

**To Reproduce**
1. Open a level
2. Create a slice / instantiate a slice
3. click on more information for any component.

**Expected behavior**
I guess the expected behavior would be to see the more information options 

**Screenshots**
http://broadcast.amazon.com/videos/374758

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: WINDOWS
 - Version 10
 - CPU INTEL CORE i7 - 7820HK 2.90Ghz
 - GPU NVidia GTX 3090
 - Memory 32 gb

**Additional context**

**Comment by AMZN-daimini** [comment] 2021-08-31 19:10
I tried reproducing this with Prefab Mode on with no success. Seems to be a slice issue.

Also note, "clicking on more information" refers to the hamburger menu button (and not the question mark as I originally thought).
![image](https://user-images.githubusercontent.com/82231674/131561802-4baf7d79-60bb-4783-95fc-4d56f1a85fee.png)

**Comment by srikappa-amzn** [comment] 2022-04-08 23:17
I can't reproduce this anymore with slices. I'm closing this for now. Feel free to reopen it if you encounter this again. Please provide

**Closed by srikappa-amzn** 2022-04-08 23:17 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
