### ISSUE TITLE
Random Atom RPI crash after the Editor starts

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#11989] opened 2022-09-14 19:55 UTC
**Describe the bug**
After building the Editor from latest stabilization in debug mode, it suddenly crashed in the "Loading Plugins..." phase of the splashscreen.

![image](https://user-images.githubusercontent.com/82231674/190248372-478201b3-cdb9-4fed-a3a1-fcce833e6533.png)

```
>	Atom_RPI.Editor.dll!AZ::RPI::ShaderOptionGroupLayout::IsFinalized() Line 446	C++
 	Atom_RPI.Editor.dll!AZ::RPI::ShaderOptionGroupLayout::ValidateIsFinalized() Line 478	C++
 	Atom_RPI.Editor.dll!AZ::RPI::ShaderOptionGroupLayout::FindShaderOptionIndex(const AZ::Name & optionName) Line 558	C++
 	Atom_RPI.Editor.dll!AZ::RPI::LuaMaterialFunctorRuntimeContext::SetShaderOptionValueHelper(const char * name, AZStd::function<bool __cdecl(AZ::RPI::ShaderOptionGroup *,AZ::RHI::Handle<unsigned int,AZ::RPI::ShaderOptionIndexNamespace>)> setValueCommand) Line 391	C++
 	Atom_RPI.Editor.dll!AZ::RPI::LuaMaterialFunctorRuntimeContext::SetShaderOptionValue<bool>(const char * name, bool value) Line 427	C++
 	Atom_RPI.Editor.dll!AZ::Internal::CallFunction<bool,char const *,bool>::Member<0,1,AZ::RPI::LuaMaterialFunctorRuntimeContext *,bool (__cdecl AZ::RPI::LuaMaterialFunctorRuntimeContext::*)(char const *,bool)>(bool(AZ::RPI::LuaMaterialFunctorRuntimeContext::*)(const char *, bool) functionPtr, AZ::RPI::LuaMaterialFunctorRuntimeContext * thisPtr, AZ::BehaviorArgument * arguments, AZ::BehaviorArgument * result, std::integer_sequence<unsigned __int64,0,1> __formal) Line 4038	C++
 	Atom_RPI.Editor.dll!AZ::Internal::BehaviorMethodImpl<bool (__cdecl AZ::RPI::LuaMaterialFunctorRuntimeContext::*)(char const *,bool)>::Call(AZ::BehaviorArgument * arguments, unsigned int numArguments, AZ::BehaviorArgument * result) Line 4311	C++
 	Atom_RPI.Editor.dll!AZ::LuaScriptCaller::Call(lua_State * lua) Line 3557	C++
 	[External Code]	
 	Atom_RPI.Editor.dll!AZ::Internal::LuaSafeCall(lua_State * lua, int numParams, int numResults) Line 616	C++
 	Atom_RPI.Editor.dll!AZ::ScriptDataContext::CallExecute() Line 2184	C++
 	Atom_RPI.Editor.dll!AZ::RPI::LuaMaterialFunctor::Process(AZ::RPI::MaterialFunctor::RuntimeContext & context) Line 135	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Material::Compile() Line 376	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Material::Init(AZ::RPI::MaterialAsset & materialAsset) Line 158	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Material::CreateInternal(AZ::RPI::MaterialAsset & materialAsset) Line 47	C++
 	Atom_RPI.Editor.dll!`AZ::RPI::MaterialSystem::Init'::`2'::<lambda_1>::operator()(AZ::Data::AssetData * materialAsset) Line 46	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::INVOKE<`AZ::RPI::MaterialSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *>(AZ::RPI::MaterialSystem::Init::__l2::<lambda_1> & f, AZ::Data::AssetData * && <args_0>) Line 208	C++
 	Atom_RPI.Editor.dll!AZStd::invoke<`AZ::RPI::MaterialSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *>(AZ::RPI::MaterialSystem::Init::__l2::<lambda_1> & f, AZ::Data::AssetData * && <args_0>) Line 54	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<AZStd::intrusive_ptr<AZ::RPI::Material>>::call<`AZ::RPI::MaterialSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *>(AZ::RPI::MaterialSystem::Init::__l2::<lambda_1> & <args_0>, AZ::Data::AssetData * && <args_1>) Line 32	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::get_invoker<AZStd::intrusive_ptr<AZ::RPI::Material> __cdecl(AZ::Data::AssetData *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::RPI::MaterialSystem::Init'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, AZ::Data::AssetData * && <args_0>) Line 172	C++
 	Atom_RPI.Editor.dll!AZStd::function_intermediate<AZStd::intrusive_ptr<AZ::RPI::Material>,AZ::Data::AssetData *>::operator()(AZ::Data::AssetData * && <args_0>) Line 604	C++
 	Atom_RPI.Editor.dll!AZStd::function<AZStd::intrusive_ptr<AZ::RPI::Material> __cdecl(AZ::Data::AssetData *)>::operator()(AZ::Data::AssetData * <args_0>) Line 684	C++
 	Atom_RPI.Editor.dll!AZ::Data::InstanceDatabase<AZ::RPI::Material>::FindOrCreate(const AZ::Data::InstanceId & id, const AZ::Data::Asset<AZ::Data::AssetData> & asset, const AZStd::any * param) Line 340	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Material::FindOrCreate(const AZ::Data::Asset<AZ::RPI::MaterialAsset> & materialAsset) Line 35	C++
 	Atom_RPI.Editor.dll!AZ::RPI::ModelLod::Init(const AZ::Data::Asset<AZ::RPI::ModelLodAsset> & lodAsset, const AZ::Data::Asset<AZ::RPI::ModelAsset> & modelAsset) Line 114	C++
 	Atom_RPI.Editor.dll!AZ::RPI::ModelLod::CreateInternal(const AZ::Data::Asset<AZ::RPI::ModelLodAsset> & lodAsset, const AZStd::any * modelAssetAny) Line 42	C++
 	Atom_RPI.Editor.dll!`AZ::RPI::ModelSystem::Init'::`2'::<lambda_1>::operator()(AZ::Data::AssetData * modelLodAsset, const AZStd::any * modelAsset) Line 48	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::INVOKE<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *,AZStd::any const *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_1> & f, AZ::Data::AssetData * && <args_0>, const AZStd::any * && <args_1>) Line 208	C++
 	Atom_RPI.Editor.dll!AZStd::invoke<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *,AZStd::any const *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_1> & f, AZ::Data::AssetData * && <args_0>, const AZStd::any * && <args_1>) Line 54	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<AZStd::intrusive_ptr<AZ::RPI::ModelLod>>::call<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_1> &,AZ::Data::AssetData *,AZStd::any const *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_1> & <args_0>, AZ::Data::AssetData * && <args_1>, const AZStd::any * && <args_2>) Line 32	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::get_invoker<AZStd::intrusive_ptr<AZ::RPI::ModelLod> __cdecl(AZ::Data::AssetData *,AZStd::any const *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, AZ::Data::AssetData * && <args_0>, const AZStd::any * && <args_1>) Line 172	C++
 	Atom_RPI.Editor.dll!AZStd::function_intermediate<AZStd::intrusive_ptr<AZ::RPI::ModelLod>,AZ::Data::AssetData *,AZStd::any const *>::operator()(AZ::Data::AssetData * && <args_0>, const AZStd::any * && <args_1>) Line 604	C++
 	Atom_RPI.Editor.dll!AZStd::function<AZStd::intrusive_ptr<AZ::RPI::ModelLod> __cdecl(AZ::Data::AssetData *,AZStd::any const *)>::operator()(AZ::Data::AssetData * <args_0>, const AZStd::any * <args_1>) Line 684	C++
 	Atom_RPI.Editor.dll!AZ::Data::InstanceDatabase<AZ::RPI::ModelLod>::FindOrCreate(const AZ::Data::InstanceId & id, const AZ::Data::Asset<AZ::Data::AssetData> & asset, const AZStd::any * param) Line 344	C++
 	Atom_RPI.Editor.dll!AZ::RPI::ModelLod::FindOrCreate(const AZ::Data::Asset<AZ::RPI::ModelLodAsset> & lodAsset, const AZ::Data::Asset<AZ::RPI::ModelAsset> & modelAsset) Line 25	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Model::Init(const AZ::Data::Asset<AZ::RPI::ModelAsset> & modelAsset) Line 96	C++
 	Atom_RPI.Editor.dll!AZ::RPI::Model::CreateInternal(const AZ::Data::Asset<AZ::RPI::ModelAsset> & modelAsset) Line 69	C++
 	Atom_RPI.Editor.dll!`AZ::RPI::ModelSystem::Init'::`2'::<lambda_2>::operator()(AZ::Data::AssetData * modelAsset) Line 56	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::INVOKE<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_2> &,AZ::Data::AssetData *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_2> & f, AZ::Data::AssetData * && <args_0>) Line 208	C++
 	Atom_RPI.Editor.dll!AZStd::invoke<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_2> &,AZ::Data::AssetData *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_2> & f, AZ::Data::AssetData * && <args_0>) Line 54	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<AZStd::intrusive_ptr<AZ::RPI::Model>>::call<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_2> &,AZ::Data::AssetData *>(AZ::RPI::ModelSystem::Init::__l2::<lambda_2> & <args_0>, AZ::Data::AssetData * && <args_1>) Line 32	C++
 	Atom_RPI.Editor.dll!AZStd::Internal::function_util::get_invoker<AZStd::intrusive_ptr<AZ::RPI::Model> __cdecl(AZ::Data::AssetData *),AZStd::Internal::function_util::function_obj_tag,AZStd::allocator>::call<`AZ::RPI::ModelSystem::Init'::`2'::<lambda_2>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr, AZ::Data::AssetData * && <args_0>) Line 172	C++
 	DiffuseProbeGrid.Editor.dll!AZStd::function_intermediate<AZStd::intrusive_ptr<AZ::RPI::Model>,AZ::Data::AssetData *>::operator()(AZ::Data::AssetData * && <args_0>) Line 604	C++
 	DiffuseProbeGrid.Editor.dll!AZStd::function<AZStd::intrusive_ptr<AZ::RPI::Model> __cdecl(AZ::Data::AssetData *)>::operator()(AZ::Data::AssetData * <args_0>) Line 684	C++
 	DiffuseProbeGrid.Editor.dll!AZ::Data::InstanceDatabase<AZ::RPI::Model>::FindOrCreate(const AZ::Data::InstanceId & id, const AZ::Data::Asset<AZ::Data::AssetData> & asset, const AZStd::any * param) Line 340	C++
 	DiffuseProbeGrid.Editor.dll!AZ::RPI::Model::FindOrCreate(const AZ::Data::Asset<AZ::RPI::ModelAsset> & modelAsset) Line 28	C++
 	DiffuseProbeGrid.Editor.dll!AZ::Render::DiffuseProbeGridFeatureProcessor::OnVisualizationModelAssetReady(AZ::Data::Asset<AZ::Data::AssetData> asset) Line 837	C++
 	DiffuseProbeGrid.Editor.dll!AZ::Render::DiffuseProbeGridFeatureProcessor::OnAssetReady(AZ::Data::Asset<AZ::Data::AssetData> asset) Line 924	C++
 	EditorLib.dll!AZStd::Internal::INVOKE<void (__cdecl AZ::Data::AssetEvents::*&)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> &,AZ::Data::Asset<AZ::Data::AssetData> &,void>(void(AZ::Data::AssetEvents::*)(AZ::Data::Asset<AZ::Data::AssetData>) & f, AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> & arg0, AZ::Data::Asset<AZ::Data::AssetData> & <args_0>) Line 178	C++
 	EditorLib.dll!AZStd::invoke<void (__cdecl AZ::Data::AssetEvents::*&)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> &,AZ::Data::Asset<AZ::Data::AssetData> &>(void(AZ::Data::AssetEvents::*)(AZ::Data::Asset<AZ::Data::AssetData>) & f, AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> & <args_0>, AZ::Data::Asset<AZ::Data::AssetData> & <args_1>) Line 55	C++
 	EditorLib.dll!AZ::EBusEventProcessingPolicy::Call<void (__cdecl AZ::Data::AssetEvents::*&)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> &,AZ::Data::Asset<AZ::Data::AssetData> &>(void(AZ::Data::AssetEvents::*)(AZ::Data::Asset<AZ::Data::AssetData>) & func, AZ::Internal::HandlerNode<AZ::Data::AssetEvents,AZ::Data::AssetEvents,AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::HandlerHolder,1> & iface, AZ::Data::Asset<AZ::Data::AssetData> & <args_0>) Line 438	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AZ::Data::AssetEvents,AZ::Data::AssetEvents,1,1>::Dispatcher<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::Event<void (__cdecl AZ::Data::AssetEvents::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::Asset<AZ::Data::AssetData> &>(const AZ::Data::AssetId & id, void(AZ::Data::AssetEvents::*)(AZ::Data::Asset<AZ::Data::AssetData>) && func, AZ::Data::Asset<AZ::Data::AssetData> & <args_0>) Line 150	C++
 	EditorLib.dll!AZ::Data::AssetManager::NotifyAssetReady(AZ::Data::Asset<AZ::Data::AssetData> asset) Line 1836	C++
 	EditorLib.dll!AZStd::Internal::INVOKE<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>,void>(void(AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>) && f, AZ::Data::AssetManager * && arg0, AZ::Data::Asset<AZ::Data::AssetData> && <args_0>) Line 178	C++
 	EditorLib.dll!AZStd::invoke<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>(void(AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>) && f, AZ::Data::AssetManager * && <args_0>, AZ::Data::Asset<AZ::Data::AssetData> && <args_1>) Line 55	C++
 	EditorLib.dll!`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>'::`5'::<lambda_1>::operator()() Line 861	C++
 	EditorLib.dll!AZStd::Internal::INVOKE<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>'::`5'::<lambda_1> &>(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction::__l5::<lambda_1> & f) Line 209	C++
 	EditorLib.dll!AZStd::invoke<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>'::`5'::<lambda_1> &>(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction::__l5::<lambda_1> & f) Line 55	C++
 	EditorLib.dll!AZStd::Internal::function_util::invoke_void_return_wrapper<void>::call<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>'::`5'::<lambda_1> &>(AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction::__l5::<lambda_1> & <args_0>) Line 42	C++
 	EditorLib.dll!AZStd::Internal::function_util::get_invoker<void __cdecl(void),AZStd::Internal::function_util::function_obj_tag,AZ::Internal::EBusEnvironmentAllocator>::call<`AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::QueueFunction<void (__cdecl AZ::Data::AssetManager::*)(AZ::Data::Asset<AZ::Data::AssetData>),AZ::Data::AssetManager *,AZ::Data::Asset<AZ::Data::AssetData>>'::`5'::<lambda_1>>(AZStd::Internal::function_util::function_buffer & function_obj_ptr) Line 148	C++
 	Atom_Feature_Common.Editor.dll!AZStd::function_intermediate<void>::operator()() Line 605	C++
 	Atom_Feature_Common.Editor.dll!AZStd::function<void __cdecl(void)>::operator()() Line 685	C++
 	Atom_Feature_Common.Editor.dll!AZ::EBusQueuePolicy<1,AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZStd::recursive_mutex>::Execute() Line 267	C++
 	Atom_Feature_Common.Editor.dll!AZ::BusInternal::EBusBroadcastQueue<AZ::EBus<AZ::Data::AssetEvents,AZ::Data::AssetEvents>,AZ::BusInternal::EBusImplTraits<AZ::Data::AssetEvents,AZ::Data::AssetEvents>>::ExecuteQueuedEvents() Line 368	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::AssetManager::DispatchEvents() Line 591	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::WaitForAsset::Wait() Line 342	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::WaitForAsset::WaitUntilReady() Line 323	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::AssetManager::BlockUntilLoadComplete(const AZ::Data::Asset<AZ::Data::AssetData> & asset) Line 849	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::AssetInternal::BlockUntilLoadComplete(const AZ::Data::Asset<AZ::Data::AssetData> & asset) Line 118	C++
 	Atom_Feature_Common.Editor.dll!AZ::Data::Asset<AZ::RPI::ShaderAsset>::BlockUntilLoadComplete() Line 1148	C++
 	Atom_Feature_Common.Editor.dll!AZ::RPI::FindShaderAsset(AZ::Data::AssetId shaderAssetId, const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & shaderFilePath) Line 362	C++
 	Atom_Feature_Common.Editor.dll!AZ::RPI::LoadShader(AZ::Data::AssetId shaderAssetId, const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & shaderFilePath, const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & supervariantName) Line 374	C++
 	Atom_Feature_Common.Editor.dll!AZ::RPI::LoadCriticalShader(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & shaderFilePath, const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & supervariantName) Line 408	C++
 	Atom_Feature_Common.Editor.dll!AZ::Render::DynamicPrimitiveProcessor::InitShader() Line 323	C++
 	Atom_Feature_Common.Editor.dll!AZ::Render::DynamicPrimitiveProcessor::Initialize(const AZ::RPI::Scene * scene) Line 53	C++
 	Atom_Feature_Common.Editor.dll!AZ::Render::AuxGeomFeatureProcessor::Activate() Line 45	C++
 	Atom_Bootstrap.dll!AZ::RPI::Scene::Activate() Line 152	C++
 	Atom_Bootstrap.dll!AZ::Render::Bootstrap::BootstrapSystemComponent::GetOrCreateAtomSceneFromAzScene(AzFramework::Scene * scene) Line 281	C++
 	EditorLib.dll!`AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1>::operator()(AZ::Render::Bootstrap::Request * bootstrapRequests) Line 166	C++
 	EditorLib.dll!AZStd::Internal::INVOKE<`AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1> &,AZ::Render::Bootstrap::Request * &>(AtomToolsFramework::RenderViewportWidget::SetScene::__l2::<lambda_1> & f, AZ::Render::Bootstrap::Request * & <args_0>) Line 209	C++
 	EditorLib.dll!AZStd::invoke<`AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1> &,AZ::Render::Bootstrap::Request * &>(AtomToolsFramework::RenderViewportWidget::SetScene::__l2::<lambda_1> & f, AZ::Render::Bootstrap::Request * & <args_0>) Line 55	C++
 	EditorLib.dll!AZ::EBusEventProcessingPolicy::Call<`AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1> &,AZ::Render::Bootstrap::Request * &>(AtomToolsFramework::RenderViewportWidget::SetScene::__l2::<lambda_1> & func, AZ::Render::Bootstrap::Request * & iface) Line 438	C++
 	EditorLib.dll!AZ::Internal::EBusContainer<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Request,0,0>::Dispatcher<AZ::EBus<AZ::Render::Bootstrap::Request,AZ::Render::Bootstrap::Request>>::Broadcast<`AtomToolsFramework::RenderViewportWidget::SetScene'::`2'::<lambda_1> &>(AtomToolsFramework::RenderViewportWidget::SetScene::__l2::<lambda_1> & func) Line 1541	C++
 	EditorLib.dll!AtomToolsFramework::RenderViewportWidget::SetScene(const AZStd::shared_ptr<AzFramework::Scene> & scene, bool useDefaultRenderPipeline) Line 175	C++
 	EditorLib.dll!EditorViewportWidget::UpdateScene() Line 2418	C++
 	EditorLib.dll!EditorViewportWidget::SetViewportId(int id) Line 925	C++
 	EditorLib.dll!CLayoutViewPane::AttachViewport(QWidget * pViewport) Line 303	C++
 	EditorLib.dll!CLayoutViewPane::SetViewClass(const QString & sClass) Line 221	C++
 	EditorLib.dll!CLayoutWnd::BindViewport(CLayoutViewPane * vp, const QString & viewClassName, QWidget * pViewport) Line 166	C++
 	EditorLib.dll!CLayoutWnd::MaximizeViewport(int paneId) Line 207	C++
 	EditorLib.dll!CLayoutWnd::LoadConfig() Line 515	C++
 	EditorLib.dll!MainWindow::InitCentralWidget() Line 444	C++
 	EditorLib.dll!MainWindow::Initialize() Line 469	C++
 	EditorLib.dll!CCryEditApp::InitInstance() Line 1745	C++
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 4010	C++
 	Editor.exe!AZStd::Internal::INVOKE<int (__cdecl*&)(int,char * * const),int &,char * * &>(int(*)(int, char * *) & f, int & <args_0>, char * * & <args_1>) Line 209	C++
 	Editor.exe!AZStd::invoke<int (__cdecl*&)(int,char * * const),int &,char * * &>(int(*)(int, char * *) & f, int & <args_0>, char * * & <args_1>) Line 55	C++
 	Editor.exe!main(int argc, char * * argv) Line 32	C++
 	Editor.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 97	C++
 	[External Code]
```

**Steps to reproduce**
Happened at Editor start. I've seen it 3 times in the last few days though.

**Expected behavior**
...no crash :D

**Found in Branch**
Personal branch off of latest stabilization

Device: PC
OS: Windows
Version 10
CPU AMD Ryzen Threadripper 3970X
GPU NVidia Geforce RTX 3070
Memory 64GB

**Comment by rgba16f** [comment] 2022-09-14 20:04
@santorac seems to be crashing in the material options system

**Comment by santorac** [comment] 2022-09-15 20:19
I'm pretty sure this is a duplicate of https://github.com/o3de/o3de/issues/9418

We need more logging to figure out why the ShaderAsset is not getting loaded, I'm hoping someone from @o3de/sig-core can help us figure out a good place to add it.

**Comment by galibzon** [comment] 2022-09-20 17:21
Closing as duplicate.

**Closed by galibzon** 2022-09-20 17:21 UTC
Labels: kind/bug, needs-triage, sig/graphics-audio, feature/graphics/rpi
