### ISSUE TITLE
Physx raycast from screen node not returning entities with colliders.

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#8681] opened 2022-04-01 19:14 UTC
**Describe the bug**
Using the script canvas node RaycastFromScreen will not return any values other than invalid entity ID

**Steps to reproduce**
1. load a new or existing level
2. open script canvas editor
3. create a script canvas graph to cast a ray from screen space into world space similar to the one below
4. attach the script canvas graph to your camera
5. attach physx colliders to world objects such as the ground and shader ball
6. run the game and observe the results.

**Expected behavior**
the script does not return entity information

**Actual behavior**
The raycast hit will return the entities

**Assets required**
![image](https://user-images.githubusercontent.com/98843754/161327275-025ef411-72f9-44a3-9109-703b1b670d09.png)

Note: You can remove the input handler nodes so that you are casting rays into the scene as you move the mouse cursor around.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC win 10
 - CPU Ryzen 5950
 - GPU Nvidia 3070
 - Memory 32 gb

**Comment by AMZN-alexpete** [comment] 2022-04-04 22:07
Hi @michleza, what does the UI `Get Position` Script Canvas node output for the mouse co-ordinates?  Is it returning the correct mouse position? Also, have you tried setting the `Distance` parameter to something other than 0?  `Distance` controls how far out to cast the ray, so a ray of zero length is likely not hitting anything, maybe try something like 1024? Distance values are in meters.

**Comment by AMZN-alexpete** [comment] 2022-04-04 22:08
Here is an example graph that I used when implementing the feature:
![image](https://user-images.githubusercontent.com/26804013/161640125-36414a08-5765-469b-b0e1-014cdcbe4a85.png)

**Comment by michleza** [comment] 2022-04-07 17:33
@AMZN-alexpete  the GetPosition node will get the cursor's x,y position relative to the upper left corner. When I debug print the output of this node I get results I expect. Setting the distance to a realistic number such as 10 or 100 does not change the results. It will always look like this:

![image](https://user-images.githubusercontent.com/98843754/162262843-c2ff016e-d286-4487-985f-1ed96b5ffad1.png)

**Comment by AMZN-alexpete** [comment] 2022-04-23 00:11
I was not able to reproduce this issue in latest development/stabilization.  Here's the level setup I used that was able to hit colliders in the scene.    I'm wondering if possibly your colliders are not setup correctly?  If you're just adding a PhysX Collider component to the ground or shader ball, likely they have a missing PhysX mesh asset.  You can also tell this because you cannot see the debug mesh for the physx collider in the scene.  If you select a valid PhysX mesh asset, or use a shape collider like a box or sphere it should work OK.

![image](https://user-images.githubusercontent.com/26804013/164836460-913b1e93-415c-4af0-86b2-d161417ea548.png)

Here's my test game level with input bindings, script etc.
[game.zip](https://github.com/o3de/o3de/files/8545218/game.zip)

**Comment by greerdv** [comment] 2022-05-11 16:37
Hi @michleza, are you still able to reproduce this issue?

**Comment by hultonha** [comment] 2022-05-25 16:50
Pinging @michleza again, we have reports this is working correctly. Is this issue still impacting you? @AMZN-Olex confirmed it is working form them too. Any update would be very helpful. Thanks!

**Comment by hultonha** [comment] 2022-05-25 16:51
@michleza - If there has been no update by 2022/06/08 this issue will be closed. Thanks!

**Comment by hultonha** [comment] 2022-06-01 16:59
@michleza - bumping this again, if there still is no update by 2022/06/08 this issue will be closed. Thanks!

**Comment by michleza** [comment] 2022-06-01 19:52
This no longer repros for me in latest development build.

**Comment by AMZN-alexpete** [comment] 2022-06-01 20:07
Resolving as fixed!

**Closed by AMZN-alexpete** 2022-06-01 20:07 UTC
Labels: kind/bug, needs-triage, triage/needs-information, priority/major, sig/simulation
