### ISSUE TITLE
3 - Drag and drop content within Asset Browser.

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12865] opened 2022-10-27 22:56 UTC
**Use Story:**

As a user I need the ability to drag and drop content inside asset browser. this means from one location to another location.

 **Notes:**

We still need to define what files can and cant be dragged in specific scenarios and when to prompt the user about their expectations in specific scenarios.

 

See #10201

**Comment by rainbj** [comment] 2022-11-24 00:48
Hi @jjjoness and @lsemp3d 

I got latest today to test drive drove this workflow. I have a few items I would like to fix before closing this item.


1.  This step here is great no issues ![2022-11-23_16-24-29](https://user-images.githubusercontent.com/82551958/203669086-6aa25141-b97e-4b7f-b5ed-81fafff22396.png)

2. This modal can be simplified.  Move up "Import [NUMBEOFASSETS] asset" to the title bar. This information is a duplicate of the title, just without the number.  Can we use the browse edit input field type here? We use the browse edit for all the field types like this throughout the editor. Remove the blank space at the bottom
![2022-11-23_16-25-11](https://user-images.githubusercontent.com/82551958/203669141-e5893157-dff9-4474-994c-774ddda7ad78.png)

3.  Duplicate content modal window. This one looks good except the extra space, and we can also remove the extra line.
![2022-11-23_16-26-48](https://user-images.githubusercontent.com/82551958/203669561-191dc153-5aa0-4d10-b86c-9e6bf7b7422d.png)

4. I don't think we need this modal. This one appears to come up every time a user adds a new image, which would get extremely irritating after seeing this a dozen times. We auto process assets in their project every time the editor loads, so I don't see a reason we would want to warn them here when we don't warn them there. 
![2022-11-23_16-27-03](https://user-images.githubusercontent.com/82551958/203669677-18616287-f9be-4791-b4d7-e958c2316034.png)

**Comment by jjjoness** [comment] 2022-11-30 12:04
![image](https://user-images.githubusercontent.com/82226755/204791533-fa136416-9971-4755-a26c-4b17851b609b.png)

**Comment by jjjoness** [comment] 2022-11-30 12:15
![image](https://user-images.githubusercontent.com/82226755/204793784-807e85a0-e109-4846-b57d-51b9efe11a7d.png)

**Closed** 2022-12-12 16:13 UTC
Labels: feature/editor, sig/content, status/active, priority/major, kind/task, feature/asset-browser

**Comment by rainbj** [comment] 2023-01-14 00:37
@jjjoness Hey I tested this today and this doesn't work in thumbnail view.

**Comment by jjjoness** [comment] 2023-01-16 09:51
@rainbj The thumbnail view was done by KDAB, I believe, and they didn't put that functionality in. I'm currently working on the Table View and as that uses the same folder code as thumbnail, I'll add Drag and Drop to both as I go along.
