### ISSUE TITLE
[macOS] O3DE app is missing default icon

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#6031] opened 2021-11-30 16:22 UTC
**Describe the bug**
Building some O3DE mac apps results in apps with generic icons, for example the o3de.app does not have an o3de icon.

**Steps to reproduce**
1. Build stabilization branch: stabilization/2110 ie `cmake --build build/mac/. --target Editor MultiplayerSample.GameLauncher --config profile` 
1. Examine app icons

**Expected behavior**
Icons default to `o3de logo` icon

**Actual behavior**
Apps have blank grey icons

**Assets required**

**Screenshots/Video**
![Screen Shot 2021-11-29 at 1 33 49 PM (2)](https://user-images.githubusercontent.com/61438964/144085762-b92371f2-7f1b-43f5-ac45-cde7ae9cacb2.png)

**Found in Branch**
stabilization/2110

**Desktop/Device (please complete the following information):**
 - Device: Mac
 - OS: macOS
 - Version: Big Sur
 - CPU: 2.5 GHz Dual-Core Intel Core i7
 - GPU: Intel Iris Plus Graphics 640 1536 MB

**Additional context**
"f there's a list of icons/icon files to use for the o3de app, it should be simple to fix. It would need something like this which we use for the Editor: https://github.com/aws-lumberyard-dev/o3de/tree/d57770293588ff21be39a1406a0db6d8cc8021d4/Code/Editor/Platform/Mac/Images.xcassets
AP has something similar too."

sig-network would own patching multiplayer sample (will clone this issue for that)

**Comment by RoddieKieley** [comment] 2022-01-07 11:20
@lmbr-pip I'll see if I can reproduce this here locally as I've got a mac here running macOS 11.1 Big Sur as indicated in the above description.

**Comment by RoddieKieley** [comment] 2022-01-14 16:47
@lmbr-pip Have attempted a macOS build a few times over the last week without much success. After an update to Xcode 12.5.1 last going off I was seeing:
`error: Build input file cannot be found: '/System/Volumes/Data/wip/src/github.com/o3de/o3de/build/mac/Code/Tools/AssetProcessor/AssetProcessor.Static_autogen/mocs_compilation.cpp' (in target 'AssetProcessor.Static' from project 'O3DE')                                  
                                                                                                                                                                                                                                                                             
** BUILD FAILED **`

By the time I check after a full failure the file does indeed exist, so not sure if it's either a filesystem mapping (/wip -> /System/Volumes/Data/wip) or case sensitivity or parallel execution issue so will see about resolving that first.

**Comment by RoddieKieley** [comment] 2022-01-22 03:34
After a number of investigations into deadends, it appears that the culprit to the above problem was that the /wip directory was mapped by necessity from /System/Volumes/Data/wip via the /etc/synthetic.conf file. My working dir was /wip, but switching to "working out of" /System/Volumes/Data/wip when building resolved the problem.

**Comment by RoddieKieley** [comment] 2022-01-22 15:06
Problem reproduced; Looks like the AssetProcessor and the Editor have the right configuration for both the main engine build:
![Screen Shot 2022-01-22 at 11 30 30 AM](https://user-images.githubusercontent.com/980979/150643937-b3d8b1cb-c7ff-48e3-906b-24051d999a04.png)

 and the project build at the moment:
![Screen Shot 2022-01-22 at 11 33 01 AM](https://user-images.githubusercontent.com/980979/150643959-fdae2772-7e18-4d94-806b-6c54ba66d26f.png)

but not the others Application's. Will see about fixing those up.

**Comment by RoddieKieley** [comment] 2022-01-22 18:59
Have a rough start made with the AssetBundler now utilizing the AssetProcessor icon for the moment:
![Screen Shot 2022-01-22 at 3 26 25 PM](https://user-images.githubusercontent.com/980979/150651803-4d492254-0472-483a-b3ef-0b1106145a01.png)
Ongoing work will be on my [issue6031](https://github.com/RoddieKieley/o3de/tree/issue6031) branch.

**Comment by RoddieKieley** [comment] 2022-01-24 01:50
Added GridHub, LuaIDE, and o3de - still need the game and server launchers as well as potentially the O3DEQtControlGallery and ReflectedPropertyEditoryStandalone Application's:
![Screen Shot 2022-01-23 at 6 15 53 PM](https://user-images.githubusercontent.com/980979/150709380-f9e12edd-c91f-47b0-9912-53ebba9be3aa.png)

**Comment by RoddieKieley** [comment] 2022-01-30 19:37
Added O3DEQtControlGallery, the ReflectedPropertyEditorStandalone and the ${Name}.GameLauncher via commits [9c97a61f8c6d25a1560db08292f995c9a830f1a6](https://github.com/RoddieKieley/o3de/commit/9c97a61f8c6d25a1560db08292f995c9a830f1a6) and [187ca978c664b0cdd7058bae6dd304a58f9eefd6](https://github.com/RoddieKieley/o3de/commit/187ca978c664b0cdd7058bae6dd304a58f9eefd6) to my [issue6031](https://github.com/RoddieKieley/o3de/tree/issue6031) branch respectively as shown below:
![Screen Shot 2022-01-30 at 3 54 13 PM](https://user-images.githubusercontent.com/980979/151714465-fae9fdf7-b9d1-4579-8aaa-1640cecfe78f.png)

Outside of the obviously missing ${Name}.ServerLauncher, the o3de project manager application bundle is also incorrect at the moment as per the above. During build of the ProjectManager target the following failure is observed:

> -- fixup_bundle
> --   app='/System/Volumes/Data/wip/Projects/NewProject/build/mac_xcode/bin/profile/o3de.app'
> --   libs='...'
> --   dirs='...'
> --   ignoreItems='Python;python3.7m;python3.7'
> -- warning: *NOT* handled - .app directory case...
> CMake Error at /opt/local/share/cmake-3.22/Modules/BundleUtilities.cmake:997 (message):
>   error: fixup_bundle: not a valid bundle
> Call Stack (most recent call first):
>   /System/Volumes/Data/wip/Projects/NewProject/build/mac_xcode/runtime_dependencies/profile/ProjectManager.cmake:290 (fixup_bundle)`

Not sure yet what the cause is, but the symptom is the failure and the end result that the *Qt* does not end up in the Contents/Framework directory.

Once the failure is addressed, and the ${Name}.ServerLauncher checked/completed will need to also test on Linux and Windows to ensure the changes haven't caused any problems there.

**Comment by RoddieKieley** [comment] 2022-01-30 20:52
Re: ServerLauncher see #6033 - looks like that would be a good next step after sorting the ProjectManager target issue above.

**Comment by RoddieKieley** [comment] 2022-02-10 20:24
As per [issue6031](https://github.com/RoddieKieley/o3de/tree/issue6031) commit [7bda7c6e3de3420b19f6c3718cfe21877c543c5f](https://github.com/RoddieKieley/o3de/commit/7bda7c6e3de3420b19f6c3718cfe21877c543c5f) the CFBundleExecutable in the plist was out of sync with the actual executable name. With this change, from a clean build, we now see that all app bundles have associated icons as required:
![Screen Shot 2022-02-10 at 4 39 26 PM](https://user-images.githubusercontent.com/980979/153490198-49739e28-8627-487f-b551-604a01261de3.png)

That being said there is some cleanup work required as likely unneeded Entitlements plist entries were added. Also need to test cross-platform, rebase to get up to speed, and squash prior to creating the PR.

**Comment by RoddieKieley** [comment] 2022-02-11 17:35
Entitlements now cleaned up leaving empty *Entitlement.plist files ready for the addition of actually required Entitlements separately as it is not clear that any are required for this work. The code built after being rebased on the latest development tip that was available at the time, and following up on Linux I needed to add two boilerplate files per project as per [729cafc7c811d8234481ae4a22336e9dc0a4d2c3](https://github.com/RoddieKieley/o3de/commit/729cafc7c811d8234481ae4a22336e9dc0a4d2c3)

Question - Is this a suitable solution for the moment to get this in, or would it be required to restructure so that this is not the case? If yes, I can update Windows and test then follow up iOS and Android however I don't have any restricted platforms to test against atm.

@byrcolin @lmbr-pip @amznestebanpapp Did either of you want to weigh in on the above prior to next steps? I'm envisioning next steps as above then squashing and PR for review.

**Closed** 2024-10-01 16:38 UTC
Labels: kind/bug, sig/platform, sig/ui-ux, triage/accepted, priority/minor
