### ISSUE TITLE
 AP compile assets report error

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#8942] opened 2022-04-15 01:23 UTC
The same asset name (different suffix) under Scanfolder cannot coexist, and an error is reported when compiling
![image](https://user-images.githubusercontent.com/97455291/163503001-76b73ab2-d772-4739-98dd-8c457fd94b6a.png)
![image](https://user-images.githubusercontent.com/97455291/163503077-c165362b-d1ba-4b11-9557-58dd2389983f.png)

**Comment by amzn-mike** [comment] 2022-04-15 13:57
Hi @macy12825, this is actually intentional behavior to alert the user of a problem.  Both gltf and fbx are scene file types processed by the same builder with the same outputs.  In this case, as indicated by the error message, cube123456_lod0_index.azbuffer is a file that is output by both of those inputs.  AP is reporting this as a failure since there can only be 1 file with that name at that path.  In this case the best thing to do is to rename one of the files to fix the conflict.

I'm marking this as closed since its working as intended.  Feel free to re-open if you disagree

**Closed by amzn-mike** 2022-04-15 13:57 UTC
Labels: kind/bug, needs-triage, sig/content
