### ISSUE TITLE
UI Editor Crashes the Engine completely

### ISSUE THREAD

**Issue by CStudios15** [o3de/o3de#2853] opened 2021-08-04 20:55 UTC
**Describe the bug**
Engine wont open unless using the rhi=vulkan argument, any attempt to open the UI editor bring up the window of the editor and then locked said window along with the engine and I have to end task thru Task manager.
reached out to @moudgils and stated: "This is probably a legit issue with how UI works within editor"

**To Reproduce**
1. run editor thru CLI with the RHI set to vulkan( -rhi=vulkan)
2. open UI editor

**Expected behavior**
UI editor opening without crashing

**Desktop/Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 
 - Version 10
 - CPU: Ryzen 3600x
 - GPU: GTX 770
 - Memory: 16GB

**Additional context**
Should mention that I am using an older GPU (GTX770) and cant open the engine regular without changing the rhi target this also limits me to only being to open the engine/project via CLI

**Comment by thefranke** [comment] 2021-08-05 09:34
I have reproduced the same issue on MacOS Big Sur (x64 on an M1). RHI is Metal.

**Comment by CStudios15** [comment] 2021-08-05 19:33
> I have reproduced the same issue on MacOS Big Sur (x64 on an M1). RHI is Metal.

So its not just me lol ok, thanks for confirming..ill just have to move my tutorial content around until this is fixed..

**Comment by michabr** [comment] 2021-08-12 16:56
Hi, could you clarify the issue? Description says: Engine wont open unless using the rhi=vulkan argument
but steps to repro say: change rhi=vulkan

**Comment by CStudios15** [comment] 2021-08-13 15:13
> Hi @CStudio15, could you clarify the issue? Description says: Engine wont open unless using the rhi=vulkan argument
> but steps to repro say: change rhi=vulkan

sorry about that I edited the OP hopefully that is more clear

**Comment by superkitcath** [comment] 2021-10-06 17:17
sig/content owns LyShine - reassigning to sig/content

**Comment by lawsonamzn** [comment] 2021-11-01 21:12
In case its useful, here's a call stack (on mac) for this crash
```
#0	0x000000016fd65a85 in AZ::Render::EsmShadowmapsPass::UpdateChildren() at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp:104
#1	0x000000016fd659f4 in AZ::Render::EsmShadowmapsPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp:96
#2	0x00000001840e24cb in AZ::RPI::Pass::FrameBegin(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp:1306
#3	0x00000001840e22ef in AZ::RPI::ParentPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp:289
#4	0x00000001840e24cb in AZ::RPI::Pass::FrameBegin(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp:1306
#5	0x00000001840e22ef in AZ::RPI::ParentPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp:289
#6	0x00000002644c19eb in AZ::RPI::Pass::FrameBegin(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp:1306
#7	0x00000002644c180f in AZ::RPI::ParentPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp:289
#8	0x000000026452db08 in AZ::RPI::SwapChainPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/SwapChainPass.cpp:138
#9	0x00000001840e24cb in AZ::RPI::Pass::FrameBegin(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp:1306
#10	0x00000001840e22ef in AZ::RPI::ParentPass::FrameBeginInternal(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp:289
#11	0x00000001840e24cb in AZ::RPI::Pass::FrameBegin(AZ::RPI::Pass::FramePrepareParams) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp:1306
#12	0x0000000184104ea4 in AZ::RPI::PassSystem::FrameUpdate(AZ::RHI::FrameGraphBuilder&) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp:316
#13	0x00000001845706fb in AZ::RPI::RPISystem::RenderTick()::$_2::operator()(AZ::RHI::FrameGraphBuilder&) const at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp:293
#14	0x00000001845706a2 in decltype(InvokeTraits::forward<AZ::RPI::RPISystem::RenderTick()::$_2&>(fp)(InvokeTraits::forward<AZ::RHI::FrameGraphBuilder&>(fp0))) AZStd::Internal::INVOKE<AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&>(AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&) at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/typetraits/invoke_traits.h:208
#15	0x0000000184570652 in AZStd::invoke_result<AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&>::type AZStd::invoke<AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&>(AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&) at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/function/invoke.h:38
#16	0x0000000184570602 in void AZStd::Internal::function_util::invoke_void_return_wrapper<void>::call<AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&>(AZ::RPI::RPISystem::RenderTick()::$_2&, AZ::RHI::FrameGraphBuilder&) at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/function/function_template.h:40
#17	0x0000000184570565 in void AZStd::Internal::function_util::get_invoker<void (AZ::RHI::FrameGraphBuilder&), AZStd::Internal::function_util::function_obj_tag, AZStd::allocator>::call<AZ::RPI::RPISystem::RenderTick()::$_2>(AZStd::Internal::function_util::function_buffer&, AZ::RHI::FrameGraphBuilder&) at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/function/function_template.h:171
#18	0x00000001846a7d2c in AZStd::function_intermediate<void, AZ::RHI::FrameGraphBuilder&>::operator()(AZ::RHI::FrameGraphBuilder&) const at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/function/function_template.h:603
#19	0x000000018468c2dd in AZStd::function<void (AZ::RHI::FrameGraphBuilder&)>::operator()(AZ::RHI::FrameGraphBuilder&) const at /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/std/function/function_template.h:683
#20	0x000000018468c163 in AZ::RHI::RHISystem::FrameUpdate(AZStd::function<void (AZ::RHI::FrameGraphBuilder&)>) at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp:198
#21	0x000000018452afd9 in AZ::RPI::RPISystem::RenderTick() at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp:288
#22	0x0000000183e2e33a in AZ::RPI::RPISystemComponent::OnSystemTick() at /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp:108
```

Note that this is the code that dies:
```
void EsmShadowmapsPass::UpdateChildren()
        {
            const RPI::PassAttachmentBinding& inputBinding = GetInputBinding(0);
            AZ_Assert(inputBinding.m_attachment->m_descriptor.m_type == RHI::AttachmentType::Image, "[EsmShadowmapsPass %s] input attachment requires an image attachment", GetPathName().GetCStr());
```

inputBinding.m_attachment is actually null:
```
inputBinding	const AZ::RPI::PassAttachmentBinding &	0x00007fbb336e5a90
m_name	AZ::Name	
m_view	AZStd::string_view	
m_begin	AZStd::basic_string_view<char, AZStd::char_traits<char> >::const_pointer	"DepthShadowmaps"	0x00007fbb2e213bd0
m_size	size_type	15
m_hash	AZ::Name::Hash	1259987661
m_data	AZStd::intrusive_ptr<AZ::Internal::NameData>	
m_shaderInputName	AZ::Name	
m_view	AZStd::string_view	
m_begin	AZStd::basic_string_view<char, AZStd::char_traits<char> >::const_pointer	"AutoBind"	0x00007fbb3d21a0a8
m_size	size_type	8
m_hash	AZ::Name::Hash	3918343893
m_data	AZStd::intrusive_ptr<AZ::Internal::NameData>	
m_shaderImageDimensionsNameIndex	AZ::RHI::ShaderInputNameIndex	
m_slotType	AZ::RPI::PassSlotType	Input
m_scopeAttachmentUsage	AZ::RHI::ScopeAttachmentUsage	Shader
m_unifiedScopeDesc	AZ::RHI::UnifiedScopeAttachmentDescriptor	
m_attachment	AZ::RPI::Ptr<AZ::RPI::PassAttachment>	
px	AZ::RPI::PassAttachment *	NULL	0x0000000000000000
m_originalAttachment	AZ::RPI::Ptr<AZ::RPI::PassAttachment>	
px	AZ::RPI::PassAttachment *	NULL	0x0000000000000000
m_connectedBinding	AZ::RPI::PassAttachmentBinding *	NULL	0x0000000000000000
m_name	AZ::Name	
m_view	AZStd::string_view	
m_begin	AZStd::basic_string_view<char, AZStd::char_traits<char> >::const_pointer	0x0	
m_size	size_type	
m_hash	AZ::Name::Hash	
m_data	AZStd::intrusive_ptr<AZ::Internal::NameData>	
m_shaderInputName	AZ::Name	
m_shaderImageDimensionsNameIndex	AZ::RHI::ShaderInputNameIndex	
m_slotType	AZ::RPI::PassSlotType	
m_scopeAttachmentUsage	AZ::RHI::ScopeAttachmentUsage	
m_unifiedScopeDesc	AZ::RHI::UnifiedScopeAttachmentDescriptor	
m_attachment	AZ::RPI::Ptr<AZ::RPI::PassAttachment>	
m_originalAttachment	AZ::RPI::Ptr<AZ::RPI::PassAttachment>	
m_connectedBinding	AZ::RPI::PassAttachmentBinding *	NULL	
m_fallbackBinding	AZ::RPI::PassAttachmentBinding *	NULL	
m_shaderInputIndex	int16_t	
m_shaderInputArrayIndex	uint16_t	
m_attachmentUsageIndex	uint8_t	
m_fallbackBinding	AZ::RPI::PassAttachmentBinding *	NULL	0x0000000000000000
m_shaderInputIndex	int16_t	-1
m_shaderInputArrayIndex	uint16_t	0
m_attachmentUsageIndex	uint8_t	'\0'
```

**Comment by jckand-amzn** [comment] 2021-11-05 17:06
I'm unable to reproduce this issue on stabilization/2110@fdc56b4a57f2f076b on a Windows machine.

**Comment by lawsonamzn** [comment] 2021-11-05 21:01
I guess I'll retest it on mac?

**Comment by AMZN-mnaumov** [comment] 2021-11-08 17:13
I have also tested on vulkan, it did not crash, I have not tested mac

**Comment by lawsonamzn** [comment] 2021-11-08 23:51
The latest version of the UI editor still crashes on mac with the same callstack as above.

**Comment by monroegm** [comment] 2021-11-15 17:44
I changed the milestone to Future Release as this appears to be a Mac-specific ticket now

**Comment by pjuneja760** [comment] 2022-02-12 17:58
Couldn't repro this issue on MacOS Monterey v12.2 with M1 chip. Picture attached below

```
# After compiling I ran the runEditor alias command below
EDITOR="/Users/parshaj/Desktop/amazon/o3de/build/mac/bin/debug/Editor.app/Contents/MacOS/Editor"
AUTOMATED_TESTING="/Users/parshaj/Desktop/amazon/o3de/AutomatedTesting"

alias runEditor="$EDITOR --project-path $AUTOMATED_TESTING"
```

Steps to reproduce
1. runEditor in command line
2. Open a prefab for editing.
3. Click on Tools.
4. Click on UI Editor in the dropdown
5. UI Editor opened without crashing.

Launch Editor from command line 
<img width="1436" alt="Screen Shot 2022-02-12 at 9 50 48 AM" src="https://user-images.githubusercontent.com/85369837/153722398-dc814d5f-4413-48f5-b7a6-5abefc84ad65.png">

**Comment by pjuneja760** [comment] 2022-02-15 01:08
Unable to reproduce this issue on Mac. Closing the issue

**Closed by pjuneja760** 2022-02-15 01:08 UTC
Labels: kind/bug, platform/macos, sig/content, triage/accepted, priority/critical, feature/lyshine
