### ISSUE TITLE
Detaching Prefab leaves a parent Entity in the detached Prefab's place

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#4143] opened 2021-09-15 10:58 UTC
**Describe the bug**
When a Detach Prefab... action is performed on a Prefab, it leaves a parent Entity in the place of the Prefab's "container", with its contents attached as children Entities.

**To Reproduce**
1. Create an Entity, right-click it and select Create Prefab... from the dropdown menu. Save it.
2. Right-click on the created Prefab and select Detach Prefab... from the dropdown menu.

**Expected behavior**
Only the original Entity is left.

**Video**

https://user-images.githubusercontent.com/86952082/133420096-ed77f912-14ef-4c05-b41d-785274116684.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment] 2021-09-21 18:52
This is because a parent is automatically created when creating a prefab

**Comment by LB-ArturSiewniak** [comment] 2021-09-22 07:30
The current behavior is unintuitive, as Detach Prefab seems to be the option to revert prefab back to entities it was made from, so it effectively adds one entity (parent) that is not present during the Prefab's creation.

**Comment by monroegm** [comment] 2022-03-01 03:32
Duplicate of #3748

**Closed by monroegm** 2022-03-01 03:32 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs
