### ISSUE TITLE
[Assert] Closing the Asset Browser after opening an unsupported format in it via File > Open Recent throws an assert

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3924] opened 2021-09-03 09:46 UTC
**Describe the bug**
It has been noticed that if an unsupported file is opened in the Asset Editor, then reopened again via File > Open Recent and the Asset Editor is closed it throws an assert. 

It should be noted that reopening the unsupported file via the File > Open Recent prints two [Error] messages to the console:
```
[Error] (AssetDatabase) - No handler was registered for this asset (id={3FD09945-D0F2-55C8-B9AF-B2FD421FE3BE}:0, type={00000000-0000-0000-0000-000000000000})!
[Error] (AssetManager) - BlockUntilLoadComplete must be called after an asset has been queued for load.  Asset  ({00000000-0000-0000-0000-000000000000}:0) is not queued for load
```
It should also be noted that this issue can be related to https://github.com/o3de/o3de/issues/3923.

**To Reproduce**
1. Go to the Asset Browser and search for the goegap_4k_iblglobalcm.exr file.
2. Right-click the asset and select Open in Asset Editor... from the dropdown menu.
3. Go to File > Open Recent and select the asset opened in step 1.
4. Close the Asset Editor.

**Expected behavior**
No assert is thrown.

**Video, assert, and Editor.log**
File:  
```
C:\Builds\o3de\Code\Framework\AzCore\AzCore/EBus/Internal/Handlers.h: (12504) '__cdecl AZ::Internal::MultiHandler<class AZ::Data::AssetEvents,class AZ::Data::AssetEvents,struct AZ::Internal::EBusContainer<class AZ::Data::AssetEvents,class AZ::Data::AssetEvents,1,1> >::~MultiHandler(void)'
EBus handlers must be disconnected prior to destruction on multi-threaded buses with virtual functions
```
Line: 343

![AssertPopUp](https://user-images.githubusercontent.com/86952082/131978508-2cf1cddf-f162-461e-95b3-a3ff6c6c1310.PNG)

https://user-images.githubusercontent.com/86952082/131978471-a3564d4d-e41f-4734-b1ae-a148e61738fd.mp4

[Editor.log](https://github.com/o3de/o3de/files/7104607/Editor.log)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by monroegm** [comment] 2021-09-09 18:50
Duplicate of #3923

**Closed** 2021-09-09 18:51 UTC
Labels: feature/editor, kind/bug, sig/content, triage/accepted, priority/major
