### ISSUE TITLE
Search is not working when clicking on the Help menus search bar's magnifying glass button.

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3de#8013] opened 2022-03-02 09:03 UTC
**Describe the bug**
Search is not working when clicking on the Help menu Search Bar's magnifying icon.

**Steps to reproduce**
1. Open the Editor.
2. Open the Help menu.
3. Type any text in the "Search Documentation" field.
4. Click the magnifying glass.

**Expected behavior**
https://www.o3de.org/docs webpage is opened with a search using the entered text.

**Actual behavior**
Button is not responding. Search is not executed.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952009/156328439-a4797ed9-35a9-4934-af2f-bcf35355a80a.mp4

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/0ab9aa5d02aeb3f40bbd2c65f21e27c4f451a4a2)

**Desktop/Device (please complete the following information):**

- Device: PC
- OS: Windows
- Version 10
- CPU Intel Core i5-9600k
- GPU Nvidia GeForce RTX 2060
- Memory 16GB

**Comment by AMZN-daimini** [comment] 2022-06-07 01:51
This is by design. As signified by the cursor not changing, the magnifying glass in the field is merely a decoration and not a button.

Tagging UX to double check whether this should be reconsidered or can just be closed.
@o3de/sig-ui-ux @yuyihsu

**Comment by amzn-leenguy** [comment] 2022-07-05 23:56
Hello @LB-BartoszDudzinski . Thank you for creating this ticket. UX appreciates it. @AMZN-daimini is correct. This is by design. 

Closing the thread.

**Closed by amzn-leenguy** 2022-07-05 23:56 UTC
Labels: kind/bug, needs-triage, sig/ui-ux, priority/minor
