### ISSUE TITLE
Prefab with collapsed entities doesn't have a bottom border in some cases

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#5219] opened 2021-11-02 19:24 UTC
**Describe the bug**
If a prefab has 2 entities, one of which is parent and the other is child, upon entering focus mode, the prefab won't have a bottom border

**Steps to reproduce**
1. Create a prefab as shown below
![After_expanding_entity](https://user-images.githubusercontent.com/82230713/139930650-3985a3a7-379e-4a33-a947-402bd4c13a81.PNG)

2. Close level and open again
3. Focus on the prefab by double clicking on it or using the edit icon next to it.

**Expected behavior**
The prefab has a bottom border

**Actual behavior**
You will see this:
![Before_expanding_entity](https://user-images.githubusercontent.com/82230713/139932844-7de844e9-342a-4fa4-b266-1ee2e033191b.PNG)

**Found in Branch**
stabilization/2110

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by AMZN-daimini** [comment] 2022-09-08 18:47
Closing as duplicate of #11738

**Closed by AMZN-daimini** 2022-09-08 18:47 UTC
Labels: feature/editor, kind/bug, sig/content, sig/ui-ux, triage/accepted, priority/minor
