### ISSUE TITLE
Performance drop during level loading and duplicating several large prefabs in the 10KEntityCpuPerfTest level

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#14207] opened 2023-01-25 10:02 UTC
**Describe the bug**
Loading time has increased significantly during level loading and duplicating several large prefabs in the 10KEntityCpuPerfTest level from the AutomatedTesting project. Values went up from around 22 seconds to around 58 seconds in the case of loading the level and from around 27 seconds to around 53 seconds in the case of duplication of several large prefabs.

The issue was first time observed on 01/20/2023.

**Steps to reproduce**
1. Set up the AutomatedTesting project.
2. Open the 10KEntityCpuPerfTest level and observe the loading time.
3. Select all of the AtomCubeWall prefabs in the Entity Outliner, and duplicate them.

**Expected behavior**
Loading time is similar to the previous values.

**Actual behavior**
Loading time has increased significantly.

**Video**

https://user-images.githubusercontent.com/96232062/214529219-2cd73ad1-023f-4589-a679-4fc5d512301c.mp4

https://user-images.githubusercontent.com/96232062/214529227-ebff2b7e-e2b0-45d2-a522-d1602c113a79.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(https://github.com/o3de/o3de/commit/fc57a9a46f3b869609874887cc0a4bde2bd01b73)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen 5 3600
 - GPU: NVIDIA GeForce RTX 2060 SUPER
 - Memory: 16GB

**Comment by jckand-amzn** [comment] 2023-01-25 15:47
@monroegm There have not been any Prefab-related check-ins that should have caused this performance regression, however can we investigate and route to the appropriate place?

NOTE: I'm unable to reproduce these extended load times locally, so may be due to specific hardware.

**Comment by lawsonamzn** [comment] 2023-01-25 16:04
Interesting.  Will have to load this up in a profiler and check.  Last time we looked at this level in particular it was more to do with the material instancing than the prefabs.

**Comment by LB-HubertUberman** [comment] 2023-02-02 11:25
The issue verified as fixed on build Development ([e12b937](https://github.com/o3de/o3de/commit/e12b9375f881ae3b8b8485d3919ce77e64a70209)).

**Comment by jckand-amzn** [comment] 2023-02-02 16:00
Fixed by https://github.com/o3de/o3de/pull/14227.

**Closed by jckand-amzn** 2023-02-02 16:00 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs
