### ISSUE TITLE
[Android] AutomatedTesting.GameLauncher crashes silently upon launching

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#9161] opened 2022-04-25 13:27 UTC
**Describe the bug**
Launching the AutomatedTesting.GameLauncher deployed to a device built for Android silently crashes upon launching.
Note that the same issue has been observed for the following levels:
`LoadLevel prefabs/default_level.spawnable`
`LoadLevel levels/graphics/hermanubis_high/hermanubis_high.spawnable`
`levels/nvcloth/nvcloth_addclothsimulationtomesh/nvcloth_addclothsimulationtomesh.spawnable`

Please refer to the attached video and logs for more information.

**Prerequisites**
- AutomatedTesting project is built for Windows.
- Assets for the Android platform are enabled and processed.
- An autoexec.cfg file has been created inside the _/o3de/AutomatedTesting_ directory containing:
`LoadLevel prefabs/default_level.spawnable`
- All the required environment variables are set as described in the instructions: https://o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/

In this test the following settings have been used:

```
SET O3DE_ENGINE_PATH=C:\o3de
SET O3DE_PROJECT_PATH=C:\o3de\AutomatedTesting
SET O3DE_BUILD_ROOT=C:\o3de-build
```
```
SET O3DE_ANDROID_SIGNCONFIG_FILE=%O3DE_BUILD_ROOT%\o3de.keystore
SET O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS=o3de_key
SET O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD=o3de_android
SET O3DE_ANDROID_SIGNCONFIG_KEY_SIZE=2048
SET O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS=10000
SET O3DE_ANDROID_DN="cn=AutomatedTesting, ou=o3de, o=LF, c=US"
```
```
set O3DE_ANDROID_SDK_PATH=C:\Android\Sdk
set O3DE_ANDROID_NDK_VERSION=22.1.7171670
set O3DE_ANDROID_SDK_API_LEVEL=30
set O3DE_ANDROID_ASSET_MODE=LOOSE
set O3DE_ANDROID_DEPLOY_TYPE=BOTH
```

**Steps to reproduce**
1. Generate KeyStore to allow APK signing:
`keytool -genkey -keystore %O3DE_ANDROID_SIGNCONFIG_FILE% -storepass %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% -alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% -keypass %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD% -keyalg RSA -keysize %O3DE_ANDROID_SIGNCONFIG_KEY_SIZE% -validity %O3DE_ANDROID_SIGNCONFIG_VALIDITY_DAYS% -dname %O3DE_ANDROID_DN%`
2. Use Python to run generate_android_project.py:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\generate_android_project.py --engine-root %O3DE_ENGINE_PATH% --project-path %O3DE_PROJECT_PATH% --build-dir %O3DE_BUILD_ROOT%\android --third-party-path %USERPROFILE%\.o3de\3rdParty --android-sdk-path %O3DE_ANDROID_SDK_PATH% --android-ndk-version %O3DE_ANDROID_NDK_VERSION% --android-sdk-platform %O3DE_ANDROID_SDK_API_LEVEL% --include-apk-assets --asset-mode %O3DE_ANDROID_ASSET_MODE% --signconfig-store-file %O3DE_ANDROID_SIGNCONFIG_FILE% --signconfig-store-password %O3DE_ANDROID_SIGNCONFIG_STORE_PASSWORD% --signconfig-key-alias %O3DE_ANDROID_SIGNCONFIG_KEY_ALIAS% --signconfig-key-password %O3DE_ANDROID_SIGNCONFIG_KEY_PASSWORD%`
3. Build the Android project:
`cd %O3DE_BUILD_ROOT%\android`
`gradlew assembleProfile`
4. Deploy the GameLauncher to the Android device:
`%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\deploy_android.py --build-dir %O3DE_BUILD_ROOT%\android --configuration profile --clean -t %O3DE_ANDROID_DEPLOY_TYPE%`
5. Launch the deployed GameLauncher.

**Expected behavior**
The deployed GameLauncher launches without issues.

**Actual behavior**
The deployed GameLauncher crashes silently upon launching.

**Video**

https://user-images.githubusercontent.com/86953659/165095788-ecf2c3c5-c160-434b-8221-1ea870983d62.mp4

**Found in Branch**
Stabilization_2205 (fa43be1)

**Device**
 - Device: Samsung S20+
 - OS: Android
 - Version 11 (API 30)

**Additional context**
[adb_logcat_AutomatedTesting.txt](https://github.com/o3de/o3de/files/8554809/adb_logcat_AutomatedTesting.txt)

**Comment by LB-KacperKapusta** [comment] 2022-04-27 13:47
It has been reverified using Stabilization_2205 (c8f1489) that the crash does still occur when attempting to run any of the mentioned levels on an Android device.

https://user-images.githubusercontent.com/86953659/165527542-38aed169-4249-4116-87b7-7418f30aff9d.mp4

Please refer to the attached log for more information.
[adb_logcat_AutomatedTesting_2.txt](https://github.com/o3de/o3de/files/8572350/adb_logcat_AutomatedTesting_2.txt)
Reopening the issue.

**Comment by amzn-sj** [comment] 2022-04-28 05:01
I'm unable to reproduce the crash on Google Pixel 5 or Samsung S21.

**Comment by LB-KacperSzczepanski** [comment] 2022-04-29 10:22
It has been verified using Stabilization_2205 (c8f1489) the crash did not occur but instead the app enters unresponsive state. This behavior is the same for all aforementioned levels.

https://user-images.githubusercontent.com/86953282/165926888-dd59519f-e86a-452a-94fc-208c7f21b0d8.mp4

Please refer to the attached log for more information.
[adp_logcat_AutomatedTesting_3.txt](https://github.com/o3de/o3de/files/8590046/adp_logcat_AutomatedTesting_3.txt)

**Device**

- Device: Google Pixel 6
- OS: Android
- Version 12 (API 31)

**Comment by tonybalandiuk** [comment] 2022-04-29 20:37
- [ ] 1. Colin - Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.	 Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 3.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	If all approvals are accepted exception PR is merged
- [ ] 6.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 7.	Exception is complete
- [

**Comment by amzn-sj** [comment] 2022-05-03 17:00
Fixed here: https://github.com/o3de/o3de/pull/9311

**Closed by amzn-sj** 2022-05-03 17:00 UTC
Labels: kind/bug, needs-triage, platform/android, sig/platform, priority/blocker

**Comment by LB-KacperKapusta** [comment] 2022-05-04 15:57
It has been reverified using Stabilization_2205 (3f37ff7) build that the issue does no longer occur for Samsung 20+ and the app launches loading levels properly.

**Comment by LB-KacperSzczepanski** [comment] 2022-05-05 10:11
It has been reverified using Stabilization_2205 (https://github.com/o3de/o3de/commit/3f37ff799f8d1aae5c328fc395acf86326980bb0) build that the issue does no longer occur for Google Pixel 6 and the app launches loading level properly.
