### ISSUE TITLE
Bug Report: Material Editor Crash

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#14220] opened 2023-01-26 07:17 UTC
**Describe the bug**
The Material Editor crashes when there is Material Canvas materials in the root directory when the Material Editor opens.

**Steps to reproduce**
1. Open the Material Canvas and create a new graph, save this graph to the root folder which is open when you open the Material Editor (opening the material editor for me opens the folders projects/project/Assets/MaterialHere)
2. Save the material graph and compile the material/shaders.
3. Open the Material Editor and once opened and trying to load the material thumbnails it should crash.

**Expected behavior**
Having Material Canvas materials saved in the root folder should not effect the Material Editor.

**Actual behavior**
Having Material Canvas materials saved in the root folder crashes the Material Editor.

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
fc57a9a46f3b869609874887cc0a4bde2bd01b73

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**

**Comment by gadams3** [comment] 2023-02-09 05:10
I am unable to reproduce this issue using the automated testing project. Could you please provide more information about the kind of material graph and material you created, if there were any textures involved, etc? Creating a new standard PBR graph in the default project assets folder and opening the generated material worked when tested. Opening other test materials also worked correctly. The issue could have been caused by the thumbnail system or something in the renderer that may have been fixed since reported. I'm closing the issue as unable to reproduce but if it reoccurs please reopen it and attach the materialeditor.log file as well as any videos or screenshots if possible.

**Closed by gadams3** 2023-02-09 05:10 UTC
Labels: kind/bug, sig/graphics-audio, priority/major

**Comment by ParasiteSt** [comment] 2023-03-06 09:25
![image](https://user-images.githubusercontent.com/100494538/223069215-a218b79d-3ede-42a7-8857-7e6cdf293ee7.png)
@gadams3 is it possible to just close all folders in the Asset Browser in the Material Editor? I know for sure that this crash is related to the thumbnails being generated in the Asset Browser. Fixes for the thumbnail generation was made for other parts of the engine, but the Material Canvas is the only thing left that crashes when generating thumbnails.

**Comment by ParasiteSt** [comment] 2023-03-06 09:26
Closing the folders does not stop the crash, but it does allow me to get back into the material editor and create/open materials and work on them, and just not use the Asset Browser inside of the material editor.
