### ISSUE TITLE
Changes made to any texture asset in the Material Property Inspector are reverted when creating a new entity

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#6286] opened 2021-12-09 14:33 UTC
**Describe the bug**
Creating a new entity results in the changes made to any texture asset in the Material Property Inspector to be reverted.

This issue also occurs in the O3DE Stable 21.11 Release build.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Create a new level.
2. Select the Ground entity.
3. Press on the preview of the Material inside the Material component.
4. Select 'Edit Material Instance...'.
5. Change the value of any 'Texture' field and save the Material.
6. Create a new entity.

**Expected behavior**
Creating a new entity results in the changes made to any texture asset in the Material Property Inspector to be reverted.

**Actual behavior**
Creating a new entity does not revert any changes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/145413304-8c043ab9-56bd-410f-848b-c5a62e8395aa.mp4

**Found in Branch**
Stabilization/2111RTE (667512c)

**Desktop/Device**
Device: PC
OS: Windows
Version: 10
CPU: Intel i5-9600K
GPU: RTX 2070
Memory: 16GB

**Comment by yuyihsu** [comment] 2021-12-09 21:07
@gadams3 @LB-KacperKapusta   I'm not sure the scope of this issue. can you verify if this issue applies to all the textures user created before? or only for this specific use case? Also, if I reassign the texture I just created again, and then add another entity, will the re-assigned texture be reset to the default one again?

**Comment by yuyihsu** [comment] 2021-12-09 21:10
I will put this in RTE M2 scope to keep track of the status. we can remove it from the M2 scope if @gadams3  can confirm the scope of this issue is limited to just this case, and that user can easily fix the problem by reassigning the texture.

**Comment by Broganab** [comment] 2021-12-09 23:02
@yuyihsu Testing on Stabilization/2111RTE, if I duplicate ShaderBall so I have three to work with. I delete or change the texture for all three ShaderBalls and the Ground then create a new entity or duplicate one, all of the texture assets revert. They continue to revert to the default texture no matter how many changes I make prior to creating a new entity.

**Comment by yuyihsu** [comment] 2021-12-10 02:26
Thanks @Broganab. @gadams3 based on @Broganab ‘s finding, I’ll keep this ticket in RTE-M2.

**Comment by LB-KacperKapusta** [comment] 2021-12-10 09:56
It has been verified that all of the changes made to texture fields from the Material Property Inspector are reverted upon creating/duplicating an entity, no matter how many of the textures are reassigned prior to that. Only the material's textures settings are affected by the issue (but it does not seem to be affecting a specific material, rather all of them). Project used for the test is a newly created one using the Standard template from the Project Manager built with Pre-built SDK engine instructions.

Please note that for the same project with the Prefabs system disabled the issue does not occur and no changes are reverted when creating/duplicating entities.

**Comment by gadams3** [comment] 2021-12-12 18:26
This issue actually appears to be caused by something related to prefabs and patching. It is being investigated by the pre fab team. I have posted a PR that will address the issue specifically for this case. If approved, that PR will act as a fall back if the underlying prefab issue cannot be fixed in time for the next release.

**Comment by NicholasVanSickle** [comment] 2021-12-14 18:51
Fix merged! This should no longer occur in `stabilization/2111RTE`

**Closed by NicholasVanSickle** 2021-12-14 18:51 UTC
Labels: kind/bug, sig/graphics-audio, priority/critical, WF5

**Comment by LB-KacperKapusta** [comment] 2021-12-16 11:08
Verified as fixed on Stabilization/2111RTE (fb36145) branch.

However, it has been observed that after modifying the settings inside the Material Property Inspector, creating. deleting or duplicating an entity results in the original material being displayed for a brief moment, which can be easily seen when rapidly duplicating entities. Should the issue be reopened based on that or a separate one logged?

https://user-images.githubusercontent.com/86953659/146360654-e94d722e-473b-48ea-93ec-15519284eb09.mp4
