### ISSUE TITLE
AR Bug Report - Test test_Multiplayer_AutoComponent_NetworkInput Failed

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#9248] opened 2022-04-28 17:38 UTC
**Describe the bug**

`test_Multiplayer_AutoComponent_NetworkInput` failed while running AR

**Failed Jenkins Job Information:**

Platform/Job: Linux - test_profile_nounity

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8131/5/pipeline/637

```
[2022-04-28T14:46:50.582Z] ../../../../../../AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py::TestAutomation::test_Multiplayer_AutoComponent_NetworkInput[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] FAILED [ 25%]
[2022-04-28T14:46:50.582Z] ../../../../../../AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py::TestAutomation::test_Multiplayer_AutoComponent_RPC[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] PASSED [ 50%]
[2022-04-28T14:46:50.582Z] ../../../../../../AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py::TestAutomation::test_Multiplayer_BasicConnectivity_Connects[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] PASSED [ 75%]
[2022-04-28T14:46:50.582Z] ../../../../../../AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py::TestAutomation::test_Multiplayer_SimpleNetworkLevelEntity[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] PASSED [100%]

[2022-04-28T14:46:50.582Z] =================================== FAILURES ===================================
[2022-04-28T14:46:50.582Z] _ TestAutomation.test_Multiplayer_AutoComponent_NetworkInput[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] _
[2022-04-28T14:46:50.582Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:440: in single_run
[2022-04-28T14:46:50.582Z]     self._run_single_test(request, workspace, editor, editor_test_data, test_spec)
[2022-04-28T14:46:50.582Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:1007: in _run_single_test
[2022-04-28T14:46:50.582Z]     self._report_result(test_name, test_result)
[2022-04-28T14:46:50.582Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:756: in _report_result
[2022-04-28T14:46:50.582Z]     pytest.fail(error_str)
[2022-04-28T14:46:50.582Z] E   Failed: Test test_Multiplayer_AutoComponent_NetworkInput:
[2022-04-28T14:46:50.582Z] E   Test FAILED
[2022-04-28T14:46:50.582Z] E   ------------
[2022-04-28T14:46:50.582Z] E   |  Output  |
[2022-04-28T14:46:50.582Z] E   ------------
[2022-04-28T14:46:50.582Z] E   Starting test Multiplayer_AutoComponent_NetworkInput...
[2022-04-28T14:46:50.582Z] E   Test Multiplayer_AutoComponent_NetworkInput finished.
[2022-04-28T14:46:50.582Z] E   Report:
[2022-04-28T14:46:50.582Z] E   [SUCCESS] Success: Unexpected line not found: LaunchEditorServer failed! The ServerLauncher binary is missing!
[2022-04-28T14:46:50.582Z] E   [SUCCESS] Success: Found expected line: Editor has connected to the editor-server.
[2022-04-28T14:46:50.582Z] E   [SUCCESS] Success: Found expected line: Editor is sending the editor-server the level data packet.
[2022-04-28T14:46:50.582Z] E   [SUCCESS] Success: Found expected line: Logger: Editor Server completed receiving the editor's level assets, responding to Editor...
[2022-04-28T14:46:50.582Z] E   [SUCCESS] Success: Found expected line: Editor-server ready. Editor has successfully connected to the editor-server's network simulation.
[2022-04-28T14:46:50.582Z] E   [FAILED ] Failure: Failed to enter game mode
[2022-04-28T14:46:50.582Z] E   EXCEPTION raised:
[2022-04-28T14:46:50.582Z] E     Traceback (most recent call last):
[2022-04-28T14:46:50.582Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
[2022-04-28T14:46:50.582Z] E         test_function()
[2022-04-28T14:46:50.582Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py", line 57, in Multiplayer_AutoComponent_NetworkInput
[2022-04-28T14:46:50.582Z] E         helper.multiplayer_enter_game_mode(Tests.enter_game_mode)
[2022-04-28T14:46:50.582Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 183, in multiplayer_enter_game_mode
[2022-04-28T14:46:50.582Z] E         Report.critical_result(msgtuple_success_fail, multiplayer.PythonEditorFuncs_is_in_game_mode())
[2022-04-28T14:46:50.582Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 410, in critical_result
[2022-04-28T14:46:50.582Z] E         TestHelper.fail_fast(fast_fail_message)
[2022-04-28T14:46:50.582Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 213, in fail_fast
[2022-04-28T14:46:50.582Z] E         raise FailFast()
[2022-04-28T14:46:50.582Z] E     editor_python_test_tools.utils.FailFast
[2022-04-28T14:46:50.582Z] E   Test result:  FAILURE
```

**Attachments**

[log.txt](https://github.com/o3de/o3de/files/8585106/log.txt)

**Comment by lmbr-pip** [comment] 2022-05-05 17:39
Close as duplicate of https://github.com/o3de/o3de/issues/9105

**Closed by lmbr-pip** 2022-05-05 17:39 UTC
Labels: feature/networking, kind/bug, needs-triage, sig/network, priority/critical, kind/automation
