### ISSUE TITLE
Feature Request-Add support of array-type shader variable configuration in material system

### ISSUE THREAD

**Issue by yanjin-rose** [o3de/o3de#5688] opened 2021-11-17 01:42 UTC
Currently, the material type file do not support array-type shader variable configuration when the connected shader file contains someting like (Texture2D m_textureArray[16], float m_num[16] ) in  material SRG.
Sometimes it's important to define array-type variables in shader. so it may be necessary to support it in material system too.
I was wondering that is there any plan to support this feature?

**Comment by santorac** [comment] 2021-11-17 19:13
@invertednormal was also asking for this recently while working on a terrain feature.

**Comment by wintermute-motherbrain** [comment] 2021-12-15 18:23
This is a duplicate of https://github.com/o3de/o3de/issues/5753

**Closed by wintermute-motherbrain** 2021-12-15 18:23 UTC
Labels: feature/graphics, sig/graphics-audio
