### ISSUE TITLE
[MultiplayerSample]Client can not connect to Server after disconnect

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#8862] opened 2022-04-12 01:18 UTC
**Describe the bug**
MultiplayerSample project. Client can not connect to Server after disconnect.

**Steps to reproduce**
1. Run MultiplayerSample.ServerLauncher.exe process
2. Run MultiplayerSample.GameLauncher.exe process as player A, player A can connect to server 
3. Run another MultiplayerSample.GameLauncher.exe process as player B, player B can connect to server
4. Open console window on player B, execute 'disconnect' and 'unloadlevel' command by sequence, player B can leave game
5. Then execute 'connect' command in console window on player B, but player B can not connect to server again

**Expected behavior**
Client can connect to Server after disconnect

**Found in Branch**
Branch: development

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel i7-10700]
 - GPU [HD630]
 - Memory [32GB]

**Additional context**

**Comment by junbo75** [comment] 2022-04-12 20:14
I was able to repro this issue locally. Attached are the client and server side logs.
[Server - Copy.log](https://github.com/o3de/o3de/files/8476243/Server.-.Copy.log)
[Game - Copy.log](https://github.com/o3de/o3de/files/8476245/Game.-.Copy.log)
[Game(1) - Copy.log](https://github.com/o3de/o3de/files/8476248/Game.1.-.Copy.log)

**Comment by junbo75** [comment] 2022-04-12 20:52
Note that I can get a different type of errors when test this issue with the following steps:
1. Run MultiplayerSample.ServerLauncher.exe process
2. Run MultiplayerSample.GameLauncher.exe process as player A and connect to the server
3. Open console window on player A, execute 'disconnect' and 'unloadlevel' command by sequence, player A can leave game
4. Then execute 'connect' command in console window on player A, but player A can not connect to server again

Client and server log attached.
[Server - Copy (2).log](https://github.com/o3de/o3de/files/8476479/Server.-.Copy.2.log)
[Game(2) - Copy.log](https://github.com/o3de/o3de/files/8476481/Game.2.-.Copy.log)

**Comment by lmbr-pip** [comment] 2022-04-14 17:41
Second reported issue with final player leaving is by design.

**Comment by lmbr-pip** [comment] 2022-04-14 17:42
Accepted as major, could raise to critical based on investigation

**Comment by junbo75** [comment] 2022-04-19 21:57
The fix for this issue has been merged into the stabilization branch.

**Closed** 2022-07-20 00:51 UTC
Labels: kind/bug, sig/network, sig/ui-ux, triage/accepted, priority/major
