### ISSUE TITLE
Need to manually force spawnables to reprocess when source prefabs change

### ISSUE THREAD

**Issue by greerdv** [o3de/o3de#2654] opened 2021-07-30 16:18 UTC
**Describe the bug**
A few times when pulling updates to prefabs, it was necessary to delete the spawnable from the cache folder to force the asset to be reprocessed before updates would take effect.

**To Reproduce**
1. Update a prefab on disk, for example by pulling an updated version from git
2. The updates do not always take effect and the modification date in the cache may indicate that the asset has not been reprocessed.

**Expected behavior**
Assets should automatically reprocess when the source changes.

**Comment by monroegm** [comment] 2022-02-28 23:35
Duplicate of #2325

**Closed** 2022-02-28 23:36 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/prefabs
