### ISSUE TITLE
Prefab: Spawner component can't use prefab file

### ISSUE THREAD

**Issue by Bond-F** [o3de/o3de#5694] opened 2021-11-17 08:01 UTC
**Describe the bug**
In Prefab project , the Spawner component can not use prefab file , only select Dynamic slice file.

**Steps to reproduce**
1. Create new entity.
2. Add Spawner component to it.
3. In Spawner component Properties , only select Dynamic slice file.

**Expected behavior**
Can select prefab file.

**Actual behavior**
Can not use prefab file , only select Dynamic slice file.

**Screenshots/Video**
![2021-11-17_160031](https://user-images.githubusercontent.com/94030027/142159574-64dbfde2-bd5d-4586-b248-bb1d85c7fe80.jpg)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-10700
 - GPU Intel UHD Graphics 630
 - Memory 32GB

**Comment by AMZN-koppersr** [comment] 2021-11-17 18:25
This is somewhat by design because the Spawner component was typically used as a way to provide a way for scripts to spawn entities in the world. There's now a dedicated node for that in Script Canvas, though a solution for general scripting (Lua) still needs to be build. With that main use case done differently there's an open question what other uses a "Spawner Component" would have. If you (or any other reader) see any use cases beyond spawning from script or what can now be done through the new Spawnable Entity Aliases, please note them on this ticket.

**Comment by Bond-F** [comment] 2021-11-18 07:33
Hi @AMZN-koppersr , i found this #2698 , does that mean that it will be deleted in later releases?
And  a dedicated node mean this?
![2021-11-18_153149](https://user-images.githubusercontent.com/94030027/142371776-be1afb04-01eb-40e3-ae01-83905bcfcbfa.jpg)

**Comment by AMZN-koppersr** [comment] 2021-12-03 23:01
Sorry for the late reply.
The node you have there is the Script Canvas node that's specifically made for spawnables I believe, so that one should remain. It is an area that could use some love though, but works for simply spawning everything in a spawnable.

**Comment by monroegm** [comment] 2022-03-01 18:47
Duplicate of #2698

**Closed by monroegm** 2022-03-01 18:47 UTC
Labels: kind/bug, release-note, sig/content, triage/accepted, priority/major, feature/prefabs
