### ISSUE TITLE
Component Edit Mode: Reset is skipped for undo and redo actions

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#3900] opened 2021-09-02 14:59 UTC
[Migrated from JIRA LYN-1381]
It has been observed that not all User's actions might be affected by undoing or redoing. The Reset action is skipped if the User uses undo or redo in the component's Edit Mode.

Please refer to the attached video for more information.
----
*Found in Build*: SpectraMainline-0.0-1099982-cmake_win_consoles_all-0

*Reproducibility*: 3/3

*Steps to Reproduce*: 
 # Create a new entity with PhysX Collider component.
 # Enter the Edit Mode via "Edit" button in Entity Inspector.
 # Switch to Offset Mode by Pressing "2" on keyboard or using Ctrl+MouseWheel.
 # Change offset of the collider two times.
 # Press "R" on keyboard.
 # Use Ctrl+Z and Ctrl+Shift+Z.

*Expected Result*: 

Reset action is recognized while using Undo or Redo.

*Actual Result*: 

Reset action is skipped while using Undo or Redo.

*GHI:*https://github.com/o3de/o3de/issues/3602

**Comment by hultonha** [comment] 2021-09-30 09:21
This is a duplicate of https://github.com/o3de/o3de/issues/3602 - closing

**Closed by hultonha** 2021-09-30 09:21 UTC
Labels: feature/physics, kind/bug, sig/content, sig/core, status/backlog, triage/accepted, priority/major, feature/viewport, WF2, RTE
