### ISSUE TITLE
Game process crash when switch to a new level

### ISSUE THREAD

**Issue by xiapeng78** [o3de/o3de#6595] opened 2021-12-30 02:38 UTC
**Describe the bug**
We open game process and enter the initial level A first. In this level, we do some operations and switch to a new level B, in this moment game process crash.
The game process is running on Linux, and level A has almost one thousand entities.

**Problem analysis**
We found process crash because it destroy one Entity which entity id is 0 in GameEntityContextComponent::DestroyGameEntityInternal() function. That is is impossible, we known that game Entity's id will never set to 0, and 0 is SystemEntity.
So we continuously analysis, and finally find the reason.
Game Entities object already released, the call procedure shows here:
```
    void SpawnableLevelSystem::UnloadLevel()
    void GameEntityContextComponent::ResetGameContext()
    void EntityContext::ResetContext()
    void SliceGameEntityOwnershipService::Reset()
    void SliceEntityOwnershipService::Reset()
    bool SliceEntityOwnershipService::DestroyEntity(AZ::Entity* entity)
    bool SliceComponent::RemoveEntity(Entity* entity, bool isDeleteEntity, bool isRemoveEmptyInstance)
    bool SliceComponent::RemoveEntity(EntityId entityId, bool isDeleteEntity, bool isRemoveEmptyInstance)
            AZStd::unique_ptr<AZ::Entity> entityToDelete(isDeleteEntity ? *entityIt : nullptr);
            return true;  **<======= Entity object release here**

```
In Entity object release procedure, some memory will modify by memory allocator.

The next procedure, visits the Entity object that already released. One entity id was set to 0, and causes crash problem.
Code shows here:
```
    auto SpawnableEntitiesManager::ProcessRequest(DestroyTicketCommand& request) -> CommandResult
    {
            for (AZ::Entity* entity : request.m_ticket->m_spawnedEntities) **<======= m_spawnedEntities is still valid**
            {
                if (entity != nullptr) **<========entity address point to the object already released**
                {
                    // Setting it to 0 is needed to avoid the infiniteloop between GameEntityContext and SpawnableEntitiesManager.
                    entity->SetSpawnTicketId(0);
                    GameEntityContextRequestBus::Broadcast(
                        &GameEntityContextRequestBus::Events::DestroyGameEntity, entity->GetId());
                }
                else
                {
                    // Entities without components wouldn't have been send to the GameEntityContext.
                    delete entity;
                }
            }
```

**Comment by xiapeng78** [comment] 2022-02-22 06:13
Hi, do you have any progress with this issue?

**Comment by srikappa-amzn** [comment] 2022-04-12 16:55
Debugged into this a bit. It looks like both the SliceEntityOwnershipService and SpawnableEntitiesManager are trying to destroy all the entities when switching levels. The fact that it crashes when EntityId is 0 (corresponds to SystemEntity) exposes this problem. The quick thing would be to just an (id !=0) check in GameEntityContextComponent::DestroyEntityInternal(). But that won't fix the underlying problem of 2 systems trying to delete the same set of entities. I'm surprised why this didn't resurface till now....probably because there aren't many workflows that tries to clear and reload game levels. Further debugging is needed here to mitigate the double delete problem

**Comment by srikappa-amzn** [comment] 2022-04-12 16:58
Steps to reproduce:
1. Build and run the GameLauncher of your project (something like 'AutomatedTesting.GameLauncher'
2. Hit '~' character. In the console that comes up, enter `loadLevel Levels/abc/abc.spawnable` (where abc is the name of your level)

**Comment by michabr** [comment] 2022-04-25 17:27
Duplicate of #8696.

**Closed** 2022-04-25 17:33 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
