### ISSUE TITLE
Console spam locks the perspective camera.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#2001] opened 2021-07-08 21:57 UTC
**Describe the bug**
If you continuously press the ` key to open and close the console your perspective camera will become unresponsive until you restart you project.
**To Reproduce**
1. Go to 'any level in the editor'
2. Click on 'The ` key repeatedly a few time until your perspective camera is unresponsive'
3. See error

**Expected behavior**
The console opens and closes with nothing happening to your perspective camera.
**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I5-8400]
 - GPU [NVidia 1080ti]
 - Memory [16GB]

**Additional context**

**Comment by cgalvan** [comment] 2021-07-14 19:59
@WashedUpStudio Can you attach the backtrace from the crash?  I'm not able to reproduce this crash. When you toggle on the Console, the input field is auto-focused, so the subsequent presses of the ` key result in that character just being typed in the Console's input field, preventing you from being able to toggle the Console on/off rapidly.

**Comment by WashedUpStudio** [comment] 2021-07-14 20:07
You are right, I was able to continuously toggle it before, but now it does not seem possible. I am not sure why it was not auto-focusing a week ago, but it seems to be solved since it auto-focuses now.

**Comment by alexmontAmazon** [comment] 2021-07-31 00:38
closing for now, since the requester can no longer reproduce. Please re-open if it recurs.

**Closed** 2021-07-31 00:37 UTC
Labels: feature/editor, kind/bug, needs-triage, sig/content
