### ISSUE TITLE
Lua Editor does not launch

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#3681] opened 2021-08-30 11:28 UTC
**Describe the bug**
It has been noticed that the Lua Editor does not start, regardless of where it is launched from - Lua Script component, Tools > Lua Editor, or directly from the <source>\windows_vs2019\bin\profile\LuaIDE.exe path. It should be noted that the loading image displays near the cursor when attempting to launch the Lua Editor from all of the sources listed above.

**To Reproduce**
1. Go to Tools > Lua Editor.
2. Create an entity and attach a Lua Script component to it. Click the Open in Lua Editor button on it.
3. Go to <source>\windows_vs2019\bin\profile\LuaIDE.exe and launch it.

**Expected behavior**
Lua Editor launches without issue on each step listed.

**Video**

https://user-images.githubusercontent.com/86952082/131332233-ef141567-c7c6-4aa2-b018-e129b9f75e69.mp4

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by NiklasHenricson** [comment] 2021-08-30 17:20
I can't seem to open LueIDE.exe period. No matter if it's through the menu from within the o3de editor OR by browsing and clicking on the LuaIDE.exe through the Windows file explorer.
I wiped out my entire installation and re-installed everything. The issue persists.

**Comment by lsemp3d** [comment] 2021-09-09 00:03
I'm seeing a failure in launching AP
```
void Console::RegisterFunctor(ConsoleFunctorBase* functor)
    {
        if (functor->m_console && (functor->m_console != this))
        {
            AZ_Assert(false, "Functor is already registered to a console");
            return;
        }
```
while loading AutomatedTesting.dll

Since AP doesn't launch, LuaIDE remains in a holding pattern waiting for:

```
ssetProcessorConnection::ConnectThread: Trace::Warning
Code\Framework\AzFramework\AzFramework\Network\AssetProcessorConnection.cpp(231): 'void __cdecl AzFramework::AssetSystem::AssetProcessorConnection::ConnectThread(void)'
AssetProcessorConnection::ConnectThread: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection::ConnectThread: ==================================================================
```

**Comment by NiklasHenricson** [comment] 2021-09-09 01:48
Any updates on this issue?

**Comment by lsemp3d** [comment] 2021-09-09 16:06
> Any updates on this issue?

I'm looking into it, currently tracking down the root cause

**Comment by jckand-amzn** [comment] 2021-11-05 16:42
Unable to reproduce on stabilization/2110@fdc56b4a57f2f076bc.

**Comment by lsemp3d** [comment] 2021-11-05 16:58
Closing, no longer happens on stabilization branch

**Closed by lsemp3d** 2021-11-05 16:58 UTC
Labels: feature/scripting, kind/bug, sig/content, triage/accepted, priority/blocker, WF2, RTE

**Comment by LB-ArturSiewniak** [comment] 2021-11-15 12:33
Issue does not occur on build Stabilization_2110 (76b7e73).
