### ISSUE TITLE
[macOS] Gems Catalog mouse scrolling is inverted

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4437] opened 2021-10-01 13:43 UTC
**Describe the bug**
Using the mouse scroll wheel to browse through the O3DE Project Manager gems list will scroll up the catalog when mouse scroll wheel is scrolled down and scroll the catalog down when mouse scroll is scrolled up.

This behavior does not occur in the O3DE Project Manager for Windows.

**To Reproduce**

1. Launch the Project Manager.
2. Create a new project or select the hamburger menu next to the already existing project and choose _Edit Project Settings..._
3. Select _Configure Gems_.
4. Use the mouse scroll wheel to browse through the Gems Catalog.

**Expected behavior**
Gems Catalog mouse scrolling is not inverted.

**Desktop/Device:**
- Device: Mac
- OS: MacOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Comment by AMZN-alexpete** [comment] 2021-12-03 01:07
Hi @LB-MateuszSzweda, can you verify this is not the behavior you see when scrolling your mouse wheel in another Mac application like the Safari web browser?  I seem to recall this is the way Mac scrolling works because of the touch pad scrolling where the page scrolls down when your fingers move up on the touchpad.

**Comment by LB-MateuszSzweda** [comment] 2021-12-21 15:36
@AMZN-alexpete  
Oh, oh yes. Sorry I was fresh in OSX environment when I logged this.
The mouse scroll behavior in Project Manager/Editor and native OSX applications is coherent with _Scroll direction_ setting in System Preferences and is 'reversed' in comparison to Windows when set as Natural.

The ticket can be treated as by design and closed.

**Comment by AMZN-alexpete** [comment] 2021-12-21 17:21
Thanks for verifying this is the expected behavior.  Closing as "by-design"

**Closed by AMZN-alexpete** 2021-12-21 17:21 UTC
Labels: kind/bug, needs-triage, sig/ui-ux, priority/minor
