### ISSUE TITLE
Editor fails to launch when assets are still being processed for a newly created project

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#5126] opened 2021-10-29 11:44 UTC
**Describe the bug**
The Editor closes silently after Loading Plugins is shown in the splash screen.

[TerminalLogs.txt](https://github.com/o3de/o3de/files/7441476/EditorLogs.txt)

**Steps to reproduce**
1. Run the following command from the engine source:
   cmake -B build/mac -S . -G "Xcode" -DLY_3RDPARTY_PATH=o3de-packages -DLY_UNITY_BUILD=ON -DLY_VERSION_ENGINE_NAME=o3de-install -DCMAKE_INSTALL_PREFIX=<Engine Directory for Install Layout>
2. Build the engine:
   cmake --build <build_dir> --target install --config <config>
3. Register the engine.
4. Create a project via the CLI:
  scripts\o3de.sh create-project -pp <project-path>
5. Navigate to the project directory and run:
  cmake -B build/mac -G "Xcode" -DLY_3RDPARTY_PATH=/Users/cmoroch/o3de-packages
6. Build the project:
  cmake --build build/mac --config profile --target ALL_BUILD
7. Launch the Asset Processor and the Editor.

**Expected behavior**
The Editor launches successfully.

**Actual behavior**
The Editor closes after the splash screen is displayed.

**Found in Branch**
Stabilization_2110 (9dac727)

**Desktop/Device (please complete the following information):**
Device: Mac
OS: macOS
Version: Big Sur 11.5.1
CPU: Intel Core i7 2,8 GHz
GPU: Radeon Pro 555
Memory: 16GB

**Comment by amzn-sj** [comment] 2021-10-29 19:31
One more question. Do you get a pop-up error message saying it was unable to find an asset "Shaders/SimpleTextured.azshader"? Or any other error messages? Please attach the log files from /Users/mac-01/osx_build/user/log/Editor.log and /Users/mac-01/osx_build/user/log/crash.log

**Comment by amzn-sj** [comment] 2021-10-30 01:56
Ok, I'm able to reproduce this if I create a project named osx_build in the engine root folder. But this is not MacOS only. I can reproduce this on PC as well. If you launch the Editor and after the AssetProcessor gets to about 800 assets left to process(with a newly created default project), the Editor gets a message that the AP is ready and it tries to continue but it crashes. If I try to launch the Editor again and the AP is still not done, then the Editor pops up a dialog complaining about not finding "Shaders/SimpleTextured.azshader" and then crashes again. Each time I launch the Editor and the AP is still processing some assets, it crashes. Once the AP finishes processing all the assets, the Editor loads correctly. I'm seeing the same behavior on both PC and MacOS. I'm removing the "platform/MacOS" filter.

**Comment by amzn-sj** [comment] 2021-10-31 19:17
I was able to narrow down the root cause. It looks like Atom requires the assetcatalog.xml file in order to be initialized but it doesn't exist yet when the Editor first tries to load it. Here's what's happening:
1. We create a new project and build it.
2. We launch the Editor passing in the new project path as a parameter.
3. The Editor calls `LoadCatalog` from `AzFramework::Application::StartCommon()`. At this point, the assetcatalog.xml hasn't been created yet so we continue.
4. The Editor launches the AssetProcessor(AP) and waits for it to process critical assets. It waits here: `CCryEditApp::CompileCriticalAssets()`. 
5. Once all critical assets have been compiled, the AP tells the Editor that it's ready but there's still no assetcatalog.xml. The AP only generates that when it's done processing all assets or when it exits(it saves
the assetcatalog.xml in AssetCatalog::~AssetCatalog()).
6. When the AP tells the Editor it's ready, the Editor continues and crashes with the following callstack:
[EditorCrashCallstack.txt](https://github.com/o3de/o3de/files/7449511/EditorCrashCallstack.txt). Other relevant logs: [Editor.log](https://github.com/o3de/o3de/files/7449601/Editor.log)

This is happening because `AZ::RPI::RPISystem::InitializeSystemAssets()` was never called. That function is supposed to be called when the asset catalog is loaded. The OnCatalogLoaded() callback in `AZ::Render::Bootstrap::BootstrapSystemComponent::OnCatalogLoaded()` is where `AZ::RPI::RPISystem::InitializeSystemAssets()` gets called. Since the catalog hasn't been created yet, that was never called. 
I was able to work around this by updating `CCryEditApp::CompileCriticalAssets()` to make a `SaveCatalog()` request to the AP on the `AssetSystemRequestBus` once the critical assets are done and then calling `LoadCatalog` on the `AssetCatalogRequestBus`. This ensures that we load the catalog(hence Atom RPI gets initialized) once the critical assets finish processing. Not sure if this is where this should be fixed since Atom is the one that depends on the asset catalog. This brings us to a second problem. If I close the AP before the critical assets are done processing, it creates an assetcatalog.xml on exit. If I now restart the Editor, the call to `LoadCatalog` from `AzFramework::Application::StartCommon()`(step 3 above) succeeds this time and the `OnCatalogLoaded()` callback is called. But since the critical assets aren't all done yet, it looks like something that Atom needs is missing and it displays an error saying "RPI System could not initialize correctly. Check log for detail.". After displaying this message, the Editor shuts down. Maybe Atom could wait till AP has completed processing the critical assets in `AZ::Render::Bootstrap::BootstrapSystemComponent::OnCatalogLoaded()`?

**Comment by amzn-sj** [comment] 2021-11-01 17:38
The following PR looks like it should fix the issue: https://github.com/o3de/o3de/pull/5050
It removes `AZ::RPI::RPISystem::InitializeSystemAssets()`'s dependency on the asset catalog being loaded.

**Comment by amzn-sj** [comment] 2021-11-03 00:15
The fix has been merged into the development branch. Closing this issue.

**Comment by LB-ArturSiewniak** [comment] 2021-11-05 11:58
This issue also occurs on Linux on build Stabilization_2110 (fdc56b4). It occurs when a new project is built or an existing one is rebuilt either via the Terminal (cmake -B build/linux -S . -G"Ninja Multi-Config" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DLY_PROJECTS=AutomatedTesting -DLY_UNITY_BUILD=ON) or directly in the Project Manger. We have also checked it on Windows on builds Development (2853c4d), and Stabilization_2110 (fdc56b4), but we could not reproduce this issue.

**Comment by amzn-sj** [comment] 2021-11-06 01:29
@LB-ArturSiewniak can you attach logs from <project_path>/user/logs/Editor.log and <project_path>/user/logs/crash.log? It looks like the PR above only fixed the issue on PC. I was able to reproduce a crash on Mac as well. It looks like there are a couple of places in Atom where null pointers are getting dereferenced if some shader asset fails to compile. I found one in FullscreenTrianglePass's InitializeInternal() and another in ReflectionProbeFeatureProcessor's LoadShader().

**Comment by amzn-sj** [comment] 2021-11-08 19:32
I have a PR that I think addresses the new crashes on Linux as well. We'd be able to confirm if we can get the logs from Linux. 
https://github.com/o3de/o3de/pull/5421

**Comment by amzn-sj** [comment] 2021-11-10 18:09
Merged some fixes in 
stabilization/2110: https://github.com/o3de/o3de/pull/5451
development: https://github.com/o3de/o3de/pull/5421

**Closed by amzn-sj** 2021-11-10 18:09 UTC
Labels: platform/linux, feature/asset-pipeline, kind/bug, platform/macos, sig/content, sig/platform, triage/accepted, priority/blocker

**Comment by LB-ArturSiewniak** [comment] 2021-11-16 16:27
@amzn-sj I've rebuilt the AutomatedTesting project on Linux on build Stabilization_2110 (7031147) and the issue does not occur anymore (The Editor launches properly.).
