### ISSUE TITLE
Creating a project with the CPP keyword as the project name causes a compilation error.

### ISSUE THREAD

**Issue by Wiktor-99** [o3de/o3de#17629] opened 2024-03-18 22:02 UTC
**Describe the bug**
Creating a project with the CPP keyword as the project name causes a compilation error.

**Assets required**
**N/A**

**Steps to reproduce**
1. Open the Project Manager, choose Create a Project. 
2. Open the New Project dropdown menu instead and choose Create New Project.
3. Give your project a name for example: "new", "default" or other cpp keyword.
4. Select the Minimal Project Template.
5. Build project.
6. Build fails.

**Expected behavior**
The build should not fail. Alternatively, it should be stated that using cpp keywords as project names is not allowed.

**Actual behavior**
The project uses it's name as a namespace, and when namespace is followed by a cpp keyword, it leads to compilation errors. For example, you may encounter an error such as 'expected identifier before 'new', if the project name is 'new'.

**Screenshots/Video**
![error](https://github.com/o3de/o3de/assets/69388767/a3925721-b534-4a2a-9a32-495099d3e9e4)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
26baf4a0e5904031469362641580047a61a2bd8a

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Linux
 - Ubuntu 22.04
 - CPU AMD Ryzen 7 6800H
 - GPU RTX 3060
 - Memory 32GB

**Additional context**
**N/A**

**Comment by lemonade-dm** [comment] 2024-03-20 16:16
While this behavior is technically a bug, it is on an unusual path of naming a project after a C++ keyword.
The issue is simple to workaround and not easy to on accident so the priority is being marked as priority/minor.

However this is a good first issue for a new contributor as an entry point to the engine.
The points in the code base where C++ names are sanitized for instantiation in from a project template is in utils.py [sanitize_identifier_for_cpp](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L284-L298) method. The `engine_template.py` script which substitutes the `${SanitizedCppName}` field into the project and Gem templates when they are instantiated to create a project and Gem respectively is what calls the `sanitize_identifier_for_cpp` method [here](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/engine_template.py#L1447-L1455).

What can be done is to update the sanitize method to reject identifiers from a python set of C++ identifiers as well.

**Comment by Wiktor-99** [comment] 2024-03-20 18:33
Grate! I believe I could handle it.

**Comment by Wiktor-99** [comment] 2024-03-30 15:41
Hi @lemonade-dm, I'm already working on it, but I'm not sure if I understand your proposal correctly. Do you mean that C++ keywords should be rejected as a project name? Or should they be sanitized?

If we want to reject them, I believe the [validate_identifier](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L244)  method should be extended. The [sanitize_identifier_for_cpp](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L284-L298) only swaps none alphanumeric chars to '_' and does not  reject nor accept identifiers. Am I correct?

**Comment by lemonade-dm** [comment] 2024-04-02 14:27
> Hi @lemonade-dm, I'm already working on it, but I'm not sure if I understand your proposal correctly. Do you mean that C++ keywords should be rejected as a project name? Or should they be sanitized?
> 
> If we want to reject them, I believe the [validate_identifier](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L244) method should be extended. The [sanitize_identifier_for_cpp](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L284-L298) only swaps none alphanumeric chars to '_' and does not reject nor accept identifiers. Am I correct?

Well actually this depends on what we want to do.
We could reject C++/C identifiers or we can try to add an underscore at the end of them to maintain intent.
I am leaning towards, appending an underscore `_` to the name of the project as that is the simplest scenario for the user as they wouldn't have to troubleshoot the failure of the project creation in that case.
However I don't mind if the project name is rejected as well, as that is an edge case the Project creator can workaround by choosing a new name (i.e changing "new" -> "New", resolves the keyword issue, as C++ keywords are case-sensitive)

I will leave the decision on whether we should reject a project/Gem with the name of a C++ keyword or "sanitize" the C++ keyword by either appending(or prepending) an underscore up to you.

Also if you need a reference of C++ keywords, they can be found in latest the C++ standard draft at the following link: https://eel.is/c++draft/lex.key#:keyword

**Comment by Wiktor-99** [comment] 2024-04-02 21:52
> > Hi @lemonade-dm, I'm already working on it, but I'm not sure if I understand your proposal correctly. Do you mean that C++ keywords should be rejected as a project name? Or should they be sanitized?
> > If we want to reject them, I believe the [validate_identifier](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L244) method should be extended. The [sanitize_identifier_for_cpp](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/utils.py#L284-L298) only swaps none alphanumeric chars to '_' and does not reject nor accept identifiers. Am I correct?
> 
> Well actually this depends on what we want to do. We could reject C++/C identifiers or we can try to add an underscore at the end of them to maintain intent. I am leaning towards, appending an underscore `_` to the name of the project as that is the simplest scenario for the user as they wouldn't have to troubleshoot the failure of the project creation in that case. However I don't mind if the project name is rejected as well, as that is an edge case the Project creator can workaround by choosing a new name (i.e changing "new" -> "New", resolves the keyword issue, as C++ keywords are case-sensitive)
> 
> I will leave the decision on whether we should reject a project/Gem with the name of a C++ keyword or "sanitize" the C++ keyword by either appending(or prepending) an underscore up to you.
> 
> Also if you need a reference of C++ keywords, they can be found in latest the C++ standard draft at the following link: https://eel.is/c++draft/lex.key#:keyword
> 
> Here is a godbolt snippet showing that underscores work for the keywords: https://godbolt.org/z/cbeMW3xEo

Added the PR [https://github.com/o3de/o3de/pull/17667](url)

**Closed** 2024-04-03 16:15 UTC
Labels: good-first-issue, kind/bug, sig/core, triage/accepted, priority/minor
