### ISSUE TITLE
Bug Report: Dispatch(x, y, z) calls work serially with no overlap in GPU for skinning pass

### ISSUE THREAD

**Issue by MoMoPF** [o3de/o3de#12792] opened 2022-10-25 11:47 UTC
**Describe the bug**
When I capture a GPU frame by PIX, I found that several Dispatch(x, y, z) command seems to be executed serially in GPU. I'm interested in the reason because the actors are independent with each other in skinning pass (Maybe they use the same big buffer allocated by skinned mesh manager but not overlapped between each other). Is that feasible to be parallel? Or is it related to the UAV resource barrier for DX12? 
![image](https://user-images.githubusercontent.com/49116245/197763891-4c28a9e5-9942-40e5-8615-57079098ff4f.png)

**Steps to reproduce**
Just add some actors with animation to the scene and capture GPU frame with PIX to analyse skinning pass.

**Expected behavior**
Several Dispatch(x, y, z) calls could be executed in parallel.

**Actual behavior**
Dispatch(x, y, z) calls are executed serially with no overlap.

**Screenshots/Video**
Shown in the description.

**Found in Branch**
Development.

**Desktop/Device (please complete the following information):**
Device: [PC]
OS: [Windows]
Version [10]
CPU [Intel Xeon Gold 6234]
GPU [NVidia RTX 5000]
Memory [32GB]
API: [DX12]

**Additional context**
I knew the skinning pass writes the same large buffer resource **_m_skinnedMeshOutputStream_**. But there seems to be no barrier between two Dispatch calls, or maybe I missed it? I think dispatch call could be overlapped because different actor render proxy holds different buffer offset so that the access of memory won't be overlapped between two different dispatch calls for skinning pass. How could I keep the calls overlapped?

**Comment by MoMoPF** [comment] 2022-10-25 11:58
Even if I remove the barrier at the beginning of skinning pass, it is still working with no overlap.
![image](https://user-images.githubusercontent.com/49116245/197767454-9f52ec56-fa3a-4498-9a01-d30b99a2432a.png)

**Comment by rgba16f** [comment] 2022-10-25 16:10
Pinging @amzn-tommy as the author of the Skinning Pass.

**Comment by amzn-tommy** [comment] 2022-10-25 17:44
@MoMoPF  Your intuition is correct - they are writing to the same big buffer, but they are not overlapping so they can be executed in parallel. The barrier at the beginning of the pass is necessary - it's what ensures the MorphTargetPass is finished writing to a shared buffer before the skinning pass starts reading from it. There is a similar barrier before any depth/shadow passes start, to ensure skinning is finished before those passes start. However, that should not prevent the individual dispatches from running in parallel. If they are in fact not running in parallel, it's because the driver is (incorrectly) deciding for some reason they can't be.

I haven't quite been able to drill all the way down on this, but it sounds like the most likely cause is a known regression in one of the 500 level NVidia drivers according to one of @jeremyong-az's contacts at NVidia. Fortunately, it sounds like the issue only occurs when taking a capture, so these should still be executing in parallel when they are actually running at runtime/editor. Can you share your driver version? If you're on one of the 5** driver versions, you might try reverting back to a 4** driver version to see if this is resolved.

An alternate explanation is our use of SetAutoBreadcrumbsEnablement for ID3D12DeviceRemovedExtendedDataSettings1. Since we're not explicitly leaving our own breadcrumbs, it's possible that the breadcrumbs DX12 automatically places are too granular and cause some things to be executed in serial when they could otherwise be parallelized. We should be able to rule that out by taking before/after captures with breadcrumbs enabled/disabled. Not sure how quickly I will get to that, but if you'd like to try on your own in the meantime, look for D3D12_DRED_ENABLEMENT_FORCED_ON in Device_Windows.cpp, and force DRED OFF instead.

**Comment by MoMoPF** [comment] 2022-10-26 08:43
Thanks for helping! @rgba16f @amzn-tommy   As @amzn-tommy  said, my dirver version is 5** and it works when I revert it to 4**. Now dispatch calls are overlapped in the GPU capture. Thanks!
![image](https://user-images.githubusercontent.com/49116245/197920551-28595a1e-dcc0-49cf-991f-c878fb7c769d.png)

But in addition, it doesn't work if I set **_D3D12_DRED_ENABLEMENT_FORCED_OFF_** for DRED settings. Does it work in your environment? @amzn-tommy 
![image](https://user-images.githubusercontent.com/49116245/197965593-38a502df-7c7d-4171-8810-3d4dee87cf80.png)

**Comment by amzn-tommy** [comment] 2022-10-26 18:16
I haven't tried turning DRED off, but what you observed is expected. The driver issue is independent of DRED. The driver issue is an issue that occurs when taking GPU captures, regardless of whether or not DRED is enabled. And reverting your driver confirms it is indeed the driver issue we were thinking of.

DRED was just an alternate theory, where we weren't sure whether or not the auto-breadcrumbs could cause something like this.

I'm going to close this issue, as at this point it's in NVidia's hands to fix it in some future driver update. If you are exploring further optimizations for skinning to cut back on frame time, let me know. I have plenty of ideas, which I won't have a chance to experiment with any time soon.

**Closed by amzn-tommy** 2022-10-26 18:16 UTC
Labels: kind/bug, sig/graphics-audio, priority/minor

**Comment by MoMoPF** [comment] 2022-10-27 01:02
> I haven't tried turning DRED off, but what you observed is expected. The driver issue is independent of DRED. The driver issue is an issue that occurs when taking GPU captures, regardless of whether or not DRED is enabled. And reverting your driver confirms it is indeed the driver issue we were thinking of.
> 
> DRED was just an alternate theory, where we weren't sure whether or not the auto-breadcrumbs could cause something like this.
> 
> I'm going to close this issue, as at this point it's in NVidia's hands to fix it in some future driver update. If you are exploring further optimizations for skinning to cut back on frame time, let me know. I have plenty of ideas, which I won't have a chance to experiment with any time soon.

I will if I have some ideas. Thanks for guiding.
