### ISSUE TITLE
Animation Editor: Lock Feet for Foot IK does not work

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#8745] opened 2022-04-06 14:03 UTC
**Describe the bug**
Creating a **Foot IK** setup in the **Animation Editor** and enabling **Lock Feet** in the **AnimGraph** by using **Footplant IK** node does not lock the actor's feet.

Please note that this issue has been reproduced on Windows and on Linux.

_The issue will be updated accordingly as soon as any more information about this issue will be available._

**Steps to reproduce**
1. Open the **Animation Editor**.
2. Load the **Actor** and its **Motion Set** (idle motion is recommended for better visualization).
3. Create a new **AnimGraph**.
4. Add **BlendTree** node to the **AnimGraph**.
5. Enter the **BlendTree** node (double click with RMB).
6. Add Motion, Parameters and **FootplantIK** nodes to the graph.
7. In Motion node select the motion (in the **Attributes** pane).
8. In **FootPlantIK** node select the foot and toe joints.
9. Create bool parameters **FootIK** and **FootLock**.
10. Connect the Motion node with **Footplant IK** node.
11. Connect the Parameters node with **Footplant IK node**.

**Expected behavior**
The **Lock Feet** for Foot IK is locking the feet of **Actor** when enabled with **Footplant IK** node in **AnimGraph**.

**Actual behavior**
The **Lock Feet** for Foot IK does **not** lock the feet of **Actor** when enabled with **Footplant IK** node in **AnimGraph**

**Video**

https://user-images.githubusercontent.com/86951967/161992582-ec4f22eb-84b6-4674-9751-684b5d35b3d4.mp4

**Found in Branch**
Stabilization_2205 (3e47df2)
Development (63aadae)

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by monroegm** [comment] 2022-04-06 15:49
Raising to critical because this seems like existing functionality that has regressed. Please lower to major if I am mistaken.

**Comment by hultonha** [comment] 2022-04-12 09:12
I have discussed this issue with @amzn-jillich and we do not believe this is a regression. We will look into this to double check but think moving this to major makes sense as nothing has changed relating to this code recently.

**Comment by hultonha** [comment] 2022-04-26 14:28
Thank you very much for following-up @amzn-jillich, much appreciated!

Also @LB-JakubSkorupka if there's additional assets that could be included in the GitHub issue that could make reproducing much easier too. Thanks!

**Comment by LB-JakubSkorupka** [comment] 2022-04-27 08:00
@amzn-jillich I've tried to reproduce this issue on build Stabilization_2205 (c8f1489) multiple times and setting up the actor feets in different positions and in various angles. I noticed that as you mentioned - if the toe or the ankle of particular foot is not touching the ground, the foot locking for that foot will not be enabled.

The behavior from the video shows that the foot locking does not work after disabling Foot IK (at 3:10). The foot of the actor at that moment is touching the ground as we can see that Foot IK is adjusting the foot position (left ankle bend) when rotating the actor instance. After disabling the Foot IK, the left foot of the actor moves into the ground - it should stay in the same place as foot locking is still enabled - that was my thought but I realised foot lock is probably dependent on the Foot IK.
Should foot locking work after disabling Foot IK? If no, the issue can be closed.

Also, thank you very much for adding the debug rendering for Foot IK.

@hultonha Here is the Cowboy actor with its idle motion, which I use to set up the Foot IK.
[Cowboy.zip](https://github.com/o3de/o3de/files/8570071/Cowboy.zip)

**Comment by hultonha** [comment] 2022-04-27 09:58
Update: Removing Release/2205 milestone due to recent investigation, issue may possibly be closed after feedback from @amzn-jillich. Thank you for the update and extra information @LB-JakubSkorupka 👍

**Comment by amzn-jillich** [comment] 2022-04-27 10:07
@LB-JakubSkorupka thanks for the quick reply and diving into the issue again! Foot locking indeed only works in case foot IK is enabled. Basically the position of the IK target is locked at a given position to stabilize the foot onto the ground but IK is still responsible for setting up the rest of the leg transforms. Thus, if IK is disabled, this is expected behavior and won't work. Closing the issue.

**Closed by amzn-jillich** 2022-04-27 10:07 UTC
Labels: feature/animation, kind/bug, sig/content, triage/accepted, priority/major, WF3, RTE
