### ISSUE TITLE
Editor crashes when Gradient components target shapes with non-default Translation Offsets

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#13396] opened 2022-11-25 12:57 UTC
**Describe the bug**
Transforming a Shape entity with a non-default Translation Offset setting crashes the Editor. The Crash occurs if the Shape entity is targeted for a Gradient component with a target option, e.g. Altitude Gradient component.

**Prerequisites**
Translation Offset mode enabled - Add "EnableShapeComponentTranslationOffset": true under "Amazon" -> "Preferences" in editorpreferences.setreg.

**Steps to reproduce**
1. Create a Gradient entity with a reference to a shape entity. E.g. Altitude Gradient.
2. Create a simple Landscape Canvas (video attached for reference).
3. In the Viewport select the Gradient entity and as the target set the Shape entity from Landscape Canvas.
4. Select the Shape entity and change the Translation Offset to non-default.
5. Move the Shape entity in the Viewport.
6. Press the "Edit" button in the Shape component.

**Expected behavior**
The Focus Mode for the component is activated.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/203987021-e3df7d02-ced9-4156-8d88-a72cc5e1acfb.mp4

**Found in Branch**
Development (da550ef)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Call Stack Trace:**
 9) 00007FFEEF1202E7 (KERNELBASE) : UnhandledExceptionFilter
 8) 00007FFEEEACD6D8 (InProcessClient64) : (function-name not available)
 7) 00007FFEEEACD321 (InProcessClient64) : (function-name not available)
 6) 00007FFEF1875530 (ntdll) : memset
 5) 00007FFEF185C876 (ntdll) : _C_specific_handler
 4) 00007FFEF187241F (ntdll) : _chkstk
 3) 00007FFEF18214A4 (ntdll) : RtlRaiseException
 2) 00007FFEF1870F4E (ntdll) : KiUserExceptionDispatcher
 1) 00000234475FEDD1 (module-name not available) : (function-name not available)

**Additional content:**
[error.zip](https://github.com/o3de/o3de/files/10092840/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/10092841/Editor.log)
[error.log](https://github.com/o3de/o3de/files/10092842/error.log)

**Comment by greerdv** [comment] 2022-12-16 19:37
What kind of repro rate were you getting on this? I think I followed the exact same steps except I used a different prefab because I didn't have chicken.prefab, and it didn't reproduce for me. I'm on ubuntu 20.04.5 LTS.

**Comment by greerdv** [comment] 2022-12-19 13:29
I wasn't able to repro on windows either btw.

**Comment by LB-KacperMetelski** [comment] 2022-12-22 12:34
No repro on both Windows and Linux on commit eadc65e; closing the issue.

**Closed by LB-KacperMetelski** 2022-12-22 12:34 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/terrain
