### ISSUE TITLE
Asset Browser - The Editor crashes when entering anything on search bar

### ISSUE THREAD

**Issue by carb-junho** [o3de/o3de#18437] opened 2024-10-31 01:13 UTC
**Describe the bug**
Currently, typing anything on Asset Browser search bar is causing the Editor to crash.

**Assets required**
N/A

**Steps to reproduce**
1. Open up Editor
2. Click on Asset Browser search bar
3. Type anything
4. Note that the Editor crashes

**Expected behavior**
Asset Browser shows the search result instead of crashing

**Actual behavior**
Editor crashes

**Screenshots/Video**
N/A

**Found in Branch**
o3de/main

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
e8570f9d635c0abbf3d733d0524a3c0ae75d726c

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11 Pro(23H2)
 - CPU: 13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
 - GPU: NVidia RTX A4000
 - Memory: 64GB

**Additional context**
N/A

**Comment by rhuthCarb** [comment] 2024-11-20 19:47
https://github.com/user-attachments/assets/1837d0c6-30b7-4b3c-b994-ff70b8ea6354

**Comment by guillaume-haerinck** [comment] 2024-11-24 12:21
Just tried on the development branch at 3aba99af74ad59cd50d22b9eab9d58686b345cc8 and no repro, might be something which needs to be merged back to main

**Comment by Twolewis** [comment] 2024-11-26 23:12
Confirmed, due to an incomplete merge on our side.  We have a fix in place.  Thank you!

**Closed** 2024-11-27 18:32 UTC
Labels: kind/bug, needs-priority, needs-triage, sig/content, sig/ui-ux
