### ISSUE TITLE
Freshly imported .exr files can crash the Editor when attempting to Edit Texture Settings

### ISSUE THREAD

**Issue by LB-KacperMetelski** [o3de/o3de#13771] opened 2022-12-19 14:53 UTC
**Describe the bug**
After right-clicking on a freshly imported .exr file in the _Asset Browser_ and selecting the _Edit Texture Settings_ option the Editor crashes abruptly.

**Steps to reproduce**
1. Launch the Editor.
2. Import an .exr file (https://polyhaven.com/hdris one of these for example) into Asset Browser.
3. Immediately right click on the file.
4. Select _Edit Texture Settings_.

**Expected behavior**
Texture Settings window opens.

**Actual behavior**
Editor crashes immediately after the Edit Texture Settings option is selected.

**Screenshots/Video**
https://user-images.githubusercontent.com/110163473/208450552-6928366f-685e-4833-bedf-f4df42cb6927.mp4
https://user-images.githubusercontent.com/110163473/208450562-170a49b9-a573-4a98-b9f1-48373f0618a4.mp4

**Found in Branch**
Development, PhysX5Support 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(5b4e148),  (de24f8a)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu, Windows
 - Version: Ubuntu 20.04.5 LTS, Windows 10
 - CPU: i7-17000F
 - GPU: RTX-3070 MSI
 - Memory: 32GB

**Attachments**
[error.zip](https://github.com/o3de/o3de/files/10260246/error.zip)
[Editor.log](https://github.com/o3de/o3de/files/10260248/Editor.log)
[error.log](https://github.com/o3de/o3de/files/10260249/error.log)

**Comment by HogJonny-AMZN** [comment] 2022-12-19 16:45
I believe it has to do with the file size, I’ve noticed some other weirdness with EXR files.  Like trying to save one from Photoshop, the save might fail, if the AP picks up the file change before the save/update is complete (which takes many seconds.)

**Comment by VickyAtAZ** [comment] 2023-01-03 23:38
The issue is due to an invalid the source asset id when an image was just added to the asset folder. 
It's fixed in this PR: https://github.com/o3de/o3de/pull/13886

**Closed** 2023-01-04 19:55 UTC
Labels: kind/bug, sig/graphics-audio, priority/critical, WF5, RTE
