### ISSUE TITLE
fails to run with undefined symbol on Manjaro

### ISSUE THREAD

**Issue by Malthbern** [o3de/o3de#14171] opened 2023-01-23 17:31 UTC
**Describe the bug**
fails to launch with "o3de: symbol lookup error: /opt/O3DE/22.10.0/bin/Linux/profile/Default/libAzQtComponents.so: undefined symbol: _ZN16QStyleSheetStyle16staticMetaObjectE, version Qt_5_PRIVATE_API" with LD_LIBRARY_PATH and LD_PRELOAD having no effect on loading the provided libraries

**Assets required**
Manjaro Linux (seems specific to this distro)
aur package: https://aur.archlinux.org/packages/o3de-bin

1. download from aur
2. run "o3de" in command line

**Expected behavior**
o3de should load

**Actual behavior**
fails to load with error "o3de: symbol lookup error: /opt/O3DE/22.10.0/bin/Linux/profile/Default/libAzQtComponents.so: undefined symbol: _ZN16QStyleSheetStyle16staticMetaObjectE, version Qt_5_PRIVATE_API"

**Found in Branch**
https://o3debinaries.org/main/Latest/Linux/o3de_2210_0.deb

**Desktop/Device**
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.15-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2

**Comment by xaque** [comment] 2023-01-23 17:58
This issue has cropped up a few times in the discord as well by users running distros such as Manjaro, Garuda. Based on this QT article: https://www.qt.io/blog/2011/10/28/rpath-and-runpath 

> When you ship binaries, either use RPATH and not RUNPATH or ensure LD_LIBRARY_PATH is set before they are run. When you build Qt on a system where 'ld' defaults to --enable-new-dtags (and thus -rpath adds a RUNPATH), be aware that you might have to set LD_LIBRARY_PATH before starting applications built against that Qt version.

The binaries from O3DE only have RUNPATH and it seems different distros are behaving differently with regards to loading the system or O3DE ones first

**Comment by byrcolin** [comment] 2023-01-26 17:14
We will take this under advisement, understand Manjaro is not a supported platform as of yet so this would be a good issue for the community to dig into and fix in such a way that would not break the officially supported platforms and would move Manjaro closer to potentially being an officially supported platform.

**Comment by ShaunaGordon** [comment] 2024-03-06 16:21
Just for reference purposes for anyone who happens along this issue, this is still happening with 23.10.2.

**Comment by ShaunaGordon** [comment] 2024-04-11 06:20
I took some time to track this down, and found that it's not something on the O3DE side, nor does it seem to be a runpath thing, but rather a permissions issue on install.

Basically, it's installing into `/opt`, which is recursively owned by root by default (of course). However, at least pip, if not `get_python` as a whole doesn't like being run with elevated privileges, and the user check in the package install script isn't behaving as expected, resulting in the whole thing failing in some silent way.

I've updated the issue on the package repository with my findings so they can implement the best fix for it. 

In the meantime, for any affected user that happens across this, you can work around the issue by `chown`ing the descendants of the `/opt/O3DE/23.10.2` folder, then running `python/get_python.sh` again.

**Comment by fhdk** [comment] 2024-04-18 15:49
Please check comment marked as solution on Manjaro Forum

https://forum.manjaro.org/t/is-something-different-about-manjaros-runpath-handling/159464/18

**Closed** 2024-10-01 16:41 UTC
Labels: platform/linux, good-first-issue, help-wanted, kind/bug, sig/platform, triage/deferred

**Comment by ShaunaGordon** [comment] 2024-10-04 23:37
That was my post on the forum. I continued to track it down and [with the help of the o3de-aur maintainers,](https://github.com/xaque/aur-o3de/issues/1) we figured out what the issue is and they fixed it a while back and released a new version. It shouldn't be an issue anymore.
