### ISSUE TITLE
Bug Report - Using fixed joint to link articulation and rigid body doesn't work

### ISSUE THREAD

**Issue by superlomo** [o3de/o3de#17384] opened 2024-01-16 02:23 UTC
**Describe the bug**
Atfer merging the commit https://github.com/o3de/o3de/pull/16794 and issue https://github.com/o3de/o3de/issues/16188. I'm trying to use a fixed joint to link a mechanical arm which is based on articulation  joint with a car which is based on rigid body, but there is  no effect.

**Assets required**
ROS2 related resource

**Steps to reproduce**
1.  create box A with rigid body component
2.  create box B with articulation component
3. create a fixed joint attached to Box A on Box B

**Expected behavior**
Box B should move with Box A

**Actual behavior**
Box B and Box A are not linked at all

**Screenshots/Video**

![截图 2024-01-16 10-00-32](https://github.com/o3de/o3de/assets/21189549/60679b22-83b3-48ad-a46b-20f87bdc5666)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/79e1df3990c5554c454d68798a0f3ef94c8ae317

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS:Ubuntu
 - Version: 22.04
 - CPU [e.g. Intel I7-12700K
 - GPU RTX3070
 - Memory 64GB

**Additional context**
No

**Comment by michalpelka** [comment] 2024-01-26 13:55
Thank you @superlomo for raising this issue.
I was able to reproduce it for the current development.

**Comment by michalpelka** [comment] 2024-01-31 12:40
Hello, I've checked out our latest development(cec608023e26525413e1cd8b8b4e125f78991484). 
In the previous, deleted message I took a point release by mistake.
I've created an entity named A with a rigid body, box shape, collider, and fixed joint:
![image](https://github.com/o3de/o3de/assets/3209244/70ae3d26-cc3b-4dd5-b152-c80948f5c9d8)
I've created a second entity called B, which contains an articulation link:
![image](https://github.com/o3de/o3de/assets/3209244/af342b50-749b-49cf-b79b-0673b131ecaa)

This setup works as intended in game mode (the joint is created):
[Screencast from 01-31-2024 01:31:05 PM.webm](https://github.com/o3de/o3de/assets/3209244/82535621-9242-4e18-aad5-92918729cded)

Please make sure:
- you are using a developers' build on o3de
- you compiled against physx 5 (articulations are not supported with physx 4). Refer to https://www.docs.o3de.org/docs/user-guide/interactivity/robotics/project-configuration/#building.
- you created a fixed joint from A to B. You somehow (it's a bug) can create a fixed joint next to the articulation component, but it is not working.

I am changing the issue status to "information-needed", please give if one of the three suggestions worked. Thanks!
Here is my test level: https://gist.github.com/michalpelka/a6ea598e61a9decf12d68e0f83759959

**Comment by jhanca-robotecai** [comment] 2024-02-29 15:44
I am closing the issue due to the missing response. Please reopen the issue if necessary.

**Comment by Huawei-CarlosCarbone** [comment] 2024-06-13 11:31
Hello, I am trying to replicate the proposed solution but I was not able to do so. I am using main for both o3de and o3de extras from the release on may so I assume that the current changes from development at the time of posting are already included. The behavior I get is that the articulation link in Entity B does not follow the constraint from the fixed joint in Entity A, has something else changed since then?

**Comment by jhanca-robotecai** [comment] 2024-06-13 15:13
I am reopening the issue following the most recent comment

**Comment by jhanca-robotecai** [comment] 2024-06-13 15:21
@Huawei-CarlosCarbone 
Thank you for raising the issue, I will look into it as soon as possible. In the meantime please find the answer to your question about `Articulations` not available as components to add: in older versions of O3DE, you needed to set a flag in one of the setreg files `"EnableReducedCoordinateArticulations": true`, please find the example in [ROSConDemo](https://github.com/o3de/ROSConDemo/blob/main/Project/Registry/awscoreconfiguration.setreg)

**Comment by Huawei-CarlosCarbone** [comment] 2024-06-14 07:26
Thank you @jhanca-robotecai, the registry file change did allow me to include articulations. I will be waiting for your comments on the main problem of the posted issue. Just giving some more feedback, @michalpelka posted a video in his solution comment that includes the expected behavior, I copied and pasted the level prefab he shared as well, and on my end the red cube falls to the ground and the green cube stay on the air

**Comment by michalpelka** [comment] 2024-06-14 13:49
Hello @Huawei-CarlosCarbone, thanks to test my solution, sorry to hear that is not working.
I've tested it against the stabilization branch and verified it against PhysX visual debugger.
It has created two PhysX actors: one as RigidDynamic body second one as Articulation link.
The joint was created successfully: 
![image](https://github.com/o3de/o3de/assets/3209244/e27c17fc-6eb3-42a6-b6ce-d1797843841d)
Make double sure that you used 2409 stabilization, or include correct compilation flags.

**Comment by Huawei-CarlosCarbone** [comment] 2024-06-14 15:01
Hello, thank you for your answer I tried the stabilization/2409 branch for o3de-extras like you suggested, but then it is not compatible with the main branch in O3DE (the compilation fails). 

I commonly tend to avoid development branches as they are very unstable in terms of compilation, I understand from your answer that I could make this work in main using the right compilation flags. Could you elaborate on that? I am using in my compilation flags already -DAZ_USE_PHYSX5=ON if that is what you mean. Otherwise does this means that I am force to use development to make use of this feature? (joints between object A with joint component and object B with articulation component)

Please let me know your comments, thanks

**Comment by michalpelka** [comment] 2024-06-17 07:03
@Huawei-CarlosCarbone 
My bad, https://github.com/o3de/o3de/commit/79e1df3990c5554c454d68798a0f3ef94c8ae317 seems to be only in stabilization/2409 and development (not in main or other 2310 releases).
You can cherry-pick https://github.com/o3de/o3de/commit/79e1df3990c5554c454d68798a0f3ef94c8ae317 to you release branch, or consider using stabilization/2409.

**Comment by Huawei-CarlosCarbone** [comment] 2024-06-17 14:10
Hello, just giving some feedback if I cherry-pick the commit I do get the behavior of the video. However, the controllers of the ros2 template with mobile robot do not work anymore as well ass the arm in the manipulation template level

If I try the latest commit in the stabilization branch I get two compilation errors, one about python modules not being found
/home/carloscarbone/.o3de/Python/venv/c3b576e4/bin/python: No module named pip
and one about PhysX5 gem not being found even when one of the directories search directories in the error is the one for the PhysX gem

Furthermore, I also tried to take the files from the cherry-picked commit and replace them in the main branch, in that case the behavior from the cubes is still the wrong one (the green cube stays in the air)

An ideal scenario for me would be to have a branch/commit for o3de and o3de-extras that has both functionalities working, the mobile robot, the arm manipulator from the ros2 templates, as well as the joint/articulation constraint. Please let me know if you can think of any solution to achieve this

**Comment by Huawei-CarlosCarbone** [comment] 2024-06-18 14:02
Hello, I confirm that the solution is working properly

**Procedure taken**: Manually add the changes made at https://github.com/o3de/o3de/commit/79e1df3990c5554c454d68798a0f3ef94c8ae317 into the current latest main branch of O3DE at https://github.com/o3de/o3de/commit/1577b1e742358461d8b2e6cfafd937637315c9d5

This ensures that a joint can specify as a lead entity an entity with an articulation, and the constrains will be maintained. this was tested by combining the robots from the ROS2 template at https://github.com/o3de/o3de-extras/tree/main/Templates/Ros2ProjectTemplate and the manipulation template at https://github.com/o3de/o3de-extras/tree/main/Templates/Ros2RoboticManipulationTemplate. With default parameters, the robot tips over to the floor since the arm is too heavy but after changing the mass and dimensions of the base robot then the simulation of a proper mobile manipulator like the one proposed in this post was achieved.

Thank you once more @michalpelka and @jhanca-robotecai for all your support you can close this issue if there are no further problems or comments.

**Closed** 2024-06-18 14:45 UTC
Labels: kind/bug, triage/needs-information, priority/major, sig/simulation
