### ISSUE TITLE
AssetProcessor fails to process some kind of TGA files.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2682] opened 2021-08-02 02:25 UTC
**Describe the bug**
AssetProcessor fails to process some kind of TGA files. 
The following is the log.

2021/6/2 17:13 | ERROR | Image Processing: Trace::Error from AssetBuilder
2021/6/2 17:13 | ERROR | >  D:/O3DE/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp(193): 'void __cdecl ImageProcessingAtom::TextureSettings::ApplyPreset(struct AZ::Uuid)' from AssetBuilder
2021/6/2 17:13 | ERROR | >  Cannot set an invalid preset {00000000-0000-0000-0000-000000000000}! from AssetBuilder
2021/6/2 17:13 | ERROR | Image Processing: Trace::Error from AssetBuilder
2021/6/2 17:13 | ERROR | >  D:/O3DE/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp(193): 'void __cdecl ImageProcessingAtom::TextureSettings::ApplyPreset(struct AZ::Uuid)' from AssetBuilder
2021/6/2 17:13 | ERROR | >  Cannot set an invalid preset {00000000-0000-0000-0000-000000000000}! from AssetBuilder
2021/6/2 17:13 | ERROR | Image Processing: Trace::Error from AssetBuilder
2021/6/2 17:13 | ERROR | >  D:/O3DE/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp(193): 'void __cdecl ImageProcessingAtom::TextureSettings::ApplyPreset(struct AZ::Uuid)' from AssetBuilder
2021/6/2 17:13 | ERROR | >  Cannot set an invalid preset {00000000-0000-0000-0000-000000000000}! from AssetBuilder
2021/6/2 17:13 | ERROR | Image Processing: Trace::Error from AssetBuilder
2021/6/2 17:13 | ERROR | >  D:/O3DE/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp(193): 'void __cdecl ImageProcessingAtom::TextureSettings::ApplyPreset(struct AZ::Uuid)' from AssetBuilder
2021/6/2 17:13 | ERROR | >  Cannot set an invalid preset {00000000-0000-0000-0000-000000000000}! from AssetBuilder
2021/6/2 17:13 | ERROR | Image Processing: Trace::Error from AssetBuilder
2021/6/2 17:13 | ERROR | >  D:/O3DE/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp(837): 'class ImageProcessingAtom::ImageConvertProcess *__cdecl ImageProcessingAtom::CreateImageConvertProcess(const class AZStd::basic_string<char,struct AZStd::char_traits<char>,class AZStd::allocator> &,const class AZStd::basic_string<char,struct AZStd::char_traits<char>,class AZStd::allocator> &,const class AZStd::basic_string<char,struct AZStd::char_traits<char>,class AZStd::allocator> &,class AZStd::vector<struct AssetBuilderSDK::JobProduct,class AZStd::allocator> &,class AZ::SerializeContext *)' from AssetBuilder

**To Reproduce**
1. Put tga files into textures folder of current project, such as D:\CODE_HMS\AutomatedTesting\textures
2. Check AssetProcessor, search the tga file.

**Expected behavior**
Succeed to process tga files.

**Screenshots**
![image](https://user-images.githubusercontent.com/80555200/127795380-c5907410-ee7c-49f7-ac77-bcd5ce6fa3ac.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by Jackie9527** [comment] 2021-08-02 15:05
The link of tga file [eye_diff.tga](https://discord.com/channels/805939474655346758/816043793576886273/859695148379668491).
![image](https://user-images.githubusercontent.com/80555200/127882917-e57f9690-fff2-41bd-8b96-c7a15947706e.png)

Such files could be loaded by Lumberyard 1.27.
Both O3DE and Lubmeryard 1.27 use Qt TGA plugin to process TGA files. So we hack the qtga.dll, use the dll within Lumberyard 1.27, to replace the dll within O3DE.
Then eye_diff.tga is well processed.
Maybe this is a version issue with Qt SDK released with O3DE.

**Comment by VickyAtAZ** [comment] 2022-08-09 01:03
The issue is fixed in PR: https://github.com/o3de/o3de/pull/11161

**Closed** 2022-08-12 16:39 UTC
Labels: kind/bug, sig/core, triage/accepted
