### ISSUE TITLE
[GNU/LINUX] Asset Processor the error image processing in format TGA

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#6381] opened 2021-12-13 11:05 UTC
**Screenshots/Video**

![image](https://user-images.githubusercontent.com/17591539/145799906-ce27948a-76b6-42d4-b906-731697472dcc.png)

![image](https://user-images.githubusercontent.com/17591539/145799954-d2ca6bb0-e07b-42e2-aec9-560251ce9c81.png)

**Found in Branch**
21.11.1 stable

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS

**Additional context**
```~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~AssetBuilder: Running processJob task
~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~AssetBuilder: Source = /home/demonevil/O3DE/Projects/Test00/TEST/test_tga.tga
~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~AssetBuilder: Platform = linux
~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~Info: Performing image conversion: /home/demonevil/O3DE/Projects/Test00/TEST/test_tga.tga
~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~Error: Unexpected error during processing job /home/demonevil/O3DE/Projects/Test00/TEST/test_tga.tga.
~~1639392808595~~1~~0x7fd0faffd700~~AssetBuilder~~S: 2 errors, 0 warnings
~~1639392808595~~3~~0x7fd0faffd700~~AssetBuilder~~E: ImageProcessing: Trace::Error
~~1639392808596~~3~~0x7fd0faffd700~~AssetBuilder~~E: >	/data/workspace/o3de/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/QtImageLoader.cpp(31): 'ImageProcessingAtom::IImageObject *ImageProcessingAtom::QtImageLoader::LoadImageFromFile(const AZStd::string &)'
~~1639392808596~~3~~0x7fd0faffd700~~AssetBuilder~~E: >	Failed to load [/home/demonevil/O3DE/Projects/Test00/TEST/test_tga.tga] via QImage
~~1639392808597~~3~~0x7fd0faffd700~~AssetBuilder~~E: Image Processing: Trace::Error
~~1639392808597~~3~~0x7fd0faffd700~~AssetBuilder~~E: >	/data/workspace/o3de/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp(784): 'ImageProcessingAtom::ImageConvertProcess *ImageProcessingAtom::CreateImageConvertProcess(const AZStd::string &, const AZStd::string &, const ImageProcessingAtom::PlatformName &, AZStd::vector<AssetBuilderSDK::JobProduct> &, AZ::SerializeContext *)'
~~1639392808597~~3~~0x7fd0faffd700~~AssetBuilder~~E: >	Load image file /home/demonevil/O3DE/Projects/Test00/TEST/test_tga.tga failed
~~1639392808598~~0~~0x7fd0faffd700~~Debug~~Job request written to /home/demonevil/O3DE/Projects/Test00/user/AssetProcessorTemp/JobTemp-rvFkqP/request.xml
~~1639392808598~~0~~0x7fd0faffd700~~Debug~~To re-run this request manually, run AssetBuilder with the following parameters:
~~1639392808598~~0~~0x7fd0faffd700~~Debug~~-task=process -id="" -project-name="Test00" -project-cache-path="/home/demonevil/O3DE/Projects/Test00/Cache" -project-path="/home/demonevil/O3DE/Projects/Test00" -engine-path="/opt/O3DE/21.11" -port 45643 -input="/home/demonevil/O3DE/Projects/Test00/user/AssetProcessorTemp/JobTemp-rvFkqP/request.xml" -output="/home/demonevil/O3DE/Projects/Test00/user/AssetProcessorTemp/JobTemp-rvFkqP/response.xml" --regset="/Amazon/AzCore/Bootstrap/project_path=/home/demonevil/O3DE/Projects/Test00" --regset="/Amazon/AzCore/Bootstrap/engine_path=/opt/O3DE/21.11" --regset="/Amazon/AzCore/Bootstrap/engine_path=/opt/O3DE/21.11"
~~1639392808598~~1~~0x7fd0faffd700~~Error~~Builder indicated that the job has failed.```

**Comment by monroegm** [comment] 2021-12-14 19:36
Sending to SIG-Graphics-Audio who own ImageProcessing

**Comment by VickyAtAZ** [comment] 2021-12-15 18:59
@Altair1024 can you post the test_tga.tga file here? 
The image builder is using QT library to load tga file. And it didn't support compressed tga (a [post ](https://forum.qt.io/topic/101971/qimage-and-tga-support-in-c)from 2019) 
It could be the same case with your test file.

**Comment by Altair1024** [comment] 2021-12-15 19:23
@VickyAtAZ [Test_images.zip](https://github.com/o3de/o3de/files/7722116/Test_images.zip)

**Comment by VickyAtAZ** [comment] 2022-01-06 18:55
This issue is same as this one: https://github.com/o3de/o3de/issues/2682
And there is a PR for the tga loading problem: https://github.com/o3de/o3de/pull/6507

**Comment by VickyAtAZ** [comment] 2022-08-09 01:03
The issue is fixed in PR: https://github.com/o3de/o3de/pull/11161

**Closed** 2022-08-12 16:39 UTC
Labels: kind/bug, sig/graphics-audio, priority/major, feature/graphics/asset
