### ISSUE TITLE
Unable to build a new project created from the Project Manager (or Editor) UI

### ISSUE THREAD

**Issue by baothientran** [o3de/o3de#2990] opened 2021-08-09 21:11 UTC
**Describe the bug**

After I build and install the engine, I'm unable to create and build a new project from the Project Manager UI (or Editor UI). The same problem also happens for `o3de-atom-sample-viewer`. I got the below cmake errors for Renderdoc. The engine and its editor are built and run successfully btw. Only new projects created from it has the problem.

```
cmake -B .\o3de-atom-sampleviewer\build\profile -S .\o3de-atom-sampleviewer\ -G "Visual Studio 16" -DLY_3RDPARTY_PATH=o3de-packages -DLY_UNITY_BUILD=ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/qt-5.15.2-rev4-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-install/python/runtime/python-3.7.10-rev1-windows
-- Using Python 3.7.10 at C:/Users/baotr/Documents/Projects/o3de/o3de-install/python/runtime/python-3.7.10-rev1-windows/python/python.exe
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/RapidJSON-1.1.0-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/Lua-5.3.5-rev5-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/RapidXML-1.13-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/zlib-1.2.8-rev2-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/zstd-1.35-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/cityhash-1.1-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/googletest-1.8.1-rev4-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/googlebenchmark-1.5.0-rev2-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/md5-2.0-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/lz4-r128-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/SQLite-3.32.2-rev3-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/OpenSSL-1.1.1b-rev2-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/expat-2.1.0-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/tiff-4.2.0.14-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/AWSNativeSDK-1.7.167-rev3-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/squish-ccr-20150601-rev3-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/assimp-5.0.1-rev11-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/Crashpad-0.8.0-rev1-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/pybind11-2.4.3-rev2-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/etc2comp-9cd0f9cae0-rev1-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/PVRTexTool-4.24.0-rev4-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/ilmbase-2.3.0-rev4-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/ISPCTexComp-2021.3-rev1-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/ASTCEncoder-2017_11_14-rev2-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/mcpp-2.7.2_az.1-rev1-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev2-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/SPIRVCross-2021.04.29-rev1-windows
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/azslc-1.7.23-rev1-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/lux_core-2.2-rev5-multiplatform
-- Using package C:/Users/baotr/Documents/Projects/o3de/o3de-packages/packages/openimageio-2.1.16.0-rev2-windows
CMake Error at C:/Users/baotr/Documents/Projects/o3de/o3de-install/cmake/LYWrappers.cmake:429 (find_package):
  No "Findrenderdoc_api.cmake" found in CMAKE_MODULE_PATH.
Call Stack (most recent call first):
  C:/Users/baotr/Documents/Projects/o3de/o3de-install/cmake/LYWrappers.cmake:220 (ly_parse_third_party_dependencies)
  C:/Users/baotr/Documents/Projects/o3de/o3de-install/Gems/Atom/RHI/Code/CMakeLists.txt:41 (ly_add_target)


CMake Warning (dev) at C:/Users/baotr/Documents/Projects/o3de/o3de-install/cmake/LYWrappers.cmake:429 (find_package):
  Findrenderdoc_api.cmake must either be part of this project itself, in this
  case adjust CMAKE_MODULE_PATH so that it points to the correct location
  inside its source tree.

  Or it must be installed by a package which has already been found via
  find_package().  In this case make sure that package has indeed been found
  and adjust CMAKE_MODULE_PATH to contain the location where that package has
  installed Findrenderdoc_api.cmake.  This must be a location provided by
  that package.  This error in general means that the buildsystem of this
  project is relying on a Find-module without ensuring that it is actually
  available.

Call Stack (most recent call first):
  C:/Users/baotr/Documents/Projects/o3de/o3de-install/cmake/LYWrappers.cmake:220 (ly_parse_third_party_dependencies)
  C:/Users/baotr/Documents/Projects/o3de/o3de-install/Gems/Atom/RHI/Code/CMakeLists.txt:41 (ly_add_target)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/Users/baotr/Documents/Projects/o3de/o3de-atom-sampleviewer/build/profile/CMakeFiles/CMakeOutput.log".
```

**To Reproduce**
1. Build and install o3de engine in the `o3de-install` directory (or any name should be fine)
2. Configure o3de-atom-sample-viewer using the below cmake command:
```
cmake -B .\o3de-atom-sampleviewer\build\profile -S .\o3de-atom-sampleviewer\ -G "Visual Studio 16" -DLY_3RDPARTY_PATH=o3de-packages
```
3. See the cmake error above

**A Workaround**
   - Build and install the engine in the `o3de-install` directory
   - Copy the whole cmake `Platform` directory from the source dir `o3de/Gems/Atom/RHI/Code/Platform` to the install directory `o3de-install/Gems/Atom/RHI/Code/Platform`
   - Then, I modify the CMakeLists.txt in the install directory `o3de-install/Gems/Atom/RHI/Code` to include those cmake files in the copied `Platform` directory. Below is the modified CMakeLists.txt:
   
     [CMakeLists.txt](https://github.com/o3de/o3de/files/6957376/CMakeLists.txt)

   - After that, atom-sample-viewer is built successfully 

**Expected behavior**
- Atom sample viewer and new projects created from Project Manager UI should be built successfully with the installed engine

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Window 10
 - CPU Intel core i7-9750H CPU @ 2.60GHz
 - GPU Laptop GeForce GTX 1650
 - Memory 32GB
 - CMake 3.20.5
 - Renderdoc is installed in the `C:\Program Files\RenderDoc` which seems to be Renderdoc default path specified in this [cmake]( https://github.com/o3de/o3de/blob/cf7681df2741188679fbb397487d3bc46ad30d86/Gems/Atom/RHI/Code/Platform/Windows/renderdoc_windows.cmake#L12)
 - Visual Studio 16.10.4

**Comment by lumberyard-employee-dm** [comment] 2021-08-09 21:50
@amznestebanpapp Ok so this issue is caused by the Atom RHI CMakeLists.txt adding an an external target of "renderdoc" in the it's [renderdoc_windows.cmake](https://github.com/o3de/o3de/blob/development/Gems/Atom/RHI/Code/Platform/Windows/renderdoc_windows.cmake) file.

Now the [Install_common.cmake](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake) script only generates an IMPORTED target for CMake targets declared using `ly_add_target`.
It doesn't examined 3rdParty targets declared using `ly_add_external_target` therefore when the install step occurs, it skips over adding those targets to the generated CMakeLists.txt file.

A potential solution is to perform the action of adding the external to the LY_DIRECTORY_TARGETS property similar to how we do it in the [ly_add_target()](https://github.com/o3de/o3de/blob/development/cmake/LYWrappers.cmake#L304-L311) inside of the [ly_external_target()](https://github.com/o3de/o3de/blob/development/cmake/3rdParty.cmake#L136) function.

We can then take advantage of the [ly_setup_subdirectory()](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L280-L289) call to be able to loop over O3DE targets along with the external targets added to make sure generate a target for 3rdParty libraries declared within gems.

**Comment by amznestebanpapp** [comment] 2021-08-10 19:03
Renderdoc is 3rdparty and it should be done with a `Find` file, we copy `Find` files to the install layout, we dont track all the externally-added targets.
Assigning to @jeremyong-az

**Comment by amznestebanpapp** [comment] 2021-08-10 19:17
There is also this code:
```
set(RENDERDOC_CMAKE ${CMAKE_CURRENT_SOURCE_DIR}/${pal_dir}/renderdoc_${PAL_PLATFORM_NAME_LOWERCASE}.cmake)
if(EXISTS ${RENDERDOC_CMAKE})
    include(${RENDERDOC_CMAKE})
endif()
```
we should always `include` the file. That `EXISTS` there can cause issues because CMake wont regenerate automatically if the file is added/removed. So, if someone was to add a file with an error in another platform and run it through Jenkins, the error may not show up until next time there is a regeneration (so the error could end up being merged). The same can happen if a file is removed.

**Comment by lumberyard-employee-dm** [comment] 2021-08-11 16:34
I think we should add documentation to mention that the `Find*.cmake` scripts are being called to the install layout when they exist under a path added by [ly_add_external_target_path] (https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L398-L408)

**Comment by jeremyong-az** [comment] 2021-08-11 22:10
Closing this issue for now since RenderDoc needs to be manually enabled via `LY_RENDERDOC_ENABLED` so new projects should build properly (separate issue will be filed for moving RenderDoc integration to a gem as an optional gem dependency of Atom.RHI

**Closed by jeremyong-az** 2021-08-11 22:10 UTC
Labels: kind/bug, needs-triage, sig/build

**Comment by baothientran** [comment] 2021-08-17 20:34
Thanks everyone! That works for me
