### ISSUE TITLE
Multiplayer Gem/Multiplayer Sample: Entity with Network Hierarchy Root with two or more children throws unhandled exception

### ISSUE THREAD

**Issue by CSteel22** [o3de/o3de#10152] opened 2022-06-15 21:56 UTC
## Bug Description
At level load in multiplayer, when spawning a Network Prefab with a Network Hierarchy Root and two or more childed entities with the Network Hierarchy Child component, an unhandled exception occurs.  

## Steps to Reproduce
1. Create and Save a Prefab comprised of a Root Entity with the Network Hierarchy Root component and two childed entities with Network Hierarchy Child components.  Ensure all component dependencies are present on the Entities.  
### Entity Outliner Sample
![image](https://user-images.githubusercontent.com/35277774/173930491-8e560234-fc54-4b19-99a0-09a2d37e66e1.png)
### Network Hierarchy Root Entity Build
![image](https://user-images.githubusercontent.com/35277774/173930598-12e07d00-3e02-43c3-a036-b19fab5c52c5.png)
### Network Hierarchy Child Entity Build (Identical for both Child Entities)
![image](https://user-images.githubusercontent.com/35277774/173930759-f8839599-b609-4c34-ac0f-c191a5138624.png)
2. Remove the prefab from the Entity Outliner.
3. Add a new network-bound entity to the level with a Network Player Spawner component (from the Multiplayer Sample project.)  In the Spawnable Asset field, add the prefab from Step 1.
![image](https://user-images.githubusercontent.com/35277774/173932171-f18ac6c0-35ff-4719-b5fb-eeea7291dad6.png)
4. Hit the Play Game icon or press Ctrl + G.

## Expected Behavior
The Prefab should spawn at the location of the entity with the Network Player Spawner component.

## Actual Behavior
No Prefab is spawned and instead the following Stack Trace is printed in the console:

```
(EditorServer) - : 00007FF90FC1578C (KERNELBASE) : UnhandledExceptionFilter
(EditorServer) - : 00007FF9122784DD (ntdll) : RtlMoveMemory
(EditorServer) - : 00007FF91225F077 (ntdll) : _C_specific_handler
(EditorServer) - : 00007FF912273D6F (ntdll) : _chkstk
(EditorServer) - : 00007FF9121EEAA6 (ntdll) : RtlFindCharInUnicodeString
(EditorServer) - : 00007FF912272D5E (ntdll) : KiUserExceptionDispatcher
(EditorServer) - : C:\o3de\Gems\Multiplayer\Code\Source\Components\NetworkHierarchyRootComponent.cpp (301) : Multiplayer::NetworkHierarchyRootComponent::InternalBuildHierarchyList
(EditorServer) - : C:\o3de\Gems\Multiplayer\Code\Source\Components\NetworkHierarchyRootComponent.cpp (239) : Multiplayer::NetworkHierarchyRootComponent::RebuildHierarchy
(EditorServer) - : C:\o3de\Code\Framework\AzCore\AzCore\EBus\Event.inl (288) : AZ::Event<enum AZ::ChildChangeType,AZ::EntityId>::Signal
(EditorServer) - : C:\o3de\Code\Framework\AzFramework\AzFramework\Components\TransformComponent.cpp (196) : AzFramework::TransformComponent::NotifyChildChangedEvent
(EditorServer) - : C:\o3de\Code\Framework\AzFramework\AzFramework\Components\TransformComponent.cpp (602) : AzFramework::TransformComponent::SetParentImpl
(EditorServer) - : C:\o3de\Code\Framework\AzCore\AzCore\Component\Entity.cpp (205) : AZ::Entity::Activate
(EditorServer) - : D:\o3de-multiplayersample\Gem\Code\Source\MultiplayerSampleSystemComponent.cpp (120) : MultiplayerSample::MultiplayerSampleSystemComponent::OnPlayerJoin
(EditorServer) - : C:\o3de\Gems\Multiplayer\Code\Source\MultiplayerSystemComponent.cpp (560) : Multiplayer::MultiplayerSystemComponent::HandleRequest
(EditorServer) - : D:\o3de-multiplayersample\build\windows_2019\External\Multiplayer-184c99d3\Code\Azcg\Generated\Source\AutoGen\Multiplayer.AutoPacketDispatcher.inl (28) : MultiplayerPackets::DispatchPacket<Multiplayer::MultiplayerSystemComponent>
(EditorServer) - : C:\o3de\Code\Framework\AzNetworking\AzNetworking\UdpTransport\UdpNetworkInterface.cpp (293) : AzNetworking::UdpNetworkInterface::Update
(EditorServer) - : C:\o3de\Code\Framework\AzNetworking\AzNetworking\Framework\NetworkingSystemComponent.cpp (77) : AzNetworking::NetworkingSystemComponent::OnSystemTick
(EditorServer) - : C:\o3de\Code\Framework\AzCore\AzCore\EBus\Internal\BusContainer.h (1360) : AZ::Internal::EBusContainer<AZ::SystemTickEvents,AZ::SystemTickEvents,0,1>::Dispatcher<AZ::EBus<AZ::SystemTickEvents,AZ::SystemTickEvents> >::Broadcast<void (__cdecl AZ::SystemTic
(EditorServer) - : C:\o3de\Code\Framework\AzCore\AzCore\Component\ComponentApplication.cpp (1357) : AZ::ComponentApplication::TickSystem
(EditorServer) - : C:\o3de\Code\LauncherUnified\Launcher.cpp (564) : O3DELauncher::Run
(EditorServer) - : C:\o3de\Code\LauncherUnified\Platform\Windows\Launcher_Windows.cpp (35) : WinMain
(EditorServer) - : d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
(EditorServer) - : 00007FF910CE244D (KERNEL32) : BaseThreadInitThunk
(EditorServer) - : 00007FF91222DF88 (ntdll) : RtlUserThreadStart
```

## Found in Branch
This is found in the Development branch and I did a git pull as recently as today.

## Desktop Specs
 - Device: PC
 - OS: Windows
 - Version: 11 (OS build: 22621.1)
 - CPU: Intel I9-12900KF
 - GPU: AMD Radeon RX 6600 XT
 - Memory: 32 GB

## Additional Context
While the Prefab spawns without error when one child entity is present, the child entity does not maintain its relative position to the parent.  Is this intended?

**Comment by AMZN-puvvadar** [comment] 2022-06-16 23:52
I did some digging on this. The reason this happens is because some of the child entities being processed aren't in the Activated state. Consequently they haven't connected to the TransformBus so the Transform get fails. A workaround here is falling back to directly grabbing the TransformComponent. I imagine the correct solution however, is that this code should not be entered until the entire hierarchy is activated.

**Comment by AMZN-puvvadar** [comment] 2022-06-17 18:12
There is a WIP change to address this here: https://github.com/o3de/o3de/pull/10193. The change so far addresses entities not in the Active state. For now, non-Active entities are skipped with the expectation that the hierarchy will be rebuilt again off an event from those entities Activating.

I'd like to also sort out the further issue around failure to examine the entirety of the hierarchy. The root cause here is that the spawnable is expected to be serialized in hierarchical order but is failing to 100% of the time.

**Comment by AMZN-puvvadar** [comment] 2022-06-17 21:36
I've taken https://github.com/o3de/o3de/pull/10193 out of draft and created https://github.com/o3de/o3de/issues/10196 to track the AssetBuilder issue on hierarchy sort order.

**Comment by AMZN-puvvadar** [comment] 2022-06-20 16:55
https://github.com/o3de/o3de/pull/10193 has been merged. Please refer to https://github.com/o3de/o3de/issues/10196 for issues around hierarchy sort order that can prevent the hierarchy from rebuilding properly.

**Closed by AMZN-puvvadar** 2022-06-20 16:55 UTC
Labels: kind/bug, sig/network, triage/accepted, priority/critical
