### ISSUE TITLE
AR Bug Report - ConcurrentAllocatorTestFixture/0.ConcurrentAllocateoDeallocate failed

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#11902] opened 2022-09-12 12:47 UTC
**Describe the bug**

`ConcurrentAllocatorTestFixture/0.ConcurrentAllocateoDeallocate` failed

**Failed Jenkins Job Information:**

Platform/Job: Windows [profile_pipe] - test_cpu_profile

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/stabilization%2F2210/22/pipeline/254

```
[2022-09-12T10:25:15.994Z] [ RUN      ] ConcurrentAllocatorTestFixture/0.ConcurrentAllocateoDeallocate
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(102): error: AZStd::static_pool_concurrent_allocator - No more free nodes!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(122): error: AZStd::static_pool_concurrent_allocator - Pointer is out of range!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(94): error: AZStd::static_pool_concurrent_allocator - No more free nodes!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(122): error: AZStd::static_pool_concurrent_allocator - Pointer is out of range!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(102): error: AZStd::static_pool_concurrent_allocator - No more free nodes!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(122): error: AZStd::static_pool_concurrent_allocator - Pointer is out of range!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(102): error: AZStd::static_pool_concurrent_allocator - No more free nodes!
[2022-09-12T10:25:15.994Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/parallel/allocator_concurrent_static.h(122): error: AZStd::static_pool_concurrent_allocator - Pointer is out of range!
[2022-09-12T10:25:15.994Z] System: Exception handler loop!System: Exception handler loop!System: Exception handler loop!System: D:\workspace\o3de\Code\Framework\AzCore\Tests\AZStd\ConcurrentAllocators.cpp (132) : `UnitTest::ConcurrentAllocatorTestFixture_ConcurrentAllocateoDeallocate_Test<AZStd::static_pool_concurrent_allocator<UnitTest::NodeType,1024> >::TestBody'::`4'::<lambda_
[2022-09-12T10:25:15.994Z] System: D:\workspace\o3de\Code\Framework\AzCore\Platform\Common\WinAPI\AzCore\std\parallel\internal\thread_WinAPI.cpp (38) : AZStd::Internal::thread_run_function
[2022-09-12T10:25:15.994Z] System: 00007FF89A5F268A (ucrtbase) : o_exp
[2022-09-12T10:25:15.994Z] System: 00007FF89C2B7974 (KERNEL32) : BaseThreadInitThunk
[2022-09-12T10:25:15.994Z] System: 00007FF89E3AA2F1 (ntdll) : RtlUserThreadStart
[2022-09-12T10:25:15.994Z] D:/workspace/o3de/Code/Framework/AzCore/AzCore/Memory/AllocatorManager.cpp(151): error: Manually created allocator 'SystemAllocator (Fundamental generic memory allocator)' must be manually destroyed before shutdown
[2022-09-12T10:25:15.994Z] D:/workspace/o3de/Code/Framework/AzCore/AzCore/Memory/AllocatorManager.cpp(151): error: Manually created allocator 'OSAllocator (OS allocator, allocating memory directly from the OS (C heap)!)' must be manually destroyed before shutdown
```

**Attachments**

[log.txt](https://github.com/o3de/o3de/files/9548058/log.1.txt)

**Comment by lumberyard-employee-dm** [comment] 2022-09-21 16:16
This is a duplicate of #11816

**Closed by lumberyard-employee-dm** 2022-09-21 16:16 UTC
Labels: kind/bug, needs-triage, sig/core, kind/automation, feature/systems
