### ISSUE TITLE
Opening and closing the Animation Editor prints a warning, and an assert to the Console

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11408] opened 2022-08-19 10:55 UTC
**Describe the bug**
When launching the Animation Editor, the following warning is printed to the Console:
```
[Warning] ((null)) - Make sure you use aznew, offers better tracking!
```

When exiting the Animation Editor, the following assert is printed to the Console:
Assert information:
File:
```
C:\o3de\Gems\Atom\RHI\Code\Include\Atom/RHI.Reflect/MemoryUsage.h
```
Condition:
```
(8712) 'void __cdecl AZ::RHI::HeapMemoryUsage::Validate(void)'
Total resident memory is larger than memory budget. Memory budget 0 Total resident 38273024
```
Line: 83

It should be noted that one of the PCs did get a similar assert when reproducing this issue, as well as when the Game Mode was being entered/exited:
Assert information:
File:
```
/home/gpc-800/O3DE/o3de/Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryUsage.h
```
Condition:
```
(139842364587264) 'void AZ::RHI::HeapMemoryUsage::Validate()'
Reserved memory is larger than memory budget. Memory budget 0 Reserved 327680
```
Line: 74

It should also be noted that another one of the PCs did not get either of the asserts printed to the Console, and only the Warning was printed.

For more information please refer to the **Video, and log files** section.

**Steps to reproduce**
1. Go to Tools > Animation Editor.
2. Close the Animation Editor.

**Expected behavior**
No warnings are printed to the Console.

**Actual behavior**
A warning is printed to the Console when launching the Animation Editor, and an assert is printed when it is closed.

**Video, and log files**

https://user-images.githubusercontent.com/86952082/185599693-b5016a42-c9d2-4a00-96fb-35b9d53ecac3.mp4

Editor.log files:
[Editor-GPC610.log](https://github.com/o3de/o3de/files/9381424/Editor-GPC610.log)
[Editor-GPC800.log](https://github.com/o3de/o3de/files/9381422/Editor-GPC800.log)

PCs dxdiag/hardinfo logs:
[DxDiag-GPC602.txt](https://github.com/o3de/o3de/files/9381402/DxDiag-GPC602.txt) - Windows Pre-built SDK, no assert.
[DxDiag-GPC610.txt](https://github.com/o3de/o3de/files/9381395/DxDiag-GPC610.txt) - Windows Pre-built SDK, assert MemoryUsage.h(83) on closing the Animation Editor.
[hardinfo_report_GPC800.txt](https://github.com/o3de/o3de/files/9381408/hardinfo_report_GPC800.txt) - Linux Pre-built SDK, assert MemoryUsage.h(74) on closing the Animation Editor, as well as entering/exiting the Game Mode.

**Found in Branch**
Development (e876c36)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment] 2022-08-19 11:47
We have also noticed that the MemoryUsage.h(83) assert is also printed when entering the Simulation Mode.

**Comment by hultonha** [comment] 2022-09-01 16:13
Tagging @amzn-rhhong as this looks like an issue with us using `new` instead of `aznew` somewhere in the Animation Editor. If you have a moment could you see if you could repro this and find the root cause, it seems like it should be pretty easy to spot hopefully.

**Comment by greerdv** [comment] 2022-10-10 17:55
I fixed the warning about using aznew in #12216. I don't know about the assert, that never triggered for me.

**Comment by hultonha** [comment] 2022-10-11 08:33
We're pretty sure this is fixed by https://github.com/o3de/o3de/pull/12216. Could you please retest @LB-ArturZieba to verify. Thank you!

**Closed by hultonha** 2022-10-11 08:33 UTC
Labels: feature/animation, kind/bug, sig/content, triage/accepted, priority/major, sig/simulation

**Comment by LB-TomaszSerwanski** [comment] 2022-10-13 09:59
@hultonha, we have verified that neither the warning nor the assert occurs on the Source engine build, however we were unable to confirm it on the Pre-built SDK due to [#12557](https://github.com/o3de/o3de/issues/12557). Will verify and comment once it is fixed.

**Comment by hultonha** [comment] 2022-10-13 10:15
Okay excellent, thank you @LB-TomaszSerwanski for the update! 👍
