### ISSUE TITLE
Editor_re:Invent_Bug - Shapes are selectable in the viewport even when they are not displayed.

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/o3de#5294] opened 2021-11-04 02:05 UTC
**Describe the bug**
Currently, Shape Components are only displayed in the viewport if the "Toggle Viewport Helpers" option is enabled on the top right. Nonetheless, even when they are not visible, clicking in the area occupied by the shape still selects the entity. This is quite confusing since the user may be trying to select the actual visible entities behind it.

Similarly, if the shape is part of a prefab, the shape will not be visualized even if the "Toggle Viewport Helpers" option is enabled (since helpers drawing is limited to the currently focused prefab) but the shape is still selectable (and will select the owning prefab).

**Steps to reproduce**
1. Load a Level
2. Create an entity
3. Add a Shape Component to it
4. Disable the "Toggle Viewport Helpers" option (top right of the viewport toolbar)
5. Deselect the entity, then click where the shape was.

**Expected behavior**
The entity is not selected, and if there's an entity behind it, that entity is selected.

**Actual behavior**
The entity with the Shape Component is selected.

**Screenshots/Video*
![shapeSelection](https://user-images.githubusercontent.com/82231674/140245312-ecfa88af-234c-4bf3-93ae-76eea0799f16.gif)
*

**Comment by hultonha** [comment] 2021-11-30 15:59
@alexmontAmazon I can take this issue and look at it later this week, I know what needs to be done to fix it. Is that okay with you?

**Comment by hultonha** [comment] 2021-12-14 11:50
Related/duplicate of https://github.com/o3de/o3de/issues/2790

**Closed** 2022-01-25 16:56 UTC
Labels: feature/editor, kind/bug, sig/content, status/active, status/backlog, triage/accepted, priority/major, feature/viewport
