### ISSUE TITLE
Asset Browser: Browsing assets fast when Tree View is enabled results in constant freeze of Editor

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#9739] opened 2022-05-24 12:19 UTC
**Describe the bug**
Browsing assets in the **Asset Browser** with **Tree View** option enabled results in the constant freeze of the Editor.
The **List View** is set as default view in the **Asset Browser**, and the freeze does **not** occur with it enabled.
To enable the **Tree View** click on the hamburger menu and click on **Tree View** in the dropdown menu.
Unfortunately, no logs are created when this issue occurs.

Please note that this issue also occurs on the Linux OS.

Similar Linux specific closed issue - https://github.com/o3de/o3de/issues/4659

**Steps to reproduce**
1. Type "a" in the **Asset Browser** search bar.
2. LMB on the slider and hover the slider to the bottom of the search results.
3. (Alternatively use scroll on mouse, it is easier to reproduce the issue by using the slider)

**Expected behavior**
The Editor remains stable at all times, browsing assets fast in the **Asset Browser** with **Tree View** enabled does **not** result in constant freeze.

**Actual behavior**
Browsing the assets fast in the **Asset Browser** with **Tree View** enabled results in constant freeze of the Editor.

**Video**

https://user-images.githubusercontent.com/86951967/170030139-9c631123-9b0d-45c9-914e-241f1919babc.mp4

**Found in Branch**
Development (840f88f)

**Desktop:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by GraphiteSIX** [comment] 2022-05-24 13:16
Just built commit c1e422fa636200c1b1f7c6539fb92eadead4697b from scratch everything deleted and repro'd this issue.
There isn't massive amounts of files On the drive the browser has access to and the hang leaves no trace.
I didn't even load or create a level I just shut the level dialog and typed 'a' then scrolled with L click and it hung.

I left it hanging quite a while (15 mins) then took a procdump it is attached below.
[Editor.exe_220524_140253.zip](https://github.com/o3de/o3de/files/8762962/Editor.exe_220524_140253.zip)

**Comment by rainbj** [comment] 2022-05-24 18:20
Hi @jjjoness - after investigating this issue. Will you let me know what you find out here? By just looking at the issue via the video it appears AP was processing a bunch of asset (spinners on all assets) and it just ran out of resources and died. If this can be prevented via UX please let me know. Thanks

**Comment by ParasiteSt** [comment] 2022-05-25 20:06
This seems to also be the same cause of opening a sprite in the ui editor when multiple folders are opened in the open a file window. I agree with rainbj that this issue is caused by a lot of assets being processed at once in the AP since their are a lot of spinners before the freeze.

**Comment by jjjoness** [comment] 2022-05-26 13:51
Fixed by increasing the QThreadPool size.

**Closed** 2022-05-27 12:27 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical

**Comment by LB-JakubSkorupka** [comment] 2022-05-30 07:46
Issue verified as fixed on build Development (a53a366).
