### ISSUE TITLE
Prefab spawning with higher than 1 level hierarchy does not update prefab with changes

### ISSUE THREAD

**Issue by AMZN-mnaumov** [o3de/o3de#2988] opened 2021-08-09 20:59 UTC
This bug happens when spawning prefabs via SpawnManager API. 

If we spawn a prefab via SpawnableEntitiesInterface->SpawnAllEntities, and the spawned prefab has a component that itself is a spawner (specifically contains AZ::Data::Asset<AzFramework::Spawnable> field) and spawns another prefab, then the last prefab will not refresh with any updates made to the child prefab in the Editor. 

A good example is if we have a prefab of a gun that shoots bullets.
Game has a gun spawner that looks like this:
```
class GunSpawner
{
   ...
   AZ::Data::Asset<AzFramework::Spawnable> m_gunPrefab;
};
```
then gun has a bullet prefab field:
```
class Gun
{
   ...
   AZ::Data::Asset<AzFramework::Spawnable> m_bulletPrefab;
};
```
When we spawn a gun, and it starts firing by spawning bullet prefab, the bullet prefab will not be updated with changes made to it in the Editor. So for example, if we change bullet color from blue to red, gun will still shoot blue bullets.

**To Reproduce**
1. Create new level, delete everything, keep camera for debugging
2. Create new entity ChildPrefab with Mesh component (works with any other component that reflects something too), assign "Sphere" mesh.
3. Create prefab from ChildPrefab entity, delete it in Entity Outliner.
4. Create new entity ParentPrefab. Attach 
[SpawnComponent.zip](https://github.com/o3de/o3de/files/6957335/SpawnComponent.zip), assign ChildPrefab as prefab to spawn.
5. Create prefab from ParentPrefab and delete in Outliner.
6. Finally create another entity "Spawner" and attach SpawnComponent to it as well. This time assign ParentPrefab into Prefab field (don't delete it this time).
7. Run the game, a sphere should spawn.
8. Now edit ChildPrefab, and replace sphere mesh with cube mesh. Save it to file, and delete it.
9. Run the game again, sphere still spawns.

**Expected behavior**
A cube should be spawning, since we've modified ChildPrefab

----
This can be fixed by editing ParentPrefab:
1. After modifying ChildPrefab, in SpawnComponent of ParentPrefab delete reference to ChildPrefab.
2. Save ParentPrefab to file.
3. Reassign ChildPrefab.
4. Save ParentPrefab again.
5. Now it works.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android]
 - Version [e.g. 10, Bug Sur, Oreo]
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by monroegm** [comment] 2022-02-28 23:37
Duplicate of #2325

**Closed by monroegm** 2022-02-28 23:37 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/critical, feature/prefabs
