### ISSUE TITLE
[CRITICAL] (Networking) If a netbinding component is added to an entity, other components won't run/activate

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2690] opened 2021-08-02 16:12 UTC
**Describe the bug**
ScriptCanvas components on entity do not run in-game if network binding component is enabled on same entity in the editor.

**To Reproduce**
1. Add an entity with a simple script canvas graph that prints something on graph start
2. Enter game mode and verify you see the print statement in the console
3. Add a netbinding component to the same entity
4. Enter game mode

**Expected behavior**
The print  statement still occurs

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by AMZN-puvvadar** [comment] 2021-08-11 19:46
@AMZN-alexpete was with the game/editor connected to a server? NetBoundEntities don't exist unless portrayed by the server.

**Comment by AMZN-alexpete** [comment] 2021-08-11 20:04
> @AMZN-alexpete was with the game/editor connected to a server? NetBoundEntities don't exist unless portrayed by the server.

No server was running, and the editor wasn't connected to anything except the asset processor.
@AMZN-Gene do you have anything to add to this issue?

**Comment by AMZN-Gene** [comment] 2021-08-11 20:19
Absolutely! I think as a user I would be confused by an entity disappearing.  If I press CTRL+G without a server running and some entities have netbind components (as thus will be removed) i'd definitely be helpful to see a popup "Running game without a server, use cvar editorsv_enabled... <blah>".  Maybe include a checkbox for "dont show this message again".

Likewise, it also be cool to have an option to just ignore net components when running CTRL+G.  Many times I want to test something like receiving controller input, and need to remember to remove the netbind component.

**Comment by AMZN-Olex** [comment] 2021-09-09 17:41
Hey, Alex, could you let us know some more information on this issue. Running multiplayer code in the Editor requires some additional steps and tweaking some cvars. See this particular doc page for details:

https://o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer/test-in-editor/

With that in mind, could you check which configuration your project has for running multiplayer code in the Editor?

**Comment by AMZN-alexpete** [comment] 2021-09-09 18:08
I think @AMZN-Gene may be better informed of our network setup, but this is our engine branch https://github.com/aws-lumberyard-dev/o3de/tree/racoonteurs

We used the default settings (https://github.com/aws-lumberyard-dev/o3de/blob/racoonteurs/Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp#L31) and didn't change any cvars, we just added the netbinding component to an entity (per the repro steps in this issue) and hit CTRL+G in the editor without any server running.  I think users will be confused that this "breaks" the entity, especially if they don't know about the cvars and are just trying to set up their level in preparation for multiplayer testing.  

If our default state is to disable any entity that has a netbinding component on it in the editor, we should make our default more user-friendly and/or notify the user that adding a netbinding component will disable their entities unless they change their cvar settings and/or get a server running that they can connect to.

**Comment by AMZN-Gene** [comment] 2021-09-09 19:06
Exactly, see my previous comment...
https://github.com/o3de/o3de/issues/2690#issuecomment-897124256

**Comment by ppinfel** [comment] 2021-09-16 17:30
i had a similar issue and asked in discord 
![image](https://user-images.githubusercontent.com/48143120/133658060-54112f71-9ecc-4e24-acc6-995c72120f13.png)

**Comment by lmbr-pip** [comment] 2021-09-16 17:47
@AMZN-alexpete Consensus is that is not a bug, code is working as designed but the UX is confusing to users. See Gene's comment about adding messaging/UX elements to aid user in troubleshooting. Move to close issue and open feature request for UX/logging relating to mis-configured setup.

@ppinfel - Will add a request for documentation, suggesting writing a tutorial that covers settingup a brand new project with Multiplayer Gem (so its not tied to Multiplayer Sample).

**Comment by lmbr-pip** [comment] 2021-09-30 17:00
Added feature request: https://github.com/o3de/o3de/issues/4415

**Comment by lmbr-pip** [comment] 2021-09-30 17:47
AMZN-alexpete - Moving to close this issue as by design. See related stories for a feature request / docs updates.

**Closed** 2021-09-30 19:05 UTC
Labels: kind/bug, needs-triage, sig/network, triage/needs-information
