### ISSUE TITLE
BSOD on project launch from Project Manager

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#2431] opened 2021-07-26 16:01 UTC
**Description**
I received a BSOD on project launch from Project Manager, and my laptop rebooted. I believe the BSOD message was KERNEL_HEAP_CORRUPTION. I was able to launch the game project twice prior to this issue, and have not been able to reproduce the BSOD.

**To Reproduce**
1. Using the gamejam fork.
2. Built as SDK
3. Create project with CLI
4. Launch editor.exe from build directory.
5. Open project from project manager.

**Expected behavior**
Editor to launch with selected project.

**Desktop/Device (please complete the following information):**
 - Device: Alienware laptop 
 - OS: Windows
 - Version 10
 - CPU Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz   3.10 GHz
 - GPU NVIDIA RTX 3070 mobile
 - Memory 32GB

**Additional context**

Project manager gave no indication it was doing anything. After about 8 seconds, the BSOD appeared and the machine rebooted. I was able to successfully launch the editor after reboot.

**Comment by AMZN-alexpete** [comment] 2021-12-03 01:15
Hi @micronAMZN, we have been unable to reproduce this crash in some time using the stabilization and dev branches.  When you get a chance would you mind updating/closing this issue if it no longer reproduces for you?

**Closed** 2021-12-03 19:42 UTC
Labels: kind/bug, needs-triage, sig/release
