### ISSUE TITLE
[Linux] Editor crashes when Viewport is configured to render 3 or more windows

### ISSUE THREAD

**Issue by LB-JakubSkoczylas** [o3de/o3de#9107] opened 2022-04-22 13:17 UTC
**Describe the bug**
When the user changes the Viewport layout so it displays 3 or more windows simultaneously, the Editor crashes.

Error logs for this issue were not created.

**Steps to reproduce**
1. Open Viewport Configure Layout menu.
2. Select any option with 3 or more Viewports.

**Expected behavior**
The Editor remains stable and the Viewport is displayed correctly.

**Actual behavior**
The Editor crashes.

**Screenshots/Video**

https://user-images.githubusercontent.com/86952591/164718043-cc1c0754-7888-47a8-a852-5119b654ca9d.mp4

**Found in Branch**
Stabilization_2205 (7c5da98)

**Desktop/Device:**
Device: PC
OS: Linux
Version Ubuntu 20.04.3 LTS
CPU AMD Ryzen 5 3600
GPU Nvidia Geforce RTX 2060 SUPER
Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/8541145/Editor.log)
[AP_GUI.log](https://github.com/o3de/o3de/files/8541146/AP_GUI.log)

**Comment by antonmic** [comment] 2022-04-26 22:57
Tracking this down, first looked like issue related to Passes and Shadow FP, but further inspection shows that it's a threading/concurrency issue, Feature Processors are being updated at the same time that the Pipeline starts it's frame render, and this shouldn't be the case. Once I figure out why this is happening and fix it, the error with the shadow passes will be resolved and this will hopefully fix the crash (only have access to Windows PC at the moment but error I repro is the same as in the Linux editor log).

**Comment by galibzon** [comment] 2022-04-27 23:15
Upcoming PR: https://github.com/o3de/o3de/pull/9230

**Comment by hultonha** [comment] 2022-04-29 08:57
@antonmic can this issue now be closed #9230 is merged? Thanks!

**Comment by galibzon** [comment] 2022-04-29 13:21
Well, unfortunately stabilkization is now broken on Linux:

**Comment by hultonha** [comment] 2022-04-29 14:16
That's unfortunate 😩 Worth pinging @antonmic? 😬 Any other ideas?

**Comment by galibzon** [comment] 2022-04-29 15:16
The Editor crashes with `-rhi=vulkan` on windows. Call stack:
```
>	Atom_RHI_Vulkan.Private.dll!AZ::Vulkan::ShaderResourceGroup::GetCompiledData() Line 35	C++
 	Atom_RHI_Vulkan.Private.dll!AZ::Vulkan::CommandList::CommitDescriptorSets(AZ::RHI::PipelineStateType type) Line 858	C++
 	[Inline Frame] Atom_RHI_Vulkan.Private.dll!AZ::Vulkan::CommandList::CommitShaderResource(const AZ::RHI::DrawItem &) Line 216	C++
 	Atom_RHI_Vulkan.Private.dll!AZ::Vulkan::CommandList::Submit(const AZ::RHI::DrawItem & drawItem) Line 251	C++
 	Atom_RPI.Editor.dll!AZ::RPI::RenderPass::BuildCommandList(const AZ::RHI::FrameGraphExecuteContext & context) Line 216	C++
 	[Inline Frame] Atom_RPI.Editor.dll!AZ::Debug::ProfileScope::BeginRegion(AZ::Debug::Budget *) Line 34	C++
 	[Inline Frame] Atom_RPI.Editor.dll!AZ::Debug::ProfileScope::{ctor}(AZ::Debug::Budget *) Line 61	C++
 	Atom_RPI.Editor.dll!AZ::RHI::FrameScheduler::ExecuteContextInternal(AZ::RHI::FrameGraphExecuteGroup & group, unsigned int index) Line 493	C++
 	Atom_RPI.Editor.dll!AZ::RHI::FrameScheduler::ExecuteGroupInternal(AZ::Job * parentJob, unsigned int groupIndex) Line 519	C++
 	EditorLib.dll!AZ::Internal::JobManagerBase::Process(AZ::Job * job) Line 31	C++
 	EditorLib.dll!AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal(AZ::Internal::JobManagerWorkStealing::ThreadInfo * info, AZ::Job * suspendedJob, std::atomic<bool> * notifyFlag) Line 421	C++
 	[Inline Frame] EditorLib.dll!AZ::Internal::JobManagerWorkStealing::ProcessJobsWorker(AZ::Internal::JobManagerWorkStealing::ThreadInfo * info) Line 310	C++
 	[Inline Frame] EditorLib.dll!AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads::__l4::<lambda_1>::operator()() Line 654	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::INVOKE(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads::__l4::<lambda_1> &&) Line 208	C++
 	[Inline Frame] EditorLib.dll!AZStd::invoke(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads::__l4::<lambda_1> &&) Line 55	C++
 	[Inline Frame] EditorLib.dll!AZStd::Internal::apply_impl(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads::__l4::<lambda_1> &&) Line 282	C++
 	[Inline Frame] EditorLib.dll!AZStd::apply(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads::__l4::<lambda_1> &&) Line 290	C++
 	[Inline Frame] EditorLib.dll!AZStd::thread::{ctor}::__l2::<lambda_1>::operator()() Line 45	C++
 	EditorLib.dll!AZStd::Internal::thread_info_impl<`AZStd::thread::thread<`AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads'::`4'::<lambda_1>>'::`2'::<lambda_1>>::execute() Line 193	C++
 	EditorLib.dll!AZStd::Internal::thread_run_function(void * param) Line 38	C++
 	[External Code]	
```

Complete log Windows with Vulkan:
[log.zip](https://github.com/o3de/o3de/files/8591822/log.zip)

**Comment by galibzon** [comment] 2022-04-29 15:17
@hultonha No ideas, waiting for @antonmic to take a look at this.

**Comment by hultonha** [comment] 2022-04-29 17:02
Thanks for the updates @galibzon, hopefully @antonmic can take a look later today

**Comment by galibzon** [comment] 2022-05-03 17:31
After @antonmic fix, it doesn't crash anymore. A Release note will be added to advice to resize the windows becomes after changing the layout the viewports render as thumbnails.

**Closed by galibzon** 2022-05-03 17:31 UTC
Labels: platform/linux, feature/graphics, kind/bug, sig/graphics-audio, priority/critical

**Comment by hultonha** [comment] 2022-05-03 19:07
Thanks for the update @galibzon, much appreciated 👍

**Comment by LB-JakubSkorupka** [comment] 2022-05-19 09:08
This issue recurred on build Development (e79ad5e). The crash occurs when choosing **any** layout. Reopening the issue.
Unfortunately, no crash logs are created when this issue occurs.

**Comment by hultonha** [comment] 2022-05-19 10:18
Blast 😞 ... @antonmic is this something you'd be able to review? Tagging @galibzon for visibility, please let me know if there's anything I can do to help 👍

**Comment by GraphiteSIX** [comment] 2022-05-19 10:30
I tested on windows and didn't get a crash but quite a few asserts.
<10:41:41> (System) - You can't dereference a null pointer
Do you want me to take a dump using task manager after triggering the null reference as it seems to reproduce
Or is there another way to get a dump file ?
[Editor.log](https://github.com/o3de/o3de/files/8728290/Editor.log)
.

**Comment by GraphiteSIX** [comment] 2022-05-19 10:42
I switched to vulkan and then went to reset the view back to a single viewport waited clicked the scrollbar once and it crashed.
Below ids the dmp and logs
[Third_test_Vulkan.zip](https://github.com/o3de/o3de/files/8728357/Third_test_Vulkan.zip)
.

**Comment by GraphiteSIX** [comment] 2022-05-19 10:48
The second test which was on dx12 didn't crash but I forced a dump though Taskmanager after getting a null reference.
It's 65165 KB so I cant upload here but can link to it on my google drive.
https://drive.google.com/file/d/1DEtEQdLzDqnJ9PpL4hcOOdSTI3X4H-mf/view?usp=sharing

**Comment by GraphiteSIX** [comment] 2022-05-19 11:32
Another test which was on dx12 didn't crash but I forced a dump though Taskmanager after getting a null reference.
It's 1.4gb so I cant upload here but can link to it on my google drive.

https://drive.google.com/file/d/143_88M_8oZ3FHIeKdrhqL_vCVEUjkvG9/view?usp=sharing

Let me know if you need anymore info or steps to repro.

**Comment by GraphiteSIX** [comment] 2022-05-19 14:57
I tried to record but its in two parts.
Open a level and PIE fullscreen and it crashes on exit.
Is this a separate GHI ?
Sorry for the clutter in the thread.

https://user-images.githubusercontent.com/105223355/169327002-0e7a85cb-e565-48ee-a634-270e6cbe54fa.mp4


https://user-images.githubusercontent.com/105223355/169327037-86b326aa-831e-4507-a1c2-21d8cf11b82b.mp4

**Comment by hultonha** [comment] 2022-05-20 10:42
Thank you very much for all the updates and detailed logs @GraphiteSIX! Super helpful! Hopefully this is something @antonmic can take a look at soon! 👍

**Comment by spham-amzn** [comment] 2022-05-23 18:56
Update: Repro on Linux (When setting a 3-window viewport), below is the callstack

```
AZStd::intrusive_ptr<AZ::Vulkan::PipelineLayout>::get() const (/src/github/o3de/Code/Framework/AzCore/AzCore/std/smart_ptr/intrusive_ptr.h:178)
AZ::Vulkan::Pipeline::GetPipelineLayout() const (/src/github/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Pipeline.cpp:46)
AZ::Vulkan::PipelineState::GetPipelineLayout() const (/src/github/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineState.cpp:30)
bool AZ::Vulkan::CommandList::CommitShaderResource<AZ::RHI::DrawItem>(AZ::RHI::DrawItem const&) (/src/github/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.h:191)
AZ::Vulkan::CommandList::Submit(AZ::RHI::DrawItem const&) (/src/github/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp:251)
AZ::RPI::RasterPass::BuildCommandListInternal(AZ::RHI::FrameGraphExecuteContext const&) (/src/github/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp:247)
AZ::RPI::RenderPass::BuildCommandList(AZ::RHI::FrameGraphExecuteContext const&) (/src/github/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp:215)
non-virtual thunk to AZ::RPI::RenderPass::BuildCommandList(AZ::RHI::FrameGraphExecuteContext const&) (/src/github/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp:0)
AZ::RHI::FrameScheduler::ExecuteContextInternal(AZ::RHI::FrameGraphExecuteGroup&, unsigned int) (/src/github/o3de/Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp:494)
AZ::RHI::FrameScheduler::ExecuteGroupInternal(AZ::Job*, unsigned int) (/src/github/o3de/Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp:519)
AZ::RHI::FrameScheduler::Execute(AZ::RHI::JobPolicy)::$_6::operator()(AZ::Job&) const (/src/github/o3de/Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp:573)
AZ::JobFunction<AZ::RHI::FrameScheduler::Execute(AZ::RHI::JobPolicy)::$_6>::ArgHelper<AZ::RHI::FrameScheduler::Execute(AZ::RHI::JobPolicy)::$_6, 1ul>::Process(AZ::RHI::FrameScheduler::Execute(AZ::RHI::JobPolicy)::$_6&, AZ::Job&) (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/JobFunction.h:61)
AZ::JobFunction<AZ::RHI::FrameScheduler::Execute(AZ::RHI::JobPolicy)::$_6>::Process() (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/JobFunction.h:42)
AZ::Internal::JobManagerBase::Process(AZ::Job*) (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerBase.cpp:30)
AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal(AZ::Internal::JobManagerWorkStealing::ThreadInfo*, AZ::Job*, std::atomic<bool>*) (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.cpp:420)
AZ::Internal::JobManagerWorkStealing::ProcessJobsWorker(AZ::Internal::JobManagerWorkStealing::ThreadInfo*) (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.cpp:310)
AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0::operator()() const (/src/github/o3de/Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.cpp:654)
decltype(InvokeTraits::forward<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0>(fp)()) AZStd::Internal::INVOKE<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0>(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0&&) (/src/github/o3de/Code/Framework/AzCore/AzCore/std/typetraits/invoke_traits.h:208)
AZStd::invoke_result<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0>::type AZStd::invoke<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0>(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0&&) (/src/github/o3de/Code/Framework/AzCore/AzCore/std/function/invoke.h:55)
decltype(AZStd::invoke(AZStd::declval<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0>())) AZStd::Internal::apply_impl<AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0, std::tuple<> >(AZ::Internal::JobManagerWorkStealing::CreateWorkerThreads(AZ::JobManagerDesc const&)::$_0&&, std::tuple<>&&, std::integer_sequence<unsigned long>) (/src/github/o3de/Code/Framework/AzCore/AzCore/std/tuple.h:282)
```

**Comment by spham-amzn** [comment] 2022-05-23 22:45
Applied a patch fix for this GHI to prevent a crash. Logged a GHI related to a window resizing issue that occurs after a new viewport is set ( #9725 )

**Comment by hultonha** [comment] 2022-05-24 13:02
Sounds good @spham-amzn, so when #9726 is merged we can close this out? Thanks!

**Comment by hultonha** [comment] 2022-05-24 16:18
> @hultonha Not sure if has solved the windows(OS) issues that may be separate cause but repro'd by the same actions. I will test and raise a GHI if its the same and point to the dumps in this thread.

Awesome thank you @GraphiteSIX :+1:

**Comment by spham-amzn** [comment] 2022-05-24 16:38
> @hultonha Not sure if has solved the windows(OS) issues that may be separate cause but repro'd by the same actions. I will test and raise a GHI if its the same and point to the dumps in this thread.

From the original call stack you provided, it looks like the patch I applied affects the 'de-reference null pointer' area. Hopefully Windows will respond at least the same way as Linux

**Comment by GraphiteSIX** [comment] 2022-05-24 16:45
Hopefully even the callstacks are completely different between Dx and vulkan the root cause is the null deref
I will retest anyway as there are some other issues with Vulkan I need to test.

**Comment by GraphiteSIX** [comment] 2022-05-24 17:47
Tested on Development https://github.com/o3de/o3de/commit/2e398bb7af90d45f7a5b9dbb1b2c5acec65b0d8c there is still a null assert but it is being supressed by the log level and spec
(System) - Pipeline layout is null.
The assert is there in Dx12 and Vulkan but viewports seem responsive and doesn't seem to crash like before.
On windows Vulkan there is the issue where viewports are tiny until signal reset, is this a separate GHI or can it tag into (#9725)
Great job in fixing the null deref @spham-amzn

**Comment by hultonha** [comment] 2022-05-26 09:46
Thanks for the info @GraphiteSIX 👍 I've just approved #9776 too, cheers!

**Comment by LB-KacperKapusta** [comment] 2022-08-31 08:38
The issue cannot be verified as the multi-viewport functionality has been disabled as described in https://github.com/o3de/o3de/issues/9907.

**Comment by hultonha** [comment] 2022-08-31 14:39
Tagging @AMZN-daimini for visibility - this might be something to come back and verify once multi-viewports are supported again
