### ISSUE TITLE
PhysX Character Controller collides with the top of PhysX Trigger colliders

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12619] opened 2022-10-14 13:44 UTC
**Describe the bug**
PhysX Character Controller collides with the top of PhysX Trigger colliders (for example a PhysX Shape Collider with Trigger property enabled + Sphere Shape entity). It should be noted that there is no collision with the same PhysX Trigger colliders when PhysX Character Controller moves to it from other sides.

**Steps to reproduce**
1. Create an entity with PhysX Character Controller, PhysX Character Gameplay and Mesh components (assign any visible asset - for example BeveledCylinder.fbx - to the Mesh as it is only used for visibility).
2. Create an entity with a PhysX Trigger collider (for example PhysX Shape Collider with Trigger property enabled and Sphere Shape entity with the Game View property enabled for visibility).
3. Place entity created in step 1 over the entity in step 2.
4. Enter the Game Mode.

**Expected behavior**
Entity from step 1 falls through the entity from step 2.

**Actual behavior**
Entity from step 1 collides with entity from step 2, remaining on top of it.

**Video**

https://user-images.githubusercontent.com/86952082/195858003-af9c1fea-343f-45d3-bc72-af94863be620.mp4

**Found in Branch**
Development (c28de14)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by greerdv** [comment] 2022-10-19 13:12
I believe this is probably a duplicate of https://github.com/o3de/o3de/issues/11895. Could you please try unticking the "In Scene Queries" option in the trigger collider to verify if it is a duplicate?

**Comment by LB-ArturZieba** [comment] 2022-10-19 13:31
I have verified this on the Development (ce8bfb7) and the PhysX Character Controller falls through PhysX Collider and PhysX Shape Collider triggers with "In Scene Queries" disabled. I believe that this issue can probably be closed.

**Comment by greerdv** [comment] 2022-10-20 08:48
Thanks for verifying! I'm going to go ahead and close this one as a duplicate.

**Closed by greerdv** 2022-10-20 08:48 UTC
Labels: kind/bug, needs-triage, priority/major, sig/simulation
