### ISSUE TITLE
Project configuration fails if newly created gems are added to the Project

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#6956] opened 2022-01-17 13:06 UTC
**Describe the bug**
If newly created Gems are added to the Project, it fails to configure due to the following error:

```
CMake Error at D:/Gems/PythonTool/CMakeLists.txt:5 (o3de_restricted_path):
  o3de_restricted_path Function invoked with incorrect arguments for function
  named: o3de_restricted_path
CMake Deprecation Warning at D:/Git/o3de/cmake/PAL.cmake:388 (message):
  ly_get_list_relative_pal_filename is being deprecated, change your code to
  use o3de_pal_dir instead.
Call Stack (most recent call first):
  D:/Gems/Nowe/PythonTool/Code/CMakeLists.txt:8 (ly_get_list_relative_pal_filename)
```

Please note that due to #6955 this has only been verified on AutomatedTesting.

Please also note that the issue is probably caused by commit c778606.

Refer to the attached log file for more details.

**Steps to reproduce**
1. Create a new Gem from any of the templates, i.e. _"<engine_root>\scripts\o3de.bat create-gem --gem-path C:/PythonTool --template-name PythonToolGem"_
2. Register the Gem in the Project:  _"<engine_root>\scripts\o3de register -gp C:/PythonTool -espp AutomatedTesting"_
3. Enable the Gem in the Project: _"<engine_root>\scripts\o3de enable-gem -gp C:/PythonTool -pp AutomatedTesting"_
4. Configure the Project: _"<project_root>cmake -B build/windows_vs2019 -S . -G "Visual Studio 16" -DLY_3RDPARTY_PATH=C:\o3de-packages"_

**Expected behavior**
Project configuration is successful.

**Actual behavior**
Project configuration fails.

**Screenshots/Video**

![ProjectConfigurationFails](https://user-images.githubusercontent.com/86953108/149773279-9b029f7a-266a-4b71-b1ef-35d8093040bf.png)

**Found in Branch**
Development (76ff7ae)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 Super
 - Memory 16GB

**Attachments**
[configure_log.txt](https://github.com/o3de/o3de/files/7881978/configure_log.txt)

**Comment by LB-KacperBieniek** [comment] 2022-01-19 10:34
Verified the issue is fixed in latest development (3bbb8d7) thanks to this pull request: https://github.com/o3de/o3de/pull/6976.

**Closed** 2022-01-19 17:16 UTC
Labels: kind/bug, sig/core, priority/blocker, WF8, RTE
