### ISSUE TITLE
ServerLauncher cannot be launched via the Game Mode more than once in the same Editor session

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#9303] opened 2022-04-29 11:23 UTC
**Describe the bug**
ServerLauncher cannot be launched via the Game Mode more than one time per Editor session. When attempting to start the Game Mode with the `Editorsv_enabled` set to true, a `[Warning](MultiplayerEditor) - Launching editor server skipped because editor failed to listen on port: 33451.` is printed to the Console.

It should be noted that on one of the PCs the ServerLauncher started properly with each subsequent Game Mode launch, though we were unable to determine it's exact cause. This was tested on three different machines with the Pre-built SDK engine configuration, and the projects using the Default Template, and all Gems except the AWS GameLift Gem. The machine that this issue did not occur on was one of the two that had the Default Template Gem configuration. 

The DxDiag file of the PC this issue did not occur on is attached in the **Video and DxDiag file** section.

**Steps to reproduce**
1. Make sure the .ServerLauncher.exe is built for the tested project, if not, then build it (e.g. for the Pre-built SDK engine and project built in the Project Manager, run the `cmake --build build/windows --target <ProjectName>.ServerLauncher --config profile` command via Command Line opened inside the project's folder).
2. Run `Editorsv_enabled true` command in the Console.
3. Enter the Game Mode.
4. Switch the focus to the Editor (e.g. by using the Alt+Tab), and press the Esc key to exit the Game Mode.
5. Type `Editorsv_` into the Console, and press Tab (this should print the list of Editorsv_ variables), verify that the `Editorsv_enabled` is still set to `true`.
6. Enter the Game Mode again.

**Expected behavior**
ServerLauncher launches along with the Game Mode start.

**Actual behavior**
ServerLauncher does not launch on certain machines, and the `[Warning](MultiplayerEditor) - Launching editor server skipped because editor failed to listen on port: 33451.` is printed to the Console.

**Video and DxDiag file**

https://user-images.githubusercontent.com/86952082/165933259-43d716a2-31a8-4c78-a77e-a86d2325c2f5.mp4

[DxDiag.txt](https://github.com/o3de/o3de/files/8590317/DxDiag.txt)

**Found in Branch**
Stabilization_2205 (ddedb53)

**Desktop**

Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by lmbr-pip** [comment] 2022-05-05 17:44
Sounds like an issue with server launchers sticking around in background.

**Comment by AMZN-puvvadar** [comment] 2022-05-12 17:22
I've been unable to reproduce this on development (5facd44e14b143490050e7e4eb6f2eb21546b563).

**Comment by AMZN-Gene** [comment] 2022-05-16 20:55
This was fixed in dev branch, but it isn't fixed in stab2205
https://github.com/o3de/o3de/pull/8765

**Closed** 2022-05-16 20:55 UTC
Labels: kind/bug, sig/network, triage/accepted

**Comment by LB-ArturZieba** [comment] 2022-05-17 14:05
Issue verified as fixed on the Development (3e42c6a) build
