### ISSUE TITLE
[PhysX] Accuracy problem for Offset/Ratation PhysX Collider.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#3006] opened 2021-08-10 12:10 UTC
**Describe the bug**
Setting new value for Offset of PhysX Collider, it could be a bit smaller than real input.
When set to 1000000000000000000000000000000000000, then it is adjusted to 999999961690316245365415600208216064.0.
When set to -1000000000000000000000000000000000000, then it is adjusted to -999999961690316245365415600208216064.0.

Setting new value for Rotation of PhysX Collider, it could be a bit smaller than real input.
When set to 360.5, it should be 0.5, but it is adjusted to 0.4999971.
When set to 0.7, then it is adjusted to 0.6999999.

**To Reproduce**
1. Open Editor.
2. Create a new Entity.
3. Add PhysX Collider.
4. Set a new value for Offset/Ratation.
5. Click Enter.
6. See error.

**Expected behavior**
No Accuracy problem. 
A recommended range includes min/max should be available to avoid such problems.

**Screenshots**

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by nemerle** [comment] 2021-08-10 12:57
Similarly to #3001 those problems are caused by the available floating-point precision.

I think those kinds of issues will be found in many places where we edit floating-point values. 
The solution some engines use is using rounding and string formatting tricks to display values in a lower precision.

**Comment by greerdv** [comment] 2022-12-19 14:42
Closing this because it is just the expected limits of floating point precision

**Closed by greerdv** 2022-12-19 14:42 UTC
Labels: feature/physics, kind/bug, triage/accepted, priority/minor, sig/simulation
