### ISSUE TITLE
AP Remove Connection Bug

### ISSUE THREAD

**Issue by macy12825** [o3de/o3de#7673] opened 2022-02-16 13:27 UTC
There is a bug,We cannot delete all custom connections, QSetting is stored before delete connections for deleteLater.

**Comment by lmbr-pip** [comment] 2023-03-30 18:14
Bug needs repro steps and some clarity to exactly how custom connections are being set up and what the issue is.

**Comment by AMZN-stankowi** [comment] 2023-03-30 18:17
Repro steps:
1. Launch asset processor
2. Go to "Connections" tab
3. Add a custom connection, give it a memorable name by editing it
4. Close Asset Processor
5. Open Asset Processor
6. Verify the connection is still there, as expected.
7. Delete the custom connection.
8. Close Asset Processor
9. Open Asset Processor
10. View the connections tab.
11. Note that the deleted connection is back.

Expected result: Connection deletes
Actual result: Connection does not get deleted

![image](https://user-images.githubusercontent.com/4838196/228927943-f7b3c66d-765f-490c-8415-41323cc7509d.png)

**Comment by AMZN-stankowi** [comment] 2023-04-04 20:32
https://github.com/o3de/o3de/pull/15555

**Comment by AMZN-stankowi** [comment] 2023-04-05 13:48
This is in and fixed now, see https://github.com/o3de/o3de/pull/15555

**Closed by AMZN-stankowi** 2023-04-05 13:48 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, triage/accepted, triage/needs-information, priority/major
