### ISSUE TITLE
Material Editor: It is possible to exceed value range of Normal Factor value by using slider

### ISSUE THREAD

**Issue by LB-JakubSkorupka** [o3de/o3de#14624] opened 2023-02-16 13:45 UTC
**Describe the bug**
In the Material Editor, it is possible to exceed the value range of Factor value in the Normal section by using slider.
The value range for Factor value is described in its tooltip as [0, 1], the slider allows to increase that value to 2.
The numerical value is not updated when moving slider to exceed the value, and is displaying the 1.0, even though slider is set to 2.
Note that the material in Material Editor Viewport does not reflect the change which exceeds the value range of Factor value.

**Steps to reproduce**
1. Open the Material Editor.
2. File -> New Material Document.
3. Create a new Standard PBR material.
4. In the Inspector window, in Normal section, assign any Texture.
5. Move the slider to increase Factor value in Normal section to 2 (note that numerical value is not updated).
6. Hover over "Factor" name to inspect its tooltip (note that the Factor value range is described as [0, 1]).

**Expected behavior**
It is **not** possible to exceed the value range of Factor value in Normal section by using slider in the Material Editor.

**Actual behavior**
The value of the Factor in Normal section in Material Editor can be set to 2 by using slider, which exceeds value range described in its tooltip.

**Video**

https://user-images.githubusercontent.com/86951967/219381072-782ed7f8-ea2a-4185-b4c1-c8b52bb64702.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/d50f3e74b82d2e03863bb1ce3a1ce7f594d89fa7

**Desktop:**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.5 LTS
 - CPU: Intel Core i7-8700K
 - GPU: NVIDIA GeForce RTX 2080 Ti
 - Memory: 16GB

**Comment by AMZN-Gene** [comment] 2023-02-18 07:04
I also ran into this problem. See #14159

**Comment by gadams3** [comment] 2023-02-18 21:40
This issue is a duplicate of https://github.com/o3de/o3de/issues/14159

**Closed** 2023-02-22 20:54 UTC
Labels: kind/bug, sig/graphics-audio, priority/minor

**Comment by LB-JakubSkorupka** [comment] 2023-02-24 10:24
Issue verified as fixed on build Development (37b6a48).
