### ISSUE TITLE
Point Release: Editor Crash Selecting Entity with Script Canvas

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#17083] opened 2023-11-16 22:27 UTC
The editor crashes when selecting a jump pad

**Steps to reproduce**
1. Open MultiplayerSample Newstarbase
2. Open a jump pad and select the child entity

**Expected behavior**
Editor doesn't crash

```
>	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::char_traits<char>::copy::__l2::<lambda_1>::operator()(char * src1, const char *) Line 546	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::char_traits<char>::copy(char *) Line 550	C++
 	ScriptCanvas.Editor.dll!AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>::assign(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & rhs, unsigned __int64 rhsOffset, unsigned __int64 count) Line 383	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>::assign(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> &) Line 328	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>::{ctor}(const AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> & rhs) Line 143	C++
 	ScriptCanvas.Editor.dll!ScriptCanvas::Datum::GetLabel() Line 2168	C++
 	ScriptCanvas.Editor.dll!AZ::AttributeMemberFunction<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> (__cdecl ScriptCanvas::Datum::*)(void)const>::Invoke(void * instance) Line 723	C++
 	[External Code]	
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function_intermediate<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator>>::operator()() Line 604	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> __cdecl(void)>::operator()() Line 684	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::InvokeFromDomArrayInternal(const AZStd::function<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> __cdecl(void)> &) Line 455	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZ::InvokeFromDomArray(const AZStd::function<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> __cdecl(void)> &) Line 468	C++
 	ScriptCanvas.Editor.dll!AZ::AttributeFunction<AZStd::basic_string<char,AZStd::char_traits<char>,AZStd::allocator> __cdecl(void)>::DomInvoke(void * instance, const AZ::Dom::Value & arguments) Line 541	C++
 	EditorLib.dll!AZ::DocumentPropertyEditor::AttributeDefinition<AZStd::basic_string_view<char,AZStd::char_traits<char>>>::LegacyAttributeToDomValue(void * instance, AZ::Attribute * attribute) Line 220	C++
 	[External Code]	
 	[Inline Frame] EditorLib.dll!AZStd::function_intermediate<void,AZ::DocumentPropertyEditor::AttributeDefinitionInterface const &>::operator()(const AZ::DocumentPropertyEditor::AttributeDefinitionInterface &) Line 604	C++
 	[Inline Frame] EditorLib.dll!AZStd::function<void __cdecl(AZ::DocumentPropertyEditor::AttributeDefinitionInterface const &)>::operator()(const AZ::DocumentPropertyEditor::AttributeDefinitionInterface & <args_0>) Line 684	C++
 	EditorLib.dll!AZ::DocumentPropertyEditor::PropertyEditorSystem::EnumerateRegisteredAttributes(AZ::Name name, const AZStd::function<void __cdecl(AZ::DocumentPropertyEditor::AttributeDefinitionInterface const &)> & enumerateCallback) Line 131	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::CacheAttributes::__l2::<lambda_1>::operator()(const AZStd::pair<unsigned int,AZ::Attribute *> * it, AZ::PointerObject instance, bool shouldDescribeChildren) Line 1213	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::CacheAttributes::__l2::<lambda_2>::operator()(AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::StackEntry & nodeData, bool isParentAttribute) Line 1337	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::CacheAttributes() Line 1349	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::HandleNodeAttributes(AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::StackEntry & parentData, AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::StackEntry & nodeData) Line 797	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::BeginNode(void * instance, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 889	C++
 	[External Code]	
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1306	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1322	C++
 	[External Code]	
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function_intermediate<bool,void *,AZ::Uuid const &,AZ::Serialize::ClassData const *,AZ::Serialize::ClassElement const *>::operator()(void * &&) Line 604	C++
 	[Inline Frame] ScriptCanvas.Editor.dll!AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::Serialize::ClassData const *,AZ::Serialize::ClassElement const *)>::operator()(void * <args_0>, const AZ::Uuid & <args_2>, const AZ::Serialize::ClassData * <args_3>, const AZ::Serialize::ClassElement *) Line 684	C++
 	ScriptCanvas.Editor.dll!AZ::Internal::AZStdBasicContainer<AZStd::vector<ScriptCanvas::GraphVariable,AZStd::allocator>,0>::EnumElements(void * instance, const AZStd::function<bool __cdecl(void *,AZ::Uuid const &,AZ::Serialize::ClassData const *,AZ::Serialize::ClassElement const *)> & cb) Line 251	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1311	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1322	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1322	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstance(AZ::Serialize::EnumerateInstanceCallContext * callContext, void * ptr, AZ::Uuid classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1322	C++
 	ComponentEntityEditorPlugin.dll!AZ::SerializeContext::EnumerateInstanceConst(AZ::Serialize::EnumerateInstanceCallContext * callContext, const void * ptr, const AZ::Uuid & classId, const AZ::Serialize::ClassData * classData, const AZ::Serialize::ClassElement * classElement) Line 1193	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AZ::Reflection::LegacyReflectionInternal::InstanceVisitor::Visit() Line 462	C++
 	ComponentEntityEditorPlugin.dll!AZ::Reflection::VisitLegacyInMemoryInstance(AZ::Reflection::IReadWrite * visitor, void * instance, const AZ::Uuid & typeId, AZ::SerializeContext * serializeContext) Line 1678	C++
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::ReflectionAdapter::GenerateContents() Line 1171	C++
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::DocumentAdapter::GetContents() Line 38	C++
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::RowFilterAdapter::GenerateContents() Line 200	C++
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::DocumentAdapter::GetContents() Line 38	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::DocumentPropertyEditor::HandleReset() Line 1689	C++
 	[External Code]	
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::DocumentAdapter::NotifyResetDocument(AZ::DocumentPropertyEditor::DocumentAdapter::DocumentResetType resetType) Line 148	C++
 	ComponentEntityEditorPlugin.dll!AZ::DocumentPropertyEditor::ComponentAdapter::SetComponent(AZ::Component * componentInstance) Line 91	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::Prefab::PrefabComponentAdapter::SetComponent(AZ::Component * componentInstance) Line 65	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::ComponentEditor::AddInstance(AZ::Component * componentInstance, AZ::Component * aggregateInstance, AZ::Component * compareInstance) Line 222	C++
 	[Inline Frame] ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityPropertyEditor::BuildSharedComponentUI(AZStd::vector<AzToolsFramework::EntityPropertyEditor::SharedComponentInfo,AZStd::allocator> &) Line 1836	C++
 	ComponentEntityEditorPlugin.dll!AzToolsFramework::EntityPropertyEditor::UpdateContents() Line 1368	C++
 	[External Code]	
 	EditorLib.dll!CryEditMain(int argc, char * * argv) Line 3837	C++
 	[Inline Frame] Editor.exe!AZStd::Internal::INVOKE(int(*)(int, char * *) &) Line 208	C++
 	[Inline Frame] Editor.exe!AZStd::invoke(int(*)(int, char * *) &) Line 54	C++
 	Editor.exe!main(int argc, char * * argv) Line 31	C++

```

**Actual behavior**
Editor crashes

**Found in Branch**
point-release/23101
4219baae7e01f14314d9d1f4623fcc888fb9debd

**Comment by G13D** [comment] 2023-11-27 05:49
in Nightly build now, If Script Canvas Component has Variables from Script Canvas Variable Manager, set "From Component" then Editor Crash will occur when Selecting Entity on Level or want to add the Script to Script Canvas Component

**Comment by alexmontAmazon** [comment] 2023-11-28 01:30
closing as a dupe of #16762

**Closed by alexmontAmazon** 2023-11-28 01:30 UTC
Labels: kind/bug, needs-triage, sig/content
