### ISSUE TITLE
Can't Open Editor: Failed to Start Python

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#7433] opened 2022-02-04 16:24 UTC
**Describe the bug**
New users are reporting Editors failing to open after [installing ](https://o3debinaries.org/download/windows.html)O3DE. 
 "Failed to start python"

**Steps to reproduce**
1. Download and install O3DE https://o3debinaries.org/download/windows.html
2. Try to open editor
3. Notice this warning popup 
![image](https://user-images.githubusercontent.com/32776221/152564697-38819a13-6b85-42ff-bc20-ccad753e00ed.png)
4. So follow the warning's instructions and run get_python.bat by hand...
![image](https://user-images.githubusercontent.com/32776221/152564762-808380de-5647-4556-860a-31dfe0d6ae29.png)
5. Try opening editor again and see error
"Failed to start Python after running python/get_python.bat"

**Expected behavior**
Editor works without error

**Actual behavior**
"Failed to start Python after running python/get_python.bat"
![image](https://user-images.githubusercontent.com/32776221/152565021-0367d5c6-af3e-4c82-9d7a-332d8d3882de.png)

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
https://o3debinaries.org/download/windows.html

**Desktop/Device (please complete the following information):**
 - OS:Windows

**Comment by AMZN-Gene** [comment] 2022-02-04 17:30
The work around was to open Project Manager instead and create a new project.
The getting started guide doesn't mention having to create a new project
https://www.o3de.org/docs/welcome-guide/setup/installing-windows/

**Comment by amzn-pratikpa** [comment] 2022-02-16 17:16
@o3de/sig-content we think this is related to the installation process

**Comment by michleza** [comment] 2022-03-08 21:49
If I add the python directory at the requested path I get different output

![image](https://user-images.githubusercontent.com/98843754/157331214-607ef6eb-5c1c-45d0-9be0-16b88d938379.png)

**Comment by robhaco** [comment] 2022-03-20 21:49
Have been unable to reproduce this as written.  Closing as Cannot Reproduce.  Investigation in the related ticket #8145 may offer a reliable repro and fix, if it is related.

**Closed by robhaco** 2022-03-20 21:49 UTC
Labels: kind/bug, sig/build, priority/critical, feature/installer
