### ISSUE TITLE
A barely readable dialog inside the Material component appears when multiple Material entities are selected

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#7427] opened 2022-02-04 13:48 UTC
**Describe the bug**
Selecting multiple entities containing a Material component results in the following barely readable dialog being displayed:
`Component cannot be edited with multiple entities selected`
Note that the same dialog is way more visible on Linux.

Please refer to the attached screenshots of Windows and Linux versions of the Editor for reference.

**Steps to reproduce**
1. Create an entity and add Material component to it.
2. Duplicate the created entity.
3. Select both entities.

**Expected behavior**
All appearing dialogs are easily readable.

**Actual behavior**
Barely readable dialog is displayed in the Material component when multiple Material entities are selected. 

**Screenshots**
Windows:

![MaterialComponent_Windows](https://user-images.githubusercontent.com/86953659/152537408-f2b57005-6156-458b-b0ce-776a6fcbec63.PNG)

Linux:

![MaterialComponent_Linux](https://user-images.githubusercontent.com/86953659/152537419-2a45c7e2-7f55-41af-8acd-9c6b8eb99767.PNG)

**Found in Branch**
Development (https://github.com/o3de/o3de/commit/01892914ead39f1d968a25c69ae745474f683a57)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i5-9600K
 - GPU: NVIDIA GeForce RTX 2070
 - Memory: 16GB

**Comment by gadams3** [comment] 2022-04-27 03:46
This is a duplicate of and will be resolved by addressing the following issue https://github.com/o3de/o3de/issues/8514

**Closed by gadams3** 2022-04-27 03:46 UTC
Labels: kind/bug, needs-triage, sig/ui-ux, priority/minor
