### ISSUE TITLE
Project Manager Blank projects you are unable to delete.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#8996] opened 2022-04-18 20:34 UTC
**Describe the bug**
When following the steps you should reproduce an issue where your project stays in the Project manager even if the Remove Project, or Delete Project Buttons are pressed. If you try and go to the project directory location it brings you to the default C: drive.
**Steps to reproduce**
1. Go to Project Manager and create a new project
2. Delete the project but do it from the file directory and not from the project manager
3. Relaunch the project manager and the bug should have occurred with a project you are no longer able to get rid of.

**Expected behavior**
If you delete a project from the file directory it should also remove it from the project manager.
**Actual behavior**
A clear and concise description of what actually happened.
It keeps the project in the project manager, but no project is actually valid.
**Assets required**
Provide sample assets needed to reproduce the issue.
N/A
**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Name of or link to the branch where the issue occurs.
Dev Branch from 4/16/2022
**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 
**Additional context**

**Comment by forhalle** [comment] 2022-04-19 18:31
@robhaco  - Thank you for agreeing to repro this :>

**Comment by robhaco** [comment] 2022-04-19 23:03
Was unable to repro this in development from today.  It's possible a recent related change could have fixed it, but it appears the project registration is being properly updated whenever the project manager is launched if a project has been manually deleted on disk.

**Comment by robhaco** [comment] 2022-04-19 23:12
Closing this since we're unable to reproduce the issue.  Please feel free to re-open if the issue persists in more recent versions of development.

**Closed by robhaco** 2022-04-19 23:12 UTC
Labels: kind/bug, needs-sig, needs-triage

**Comment by robhaco** [comment] 2022-04-19 23:37
For reference, the related change that we believe resolved this: https://github.com/o3de/o3de/pull/8898
