### ISSUE TITLE
When going to Game Mode and hitting Esc, on return to the Editor the viewport does not have focus

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3777] opened 2021-08-31 20:11 UTC
### Problem description

When pressing Ctrl-G to go to Game Mode, if quickly iterating it's common to want to hit Esc and Ctrl-G again in quick succession to re-enter the game. The problem at the moment is when returning from Game Mode the Viewport does not have focus and Ctrl-G has no effect until it is pressed which can be confusing and frustrating for the user.

The workaround solution is Click in the viewport after returning from Game Mode

Reported by @hultonha through LY game Jam

**Comment by cgalvan** [comment] 2021-08-31 20:49
Duplicate of #2194

**Closed by cgalvan** 2021-08-31 20:49 UTC
Labels: feature/editor, sig/content, sig/ui-ux, RTE
