### ISSUE TITLE
Edit materials for multiple entities with the same model at the same time

### ISSUE THREAD

**Issue by liukaikai-g** [o3de/o3de#8984] opened 2022-04-18 12:43 UTC
**Is your feature request related to a problem? Please describe.**
I want to edit materials for multiple entities with the same model at the same time, however, the Material Component does not currently support this feature. When I select multiple entities, the Material Component shows that "Component cannot be editor with muliple entities selected"

**Describe the solution you'd like**
We can edit materials for multiple entities with the same model at the same time.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/55627654/163810046-d56235bb-31fb-4cb4-a8cf-00148f1bc1dc.png)

**Comment by gadams3** [comment] 2022-04-27 03:44
This is a duplicate of the following issue https://github.com/o3de/o3de/issues/8514

**Closed by gadams3** 2022-04-27 03:44 UTC
Labels: needs-triage, sig/graphics-audio, feature/graphics/materials
