### ISSUE TITLE
atom_rpi_tools_tests hangs when run in parallel

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7653] opened 2022-02-15 21:09 UTC
**Describe the bug**
There appears to be a hang caused by executing the RPI unit tests in parallel with other modules. This is likely environment-dependent, though reproduced consistently (92/92 failures) across two machines with quite different hardware. Please prefer fixing the contention issue, versus simply excluding this module from parallel execution.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration. Command to build the tests 'cmake --build . --target TEST_SUITE_smoke TEST_SUITE_main --config profile  -- /m /nologo' (from /build folder)
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -L "(SUITE_main|SUITE_smoke)" --output-on-failure -j 32`

**Expected behavior**
Tests quickly succeed, or quickly fail with output

**Actual behavior**
`Test  #51: RPI::atom_rpi_tools_tests.main::TEST_RUN .................................***Timeout 151.46 sec`

**Found in Branch**
Development @ https://github.com/o3de/o3de/commit/4982787043a45449ef37a1435e37402611918ceb

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-9750H / Ryzen TR 3970X 
 - GPU NVidia
 - Memory 32GB / 64 GB

**Additional context**

- This test does not fail when run in isolation with `ctest -C profile -R RPI::atom_rpi_tools_tests.main::TEST_RUN --output-on-failure`
- User should update the value provided to flag -j to be the number of physical cores of their processor.
- This is likely related to https://github.com/o3de/o3de/issues/7654

**Comment by Kadino** [comment] 2022-02-28 20:05
This failure is not reproducing (0/130) in local soak tests of development @ b64cce7f14, which may be due to a moved race condition

**Comment by VickyAtAZ** [comment] 2022-04-22 18:48
@Kadino I can't reproduce this failure with stabilization 2205 branch @ 7c52d94dcfc4b4a644b4451015c3b910490bb644. 
Maybe we should close this issue.

**Comment by jromnoa** [comment] 2023-03-09 19:36
We advise against using parallel tests now and instruct users to use batched tests instead. While the parallel tests can be accessed and used, its a risk that is placed solely on the user until we have official support provided for it. 

You can read the wiki for the Multitest Framework here: https://github.com/o3de/o3de/wiki/Multitest-Framework:-Running-one-or-multiple-tests-in-one-or-multiple-executable(s). 

When we officially support parallel tests we can explore debugging and fixing the issues related to them, but for thew time being we use batched tests instead of parallel tests.

**Closed by jromnoa** 2023-03-09 19:36 UTC
Labels: kind/bug, sig/graphics-audio, priority/critical, feature/graphics/rpi
