### ISSUE TITLE
Changing Translation Offset in entity with Noise Gradient is not reflected on Terrain Layer Spawner entity

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#13398] opened 2022-11-25 14:37 UTC
**Describe the bug**
Modifying Translation Offset in entity with Noise Gradient component targeting a Terrain Layer Spawner entity does not change the terrain being generated. Although, the change is reflected in the Preview window of the Noise Gradient component.

**Prerequisites**

- Translation Offset mode enabled - Add "EnableShapeComponentTranslationOffset": true under "Amazon" -> "Preferences" in editorpreferences.setreg.
- A project with enabled Terrain gem is built.

**Steps to reproduce**
1. Add Terrain World and Terrain World Renderer components to Level entity.
2. Create Entity1 with Terrain Layer Spawner, Axis Aligned Box Shape and Terrain Height Gradient List components.
3. Change Axis Aligned Box Shape's Dimensions to e.g. X:10, Y:10 and move the Entity1 above Z:0 for the terrain to be rendered.
4. Create Entity2 with Perlin or Random Noise Gradient component and add the required components to it (as shape use Axis Aligned Box Shape, Box Shape, Capsule Shape or Sphere Shape component).
5. Select Entity1 and choose Entity2 as target in Terrain Height Gradient List component.
6. Select Entity2 and modify Translation Offset in its shape component.

**Expected behavior**
The generated terrain updates as the Noise Gradient entity's Preview does.

**Actual behavior**
The Noise Gradient entity's Preview updates but the change is not reflected on the generated terrain.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953659/204005712-d006eff2-6d85-4c04-8550-32be06efb94b.mp4

**Found in Branch**
Development (da550ef)

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**

**Comment by greerdv** [comment] 2023-02-17 16:52
Talking to @mbalfour-amzn it seems like this is the expected behaviour, although it did lead to discovering a couple of other issues (https://github.com/o3de/o3de/pull/14648 https://github.com/o3de/o3de/issues/14650)

**Comment by greerdv** [comment] 2023-02-20 09:49
Closing as by design

**Closed by greerdv** 2023-02-20 09:49 UTC
Labels: kind/bug, sig/content, triage/accepted, priority/major, feature/terrain

**Comment by LB-KacperKapusta** [comment] 2023-02-21 07:24
Confirming the issue has been closed as by design as per comment above.
