### ISSUE TITLE
The value on the slider is a bit smaller than the real value when editing float value of new material with Material Editor.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2648] opened 2021-07-30 09:23 UTC
**Describe the bug**
The value on the slider is a bit smaller than the real value when editing float value of new material with Material Editor.

**To Reproduce**
1. Open Editor.
2. Click on Tools -> Material Editor
3. Wait for Material Editor to open
4. Click File -> New, select StandardPBR, and save to somewhere.
5. Modify a float value such as Factor using the slider.
6. Check the values on the slider and the input text.

**Expected behavior**
The values from the slider and the input text are the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/80555200/127632038-5f37cdc1-dd6e-4701-95b5-91c11264ae46.png)

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Windows]
 - Version [10]
 - CPU [Intel I7-10700 2.90GHz (16 CPUs)]
 - GPU [Intel(R) UHD Graphics 630]
 - Memory [32GB]

**Additional context**

**Comment by gadams3** [comment] 2022-03-24 03:31
@superkitcath @monroegm This is a known issue for @o3de/sig-content where the floating point property spinner/slider control is not respecting the precision or step attribute.

**Comment by gadams3** [comment] 2022-03-24 18:57
closing as duplicate of #8295

**Closed by gadams3** 2022-03-24 18:57 UTC
Labels: kind/bug, needs-priority, sig/graphics-audio
