### ISSUE TITLE
White Box is not rendering due to "Could not load material" error

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15116] opened 2023-03-15 13:05 UTC
**Describe the bug**
White Box is missing it's material, making it invisible in the Viewport. It should be noted that the mesh of a White Box can still be seen and manipulated while in the Edit mode. Modifying White Box causes these lines to be printed to the Console:
```
[Warning] (AssetUtils) - Unable to find product asset 'materials/defaultpbr.azmaterial'. Has the source asset finished building?
[Error] (CreateLodAsset) - Could not load material.
[Error] (ModelDataInstance::MeshLoader) - Invalid model asset Id.
```

**Steps to reproduce**
1. Create an entity and add a White Box component to it.

**Expected behavior**
White Box is visible.

**Actual behavior**
White Box is invisible.

**Video**

https://user-images.githubusercontent.com/86952082/225314869-e03c5433-85f7-463a-ac46-50a09afefc93.mp4

**Found in Branch**
Development (2a3a7ae)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
2a3a7aebca6d6cf05876047af324d001f2f47d64

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 22.04.1 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment] 2023-03-15 15:24
Unable to reproduce this using the latest source from development branch. Is it possible that assets were still processing in the background?

**Comment by LB-ArturZieba** [comment] 2023-03-15 15:32
Assets were processed and this was also reproduced on three other machines (Windows Pre-built SDK, Linux Source and Linux Pre-built SDK builds on the same commit).

**Comment by LB-ArturZieba** [comment] 2023-03-15 16:06
I've also checked deleting the Cache folder and reprocessing assets, as well as building a new Default Template project followed by processing all of it's assets on my machine (Linux Pre-built SDK). The issue still occurred in both cases and I've noticed that the defaultpbr material is not found on neither project's Asset Processor:
![APAfterDeletingCacheAndReprocessing](https://user-images.githubusercontent.com/86952082/225369944-92daae93-9d01-400a-8305-5eed5a0c666b.png)
![APOnNewDefaultTemplateProject](https://user-images.githubusercontent.com/86952082/225369955-f954f53f-129f-4d54-af8c-8da3bf1aa0fe.png)

**Comment by lmbr-pip** [comment] 2023-03-16 18:51
Material is here: https://github.com/o3de/o3de/tree/development/AutomatedTesting/Materials should either be in Editor assets folder or in a separate asset used just by the whitebox tool

**Comment by VickyAtAZ** [comment] 2023-03-17 16:12
Fixed in https://github.com/o3de/o3de/pull/15154

**Closed by VickyAtAZ** 2023-03-17 16:12 UTC
Labels: feature/whitebox, kind/bug, needs-triage, sig/graphics-audio, priority/critical
