### ISSUE TITLE
[Linux] Editor’s Maximize button icon does not update when maximizing the window

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de#10048] opened 2022-06-10 11:26 UTC
**Describe the bug**
If the Editor is maximized, the Maximize button does not change it's appearance to represent it.

It should be noted that this issue only occurs on Linux.

**Steps to reproduce**
1. Launch the Editor.
2. Maximize the Editor’s window.
3. Observe the Maximize button icon.

**Expected behavior**
Maximize button icon changes it's appearance.

**Actual behavior**
Maximize button icon does not change it's appearance.

**Screenshots/Video**

https://user-images.githubusercontent.com/86951905/173055143-ac753dfb-bb6f-445b-8f42-8d551787ee80.mp4

**Found in Branch**
Development (480eff6)

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 18.04
- CPU AMD Ryzen 3600
- GPU Nvidia GeForce RTX 2060 SUPER
- Memory 16GB

**Comment by pollend** [comment] 2022-06-13 02:56
would it make sense to have an asset for the maximized version of the o3de window. I guess this problem is not really exclusive to linux since the frame is custom?

**Comment by srikappa-amzn** [comment] 2022-07-27 18:41
@LB-RostyslavGavryliuk , Should this be closed because of the above fix?

**Comment by pollend** [comment] 2022-07-27 19:45
> @LB-RostyslavGavryliuk , Should this be closed because of the above fix?

what is the policy for closing issues there are quite a lot of issues like this.

**Comment by LB-RostyslavGavryliuk** [comment] 2022-07-28 10:27
Issue verified as fixed.

**Closed** 2022-07-28 10:27 UTC
Labels: platform/linux, kind/bug, needs-triage, sig/ui-ux, priority/minor

**Comment by srikappa-amzn** [comment] 2022-07-28 20:51
> what is the policy for closing issues there are quite a lot of issues like this.

If you are the author of a PR who fixed an issue, you can close the issue after verifying that it's no longer reproducible. Alternatively, you can also request the author of the github issue if you want an additional set of eyes to validate the fix.
