### ISSUE TITLE
o3de could not initialize correctly for the follwing reason(s);

### ISSUE THREAD

**Issue by 860000023** [o3de/o3de#4038] opened 2021-09-10 07:33 UTC
unable to find product asset"shaders/simpletextured.azshader",has the source asset finished building?
could not load font:Fonts/default.font.

when i open editor by automatedtesting .i got this error

**Comment by xw901103** [comment] 2021-09-12 00:05
Duplicate of #3955

**Comment by superkitcath** [comment] 2021-09-15 17:14
Closing this issue, as it is a duplicate of[ #3955.](https://github.com/o3de/o3de/issues/3955)

**Closed by superkitcath** 2021-09-15 17:14 UTC
Labels: kind/bug, needs-triage, sig/graphics-audio
