### ISSUE TITLE
File and Edit Menu, no Hover

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#14471] opened 2023-02-08 19:38 UTC
**Describe the bug**
There is no UI reaction when I hover the mouse over the File or Edit Menubar Items.  I can't click to open them, but if I click another menu like Game, after it's open I can move to the left and enter the File or Edit menu.

**Steps to reproduce**
1. start the Editor and open a level.
2. try to click on File or Edit Menu

**Expected behavior**
I can click on File menu and access menu actions like Open.

**Actual behavior**
I can not get into the File or Edit Menu (unless I use the workaround, of opening another menu like Game and then sliding left.

**Screenshots/Video**
![Editor_M8wGeLCqT1](https://user-images.githubusercontent.com/23222931/217633591-69d75f99-7548-4531-887a-7f965adefefc.gif)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
0adc21213ad0d609b2cc634091a435ba34f7ae9a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win11
 - CPU threadripper
 - GPU 3070 rtx
 - Memory 64GB

**Comment by forkercat** [comment] 2023-02-08 23:08
I also noticed this issue since 2/7 on a 4k monitor.

**Comment by hultonha** [comment] 2023-02-09 09:08
Assigning to @o3de/sig-content for further triage

**Comment by allisaurus** [comment] 2023-02-17 21:33
FYI able to reproduce this on `1fc2dc2149f` (2/17/2023)

**Comment by AMZN-daimini** [comment] 2023-02-20 14:59
Upon inspection, it looks like this may have been introduced by this PR:
https://github.com/o3de/o3de/pull/14197/files#diff-d5729d094928c4642299dddca98bba2de13aec0c7220ead69fb2f42f949fb751

As the widget blocking the interactions seems to be a Toast Notifications View widget

![image](https://user-images.githubusercontent.com/82231674/220139798-4adda5fa-c1eb-473c-b22a-6136520ba114.png)

I'll look into a quick fix at the moment, and then possibly plan on overhauling the toast system since it's something we've been wanting to streamline for a while.

**Comment by AMZN-daimini** [comment] 2023-02-20 15:33
A fix for this issue is in PR.
https://github.com/o3de/o3de/pull/14677

**Closed** 2023-02-21 07:59 UTC
Labels: feature/editor, kind/bug, sig/content, triage/accepted, priority/major
