### ISSUE TITLE
Editor fails to launch due to processing assets

### ISSUE THREAD

**Issue by micronAMZN** [o3de/o3de#13247] opened 2022-11-16 23:36 UTC
When opening a newly built project from Project Manager, the Editor splash screen exits before assets are done processing, which consequently kills Asset Processor, meaning required assets don't finish processing, leaving the user unable to launch the editor. The only work around is to run Asset Processor from the command line and wait for it to process required assets before launching the Editor.

You can use either the 22.10.0 release or development branch to test this.

**Steps to reproduce**
1. Create a new project in Project Manager with a Default template.
2. Build the project from Project Manager.
3. Click Open Editor on the project tile in project manager.

The splash screen appears, Asset Processor starts, you can open the Asset Processor UI and watch it scan and start processing assets. With over 1,000 jobs in the job queue, the editor splash screens disappears and then Asset Processor exits. Launch the editor again and observe the same results. You can keep relaunching the editor, and maybe eventually, the required assets will be processed in the short window that Asset Processor is open to allow the editor to launch successfully.

If you launch asset processor from the command line with the project path and wait for the assets to finish processing, the editor can be launched.

**Expected behavior**
When I click Open Editor on a project in project manager the, Editor should eventually open once assets have been processed. 

**Actual behavior**
The editor dies on the splash screen and takes Asset Processor down as well, leaving required assets unprocessed and making it not possible to launch the editor.

**Found in Branch**
Current Development and 22.10.0 Release

**Desktop/Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Version: 10
 - CPU: Intel i9-10980HK
 - GPU: NVidia RTX 3070 M
 - Memory: 32GB

**Additional context**
I've had this issue for months, but assumed it had something to do with my development build. Today I decided to test it on a clean installation of the release.

**Comment by jackalbe** [comment] 2022-11-17 23:11
I tried this steps and the described behavior did not happen. Is this really critical?

**Comment by lmbr-pip** [comment] 2022-11-18 16:34
@jackalbe SIG/content has not triaged the issue so priority is still to be negotiated.

**Comment by micronAMZN** [comment] 2022-11-18 18:09
I tried debugging this, I'm getting this exception.

![editorexception](https://user-images.githubusercontent.com/58789750/202773610-bdc2d2ca-bdd5-40e9-b6f7-e6947f7d0963.png)

**Comment by AMZN-stankowi** [comment] 2022-12-06 15:03
This is a duplicate of https://github.com/o3de/o3de/issues/11926

**Closed by AMZN-stankowi** 2022-12-06 15:03 UTC
Labels: feature/asset-pipeline, kind/bug, sig/content, triage/accepted, priority/critical
